#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
source "$source_dir/../include/colors.bash"

set -e # exit on any error

echo $(cyan "$(bold)Output each color or style:")
echo $(black "This is a black line.")
echo $(red "This is a red line.")
echo $(green "This is a green line.")
echo $(yellow "This is a yellow line.")
echo $(blue "This is a blue line.")
echo $(magenta "This is a magenta line.")
echo $(cyan "This is a cyan line.")
echo $(white "This is a white line.")
echo $(bg_black "This is a bg_black line.")
echo $(bg_red "This is a bg_red line.")
echo $(bg_yellow "This is a bg_yellow line.")
echo $(bg_blue "This is a bg_blue line.")
echo $(bg_magenta "This is a bg_magenta line.")
echo $(bg_cyan "This is a bg_cyan line.")
echo $(bg_white "This is a bg_white line.")
echo $(bold "This is a bold line.")
echo $(underline "This is a underline line.")
echo $(inverse "This is a inverse line.")
echo $(dim "This is a dim line.")
echo

echo $(cyan "$(bold)Output methods:")
echo "$(red multiple parameters are joined by spaces)"
echo "this $(bold)is a $(red)mixed$(reset) text."
echo "This text is colored using pipe" | cyan
echo

ctext=$(bg_red "This text with red background")
echo $(cyan "$(bold)Remove colors:")
echo "original: $ctext"
echo "uncolor using parameters: $(uncolor $ctext)"
echo "uncolor using pipe: $ctext" | uncolor
