#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
source "$source_dir/../src/include/log.bash"

set -e # exit on any error

LOG_LEVEL=TRACE

echo $(cyan "$(bold)Directly given:")
log AUTO "text with TRACE level"
log AUTO "text with DEBUG level"
log AUTO "text with INFO level"
log AUTO "text with NOTICE level"
log AUTO "text with WARN level"
log AUTO "text with WARNING level"
log AUTO "text with ERR level"
log AUTO "text with ERROR level"
log AUTO "text with CRIT level"
log AUTO "text with CRITICAL level"
log AUTO "text with ALERT level"
log AUTO "text with EMERG level"
log AUTO "text with EMERGENCY level"
echo

echo $(cyan "$(bold)Exceptions:")
log AUTO "Exception in thread "main" java.lang.NullPointerException"
log AUTO "        at com.example.myproject.Book.getTitle(Book.java:16)"
echo

echo $(cyan "$(bold)User defined auto detection:")
LOG_AUTO[MARK]="alex"
log AUTO "This is a normal line"
log AUTO "while this is special for alex"
echo
