#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
LOG_FILE="$source_dir/test.log"
source "$source_dir/../include/log.bash"

set -e # exit on any error

echo $(cyan "$(bold)Simple commands:")
log_cmd apt-get update || log_exit ALERT "Could not..."
echo "Done"
