#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
LOG_FILE="$source_dir/test.log"
source "$source_dir/../src/include/log.bash"

set -e # exit on any error

echo $(cyan "$(bold)All log levels:")
LOG_LEVEL=TRACE
log TRACE "text with TRACE level"
log DEBUG "text with DEBUG level"
log INFO "text with INFO level"
log NOTICE "text with NOTICE level"
log WARN "text with WARN level"
log WARNING "text with WARNING level"
log ERR "text with ERR level"
log ERROR "text with ERROR level"
log CRIT "text with CRIT level"
log CRITICAL "text with CRITICAL level"
log ALERT "text with ALERT level"
log EMERG "text with EMERG level"
log EMERGENCY "text with EMERGENCY level"
cat $LOG_FILE
echo "" > $LOG_FILE
echo

echo $(cyan "$(bold)Only EMERGENCY level output:")
LOG_LEVEL=EMERGENCY
log TRACE "text with TRACE level"
log DEBUG "text with DEBUG level"
log INFO "text with INFO level"
log NOTICE "text with NOTICE level"
log WARN "text with WARN level"
log WARNING "text with WARNING level"
log ERR "text with ERR level"
log ERROR "text with ERROR level"
log CRIT "text with CRIT level"
log CRITICAL "text with CRITICAL level"
log ALERT "text with ALERT level"
log EMERG "text with EMERG level"
log EMERGENCY "text with EMERGENCY level"
cat $LOG_FILE
echo "" > $LOG_FILE
echo

echo $(cyan "$(bold)Different dateformat and tags:")
LOG_LEVEL=INFO
LOG_DATE_FORMAT="+%Y-%m-%d"
LOG_TAG=test
log INFO "text with INFO level"
cat $LOG_FILE
echo "" > $LOG_FILE
echo

rm $LOG_FILE
