#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
LOG_FILE="$source_dir/test.log"
LOG_ROTATE_SIZE=100
LOG_ROTATE_COMPRESS=1
source "$source_dir/../include/log.bash"

set -e # exit on any error
#set -x # output each command

echo $(cyan "$(bold)Rotate size:")
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
echo

rm -rf $LOG_FILE* 2>/dev/null
exit 0
