#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
LOG_FILE="$source_dir/test.log"
LOG_ROTATE_TIME=DAILY
LOG_ROTATE_COMPRESS=1
source "$source_dir/../src/include/log.bash"

set -e # exit on any error

echo $(cyan "$(bold)Rotate time:")
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
touch -d "yesterday" $LOG_FILE
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
log INFO "This is a short line to fill up the log file."
echo

rm -rf $LOG_FILE* 2>/dev/null
exit 0
