#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
source "$source_dir/../src/include/process.bash"

# Configuration

LIMIT_TIME=${LIMIT_TIME:-3600}        # max. 1 hour to collect versions
LIMIT_NUM=${LIMIT_NUM:-10000}         # max. 10.000 versions
LIMIT_SIZE=${LIMIT_SIZE:-1000000000}  # max. 1GB

STEPFILE=${STEPFILE:-/tmp/$(basename $0)-steps}
LOG_CONSOLE=FULL

# Tasks

f1 () {
  log_cmd sleep 3
}
f2 () {
  log_cmd sleep 1
}
f3 () {
  log_cmd sleep 1
}

# Processing

lock_exit # exit if same process is already running

# remove old stepfile
[ -e $STEPFILE ] \
  && [ "$(date -d "$(stat -c %y $STEPFILE)" +%Y-%m-%d)" != "$(date +%Y-%m-%d)" ] \
  && rm $STEPFILE

async f1 help
async f2
async_wait f1 || log_exit ALERT "Failed in call to f1"
async_wait f2 || log_exit ALERT "Failed in call to f2"
async f3
async_wait f3 || log_exit ALERT "Failed in call to f3"

rm $STEPFILE # clear steps
unlock # free the file lock

log NOTICE Done
