#!/bin/bash

source_dir=$(dirname "${BASH_SOURCE[0]}")
source "$source_dir/../src/include/process.bash"
source_dir=$(dirname "${BASH_SOURCE[0]}")

read -r -d '' HTML_HEADER <<- EOT
<html lang="de" style="background: #ddd; padding: 20px;">
  <head>
    <meta charset="UTF-8">
  </head>
  <body style="-moz-hyphens: auto; -ms-hyphens: auto; -ms-word-break: break-all; -webkit-hyphenate-after: 3; -webkit-hyphenate-before: 2; -webkit-hyphens: auto; font-family: 'Helvetica Neue',Helvetica,'Segoe UI',Arial,freesans,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'; font-size: 16px; hyphenate-lines: 3; hyphens: auto; line-height: 1.2; word-break: break-word; word-wrap: break-word;">
  <div style="float:right">
    <img src="http://www.ekz-gruppe.de/media/images/logo_divibib.png" alt="divibib Logo" style="max-width: 100%; vertical-align: middle;">
  </div>
EOT

read -r -d '' HTML_FOOTER <<- EOT
  </body>
</html>
EOT

# temp_dir=$(mktemp -d)
# COPY (SELECT * FROM dvb_manage.mng_value) TO '$temp_dir/data.csv' DELIMITER ',' CSV;

$source_dir/../src/bin/sendmail -t alexander.schilling@divibib.com -u Bash-Mail \
  -o message-content-type=html \
  -a $source_dir/sendmail <<- EOT
$HTML_HEADER
<h1>Test HTML</h1><p>Email with this script as attachement.</p>
$HTML_FOOTER
EOT
    #-a $temp_dir/data.csv

# rm -rf $temp_dir

echo Done
