#!/usr/bin/env bash

export BASHLIB_HOME=/mnt

# install needed packages
export DEBIAN_FRONTEND=noninteractive
echo "tzdata tzdata/Areas select Europe" | debconf-set-selections
echo "tzdata tzdata/Zones/Europe select Berlin" | debconf-set-selections
apt-get update &>/dev/null
apt-get install -y git tzdata curl gettext &>/dev/null

# Set timezone (for date tests)
ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime && dpkg-reconfigure -f noninteractive tzdata 2>/dev/null

# install newest bats
git clone https://github.com/bats-core/bats-core.git 2>/dev/null
cd bats-core || exit
./install.sh /usr/local >/dev/null
cd /mnt || exit
