stages:
  - Debian

bats_tests:
  stage: test
  image: debian:$DEBIAN_VERSION
  parallel:
    matrix:
      - DEBIAN_VERSION: ["10", "11", "12"]
  before_script:
    - apt-get update -qq
    - apt-get install -y git curl ca-certificates bats bats-assert bats-support
  script:
    - mkdir -p test-results
    #- bats --tap test/*.bats
    - bats --formatter junit --output test-results/ core/date.bats
  artifacts:
    when: always
    paths:
      - test-results/
    reports:
      junit: test-results/*.xml
  only:
    - main
    - merge_requests
