test:
  image: node:latest
  script:
    - npm install -g bats
    - bats test -t

#lint1:
#  image: koalaman/shellcheck:stable
#  script:
#    - echo include/*
#    - shellcheck include/colors.bash

lint:
  image: debian/latest
  before_script:
    - apt-get update
    - apt-get -y install shellcheck
  script:
    - shellcheck include/colors.bash
