#!/usr/bin/env bash
# shellcheck disable=SC2329
# shellcheck source=base disable=SC2015
test -z "${DEBUG-}" && source "$BASHLIB_HOME"/full || source "$BASHLIB_HOME"/loader

TITLE="Test suite"
USAGE="$(basename "$0") [<options>] <instance>"
OPTIONS="
n name  string  Name of Birthday Person
a age   int     Age in years
h help  -       Show Help Page"
DESCRIPTION=""
# parse and validate arguments
eval set -- "$(option_parse "$OPTIONS" "$@")"
while true; do
    case "$1" in
    -n | --name) shift 2 ;;
    -a | --age) shift 2 ;;
    -h | --help)
        help "$TITLE" "$USAGE" "$OPTIONS" "$DESCRIPTION"
        exit
        ;;
    --)
        shift
        break
        ;;
    *) die "Unerwartete option: $1" ;;
    esac
done
################################################################################################

#queue add sleep 5
#queue add sleep 4
#queue add sleep 3
#queue add sleep 8
#queue add sleep 2
#queue run
#exit

##steps init
#echo start
#async sleep 5
#async --verbose sleep 4
#async wait sleep 5
#async sleep 3
#async wait
#echo end
##steps end
#exit

#QUEUE_MAX_NUM=1
#trivy_test /tmp/_test_1474058_trivy
#_trivy_report /tmp/_test_1576440_trivy /tmp/_test_1576440_trivy/split/000014 local-test
#exit

trivy files local-test
exit

task1() { echo "task1"; }
task2() { echo "task2"; }
#tasks "task1|run task 1" "task2| run task 2"
echo -e "task1 | run task 1\ntask2 | run task 2" | tasks
exit

json=""
echo "$json" | jq
exit

SECURITY_BOARD_ID=10134
cve=CVE-2017-5336
jql="project = ${SECURITY_BOARD_ID} AND summary ~ $cve ORDER BY created ASC"
issueId="$(jira search "$jql" | head -1)"
jira get "$issueId" | jq
