#!/usr/bin/env bash
# shellcheck disable=SC2329
# shellcheck source=base disable=SC2015
test -z "${DEBUG-}" && source "$BASHLIB_HOME"/full || source "$BASHLIB_HOME"/loader

TITLE="Test suite"
USAGE="$(basename "$0") [<options>] <instance>"
OPTIONS="h help  -       Show Help Page"
DESCRIPTION=""
# parse and validate arguments
#eval set -- "$(option_parse "$OPTIONS" "$@")"
#while true; do
#    case "$1" in
#    -h | --help) help "$TITLE" "$USAGE" "$OPTIONS" "$DESCRIPTION" && exit ;;
#    --) shift && break ;;
#    *) die "Unerwartete option: $1" ;;
#    esac
#done
################################################################################################

ask ipv4
exit

in="$(
    cat <<'EOT'
col1	col2
4	four
5	five
10	ten
EOT
)"
echo "$in" | tsv to postgres --table=data
exit

server=operations.host.cloud.dvb
echo "--------"
remote false || true
echo 1
remote bashlib os false || true
echo 2
exit

dns_list | tsv filter --exact A 2 | tsv filter '^(10|172)\.' 3
exporter job=node | tsv select 1 | sed '1d;s#.*://##;s#:.*##'
exit

in=$'Number\tName\n1234\tone\n2\ttwo\n10\tten thousand and one hundred forty five\n'
#echo "$in" | tsv "$@" | tsv print
timer_info | tsv headers --remove
exit

dns_list "host.test.grp\sA" 2>/dev/null | tsv sort --natural INHALT | tsv print
while true; do
    xip=$(ask string "Welche IP soll geprüft werden" --empty)
    is set -- "$xip" || break
    ping_check $xip && error "Unter $xip läuft bereits eine VM!" || ok "Keine Reaktion bei $xip auf Ping."
done

exit

STEPS_VARIABLES="num"
steps init

task_1() {
    sleep 10
    num=1
}
sync task_1
echo "num=$num"

task_2() {
    sleep 10
    num=2
}
sync task_2
echo "num=$num"

task_3() {
    sleep 10
    num=3
}
sync task_3
echo "num=$num"

steps end

exit

timer_info #| qsv table -d $'\t'
exit

ask time
exit

server=grafana.host.cloud.dvb
remote sudo lvs --noheadings -o lv_name "$vg"
volume=$(remote sudo lvs --noheadings -o lv_name "$vg" | choose -d 1 -t "Welchem Volume soll der freie Speicher zugeordnet werden?")
info "Volume $volume vergrößern"

exit

echo "one
two
three
four
five
six
seven
eight
nine" | choose
exit

#process tree mattermost
#process wait mattermost --watch
#process tree mattermost
#exit

#queue add sleep 5
#queue add sleep 4
#queue add sleep 3
#queue add sleep 8
#queue add sleep 2
#queue run
#exit

##steps init
#echo start
#async sleep 5
#async --verbose sleep 4
#async wait sleep 5
#async sleep 3
#async wait
#echo end
##steps end
#exit

#QUEUE_MAX_NUM=1
#trivy_test /tmp/_test_1474058_trivy
#_trivy_report /tmp/_test_1576440_trivy /tmp/_test_1576440_trivy/split/000014 /home/alex/dvb/divibib-search-api
#exit

trivy files /home/alex/dvb/divibib-search-api --progress
exit

task1() { echo "task1"; }
task2() { echo "task2"; }
#tasks "task1|run task 1" "task2| run task 2"
echo -e "task1 | run task 1\ntask2 | run task 2" | tasks
exit

json=""
echo "$json" | jq
exit

SECURITY_BOARD_ID=10134
cve=CVE-2017-5336
jql="project = ${SECURITY_BOARD_ID} AND summary ~ $cve ORDER BY created ASC"
issueId="$(jira search "$jql" | head -1)"
jira get "$issueId" | jq
