#!/usr/bin/env bash
set -eE
set -o pipefail
BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}
CC_RESET=$'\033[0m'
CC_CRITICAL=$'\033[1;45m'
export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
source gettext.sh
input(){
test -p /dev/stdin&&(($#==0))&&cat -||echo "$*"
}
input_args(){
local num=${1-}
local start=$((num+2))
[ -n "$num" ]||die "No <num> argument in call to input_args!"
((num>0))||die "<num>=$num argument is not a valid number!"
test -p /dev/stdin&&cat -||echo "${@:start}"
}
input_lines(){
if [ -p /dev/stdin ]&&[ -z "${1-}" ];then
cat -
else
for arg in "$@";do echo "$arg";done
fi
}
die(){
echo -e "$CC_CRITICAL$(input "$@")$CC_RESET" >&2
exit 1
}
trap_add(){
local new="$1"
local sig="$2"
local old
old="$(trap -p "$sig"|awk -F"'" '{print $2}')"
if [[ -n $old ]];then
trap "$new; $old" "$sig"
else
trap "$new" "$sig"
fi
}
trap_remove(){
local remove="$1"
local sig="$2"
local current new
current="$(trap -p "$sig"|awk -F"'" '{print $2}')"
new="$(echo "$current"|sed "s#;* *$remove##")"
trap "$new" "$sig"
}
mktemp(){
eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -' "$@")"
local dir ext result rand
local path=${TMPDIR:-/tmp}
while true;do
case "$1" in
-d|--directory)dir=1
shift
;;
-e|--extension)ext=".$2"
shift 2
;;
-m|--memory)path="/dev/shm"
shift
;;
-p|--path)path="$2"
shift 2
;;
-r|--random)rand=$RANDOM
shift
;;
--)shift
break
;;
*)shift
esac
done
result="$path/$(basename "$0")_$1$rand$ext"
if [ -n "$rand" ];then
while [ -e "$result" ];do
result="$path/$(basename "$0")_$1$RANDOM$ext"
done
fi
if [ -n "$dir" ];then
mkdir -p "$result"
else
touch "$result"
fi
echo "$result"
}
option_parse(){
local opt name type desc short="" long=""
while IFS=$' \t\n' read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
if [ ! "$type" = "-" ];then
[ "$opt" = "-" ]||short+="$opt:"
long+="$name:,"
else
[ "$opt" = "-" ]||short+="$opt"
long+="$name,"
fi
done <<<"$1"
shift
getopt -o "$short" --long "$long" -n "$0" -- "$@"
}
option_help(){
declare opt name type desc
declare -A opt_descriptions
declare -A opt_type
declare -A opt_short
while read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
opt_descriptions[$name]="$desc"
opt_type[$name]=$type
opt_short[$name]=$opt
done <<<"$1"
echo "$(gettext "Options"):"
for name in "${!opt_descriptions[@]}";do
local type_text=""
local short_text=""
if [ ! "${opt_type[$name]}" = "-" ];then
type_text=" <${opt_type[$name]}>"
fi
if [[ ! ${opt_short[$name]} == "-" ]];then
short_text="-${opt_short[$name]}$type_text, "
fi
printf "  %-40s %s\n" "$short_text--$name$type_text" "${opt_descriptions[$name]}"
done
}
