#!/usr/bin/env bash
BASHLIB_LOADER=${BASHLIB_LOADER:-base}
option_parse(){
local opt name type desc short="" long="" spec="$1" permute
[ -n "$spec" ]||die "$(gettext 'A specification string is needed as first argument')"
if [[ $spec =~ ^\+ ]];then
permute=+
spec="${spec:1}"
fi
while IFS=$' \t\n' read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
if [ ! "$type" = "-" ];then
[ "$opt" = "-" ]||short+="$opt:"
long+="$name:,"
else
[ "$opt" = "-" ]||short+="$opt"
long+="$name,"
fi
done <<<"$spec"
shift
getopt -o "$permute$short" --long "$long" -n "$0" -- "$@"
}
option_help(){
is set --name=spec --die -- "$1"
declare opt name type desc
declare -A opt_descriptions
declare -A opt_type
declare -A opt_short
while read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
is empty -- "$opt"&&continue
opt_descriptions[$name]="$desc"
opt_type[$name]=$type
opt_short[$name]=$opt
done <<<"$1"
echo "$(gettext "Options"):"
for name in "${!opt_descriptions[@]}";do
local type_text=""
local short_text=""
if [ ! "${opt_type[$name]}" = "-" ];then
type_text=" <${opt_type[$name]}>"
fi
if [[ ! ${opt_short[$name]} == "-" ]];then
short_text="-${opt_short[$name]}$type_text, "
fi
printf "  %-40s %s\n" "$short_text--$name$type_text" "${opt_descriptions[$name]}"
done
}
input(){
test -p /dev/stdin&&(($#==0))&&cat -||echo "$*"
}
input_args(){
local num=${1-}
local start=$((num+2))
is set --name="num" --die -- "$num"
((num>0))||die "<num>=$num $(gettext 'argument is not a valid number!')"
test -p /dev/stdin&&(($#<num+2))&&cat -||echo "${@:start}"
}
input_lines(){
if [ -p /dev/stdin ]&&is empty -- "$1" ];then
cat -
else
for arg in "$@";do echo "$arg";done
fi
}
escape_args(){
local escaped_args=()
for arg in "$@";do
escaped_args+=("$(printf '%q' "$arg")")
done
echo "${escaped_args[*]}"
}
contains(){
_deprecated "use array <array-name> has <value>" warn
array "$1" has "$2"
}
array(){
is integer --name=arguments --max=3 --die -- $#
is set --name=array-name --die -- "$1"
is enum --name=command --allow="has indexof" --die -- "$2"
is set --name=value --die -- "$3"
declare -n arr="$1"
local cmd="$2"
local value="$3"
case "$cmd" in
has)for e in "${arr[@]}"
do
[ ! "$e" = "$value" ]||return 0
done
return 1
;;
indexof)for i in "${!arr[@]}"
do
if [ "${arr[i]}" = "$value" ];then
echo "$i"
return 0
fi
done
return 1
esac
}
join(){
is integer --name=arguments --max=2 --die -- $#
is set --name=array-name --die -- "$1"
local -n array=$1
local sep="${2:-,}"
local joined="${array[0]}"
for element in "${array[@]:1}";do
joined+="$sep$element"
done
echo "$joined"
}
split(){
is integer --name=arguments --max=3 --die -- $#
is set --name=array-name --die -- "$2"
local string="$1"
local -n array=$2
local sep="${3:-,}"
IFS="$sep" read -ra array <<<"$string"
}
hash(){
local keyFormat="simple"
eval set -- "$(option_parse $'k key-format +' "$@")"
while true;do
case "$1" in
-k|--key-format)keyFormat="$(check enum --allow="simple base64" -- "$2")"&&shift 2;;
--)shift&&break;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
is integer --name=arguments --max=4 --die -- $#
is set --name=array-name --die -- "$1"
is enum --name=command --allow="set get unset has contains" --die -- "$2"
declare -n arr="$1"
local cmd="$2" key value="$4"
case $keyFormat in
base64)key="$(base64 -w0 <<<"$3")";;
simple)key="${3//[^a-zA-Z0-9_]/_}"
esac
case "$cmd" in
set)is set --name=key --die -- "$3"&&arr["$key"]="$value";;
get)is set --name=key --die -- "$3"&&echo "${arr["$key"]}";;
unset)is set --name=key --die -- "$3"&&unset 'arr[$key]';;
has)is set --name=key --die -- "$3"&&[[ -v arr["$key"] ]];;
contains)is set --name=value --die -- "$3"
for key in "${!arr[@]}";do
[[ ${arr["$key"]} != "$3" ]]||return 0
done
return 1
esac
}
COLORS=$(tput colors 2>/dev/null||echo 0)
CC_RESET=$'\033[0m'
CC_RESET_FG=$'\033[39m'
CC_RESET_BG=$'\033[49m'
CC_INTENSITY_BOLD=$'\033[1m'
CC_INTENSITY_LIGHT=$'\033[2m'
CC_INTENSITY_OFF=$'\033[22m'
CC_ITALIC=$'\033[3m'
CC_ITALIC_OFF=$'\033[23m'
CC_UNDERLINE=$'\033[4m'
CC_UNDERLINE_OFF=$'\033[24m'
CC_INVERSE=$'\033[7m'
CC_INVERSE_OFF=$'\033[27m'
CC_DASHED=$'\033[9m'
CC_DASHED_OFF=$'\033[29m'
CC_BLACK=$'\033[30m'
CC_RED=$'\033[31m'
CC_GREEN=$'\033[32m'
CC_YELLOW=$'\033[33m'
CC_BLUE=$'\033[34m'
CC_MAGENTA=$'\033[35m'
CC_CYAN=$'\033[36m'
CC_WHITE=$'\033[37m'
CC_BLACK_BOLD=$'\033[90m'
CC_RED_BOLD=$'\033[91m'
CC_GREEN_BOLD=$'\033[92m'
CC_YELLOW_BOLD=$'\033[93m'
CC_BLUE_BOLD=$'\033[94m'
CC_MAGENTA_BOLD=$'\033[95m'
CC_CYAN_BOLD=$'\033[96m'
CC_WHITE_BOLD=$'\033[97m'
CC_BLACK_BG=$'\033[40m'
CC_RED_BG=$'\033[41m'
CC_GREEN_BG=$'\033[42m'
CC_YELLOW_BG=$'\033[43m'
CC_BLUE_BG=$'\033[44m'
CC_MAGENTA_BG=$'\033[45m'
CC_CYAN_BG=$'\033[46m'
CC_BLACK_BOLD_BG=$'\033[100m'
CC_RED_BOLD_BG=$'\033[101m'
CC_GREEN_BOLD_BG=$'\033[102m'
CC_YELLOW_BOLD_BG=$'\033[103m'
CC_BLUE_BOLD_BG=$'\033[104m'
CC_MAGENTA_BOLD_BG=$'\033[105m'
CC_CYAN_BOLD_BG=$'\033[106m'
color_256(){
is integer --name=arguments --max=1 --die -- $#
local num
num="$(check integer --name=num "$1" --sanitize --min=0 --max=255 --die)"
echo $'\033[38;5;'"$num"'m'
}
color_256_bg(){
is integer --name=arguments --max=1 --die -- $#
local num
num="$(check integer --name=num "$1" --sanitize --min=0 --max=255 --die)"
echo $'\033[48;5;'"$num"'m'
}
CC_CRITICAL=$'\033[1;45m'
CC_ERROR=$'\033[1;31m'
CC_WARN=$'\033[1;33m'
CC_NOTICE=$'\033[1;34m'
CC_OK=$'\033[1;32m'
CC_HEADING=$'\033[44m'
CC_INVERS=$'\033[7m'
color_table(){
is integer --name=arguments --max=0 --die -- $#
echo "Basic Colors:"
echo -e "\t${CC_BLACK}CC_BLACK\t${CC_BLACK_BOLD}CC_BLACK_BOLD\t${CC_BLACK_BG}CC_BLACK_BG\t${CC_BLACK_BOLD_BG}CC_BLACK_BOLD_BG$CC_RESET"
echo -e "\t${CC_RED}CC_RED\t\t${CC_RED_BOLD}CC_RED_BOLD\t${CC_RED_BG}CC_RED_BG\t${CC_RED_BOLD_BG}CC_RED_BOLD_BG$CC_RESET"
echo -e "\t${CC_GREEN}CC_GREEN\t${CC_GREEN_BOLD}CC_GREEN_BOLD\t${CC_GREEN_BG}CC_GREEN_BG\t${CC_GREEN_BOLD_BG}CC_GREEN_BOLD_BG$CC_RESET"
echo -e "\t${CC_YELLOW}CC_YELLOW\t${CC_YELLOW_BOLD}CC_YELLOW_BOLD\t${CC_YELLOW_BG}CC_YELLOW_BG\t${CC_YELLOW_BOLD_BG}CC_YELLOW_BOLD_BG$CC_RESET"
echo -e "\t${CC_BLUE}CC_BLUE\t\t${CC_BLUE_BOLD}CC_BLUE_BOLD\t${CC_BLUE_BG}CC_BLUE_BG\t${CC_BLUE_BOLD_BG}CC_BLUE_BOLD_BG$CC_RESET"
echo -e "\t${CC_MAGENTA}CC_MAGENTA\t${CC_MAGENTA_BOLD}CC_MAGENTA_BOLD\t${CC_MAGENTA_BG}CC_MAGENTA_BG\t${CC_MAGENTA_BOLD_BG}CC_MAGENTA_BOLD_BG$CC_RESET"
echo -e "\t${CC_CYAN}CC_CYAN\t\t${CC_CYAN_BOLD}CC_CYAN_BOLD\t${CC_CYAN_BG}CC_CYAN_BG\t${CC_CYAN_BOLD_BG}CC_CYAN_BOLD_BG$CC_RESET"
echo "Special Formats:"
echo -e "\t${CC_INTENSITY_BOLD}CC_INTENSITY_BOLD\t${CC_INTENSITY_LIGHT}CC_INTENSITY_LIGHT$CC_RESET"
echo -e "\t${CC_ITALIC}CC_ITALIC$CC_RESET"
echo -e "\t${CC_UNDERLINE}CC_UNDERLINE$CC_RESET"
echo -e "\t${CC_DASHED}CC_DASHED$CC_RESET"
echo -e "\t${CC_INVERSE}CC_INVERSE$CC_RESET"
echo "256 Color palette:"
local cols=15
local rows=15
for c in $(seq 0 "$cols");do
for r in $(seq 0 "$rows");do
num=$((r*cols+c))
echo -ne "\t$(color_256 "$num")FG $num"
done
echo ""
done
for c in $(seq 0 "$cols");do
for r in $(seq 0 "$rows");do
num=$((r*cols+c))
echo -ne "\t$(color_256_bg "$num")BG $num$CC_RESET"
done
echo ""
done
echo "Context specific colors:"
echo -e "\t${CC_CRITICAL}CC_CRITICAL$CC_RESET"
echo -e "\t${CC_ERROR}CC_ERROR$CC_RESET"
echo -e "\t${CC_WARN}CC_WARN$CC_RESET"
echo -e "\t${CC_NOTICE}CC_NOTICE$CC_RESET"
echo -e "\t${CC_OK}CC_OK$CC_RESET"
echo -e "\t${CC_HEADING}CC_HEADING$CC_RESET"
echo -e "\t${CC_INVERS}CC_INVERS$CC_RESET"
}
BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}
DEBUG=${DEBUG-}
CC_RESET=$'\033[0m'
CC_CRITICAL=$'\033[1;45m'
CC_BLACK=$'\033[30m'
now(){
is integer --name=arguments --max=0 --die -- $#
date +%s
}
date_diff(){
is integer --name=arguments --max=2 --die -- $#
local start end
is integer -- "$1"&&start="$1"||start=$(date -d "$1" +%s)||die "Date format '$1' not parsable!"
is integer -- "$2"&&end="$2"||end=$(date -d "$2" +%s)||die "Date format '$2' not parsable!"
echo $((end-start))
}
date_format(){
is integer --name=arguments --max=2 --die -- $#
is set --name=format --die -- "$1"
local value format
case $1 in
iso)format="-Iseconds";;
iso-date)format="-I";;
zulu)format="-u +%Y-%m-%dT%H:%M:%SZ";;
sql)format='+"%Y-%m-%d %H:%M:%S"';;
unix)format="+%s";;
eu-date)format="+%Y-%m-%d";;
us-date)format="+%m/%d/%Y";;
human-date)format="+%A, %B %d, %Y";;
time)format="+%H:%M:%S";;
time-short)format="+%H:%M";;
*)format="+$1"
esac
value="${2-$(now)}"
is integer -- "$value"&&eval "date -d @$value $format"||eval "date -d \"$value\" $format"||die "Date format '$value' not parsable!"
}
duration_format(){
is integer --name=arguments --max=2 --die -- $#
is enum --name=format --allow="seconds minutes hours days human" --die -- "$1"
local value
is integer -- "$2"&&value="$2"||value="$(_parse_duration "$2")"
case $1 in
seconds)echo "$value";;
minutes)echo $((value/60));;
hours)echo $((value/3600));;
days)echo $((value/86400));;
human)_format_duration "$value"
esac
}
_parse_duration(){
local input="$1"
local total=0
local overall_sign=1
local value unit v_num
if [[ $input == -* ]];then
overall_sign=-1
input="${input#-}"
elif [[ $input == +* ]];then
overall_sign=1
input="${input#+}"
fi
while read -r value unit;do
if [[ $value =~ ^[+-] ]];then
v_num="$value"
else
v_num=$((overall_sign*value))
fi
case "$unit" in
''|s|sec|secs|second|seconds)total=$((total+v_num));;
m|min|mins|minute|minutes)total=$((total+v_num*60));;
h|hr|hrs|hour|hours)total=$((total+v_num*3600));;
d|day|days)total=$((total+v_num*86400));;
w|week|weeks)total=$((total+v_num*604800));;
*)printf "$(gettext 'Invalid duration unit'): %s\n" "$unit" >&2
return 1
esac
done < <(grep -Eo '[+-]?[0-9]+[[:alpha:]]*' <<<"$input"|sed -E 's/^([+-]?[0-9]+)([[:alpha:]]*)$/\1 \2/')
printf '%d\n' "$total"
}
_format_duration(){
local total="$1"
local sign=""
if ((total<0));then
sign="-"
total=$((-total))
fi
local w=$((total/604800))
local d=$((total/86400))
local h=$(((total%86400)/3600))
local m=$(((total%3600)/60))
local s=$((total%60))
local out=""
((w))&&out+="${w}w "
((d))&&out+="${d}d "
((h))&&out+="${h}h "
((m))&&out+="${m}m "
((s))&&out+="${s}s "
is empty -- "$out"&&out="0s"&&sign=""||true
echo "$sign${out% }"
}
_timer_start=0
timer(){
case $1 in
start)_timer_start=$(date +%s.%N)
;;
stop)local seconds nano len
IFS='.' read -r seconds nano <<<"$(echo "$(date +%s.%N) - $_timer_start"|bc)"
len=$((4-${#seconds}))
((len>=0))||len=0
LANG=C printf "%0.${len}f\n" "$seconds.$nano"
debug "Measurement: $seconds.$nano"
;;
*)die "Command $1 undefined, use: start stop"
esac
}
timer_start(){
_deprecated "Use: timer start"
timer start
}
timer_stop(){
_deprecated "Use: timer stop"
timer stop
}
export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
source gettext.sh
_deprecated(){
IFS=$' \t\n' read -r line func file <<<"$(caller 1)"
local message="DEPRECATED: ${FUNCNAME[1]} at $func in $file:$line $1"
[ -n "$2" ]&&echo -e "$CC_WARN$message (update it)$CC_RESET" >&2||die "$message"
}
_stacktrace(){
local frame=1 line func src bestChoice
if [ -z "$1" ]&&((DEBUG<5));then bestChoice=1;fi
while read -r line func src < <(caller "$frame"||true);do
if [ -n "$bestChoice" ]&&[[ ! $func =~ ^is$|^check$ ]];then
printf "Triggered at %s:%d (%s)\n" "$src" "$line" "$func"|warn >&2
bestChoice=""
fi
printf "\033[1m%s:%d (%s)\n" "$src" "$line" "$func"|([ -n "$1" ]&&( ((frame==1))&&warn||notice)||debug 5)
awk -v n="$line" '
            NR>=n-2 && NR<=n+2 {
                gsub(/^[ \t]+/, "", $0)  # Remove leading spaces/tabs
                printf "%4d: %s\n", NR, $0
                if(NR==n+2) exit
            }' "$src"|sed "/$line:/s/^/"$'\033[1m'"/;/$line:/s/$/"$'\033[22m'"/"|([ -n "$1" ]&&info||debug 6)
((frame++))||true
done
}
use(){
is integer --name=arguments --max=1 --die -- $#
is set --name=module-path --die -- "$1"
local module=$1
[[ $module =~ / ]]||module="module/$module"
local path
path="$(dirname "$module")"
case $path in
core)return 0;;
module)[[ ! $BASHLIB_LOADER =~ loader|full|remote ]]||return 0
esac
debug 5 "Loading module $module"
source "$module"
}
trap_add(){
is integer --name=arguments --min=2 --max=2 --die -- $#
is set --name=code --die -- "$1"
is enum --name=signal --allow="SIGINT SIGTERM SIGHUP SIGQUIT SIGUSR1 SIGALRM EXIT ERR DEBUG" --die -- "$2"
local new="$1"
local sig="$2"
local old
old="$(trap -p "$sig"|awk -F"'" '{print $2}')"
if [[ -n $old ]];then
trap "$new; $old" "$sig"
else
trap "$new" "$sig"
fi
}
trap_remove(){
is integer --name=arguments --min=2 --max=2 --die -- $#
is set --name=code --die -- "$1"
is enum --name=signal --allow="SIGINT SIGTERM SIGHUP SIGQUIT SIGUSR1 SIGALRM EXIT ERR DEBUG" --die -- "$2"
local remove="$1"
local sig="$2"
local current new
debug 3 "remove $remove from $sig"
current="$(trap -p "$sig"|awk -F"'" '{print $2}')"
new="$(echo "$current"|sed "s#;* *$remove##")"
trap "$new" "$sig"
}
mktemp(){
eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -\nT ttl +' "$@")"
local dir ext result rand
local path=${TMPDIR:-/tmp}
while true;do
case "$1" in
-d|--directory)dir=1&&shift;;
-e|--extension)ext=".$2"&&shift 2;;
-m|--memory)path="/dev/shm"&&shift;;
-p|--path)path="$2"&&shift 2;;
-r|--random)rand=$RANDOM&&shift;;
-T|--ttl)ttl="$(duration_format seconds "$2")"&&shift 2;;
--)shift&&break;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
is integer --name=arguments --max=1 --die -- $#
local ident
is set -- "$1"&&ident="_$1"
result="$path/$(basename "$0")$ident$rand$ext"
if is empty -- "$rand";then
while [ -e "$result" ];do
result="$path/$(basename "$0")$ident$RANDOM$ext"
done
fi
if [ -e "$result" ];then
debug "already exists $result"
else
if is set -- "$dir";then
debug "create dir $result"
mkdir -p "$result"
else
debug "create file $result"
touch "$result"
fi
fi
echo "$result"
is empty -- "$ttl"||(_rm_temp "$ttl" "$result" >/dev/null 2>&1&
disown)
}
_rm_temp(){
local wait="$1" file="$2"
while [ -e "$result" ]&&((wait>0));do
sleep 1
((wait--))
done
[ ! -e "$result" ]||rm -r "$result"
debug "Removed $file after TTL $1 seconds"
}
CURL_HTTP_CODE=""
curl(){
local args=("$@")
local file res
array args has '-o'||file=$(mktemp -r)
local opt
[ -z "$file" ]||opt="-o $file"
debug "command curl -s -w \"Error: %{url_effective} with RC:%{http_code}\" $opt -L $(escape_args "$@")"
res=$(command curl -s -w "%{url_effective} with RC:%{http_code}" $opt -L "$@"|tail -1)
debug "Response: $res"
CURL_HTTP_CODE=${res: -3}
if [[ $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
if [ -n "$file" ];then
cat "$file"
rm "$file"
fi
else
if [ -n "$file" ];then
jq . "$file" >&2 2>/dev/null||cat "$file" >&2
rm "$file"
fi
error "Error: $res" >&2
return 1
fi
}
debug(){
local level=1 func text sign='>'
is integer --name=arguments --max=2 --die -- $#
is integer --min 1 -- "$1"&&level="$1"&&shift||true
IFS=$' \t\n' read -r _ func _ <<<"$(caller 0||true)"
func="${func:-(main)}"
is set -- "$DEBUG"||return 0
text="$(input "$@")"
[[ $BASHLIB_LOADER != "remote" ]]||sign='>>'
if is integer -- "$DEBUG";then
is integer --min=0 --die -- "$DEBUG"
((level<=DEBUG))||return 0
else
[[ $func =~ .*(${DEBUG//, /|}) ]]||return 0
fi
while IFS= read -r line;do
printf "$CC_BLACK%-2s %-20s %s$CC_RESET\n" "$sign" "$func" "$line" >&2
done <<<"$text"
! command -v log >/dev/null||log debug "$func: $text"
}
die(){
is integer --name=arguments --max=1 --die -- $#
local text trap line func src
text="$(input "$@")"
[[ $text != *"Uncaught exception at"* ]]||trap=1
echo -e "$CC_CRITICAL$text in ${FUNCNAME[1]}$CC_RESET" >&2
_stacktrace "$trap" 2>&1
if command -v log >/dev/null;then
log critical "$text"
_stacktrace "$trap" 2>&1|log critical
fi
sleep 1
kill -- -$$ 2>/dev/null
exit 143
}
help(){
is integer --name=arguments --min=2 --max=4 --die -- $#
is set --name=heading --die -- "$1"
is set --name=usage --die -- "$2"
heading "$(gettext Help): $1"
info "Usage: $2"
echo ""
if is set -- "$3";then
option_help "$3"
echo ""
fi
if is set -- "$4";then
echo "$4"
echo
fi
exit 0
}
heading(){
local prefix=""
is empty -- "$server"||prefix="${server-} "
printf "\n%s\n\n" "$CC_INVERS$prefix$CC_RESET$CC_HEADING$(input "$@")...$CC_RESET"
}
critical(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
printf "%s\n" "$CC_CRITICAL$text$CC_RESET"
((${#_log_active[@]}==0))||log critical "$text"
}
error(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
printf "%s\n" "$CC_ERROR$text$CC_RESET"
((${#_log_active[@]}==0))||log error "$text"
}
warn(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
printf "%s\n" "$CC_WARN$text$CC_RESET"
((${#_log_active[@]}==0))||log warn "$text"
}
notice(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
printf "%s\n" "$CC_NOTICE$text$CC_RESET"
((${#_log_active[@]}==0))||log notice "$text"
}
info(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
printf "%s\n" "$text"
((${#_log_active[@]}==0))||log info "$text"
}
ok(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
echo -e "$CC_OK$text$CC_RESET"
((${#_log_active[@]}==0))||log notice "$text"
}
invers(){
local text
text="$(input "$@")"
is set -- "$text"||return 0
echo -e "$CC_INVERS$text$CC_RESET"
((${#_log_active[@]}==0))||log info "$text"
}
color(){
local text
text="$(input_args 1 "$@")"
is set -- "$text"||return 0
echo -e "$CC_ERROR$text$CC_RESET"
((${#_log_active[@]}==0))||log info "$text"
}
uncolorize(){
input "$@"|sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}
html2md(){
input "$@"|sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li>#\n- #g;s#<[^>]*>##g'|grep -v '^$'
}
nocr(){
input "$@"|sed 's/\r$//'
}
urlencode(){
install jq
input "$@"|jq -sRr @uri|sed 's/%0A$//'
}
erase_line(){
is integer --name=arguments --max=0 --die -- $#
printf '%b' $'\e[1K\r'
}
horizontal_line(){
is integer --name=arguments --max=1 --die -- $#
is empty -- "$1"||is enum --name=format --allow="light bold double half full"--die -- "$1"
local char
case $1 in
bold)char="━";;
double)char="═";;
half)char="▄";;
full)char="█";;
*)char="─"
esac
local cols
read -r _ cols < <(stty size)
((cols>60))||cols=60
printf "%.0s$char" $(seq 1 "$cols")
}
_spinner_pid=""
spinner_start(){
is integer --name=arguments --max=2 --die -- $#
is empty -- "$1"||is enum --name=format --allow="simple arrows vertical bar fade braille roll moon clock weather" --die -- "$1"
if ! command -v tput >/dev/null 2>&1||[ ! -t 2 ];then
debug "Disabled because tput and terminal is needed"
return 0
fi
local format="${1:-braille}"
local spinner
local size=1
local chars=1
local delay=${2:-0.2}
case $format in
arrows)spinner='→↑←↓';;
vertical)spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏';;
bar)spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ '&&chars=2&&size=2;;
fade)spinner=' ░▒▓█▓▒░';;
braille)spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏';;
roll)spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓';;
moon)spinner='🌑🌒🌓🌔🌕🌖🌗🌘'&&size=2;;
clock)spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛'&&size=2;;
weather)spinner='🌤🌥🌦🌧🌨🌩🌪';;
*)spinner='-\|/'
esac
local back=$((size+1))
printf '\e[?25l'
(while
true
do
for ((i=0; i<${#spinner}; i+=chars));do
printf " %s%s" "${spinner:i:chars}" "$(printf '\b%.0s' $(seq 1 "$back"))" >/dev/tty
sleep "$delay"
done
done) \
&
_spinner_pid=$!
disown
}
spinner_stop(){
is integer --name=arguments --max=0 --die -- $#
[ -n "$_spinner_pid" ]||return
kill "$_spinner_pid" >/dev/null 2>&1
wait "$_spinner_pid" 2>/dev/null
_spinner_pid=""
printf "    \b\b\b\b"
printf '\e[?25h'
}
check(){
eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +' "$@")"
local name die sanitize min max allow
while true;do
case "$1" in
-n|--name)name="$2"&&shift 2;;
-d|--die)die=1&&shift;;
-s|--sanitize)sanitize=1&&shift;;
--min)[[ $2 =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]]&&min="$2"&&shift 2||die "$(printf "$(gettext "Parameter %s needs number")" min)";;
--max)[[ $2 =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]]&&max="$2"&&shift 2||die "$(printf "$(gettext "Parameter %s needs number")" max)";;
--allow)[ -n "$2" ]&&allow="$2"&&shift 2||die "$(gettext "A list of words is needed")";;
--)shift&&break;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
name="${name:-argument}"
local usage
usage="$(gettext "Incorrect call"): is <check> <value> [options]"
[ -n "$1" ]&&local check="$1"||die "$usage"
local val="$2" res="$2"
case $check in
set)if
[ -z "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be set with a value')"
fi
;;
empty)if
[ -n "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be empty but has »${val}«')"
fi
;;
bool)if
[[ ${val,,} =~ ^(true|t|1|yes|y|ja|j)$ ]]
then
res=1
elif [[ -z $val || ${val,,} =~ ^(false|f|0|no|n|nein)$ ]];then
res=0
else
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')"
fi
;;
integer)if
[ -n "$sanitize" ]
then
[[ $val =~ ^(-?[0-9]+) ]]&&res="${BASH_REMATCH[1]}"||true
fi
if [[ ! $res =~ ^-?[0-9]+$ ]];then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')"
fi
if [[ -n $min ]]&&[[ $min == "$max" ]];then
if ((res!=min));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
fi
elif [[ -n $min && -n $max ]];then
if ((res<min||res>max));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
fi
elif [[ -n $min ]];then
if ((res<min));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
fi
elif [[ -n $max ]];then
if ((res>max));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
fi
fi
;;
float)if
[ -n "$sanitize" ]
then
[[ $val =~ ^(-?[0-9]+([.][0-9]+)?) ]]&&res="${BASH_REMATCH[1]}"||true
fi
if [[ ! $res =~ ^-?[0-9]+([.][0-9]+)?$ ]];then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given')"
fi
if [[ -n $min ]]&&[[ $min == "$max" ]];then
if ((res!=min));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
fi
elif [[ -n $min && -n $max ]];then
if ((res<min||res>max));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
fi
elif [[ -n $min ]];then
if ((res<min));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
fi
elif [[ -n $max ]];then
if ((res>max));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
fi
fi
;;
length)val=${#val}
if [[ -n $min ]]&&[[ $min == "$max" ]];then
if ((res!=min));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')"
fi
elif [[ -n $min && -n $max ]];then
if ((val<min||val>max));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')"
fi
elif [[ -n $min ]];then
if ((val<min));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')"
fi
elif [[ -n $max ]];then
if ((val>max));then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')"
fi
fi
;;
enum)[ -n "$allow" ]||die "$(gettext "A list with --allow=<words> is needed for enum check")"
if [[ " $allow " != *" $val "* ]];then
[ -z "$die" ]&&return 1||die "$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')"
fi
;;
duration)[[ $res =~ ^-?[0-9] ]]&&res="$(duration_format seconds "$val")"||true
if [[ ! $res =~ ^-?[0-9]+$ ]];then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be an integer or human duration but »${val}« was given')"
fi
;;
path)if
[ ! -e "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing path')"
fi
;;
file)if
[ ! -f "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing file')"
fi
;;
directory)if
[ ! -d "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing directory')"
fi
;;
readable)if
[ ! -r "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be a file readable for user')"
fi
;;
writable)if
[ ! -w "$val" ]
then
[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be a file writable for user')"
fi
;;
*)die "$(eval_gettext 'A check named ${check} is not defined')"
esac
echo "$res"
}
is(){
check "$@" >/dev/null
}
num_parameters(){
_deprecated "Use: is integer $# --min=<val> --max=<val>" warn
eval set -- "$(option_parse $'- min +\n- max +\n- die +' "$@")"
local min max die
while true;do
case "$1" in
--min)min=$2
shift 2
;;
--max)max=$2
shift 2
;;
--die)die=$2
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_die(){
read -r line func file <<<"$(caller 1)"
echo "Check ${FUNCNAME[1]}: $1 ($func in $file:$line)" >&2
[ -z "$die" ]||die "$die"
return 1
}
[ -z "$min" ]||(($#>=min))||_die "[$*] $# < $min (min)"||return 1
[ -z "$max" ]||(($#<=max))||_die "[$*] $# > $max (max)"||return 1
}
is_empty(){
_deprecated "Use: is empty -- <value>"
is empty -- "$1"
}
is_integer(){
_deprecated "Use: is integer <value>" warn
is integer -- "$1"
}
is_float(){
_deprecated "Use: is float -- <value>" warn
is float -- "$1"
}
trim_start(){
is integer --name=arguments --max=2 --die -- $#
local str="${1-}"
local char="${2:-[:space:]}"
echo "${str#"${str%%[!$char]*}"}"
}
trim_end(){
is integer --name=arguments --max=2 --die -- $#
local str="${1:-}"
local char="${2:-[:space:]}"
echo "${str%"${str##*[!$char]}"}"
}
trim(){
is integer --name=arguments --max=2 --die -- $#
trim_end "$(trim_start "$1" "$2")" "$2"
}
to_alphanum(){
is integer --name=arguments --max=1 --die -- $#
local text
text="$(input "$@")"
echo "${text//[^a-zA-Z0-9_]/_}"
}
value_if_variable(){
is integer --name=arguments --max=2 --die -- $#
local _name="$1"
if [[ $_name =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]&&[ -n "${!_name-}" ];then
echo "${!_name}"
else
echo "$_name"
fi
}
[[ $- =~ i ]]||set -eE
set -o pipefail
is set -- "${BASH_VERSION:-}"||die "No bash CLI! This can only be run under bash"
((BASH_VERSINFO[0]>4||(BASH_VERSINFO[0]==4&&BASH_VERSINFO[1]>=2)))||die "No bash CLI! This can only be run under bash >=4.2!"
trap 'die "💥 Uncaught exception at »${BASH_COMMAND}« with exit code $?"' ERR
debug "Running in DEBUG=${DEBUG-} mode!"
