#!/usr/bin/env bash
option_parse(){
local opt name type desc short="" long=""
while IFS=$' \t\n' read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
if [ ! "$type" = "-" ];then
[ "$opt" = "-" ]||short+="$opt:"
long+="$name:,"
else
[ "$opt" = "-" ]||short+="$opt"
long+="$name,"
fi
done <<<"$1"
shift
getopt -o "$short" --long "$long" -n "$0" -- "$@"
}
option_help(){
declare opt name type desc
declare -A opt_descriptions
declare -A opt_type
declare -A opt_short
while read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
opt_descriptions[$name]="$desc"
opt_type[$name]=$type
opt_short[$name]=$opt
done <<<"$1"
echo "$(gettext "Options"):"
for name in "${!opt_descriptions[@]}";do
local type_text=""
local short_text=""
if [ ! "${opt_type[$name]}" = "-" ];then
type_text=" <${opt_type[$name]}>"
fi
if [[ ! ${opt_short[$name]} == "-" ]];then
short_text="-${opt_short[$name]}$type_text, "
fi
printf "  %-40s %s\n" "$short_text--$name$type_text" "${opt_descriptions[$name]}"
done
}
input(){
test -p /dev/stdin&&(($#==0))&&cat -||echo "$*"
}
input_args(){
local num=${1-}
local start=$((num+2))
[ -n "$num" ]||die "$(gettext "No <num> argument in call to input_args!")"
((num>0))||die "<num>=$num $(gettext 'argument is not a valid number!')"
test -p /dev/stdin&&cat -||echo "${@:start}"
}
input_lines(){
if [ -p /dev/stdin ]&&[ -z "${1-}" ];then
cat -
else
for arg in "$@";do echo "$arg";done
fi
}
set -eE
set -o pipefail
BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}
DEBUG=${DEBUG-}
CC_RESET=$'\033[0m'
CC_CRITICAL=$'\033[1;45m'
CC_BLACK=$'\033[30m'
declare -F "is_integer" >/dev/null||source "$BASHLIB_HOME"/module/validator
now(){
date +%s
}
date_diff(){
local start end
num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: diff_sec <start> <end>"
is_integer "$1"&&start=${1-}||start=$(date -d "$1" +%s)||die "Date format '$1' not parsable!"
is_integer "$2"&&end=${2-}||end=$(date -d "$2" +%s)||die "Date format '$2' not parsable!"
echo $((end-start))
}
date_format(){
local value format
case $1 in
iso)format="--iso-8601=seconds";;
iso-date)format="--iso-8601";;
zulu)format="-u +%Y-%m-%dT%H:%M:%SZ";;
sql)format='+"%Y-%m-%d %H:%M:%S"';;
unix)format="+%s";;
eu-date)format="+%Y-%m-%d";;
us-date)format="+%m/%d/%Y";;
human-date)format="+%A, %B %d, %Y";;
time)format="%H:%M:%S";;
time-short)format="%H:%M";;
*)format="$1"
esac
[ -n "$2" ]&&value="${2-}"||value=$(now)
is_integer "$value"&&eval "date -d @$value $format"||eval "date -d \"$value\" $format"||die "Date format '$value' not parsable!"
}
duration_format(){
local value
is_integer "$2"&&value="$2"||value="$(_parse_duration "$2")"
case $1 in
seconds)echo "$value";;
minutes)echo $((value/60));;
hours)echo $((value/3600));;
days)echo $((value/86400));;
human)_format_duration "$value"
esac
}
_parse_duration(){
local input="$1"
local total=0
local overall_sign=1
local value unit vnum
if [[ $input == -* ]];then
overall_sign=-1
input="${input#-}"
elif [[ $input == +* ]];then
overall_sign=1
input="${input#+}"
fi
while read -r value unit;do
if [[ $value =~ ^[+-] ]];then
vnum="$value"
else
vnum=$((overall_sign*value))
fi
case "$unit" in
''|s|sec|secs|second|seconds)total=$((total+vnum));;
m|min|mins|minute|minutes)total=$((total+vnum*60));;
h|hr|hrs|hour|hours)total=$((total+vnum*3600));;
d|day|days)total=$((total+vnum*86400));;
w|week|weeks)total=$((total+vnum*604800));;
*)printf "$(gettext 'Invalid duration unit'): %s\n" "$unit" >&2
return 1
esac
done < <(grep -Eo '[+-]?[0-9]+[[:alpha:]]*' <<<"$input"|sed -E 's/^([+-]?[0-9]+)([[:alpha:]]*)$/\1 \2/')
printf '%d\n' "$total"
}
_format_duration(){
local total="$1"
local sign=""
if ((total<0));then
sign="-"
total=$((-total))
fi
local w=$((total/604800))
local d=$((total/86400))
local h=$(((total%86400)/3600))
local m=$(((total%3600)/60))
local s=$((total%60))
local out=""
((w))&&out+="${w}w"
((d))&&out+="${d}d"
((h))&&out+="${h}h"
((m))&&out+="${m}m"
((s))&&out+="${s}s"
[[ -z $out ]]&&out="0s"&&sign=""
echo "$sign$out"
}
export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
source gettext.sh
_deprecated(){
IFS=$' \t\n' read -r line func file <<<"$(caller 1)"
die "DEPRECATED: ${FUNCNAME[0]} at $func in $file:$line please use [[ ... ]] instead"
}
debug(){
local level=1 func
if [[ $1 =~ ^-?[0-9]+$ ]];then
level="$1"
shift
fi
IFS=$' \t\n' read -r _ pfunc _ <<<"$(caller 2)"
IFS=$' \t\n' read -r _ func _ <<<"$(caller 1)"
[ -z "$pfunc" ]||func="$pfunc/$func"
local text
text="$(input "$@")"
test -n "$text"||return 0
[[ -n $DEBUG ]]||return 0
if [[ $DEBUG =~ ^-?[0-9]+$ ]];then
((level<=DEBUG))||return 0
else
[[ $func =~ ${DEBUG//, /|} ]]||return 0
fi
while IFS= read -r line;do
printf "$CC_BLACK> %-20s %s$CC_RESET\n" "$func" "$line"
done <<<"$text"
}
debug "Running in DEBUG=${DEBUG-} mode!"
die(){
echo -e "$CC_CRITICAL$(input "$@")$CC_RESET" >&2
exit 1
}
[ -n "${BASH_VERSION:-}" ]||die "No bash CLI! This can only be run under bash"
trap_add(){
local new="$1"
local sig="$2"
local old
old="$(trap -p "$sig"|awk -F"'" '{print $2}')"
if [[ -n $old ]];then
trap "$new; $old" "$sig"
else
trap "$new" "$sig"
fi
}
trap_remove(){
local remove="$1"
local sig="$2"
local current new
current="$(trap -p "$sig"|awk -F"'" '{print $2}')"
new="$(echo "$current"|sed "s#;* *$remove##")"
trap "$new" "$sig"
}
mktemp(){
eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -\nT ttl +' "$@")"
local dir ext result rand
local path=${TMPDIR:-/tmp}
while true;do
case "$1" in
-d|--directory)dir=1
shift
;;
-e|--extension)ext=".$2"
shift 2
;;
-m|--memory)path="/dev/shm"
shift
;;
-p|--path)path="$2"
shift 2
;;
-r|--random)rand=$RANDOM
shift
;;
-T|--ttl)ttl="$(duration_format seconds "$2")"
shift 2
;;
--)shift
break
;;
*)shift
esac
done
result="$path/$(basename "$0")_$1$rand$ext"
if [ -n "$rand" ];then
while [ -e "$result" ];do
result="$path/$(basename "$0")_$1$RANDOM$ext"
done
fi
if [ -n "$dir" ];then
mkdir -p "$result"
else
touch "$result"
fi
echo "$result"
debug "$result"
[ -z "$ttl" ]||(_rmtemp "$ttl" "$result" >/dev/null 2>&1&
disown)
}
_rmtemp(){
local wait="$1" file="$2"
while [ -e "$result" ]&&((wait>0));do
sleep 1
debug "$wait"
((wait--))
done
[ ! -e "$result" ]||rm -r "$result"
}
