#!/bin/bash

# Error handlers
#
# https://gitlab.ekz.de/divibib-betrieb/helper-lib/blob/master/doc/errors.md
#
# Usage:
#
# source ../helper-lib/errors  # load error handler
# error_message "Invalid setup, stopping!", -1

# Usage: error_message <string> <code>
function error_message {
    echo "$1" >&2   # Send message to stderr. Exclude >&2 if you don't want it that way.
    code="${2:-1}"
    [ $code = "0" ] || exit $code # don't exit on code == 0
}

