#!/bin/bash

# Error handlers
#
# https://gitlab.ekz.de/divibib-betrieb/helper-lib/blob/master/doc/errors.md
#
# Usage:
#
# source ../helper-lib/errors  # load error handler
# error_message "Invalid setup, stopping!", -1

source_dir=$(dirname "${BASH_SOURCE[0]}")
source "$source_dir/colors" # load color methods

# Usage: error_message <string> <code>
error_message() {
    echo "$(red)$(bold)$1$(reset)" >&2   # Send message to STDERR
}
exit_message() {
    error_message $1
    code="${2:-1}"
    exit $code
}
