#!/usr/bin/env bash
option_parse(){
local opt name type desc short="" long=""
local spec="$1" permut
if [[ $spec =~ ^\+ ]];then
permut=+
spec="${spec:1}"
fi
while IFS=$' \t\n' read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
if [ ! "$type" = "-" ];then
[ "$opt" = "-" ]||short+="$opt:"
long+="$name:,"
else
[ "$opt" = "-" ]||short+="$opt"
long+="$name,"
fi
done <<<"$spec"
shift
getopt -o "$permut$short" --long "$long" -n "$0" -- "$@"
}
option_help(){
declare opt name type desc
declare -A opt_descriptions
declare -A opt_type
declare -A opt_short
while read -r opt name type desc;do
[[ $opt =~ ^# ]]&&continue
[[ -z $opt ]]&&continue
opt_descriptions[$name]="$desc"
opt_type[$name]=$type
opt_short[$name]=$opt
done <<<"$1"
echo "$(gettext "Options"):"
for name in "${!opt_descriptions[@]}";do
local type_text=""
local short_text=""
if [ ! "${opt_type[$name]}" = "-" ];then
type_text=" <${opt_type[$name]}>"
fi
if [[ ! ${opt_short[$name]} == "-" ]];then
short_text="-${opt_short[$name]}$type_text, "
fi
printf "  %-40s %s\n" "$short_text--$name$type_text" "${opt_descriptions[$name]}"
done
}
input(){
test -p /dev/stdin&&(($#==0))&&cat -||echo "$*"
}
input_args(){
local num=${1-}
local start=$((num+2))
[ -n "$num" ]||die "$(gettext "No <num> argument in call to input_args!")"
((num>0))||die "<num>=$num $(gettext 'argument is not a valid number!')"
test -p /dev/stdin&&cat -||echo "${@:start}"
}
input_lines(){
if [ -p /dev/stdin ]&&[ -z "${1-}" ];then
cat -
else
for arg in "$@";do echo "$arg";done
fi
}
set -eE
set -o pipefail
BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}
DEBUG=${DEBUG-}
CC_RESET=$'\033[0m'
CC_CRITICAL=$'\033[1;45m'
CC_BLACK=$'\033[30m'
now(){
date +%s
}
date_diff(){
local start end
num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: diff_sec <start> <end>"
[[ $1 =~ ^-?[0-9]+$ ]]&&start=${1-}||start=$(date -d "$1" +%s)||die "Date format '$1' not parsable!"
[[ $2 =~ ^-?[0-9]+$ ]]&&end=${2-}||end=$(date -d "$2" +%s)||die "Date format '$2' not parsable!"
echo $((end-start))
}
date_format(){
local value format
case $1 in
iso)format="-Iseconds";;
iso-date)format="-I";;
zulu)format="-u +%Y-%m-%dT%H:%M:%SZ";;
sql)format='+"%Y-%m-%d %H:%M:%S"';;
unix)format="+%s";;
eu-date)format="+%Y-%m-%d";;
us-date)format="+%m/%d/%Y";;
human-date)format="+%A, %B %d, %Y";;
time)format="%H:%M:%S";;
time-short)format="%H:%M";;
*)format="$1"
esac
[ -n "$2" ]&&value="${2-}"||value=$(now)
[[ $value =~ ^-?[0-9]+$ ]]&&eval "date -d @$value $format"||eval "date -d \"$value\" $format"||die "Date format '$value' not parsable!"
}
duration_format(){
local value
[[ $2 =~ ^-?[0-9]+$ ]]&&value="$2"||value="$(_parse_duration "$2")"
case $1 in
seconds)echo "$value";;
minutes)echo $((value/60));;
hours)echo $((value/3600));;
days)echo $((value/86400));;
human)_format_duration "$value"
esac
}
_parse_duration(){
local input="$1"
local total=0
local overall_sign=1
local value unit vnum
if [[ $input == -* ]];then
overall_sign=-1
input="${input#-}"
elif [[ $input == +* ]];then
overall_sign=1
input="${input#+}"
fi
while read -r value unit;do
if [[ $value =~ ^[+-] ]];then
vnum="$value"
else
vnum=$((overall_sign*value))
fi
case "$unit" in
''|s|sec|secs|second|seconds)total=$((total+vnum));;
m|min|mins|minute|minutes)total=$((total+vnum*60));;
h|hr|hrs|hour|hours)total=$((total+vnum*3600));;
d|day|days)total=$((total+vnum*86400));;
w|week|weeks)total=$((total+vnum*604800));;
*)printf "$(gettext 'Invalid duration unit'): %s\n" "$unit" >&2
return 1
esac
done < <(grep -Eo '[+-]?[0-9]+[[:alpha:]]*' <<<"$input"|sed -E 's/^([+-]?[0-9]+)([[:alpha:]]*)$/\1 \2/')
printf '%d\n' "$total"
}
_format_duration(){
local total="$1"
local sign=""
if ((total<0));then
sign="-"
total=$((-total))
fi
local w=$((total/604800))
local d=$((total/86400))
local h=$(((total%86400)/3600))
local m=$(((total%3600)/60))
local s=$((total%60))
local out=""
((w))&&out+="${w}w "
((d))&&out+="${d}d "
((h))&&out+="${h}h "
((m))&&out+="${m}m "
((s))&&out+="${s}s "
[[ -z $out ]]&&out="0s"&&sign=""
echo "$sign${out% }"
}
_timer_start=0
timer_start(){
_timer_start=$(date +%s.%N)
}
timer_stop(){
local seconds nano len
IFS='.' read -r seconds nano <<<"$(echo "$(date +%s.%N) - $_timer_start"|bc)"
len=$((4-${#seconds}))
((len>=0))||len=0
LANG=C printf "%0.${len}f\n" "$seconds.$nano"
debug "Measurement: $seconds.$nano"
}
export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
source gettext.sh
_deprecated(){
IFS=$' \t\n' read -r line func file <<<"$(caller 1)"
local message="DEPRECATED: ${FUNCNAME[1]} at $func in $file:$line $1"
[ -n "$2" ]&&echo -e $'\033[1;31m'"$message (update it)$CC_RESET" >&2||die "$message"
}
_stacktrace(){
local level="${1:-5}"
local i
for ((i=1; i<${#FUNCNAME[@]}; i++));do
local func="${FUNCNAME[i]}"
local line="${BASH_LINENO[i-1]}"
local src="${BASH_SOURCE[i]}"
printf "at %s() in %s:%s\n" "$func" "$src" "$line"|debug "$level"
done
}
debug(){
local level=1 func
if [[ $1 =~ ^-?[0-9]+$ ]];then
level="$1"
shift
fi
IFS=$' \t\n' read -r _ func _ <<<"$(caller 0)"
[ -z "$pfunc" ]||[ "$pfunc" = "$func" ]||func="$pfunc/$func"
local text
text="$(input "$@")"
test -n "$text"||return 0
[[ -n $DEBUG ]]||return 0
if [[ $DEBUG =~ ^-?[0-9]+$ ]];then
((level<=DEBUG))||return 0
else
[[ $func =~ .*(${DEBUG//, /|}) ]]||return 0
fi
while IFS= read -r line;do
printf "$CC_BLACK> %-20s %s$CC_RESET\n" "$func" "$line" >&2
done <<<"$text"
}
debug "Running in DEBUG=${DEBUG-} mode!"
die(){
echo -e "$CC_CRITICAL$(input "$@")$CC_RESET" >&2
_stacktrace
exit 1
}
[ -n "${BASH_VERSION:-}" ]||die "No bash CLI! This can only be run under bash"
trap_add(){
local new="$1"
local sig="$2"
local old
old="$(trap -p "$sig"|awk -F"'" '{print $2}')"
if [[ -n $old ]];then
trap "$new; $old" "$sig"
else
trap "$new" "$sig"
fi
}
trap_remove(){
local remove="$1"
local sig="$2"
local current new
debug 3 "remove $remove from $sig"
current="$(trap -p "$sig"|awk -F"'" '{print $2}')"
new="$(echo "$current"|sed "s#;* *$remove##")"
trap "$new" "$sig"
}
mktemp(){
eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -\nT ttl +' "$@")"
local dir ext result rand
local path=${TMPDIR:-/tmp}
while true;do
case "$1" in
-d|--directory)dir=1
shift
;;
-e|--extension)ext=".$2"
shift 2
;;
-m|--memory)path="/dev/shm"
shift
;;
-p|--path)path="$2"
shift 2
;;
-r|--random)rand=$RANDOM
shift
;;
-T|--ttl)ttl="$(duration_format seconds "$2")"
shift 2
;;
--)shift
break
;;
*)shift
esac
done
local ident
[ -n "$1" ]&&ident="_$1"
result="$path/$(basename "$0")$ident$rand$ext"
if [ -n "$rand" ];then
while [ -e "$result" ];do
result="$path/$(basename "$0")$ident$RANDOM$ext"
done
fi
if [ -e "$result" ];then
debug "already exists $result"
else
if [ -n "$dir" ];then
debug "create dir $result"
mkdir -p "$result"
else
debug "create file $result"
touch "$result"
fi
fi
echo "$result"
[ -z "$ttl" ]||(_rmtemp "$ttl" "$result" >/dev/null 2>&1&
disown)
}
_rmtemp(){
local wait="$1" file="$2"
while [ -e "$result" ]&&((wait>0));do
sleep 1
((wait--))
done
[ ! -e "$result" ]||rm -r "$result"
debug "Removed $file after TTL $1 seconds"
}
contains(){
local -n array=$1
local value=$2
local e
for e in "${array[@]}";do
[[ $e != "$value" ]]||return 0
done
return 1
}
join(){
local -n array=$1
local sep="${2:-,}"
local joined="${array[0]}"
for element in "${array[@]:1}";do
joined+="$sep$element"
done
echo "$joined"
}
split(){
local string="$1"
local -n array=$2
local sep="${3:-,}"
IFS="$sep" read -ra array <<<"$string"
}
confluence(){
install jq
curl -H "Content-Type: application/json" -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" "$CONFLUENCE_API/content/$1?expand=body.storage"|jq .body.storage.value -r||die "Could not read confluence page!"
}
jira_search(){
install jq
curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X GET "$JIRA_API/search/jql?jql=$1&fields=*all"|jq '.issues[]'||die "Could not search for Jira issues using $1!"
}
jira_get(){
curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X GET "$JIRA_API/issue/$1"||die "Could not get Jira issue $1!"
}
jira_create(){
install jq
curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X POST "$JIRA_API/issue/" -d "$1"|jq '.key' -r||die "Could not create Jira issue!"
}
jira_update(){
curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X PUT "$JIRA_API/issue/$1" -d "$1"||die "Could not update Jira issue $1!"
}
COLORS=$(tput colors 2>/dev/null||echo 0)
CC_RESET=$'\033[0m'
CC_RESET_FG=$'\033[39m'
CC_RESET_BG=$'\033[49m'
CC_INTENSITY_BOLD=$'\033[1m'
CC_INTENSITY_LIGHT=$'\033[2m'
CC_INTENSITY_OFF=$'\033[22m'
CC_ITALIC=$'\033[3m'
CC_ITALIC_OFF=$'\033[23m'
CC_UNDERLINE=$'\033[4m'
CC_UNDERLINE_OFF=$'\033[24m'
CC_INVERSE=$'\033[7m'
CC_INVERSE_OFF=$'\033[27m'
CC_DASHED=$'\033[9m'
CC_DASHED_OFF=$'\033[29m'
CC_BLACK=$'\033[30m'
CC_RED=$'\033[31m'
CC_GREEN=$'\033[32m'
CC_YELLOW=$'\033[33m'
CC_BLUE=$'\033[34m'
CC_MAGENTA=$'\033[35m'
CC_CYAN=$'\033[36m'
CC_WHITE=$'\033[37m'
CC_BLACK_BOLD=$'\033[90m'
CC_RED_BOLD=$'\033[91m'
CC_GREEN_BOLD=$'\033[92m'
CC_YELLOW_BOLD=$'\033[93m'
CC_BLUE_BOLD=$'\033[94m'
CC_MAGENTA_BOLD=$'\033[95m'
CC_CYAN_BOLD=$'\033[96m'
CC_WHITE_BOLD=$'\033[97m'
CC_BLACK_BG=$'\033[40m'
CC_RED_BG=$'\033[41m'
CC_GREEN_BG=$'\033[42m'
CC_YELLOW_BG=$'\033[43m'
CC_BLUE_BG=$'\033[44m'
CC_MAGENTA_BG=$'\033[45m'
CC_CYAN_BG=$'\033[46m'
CC_BLACK_BOLD_BG=$'\033[100m'
CC_RED_BOLD_BG=$'\033[101m'
CC_GREEN_BOLD_BG=$'\033[102m'
CC_YELLOW_BOLD_BG=$'\033[103m'
CC_BLUE_BOLD_BG=$'\033[104m'
CC_MAGENTA_BOLD_BG=$'\033[105m'
CC_CYAN_BOLD_BG=$'\033[106m'
color_256(){
local num="${1//[!0-9]/}"
echo $'\033[38;5;'"${num:-0}"'m'
}
color_256_bg(){
local num="${1//[!0-9]/}"
echo $'\033[48;5;'"${num:-0}"'m'
}
CC_CRITICAL=$'\033[1;45m'
CC_ERROR=$'\033[1;31m'
CC_WARN=$'\033[1;33m'
CC_INFO=$'\033[1;34m'
CC_OK=$'\033[1;32m'
CC_HEADING=$'\033[44m'
CC_INVERS=$'\033[7m'
color_table(){
echo "Basic Colors:"
echo -e "\t${CC_BLACK}CC_BLACK\t${CC_BLACK_BOLD}CC_BLACK_BOLD\t${CC_BLACK_BG}CC_BLACK_BG\t${CC_BLACK_BOLD_BG}CC_BLACK_BOLD_BG$CC_RESET"
echo -e "\t${CC_RED}CC_RED\t\t${CC_RED_BOLD}CC_RED_BOLD\t${CC_RED_BG}CC_RED_BG\t${CC_RED_BOLD_BG}CC_RED_BOLD_BG$CC_RESET"
echo -e "\t${CC_GREEN}CC_GREEN\t${CC_GREEN_BOLD}CC_GREEN_BOLD\t${CC_GREEN_BG}CC_GREEN_BG\t${CC_GREEN_BOLD_BG}CC_GREEN_BOLD_BG$CC_RESET"
echo -e "\t${CC_YELLOW}CC_YELLOW\t${CC_YELLOW_BOLD}CC_YELLOW_BOLD\t${CC_YELLOW_BG}CC_YELLOW_BG\t${CC_YELLOW_BOLD_BG}CC_YELLOW_BOLD_BG$CC_RESET"
echo -e "\t${CC_BLUE}CC_BLUE\t\t${CC_BLUE_BOLD}CC_BLUE_BOLD\t${CC_BLUE_BG}CC_BLUE_BG\t${CC_BLUE_BOLD_BG}CC_BLUE_BOLD_BG$CC_RESET"
echo -e "\t${CC_MAGENTA}CC_MAGENTA\t${CC_MAGENTA_BOLD}CC_MAGENTA_BOLD\t${CC_MAGENTA_BG}CC_MAGENTA_BG\t${CC_MAGENTA_BOLD_BG}CC_MAGENTA_BOLD_BG$CC_RESET"
echo -e "\t${CC_CYAN}CC_CYAN\t\t${CC_CYAN_BOLD}CC_CYAN_BOLD\t${CC_CYAN_BG}CC_CYAN_BG\t${CC_CYAN_BOLD_BG}CC_CYAN_BOLD_BG$CC_RESET"
echo "Special Formats:"
echo -e "\t${CC_INTENSITY_BOLD}CC_INTENSITY_BOLD\t${CC_INTENSITY_LIGHT}CC_INTENSITY_LIGHT$CC_RESET"
echo -e "\t${CC_ITALIC}CC_ITALIC$CC_RESET"
echo -e "\t${CC_UNDERLINE}CC_UNDERLINE$CC_RESET"
echo -e "\t${CC_DASHED}CC_DASHED$CC_RESET"
echo -e "\t${CC_INVERSE}CC_INVERSE$CC_RESET"
echo "256 Color palette:"
local cols=15
local rows=15
for c in $(seq 0 "$cols");do
for r in $(seq 0 "$rows");do
num=$((r*cols+c))
echo -ne "\t$(color_256 "$num")FG $num"
done
echo ""
done
for c in $(seq 0 "$cols");do
for r in $(seq 0 "$rows");do
num=$((r*cols+c))
echo -ne "\t$(color_256_bg "$num")BG $num$CC_RESET"
done
echo ""
done
echo "Context specific colors:"
echo -e "\t${CC_CRITICAL}CC_CRITICAL$CC_RESET"
echo -e "\t${CC_ERROR}CC_ERROR$CC_RESET"
echo -e "\t${CC_WARN}CC_WARN$CC_RESET"
echo -e "\t${CC_INFO}CC_INFO$CC_RESET"
echo -e "\t${CC_OK}CC_OK$CC_RESET"
echo -e "\t${CC_HEADING}CC_HEADING$CC_RESET"
echo -e "\t${CC_INVERS}CC_INVERS$CC_RESET"
}
declare -F "num_parameters" >/dev/null||source "$BASHLIB_HOME"/module/validator
mongosh(){
num_parameters --min 2 --max 2 --die "Mongosh needs two parameters: Usage mongosh <database> <command>" "$@"
local cluster
cluster="$(sed 's/^[^.]*\.//' <<<"$server")"
command mongosh "mongodb://${MONGO_ADMIN_USERPASS["$cluster"]}@$server:27017/$1" --eval "$2"
}
postgres(){
echo "TODO"
}
declare -F "num_parameters" >/dev/null||source "$BASHLIB_HOME"/module/validator
dns_list(){
echo $'NAME\tTYPE\tCONTENT\tTTL'
powerdns "$1"|tail -n +2||true
plusserver_dns "$1"|tail -n +2||true
}
powerdns(){
if [ -z "$POWERDNS_API" ]||[ -z "$POWERDNS_TOKEN" ];then
debug "Disabled because POWERDNS_API and POWERDNS_TOKEN are not both set"
return 0
fi
echo $'NAME\tTYPE\tCONTENT\tTTL'
curl -s -H "X-API-Key:$POWERDNS_TOKEN" "$POWERDNS_API/servers/localhost/search-data?q=*&max=10000"|jq -r '.[] | select(.object_type == "record" and .disabled == false) | [(.name | sub("\\.$"; "")), .type, (.content | sub("\\.$"; "")), .ttl] | @tsv'|grep -E "$1"
}
plusserver_dns(){
if [ -z "$PLUSSERVER_PORTAL" ];then
debug "Disabled because PLUSSERVER_PORTAL is not set"
return 0
fi
local list time
list="$(ls -lt ~/Downloads/csv_list*.csv|head -1|cut -d' ' -f 9-)"
time="$(ls -lt ~/Downloads/csv_list*.csv|head -1|cut -d' ' -f 6-8)"
warn "$(eval_gettext 'To update $PLUSSERVER_PORTAL/services/nameservers -> download CSV (manually).')" >&2
test -n "$list"||die "Keine lokale DNS Liste gefunden, bitte herunterladen."
echo "Benutze $list vom $time." >&2
echo "" >&2
mlr --icsv --ifs ';' --otsv \
put '$name = $record_name . "." . $zone; $record_data = substr($record_data,0,80)' then \
cut -o -f name,record_type,record_data,record_ttl then \
sort -f name then \
rename name,NAME,record_type,TYPE,record_data,CONTENT,record_ttl,TTL \
"$list"|awk 'NR == 1 || /'"$1"'/'
}
basename(){
local path
path="$(input "$@")"
path="${path%/}"
echo "${path##*/}"
}
dirname(){
local path
path="$(input "$@")"
[[ $path == '/' ]]&&echo '/'&&return 0
[[ $path =~ ^'../' ]]&&echo '.'&&return 0
[[ ! $path =~ / ]]&&echo '.'&&return 0
echo "${path%/*}"
}
extname(){
local path
path="$(input "$@")"
[[ $path =~ ^\. ]]&&echo ''&&return
[[ ! $path =~ \. ]]&&echo ''&&return
echo ".${path##*.}"
}
script_path(){
dirname "$(readlink -f "${BASH_SOURCE[-1]:-$(pwd)/x}")"
}
declare -F "color_256" >/dev/null||source "$BASHLIB_HOME"/module/color
pause(){
local timeout abort
eval set -- "$(option_parse $'a abort -\nT timeout +' "$@")"
while true;do
case "$1" in
-T|--timeout)timeout="$(duration_format seconds "$2")"
shift 2
;;
-a|--abort)abort=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local text length
text="$(input "$@")"
if [ -z "$text" ];then
[ -n "$timeout" ]&&[ -z "$abort" ]&&text="$(gettext 'Please wait to go on')"||text="$(gettext 'Press any key to continue...')"
fi
echo -en "$CC_INFO$text$CC_RESET "
if [ -z "$timeout" ];then
read -n 1 -s -r _ </dev/tty
else
stty -echo </dev/tty
while ((timeout>0));do
echo -ne "\r$CC_INFO$text$CC_RESET $(duration_format human "$timeout")     "
if read -r -s -t 1 -n 1 _ </dev/tty;then
if [ -n "$abort" ];then
echo -e "\b\b\b\b$(gettext 'aborted by user')    "
stty echo </dev/tty
return 1
fi
fi
((timeout--))
((timeout>0))||echo -ne "\r$CC_INFO$text$CC_RESET 0s      "
done
stty echo </dev/tty
fi
echo ""
}
confirm(){
local default timeout
eval set -- "$(option_parse $'t true -\nf false -\nT timeout +' "$@")"
while true;do
case "$1" in
-t|--true)default=1
shift
;;
-f|--false)default=0
shift
;;
-T|--timeout)timeout="$(duration_format seconds "$2")"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local prompt
prompt="${1:-$(gettext "Should this be done")}"
local char="" seq itext invalid rc
local countdown="$timeout"
if [ -n "$default" ];then
((default==0))&&prompt="$prompt [$(gettext "No")]"||prompt="$prompt [$(gettext "Yes")]"
fi
echo -en "$CC_INFO$prompt?$CC_RESET " >/dev/tty
stty -echo </dev/tty
while IFS= read -r -s -t 1 -n 1 char </dev/tty||rc=$?;do
if [ -n "$invalid" ];then
invalid=0
printf ' %.0s' {1..30} >/dev/tty
printf '\b%.0s' {1..30} >/dev/tty
fi
if ((rc==142));then
rc=0
if [ -n "$timeout" ];then
((countdown--))
if ((countdown>0));then
itext="  $(duration_format human "$countdown")     "
echo -ne "$itext$(printf '\b%.0s' $(seq 1 ${#itext}))" >/dev/tty
continue
fi
else
continue
fi
fi
if [[ $char == "" ]];then
if [ -n "$default" ];then
if ((default==1));then
echo -e "$(gettext "Yes")     " >/dev/tty
stty echo </dev/tty
return 0
else
echo -e "$(gettext "No")     " >/dev/tty
stty echo </dev/tty
return 1
fi
elif [ -n "$itext" ];then
itext="$(gettext 'value needed')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
fi
elif [[ $char == $'\033' ]];then
read -r -s -n 1 -t 0.01 seq
while [[ $seq == "[" || $seq =~ [0-9A-Za-z~] ]];do
read -r -s -n 1 -t 0.01 seq||break
done
elif [[ $char =~ [JjYy] ]];then
echo -e "$(gettext "Yes")" >/dev/tty
stty echo </dev/tty
return 0
elif [[ $char =~ [Nn] ]];then
echo -e "$(gettext "No")" >/dev/tty
stty echo </dev/tty
return 1
else
itext="$(gettext 'invalid character')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
fi
itext=""
done
stty echo </dev/tty
}
ask_no(){
_deprecated "use confirm --false <question>" warn
confirm --false "$1"
}
ask_yes(){
_deprecated "use confirm --true <question>"
confirm --true "$1"
}
ask_input(){
_deprecated "use ask <question>"
ask "$@"
}
ask(){
local default empty negative timeout
eval set -- "$(option_parse $'e empty -\nd default +\nT timeout +\nn allow-negative -' "$@")"
while true;do
case "$1" in
-e|--empty)empty=1
shift
;;
-d|--default)default="$2"
shift 2
;;
-T|--timeout)timeout="$(duration_format seconds "$2")"
shift 2
;;
-n|--allow-negative)negative=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local prompt pattern mask
local format="$1"
case $format in
integer|number)prompt="${2:-$(gettext "Enter integer number")}"
if [ -n "$negative" ];then
pattern="^(0|-?([1-9][0-9]*)?)$"
final="^-?[0-9]+$"
else
pattern="^(0|[1-9][0-9]*)$"
fi
;;
float)prompt="${2:-$(gettext "Enter float number")}"
if [ -n "$negative" ];then
pattern="^(0|-?([1-9][0-9]*)?)(\.[0-9]*)?$"
final="^(0|-?[1-9][0-9]*)(\.[0-9]+)?$"
else
pattern="^(0|[1-9][0-9]*)(\.[0-9]*)?$"
final="^(0|[1-9][0-9]*)(\.[0-9]+)?$"
fi
;;
password)prompt="${2:-$(gettext "Enter password")}"
mask=1
;;
time)prompt="${2:-$(gettext "Enter time")}"
pattern="^([0-1]?[0-9]|2[0-3])(:([0-5]?[0-9])?)?$"
final="^([0-1][0-9]|2[0-3]):[0-5][0-9]$"
;;
*)prompt="${2:-$(gettext "Enter short text")}"
esac
local input="" char="" seq invalid itext utext q
local countdown="$timeout"
[ -z "$default" ]&&[ -z "$empty" ]||prompt="$prompt [$default]"
echo -en "$CC_INFO$prompt:$CC_RESET " >/dev/tty
stty -echo </dev/tty
while IFS= read -r -s -t 1 -n 1 char </dev/tty||rc=$?;do
if [ -n "$invalid" ];then
invalid=0
printf ' %.0s' {1..30} >/dev/tty
printf '\b%.0s' {1..30} >/dev/tty
fi
if ((rc==142));then
rc=0
if [ -n "$timeout" ];then
((countdown--))
if ((countdown>0));then
itext="  $(duration_format human "$countdown")     "
echo -ne "$itext$(printf '\b%.0s' $(seq 1 ${#itext}))" >/dev/tty
continue
fi
else
continue
fi
fi
if [[ $char == "" ]];then
if [ -n "$final" ];then
if [[ $input =~ $final ]];then
echo "          " >/dev/tty
break
else
itext="$(gettext 'incomplete')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
fi
elif [ -n "$input" ];then
echo "          " >/dev/tty
break
elif [ -n "$default" ];then
input="$default"
echo "          " >/dev/tty
break
elif [ -n "$empty" ];then
echo >/dev/tty
break
elif [ -n "$itext" ];then
itext="$(gettext 'value needed')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
fi
elif [[ $char == $'\177' ]];then
if [ ${#input} -gt 0 ];then
input=${input:0:-1}
echo -ne "\b \b" >/dev/tty
fi
elif [[ $char == $'\033' ]];then
read -r -s -n 1 -t 0.01 seq
while [[ $seq == "[" || $seq =~ [0-9A-Za-z~] ]];do
read -r -s -n 1 -t 0.01 seq||break
done
else
if [ -n "$pattern" ];then
debug 7 "$(od -An -to1 -v <<<"$char") [[ \"$input$char\" =~ $pattern ]] $([[ "$input$char" =~ $pattern ]]&&echo true||echo false)"
if [ "$format" = "float" ]&&[ "$char" = "," ];then
char=.
fi
if [[ ! "$input$char" =~ $pattern ]];then
itext="$(gettext 'invalid character')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
continue
fi
fi
input+="$char"
[ -n "$mask" ]&&echo -n "*" >/dev/tty||echo -n "$char" >/dev/tty
if [ "$format" = "password" ];then
q=$(_password_strength "$input")
if ((q<25));then
itext="$CC_RED$(gettext 'bad')$CC_RESET"
elif ((q<50));then
itext="$CC_YELLOW$(gettext 'weak')$CC_RESET"
elif ((q<75));then
itext="$(gettext 'good')"
else
itext="$CC_GREEN$(gettext 'strong')$CC_RESET"
fi
utext="$(uncolorize "$itext")"
echo -en "   $itext$(printf '\b%.0s' $(seq 1 $((${#utext}+3))))" >/dev/tty
invalid=1
fi
fi
itext=""
done
stty echo </dev/tty
debug 4 "Octal result: $(od -An -to1 -v <<<"$input")"
echo "$input"
}
_password_strength(){
local password="$1"
local len=${#password}
local score=0
((score+=len*4))
((score=score>40?40:score))
debug 7 "len $score"
[[ $password =~ [a-z] ]]&&((score+=5))
[[ $password =~ [A-Z] ]]&&((score+=5))
[[ $password =~ [0-9] ]]&&((score+=5))
[[ $password =~ [^a-zA-Z0-9] ]]&&((score+=5))
debug 7 "variety $score"
local unique
unique=$(echo "$password"|fold -w1|sort -u|wc -l)
((score+=unique*2))
((score=score>100?100:score))
debug 7 "uniqueness $score"
local check
for check in password qwerty qwertz;do
[[ ${password,,} =~ $check ]]&&((score-=40))
done
for check in 123 456 789 abc def ghi jkl mno pqr stv xyz;do
[[ ${password,,} =~ $check ]]&&((score-=15))
done
[[ $password =~ (.)\1{2,} ]]&&((score-=10))
((score=score<0?0:score))
debug 7 "penalties $score"
echo "$score"
}
choose(){
local end default timeout
eval set -- "$(option_parse $'t title +\nx exit +\nd default +\nT timeout +' "$@")"
while true;do
case "$1" in
-t|--title)info "$2" >/dev/tty
shift 2
;;
-d|--default)default="$2"
shift 2
;;
-x|--exit)end="$2"
shift 2
;;
-T|--timeout)timeout="$(duration_format seconds "$2")"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local list line key display num=0 pattern max
list="$(input_lines "$@")"
list="$(trim "$list"|grep -v ^#)"
max="$(wc -l <<<"$list")"
length="${#max}"
while read -r line;do
num=$((num+1))
IFS="|" read -r key display <<<"$line"
if [ -n "$default" ];then
[ "$default" = "$(trim "$key")" ]&&default="$num"||true
[ "$default" = "$(trim "$display")" ]&&default="$num"||true
fi
printf "  %0${length}d) $(trim "${display:-$key}")\n" "$num" >/dev/tty
done <<<"$list"
[ -z "$default" ]||is_integer "$default"||die "Default option $default not recognized."
[ -z "$end" ]||printf "  %${length}s) $end\n" x >/dev/tty
if ((length==1));then
pattern="[1-$max]"
elif ((length==2));then
pattern="0[1-9]?|"
((${max:0:1}==1))||pattern+="[1-$((${max:0:1}-1))][0-9]?|"
pattern+="${max:0:1}[0-${max:1:1}]?"
elif ((length==3));then
pattern="0(0[1-9]?)?|0([1-9][0-9]?)?|"
((${max:0:1}==1))||pattern+="[1-$((${max:0:1}-1))]([0-9][0-9]?)?|"
pattern+="${max:0:1}([0-$((${max:1:1}-1))][0-9]?)?|"
pattern+="${max:0:1}(${max:1:1}[0-${max:3:1}]?)?"
else
pattern="[0-9]*"
fi
((length==1))||pattern="(0|$pattern)"
[ -z "$end" ]||pattern="(x|$pattern)"
pattern="^$pattern$"
local input="" char="" itext invalid
local countdown="$timeout"
local question="$(gettext "Select one of the above options")"
[ -z "$default" ]&&timeout=""||question="$question [$default]"
echo -n "$question: " >/dev/tty
stty -echo </dev/tty
while read -r -s -t 1 -n 1 char </dev/tty||rc=$?;do
if [ -n "$invalid" ];then
invalid=0
printf ' %.0s' {1..30} >/dev/tty
printf '\b%.0s' {1..30} >/dev/tty
fi
if ((rc==142));then
rc=0
if [ -n "$timeout" ];then
((countdown--))
if ((countdown>0));then
itext="  $(duration_format human "$countdown")     "
echo -ne "$itext$(printf '\b%.0s' $(seq 1 ${#itext}))" >/dev/tty
continue
fi
else
continue
fi
fi
if [[ $char == "" ]];then
if [ -n "$final" ];then
echo "          " >/dev/tty
break
elif [ -n "$input" ];then
echo "          " >/dev/tty
break
elif [ -n "$default" ];then
input="$default"
echo "          " >/dev/tty
break
else
itext="$(gettext 'value needed')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
fi
elif [[ $char == $'\177' ]];then
if [ ${#input} -gt 0 ];then
input=${input:0:-1}
echo -ne "\b \b" >/dev/tty
fi
elif [[ $char == $'\033' ]];then
read -r -s -n 1 -t 0.01 seq
while [[ $seq == "[" || $seq =~ [0-9A-Za-z~] ]];do
read -r -s -n 1 -t 0.01 seq||break
done
elif [ -n "$end" ]&&[[ $char =~ [xX] ]];then
echo "$char" >/dev/tty
echo "exit"
stty echo </dev/tty
return 0
else
if [[ ! "$input$char" =~ $pattern ]];then
itext="$(gettext 'invalid character')"
echo -en "   $CC_RED$itext$CC_RESET$(printf '\b%.0s' $(seq 1 $((${#itext}+3))))" >/dev/tty
invalid=1
continue
fi
input+="$char"
echo -n "$char" >/dev/tty
if ((${#input}==length));then
echo >/dev/tty
break
fi
fi
done
stty echo </dev/tty
sed -n "${input}p" <<<"$list"|sed 's/\s*|.*//'
}
tasks(){
local end title _default opt loop
eval set -- "$(option_parse $'t title +\nd default +\nT timeout +\nl loop -' "$@")"
while true;do
case "$1" in
-t|--title)title="-t$2" >/dev/tty
shift 2
;;
-d|--default)_default="$2" >/dev/tty
shift 2
;;
-T|--timeout)opt="-T $2 " >/dev/tty
shift 2
;;
-l|--loop)loop=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local raw list task num newlist cmd name
find /dev/shm -regex ".*/$0_tasks_[0-9]*" -mmin +60 -delete 2>/dev/null||true
newlist="$(mktemp -m "tasks_$$")"
raw="$(input_lines "$@"|grep -v '^[[:space:]]*#')"||true
while true;do
list="$raw"
while grep -qv '|' <<<"$list";do
: >"$newlist"
while IFS= read -r line;do
IFS='|' read -r cmd name <<<"$line"
if [ -n "$name" ];then
echo "$line" >>"$newlist"
else
$cmd </dev/null >>"$newlist"||die "$(gettext "Could not get task list from command"): $cmd"
fi
done <<<"$list"
list="$(sed '/^[[:space:]]*$/d' "$newlist")"
rm "$newlist"
if [ -z "$list" ];then
ok "$(gettext "No tasks found to be executed.")"
return
fi
done
_default="$(value_if_variable "$_default")"
task=$(choose "$title" -x "$(gettext "Exit")" $opt -d "$_default" <<<"$list")
debug "choosen $task"
[[ $task != "exit" ]]||break
local error
if ! eval "$task";then
error=$?
die "$(eval_gettext 'Got error $error running $task')"
fi
echo ""
[ -n "$loop" ]||break
done
}
declare -A _mattermost_cache
_mattermost_user(){
if [[ ! -v _mattermost_cache["__u"] ]];then
debug "GET mattermost/users/me"
_mattermost_cache["__u"]="$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/users/me|jq '.id' -r)"||die "Could not find myself in mattermost!"
fi
echo "${_mattermost_cache["__u"]}"
}
_mattermost_team(){
if [[ ! -v _mattermost_cache["__t_$1"] ]];then
debug "GET mattermost/teams"
_mattermost_cache["__t_$1"]="$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/teams|jq '.[] | select(.display_name == "'"$1"'") | .id' -r)"||die "Could not get ID of team $1 in mattermost!"
fi
[ -n "${_mattermost_cache["__t_$1"]}" ]||die "Team $1 does not exist in mattermost."
echo "${_mattermost_cache["__t_$1"]}"
}
_mattermost_channel(){
if [[ ! -v _mattermost_cache["channel_$1_$2"] ]];then
debug "GET mattermost/users/me/teams/<team-id>/channels"
_mattermost_cache["channel_$1_$2"]="$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/users/me/teams/"$1"/channels|jq '.[] | select(.display_name == "'"$2"'") | .id' -r)"||die "Could not get ID of channel $1/$2 in mattermost!"
fi
[ -n "${_mattermost_cache["channel_$1_$2"]}" ]||die "Channel $2 does not exist in mattermost (team $1)"
echo "${_mattermost_cache["channel_$1_$2"]}"
}
_mattermost_channel_bypost(){
debug "GET mattermost/posts/<post-id>"
curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/posts/"$1"|jq '.channel_id' -r||die "Could not get channel of post $1 in mattermost!"
}
_mattermost_post(){
local att=""
if [ -n "$3" ];then
[[ $3 == \[* ]]&&att="$3"||att="[$3]"
att=', "props": {"attachments": '"$att"'}'
fi
local json pid
json="$(jq -n --arg c "$1" --arg t "$2" '{ channel_id: $c, message: $t '"$att"' }')"
debug "POST mattermost/posts"
debug "JSON: $json" >&2
pid=$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' -X POST "$MATTERMOST_API"/posts -d "$json"|jq '.id' -r)||die "Couls not send new post to mattermost!"
debug "-> $pid"
echo "$1/$pid"
}
_mattermost_repost(){
local att=""
if [ -n "$4" ];then
[[ $4 == \[* ]]&&att="$4"||att="[$4]"
att=', "props": {"attachments": '"$att"'}'
fi
local json pid
json="$(jq -n --arg c "$1" --arg r "$2" --arg t "$3" '{ channel_id: $c, root_id: $r, message: $t '"$att"' }')"
debug "POST mattermost/posts"
debug "JSON: $json" >&2
pid=$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' -X POST "$MATTERMOST_API"/posts -d "$json"|jq '.id' -r)||die "Could not send repost to mattermost!"
echo "$1/$pid"
}
_mattermost_reaction(){
local json
json="$(jq -n --arg u "$(_mattermost_user)" --arg p "$1" --arg t "$2" '{ user_id: $u, post_id: $p, emoji_name: $t }')"
debug "POST mattermost/reactions"
curl -X POST -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' "$MATTERMOST_API"/reactions -d "$json" > \
/dev/null||die "Could not add reaction to mattermost post!"
}
_mattermost_delete(){
debug "DELETE mattermost/posts"
curl -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' -X DELETE "$MATTERMOST_API"/posts/"$1"||die "Could not send delete to mattermost!"
}
_mattermost_find_channels(){
id(){
local val
val=$(_mattermost_channel "$1" "$2")||exit 1
echo -n "$1/$val "
}
local channel=${1:-$server}
local divibib ekz result
divibib=$(_mattermost_team divibib)||exit 1
ekz=$(_mattermost_team ekz)||exit 1
result=""
shopt -s nocasematch
local missing=0 found team
shopt -s nocasematch
for team in divibib ekz;do
found=0
for ((i=0; i<${#MATTERMOST_CHANNEL_PATTERN[@]}; i+=3));do
[[ ${MATTERMOST_CHANNEL_PATTERN[i]} == "$team" ]]||continue
if [[ $channel =~ ${MATTERMOST_CHANNEL_PATTERN[i+1]} ]];then
if [[ ${MATTERMOST_CHANNEL_PATTERN[i+2]} != "-" ]];then
id "${!team}" "${MATTERMOST_CHANNEL_PATTERN[i+2]}"
found=1
else
((missing++))||true
fi
debug "Match Mattermost channel ${MATTERMOST_CHANNEL_PATTERN[i]} ${MATTERMOST_CHANNEL_PATTERN[i+1]} ${MATTERMOST_CHANNEL_PATTERN[i+2]}"
break
fi
done
if ((found>0));then
debug "search for links"
for ((i=0; i<${#MATTERMOST_LINK_PATTERN[@]}; i+=3));do
[[ ${MATTERMOST_LINK_PATTERN[i]} == "$team" ]]||continue
if [[ $channel =~ ${MATTERMOST_LINK_PATTERN[i+1]} ]];then
id "${!team}" "${MATTERMOST_LINK_PATTERN[i+2]}"
debug "Match Mattermost link ${MATTERMOST_LINK_PATTERN[i]} ${MATTERMOST_LINK_PATTERN[i+1]} ${MATTERMOST_LINK_PATTERN[i+2]}"
break
fi
done
fi
echo ""
done
shopt -u nocasematch
((missing<2))||die "Could not detect mattermost channel for $1"
shopt -s nocasematch
}
mattermost_post_ids=""
mattermost(){
if [ -z "$MATTERMOST_API" ]||[ -z "$MATTERMOST_TOKEN" ];then
debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
return 0
fi
install jq
local channels line main links link mainid postid result
channels="$(_mattermost_find_channels "$1")"||exit 1
while read -r line;do
[ -n "$line" ]||continue
read -r main links <<<"$line"
IFS="/" read -r _ channel <<<"$main"
mainid=$(_mattermost_post "$channel" "$2" "$3")
IFS="/" read -r _ post <<<"$mainid"
result="$result\n$mainid"
while IFS=" " read -r link;do
[ -n "$link" ]||continue
IFS="/" read -r _ channel <<<"$link"
postid=$(_mattermost_post "$channel" "https://mattermost.ekz.de/divibib/pl/$post")
result="$result $postid"
done <<<"$links"
done <<<"$channels"
mattermost_post_ids="${result:2}"
}
mattermost_attachment(){
if [ -z "$MATTERMOST_API" ]||[ -z "$MATTERMOST_TOKEN" ];then
debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
return 0
fi
install jq
local json="{}"
local fields
eval set -- "$(option_parse $'- color +\n- text +\n- author +\n- avatar +\n- home +\n- title +\n- link +\n- image +\n- thumb +\n- fields +\n- footer +\n- logo +' "$@")"
while true;do
case "$1" in
--color)local color="$2"
case $color in
critical)color="#FF0000";;
error)color="#FFA500";;
warning)color="#FFFF00";;
ok)color="#008000";;
info)color="#0000FF";;
default)color="#808080"
esac
json="$(echo "$json"|jq --arg i "$color" '. + {color: $i}')"
shift 2
;;
--text)json="$(echo "$json"|jq --arg i "$2" '. + {text: $i}')"
shift 2
;;
--author)json="$(echo "$json"|jq --arg i "$2" '. + {author_name: $i}')"
shift 2
;;
--avatar)json="$(echo "$json"|jq --arg i "$2" '. + {author_icon: $i}')"
shift 2
;;
--home)json="$(echo "$json"|jq --arg i "$2" '. + {author_link: $i}')"
shift 2
;;
--title)json="$(echo "$json"|jq --arg i "$2" '. + {title: $i}')"
shift 2
;;
--link)json="$(echo "$json"|jq --arg i "$2" '. + {title_link: $i}')"
shift 2
;;
--image)json="$(echo "$json"|jq --arg i "$2" '. + {image_url: $i}')"
shift 2
;;
--thumb)json="$(echo "$json"|jq --arg i "$2" '. + {thumb_url: $i}')"
shift 2
;;
--fields)fields="$2"
shift 2
;;
--footer)json="$(echo "$json"|jq --arg i "$2" '. + {footer: $i}')"
shift 2
;;
--logo)json="$(echo "$json"|jq --arg i "$2" '. + {footer_image: $i}')"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
if [ -n "$fields" ];then
[[ $fields == \[* ]]||fields="[$fields]"
json="$(echo "$json"|jq ". + {fields: $fields}")"
fi
echo "$json"
}
mattermost_reaction(){
if [ -z "$MATTERMOST_API" ]||[ -z "$MATTERMOST_TOKEN" ];then
debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
return 0
fi
local post_links emoji line main links link channel post
eval set -- "$(option_parse $'l links -' "$@")"
while true;do
case "$1" in
-l|--links)post_links=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
emoji=$1
case $1 in
check|ok)emoji=white_check_mark
esac
while read -r line;do
[ -n "$line" ]||continue
read -r main links <<<"$line"
IFS="/" read -r channel post <<<"$main"
_mattermost_reaction "$post" "$emoji"
if [ -n "$post_links" ];then
while IFS=" " read -r link;do
[ -n "$link" ]||continue
IFS="/" read -r channel post <<<"$link"
_mattermost_reaction "$post" "$emoji"
done <<<"$links"
fi
done <<<"$mattermost_post_ids"
}
mattermost_repost(){
if [ -z "$MATTERMOST_API" ]||[ -z "$MATTERMOST_TOKEN" ];then
debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
return 0
fi
local line main channel post
while read -r line;do
[ -n "$line" ]||continue
read -r main _ <<<"$line"
debug "main $main"
IFS="/" read -r channel post <<<"$main"
debug "channel $channel post $post"
_mattermost_repost "$channel" "$post" "$1" "$2" >/dev/null
done <<<"$mattermost_post_ids"
}
declare -F "curl" >/dev/null||source "$BASHLIB_HOME"/module/remote
exporter(){
if [ -z "$PROMETHEUS_HOST" ]||[ -z "$PROMETHEUS_API" ];then
debug "Disabled because PROMETHEUS_HOST and PROMETHEUS_API are not both set"
return 0
fi
install jq yq
local arg name value
local filter=""
for arg in "$@";do
IFS='=' read -r name value <<<"$arg"
unset IFS
case $name in
instance)filter="$filter select(.labels.$name|test(\"$value\")) |";;
*)filter="$filter select(.labels.$name==\"$value\") |"
esac
done
local server api line
local auth=""
for server in $PROMETHEUS_HOST;do
remote true 2>/dev/null||continue
auth="$auth"$'\n'"$(remote cat /etc/prometheus/prometheus.yml|yq -r '.scrape_configs[] 
            | select(.basic_auth) 
            | .job_name as $j 
            | .basic_auth as $b 
            | .static_configs[].targets[] 
            | [$j, $b.username, $b.password, .] 
            | @tsv')"
done
for api in $PROMETHEUS_API;do
curl "$api"/targets|jq '.data.activeTargets[] | '"$filter"' [.scrapeUrl, .labels.job, (.labels | join(", ")), .discoveredLabels.__address__] | @tsv' -r|while read -r line;do
local login user pass
login="$(echo "$auth"|grep "$(echo "$line"|cut -f2)"|grep "$(echo "$line"|cut -f4)")"
if [ -n "$login" ];then
user="$(echo "$login"|cut -f2|tr -d '\n'|urlencode)"
pass="$(echo "$login"|cut -f3|tr -d '\n'|urlencode)"
echo "$line"|cut -f1-3|sed "s#://#://$user:$pass@#"
else
echo "$line"|cut -f1-3
fi
done||(($?==141))||die "$(gettext "Could not get exporters from prometheus!")"
done
}
scrape(){
local url="$1"
num_parameters "$@" --min 1 --max 2 --die "Wrong number of parameters for scrape!"
debug "Scrape the prometheus exporter at $1"
local metrics
metrics="$(curl "$url"|grep -Ev '^($|#)'||die "$(eval_gettext 'Could not scrape the prometheus exporter at $url!')")"
debug ">>> $metrics"
local found=2
echo "$metrics"|grep -E "$2"|grep '{'|sed 's/,\?[{}] \?/\t/g'||((found--))
echo "$metrics"|grep -E "$2"|grep -v '{'|sed 's/ /\t\t/g'||((found--))
((found>0))
}
alerts(){
if [ -z "$GRAFANA_API" ]||[ -z "$GRAFANA_TOKEN" ];then
debug "Disabled because GRAFANA_API and GRAFANA_TOKEN are not both set"
return 0
fi
local filter="" quiet
eval set -- "$(option_parse $'a alertname +\ni instance +\nn net +\ns summary +\nq quiet -' "$@")"
while true;do
case "$1" in
-i|--instance)[ -z "$2" ]||filter="$filter | select(.labels.instance|test(\"$2\"; \"i\"))"
shift 2
;;
-a|--alertname)[ -z "$2" ]||filter="$filter | select(.labels.alertname|test(\"$2\"; \"i\"))"
shift 2
;;
-s|--summary)[ -z "$2" ]||filter="$filter | select(.annotations.summary? // \"\"|test(\"$2\"; \"i\"))"
shift 2
;;
-n|--net)[ -z "$2" ]||filter="$filter | select(.labels.net? // \"\"|test(\"$2\"; \"i\"))"
shift 2
;;
-q|--quiet)quiet=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
install jq mlr
local list
list="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts")"||die "$(gettext "Could not get alerts from Grafana!")"
list="$(jq 'sort_by(.startsAt) | .[] '"$filter" <<<"$list")"||die "$(gettext "Parse error in Grafana alerts list with filter"): $filter"
local format=${1:-console}
[ -n "$list" ]||return 0
[ -z "$quiet" ]||return 1
case $format in
mattermost)list="$(jq -s '.[] | {
                color:  (if .labels.severity == "disaster" then "#ff0000"
                        elif  .labels.severity == "critical" then "#FFA500"
                        elif  .labels.severity == "warning" then "#FFFF00"
                        else "#0000FF" end), 
                title:  ((.labels.severity|(.[:1] | ascii_upcase) + .[1:]) + ": " + .labels.alertname), 
                linktitle_link: .generatorURL,
                text:   ("**" + .annotations.summary + "**\n" + .annotations.description), 
                footer: "Grafana Alerts",
                fields: (.labels 
                    | {
                        Netz:(.net|ascii_upcase),Instanz:.instance
                    } 
                    | to_entries
                    | map({title: (.key|(.[:1] | ascii_upcase) + .[1:]), value: .value, short:true})
                )
            }' <<<"$list"|jq -s .)"
;;
*)header="$(echo -e "$(gettext "Severity\tNetwork\tInstance\tSummary\tStart")")"
list="$header"$'\n'"$(jq -r '[.labels.severity, .labels.net, .labels.instance, .annotations.summary, (.startsAt| split(".")[0]| strptime("%Y-%m-%dT%H:%M:%S")| strftime("%Y-%m-%d %H:%M:%S"))] | @tsv' <<<"$list")"
esac
case $format in
console)local first=1
echo -e "$list"|tsv2table|while read -r line;do
case $line in
warning*)warn "$line";;
critical*)error "$line";;
disaster*)critical "$line";;
*)if
[ -n "$first" ]
then
invers "$line"
first=""
else
echo "$line"
fi
esac
done
;;
*)echo "$list"
esac
return 1
}
prometheus(){
if [ -z "$PROMETHEUS_API" ];then
debug "Disabled because PROMETHEUS_API is not set"
return 0
fi
local api
api="${PROMETHEUS_API%% *}"
curl "$api/query?query=$(echo "$1"|urlencode)"
}
prometheus_scrape_now(){
if [ -z "$PROMETHEUS_HOST" ];then
debug "Disabled because PROMETHEUS_HOST is not set"
return 0
fi
install yq
local job=$1
local -i seconds=${2:-60}
for server in $PROMETHEUS_HOST;do
remote true 2>/dev/null||continue
echo "Let $server scrape $job again, now."
echo "yq '(.scrape_configs[] | select(.job_name == \"$job\")).scrape_interval = \"${seconds}s\" | (.scrape_configs[] | select(.job_name == \"$job\")).scrape_timeout = \"${seconds}s\"' </etc/prometheus/prometheus.yml | sponge /etc/prometheus/prometheus.yml"|remote
remote curl -sX POST http://localhost:9090/-/reload
done
countdown "$seconds" "Wait till scrape should be done..."
echo "Reset config back to default."
for server in $PROMETHEUS_HOST;do
remote true 2>/dev/null||continue
remote /etc/prometheus/config-builder/update >/dev/null
done
}
ip_intern(){
case ${1-} in
data)echo -e "$(gettext "IP\tInterface")"
ip -o addr show|awk 'BEGIN { OFS="\t" } $2 != "lo" {print $4, $2}'
;;
*)ip route get 1|awk '{print $7; exit}'
esac
}
ip_pattern(){
num_parameters --min 1 --max 2 --die "A type has to be defined, an ip is optional." -- "$@"
local type=$1
local ip=${2-}
[ -n "$ip" ]||ip="$(ip_intern)"
local name="IP_${type^^}_PATTERN"
declare -p "$name" 2>/dev/null|grep -q 'declare \-a'||die "No configuration array $name defined."
debug "checking $ip against $name"
declare -n lookup="$name"
for ((i=0; i<${#lookup[@]}; i+=2));do
if [[ $ip =~ ${lookup[i]} ]];then
echo "${lookup[i+1]}"
return 0
fi
debug 7 "$ip =~ ${lookup[i]} => false"
done
return 1
}
_ip_extern_json=
ip_extern(){
num_parameters --min 1 --max 1 --die "A format is needed." -- "$@"
[ -n "$_ip_extern_json" ]||_ip_extern_json="$(curl http://ip-api.com/json)"
case ${1-} in
data)jq -r 'with_entries(if .key == "query" then .key = "ip" else . end) | to_entries[] | "\(.key)\t\(.value)"' <<<"$_ip_extern_json";;
ip)jq -r .query <<<"$_ip_extern_json";;
*)jq -r ".$1" <<<"$_ip_extern_json"
esac
}
detect_extern_ip(){ _deprecated "use ip_extern instead";}
declare -A _os_detected
os_detect(){
num_parameters --min 1 --max 1 --die "A format is needed." -- "$@"
if [ ${#_os_detected[@]} -eq 0 ];then
_os_detected["os"]="$(case "$(uname -s)" in
"Darwin")echo MacOS;;
"SunOS")echo Solaris;;
"GNU"*)echo Linux;;
*"BSD"|"DragonFly"|"Bitrig")echo BSD;;
"CYGWIN"*|"MSYS"*|"MINGW"*)echo Windows;;
*)uname -s
esac)"
case ${_os_detected["os"]} in
Linux)if
[ -f /etc/arch-release ]
then
_os_detected["base"]=ArchLinux
_os_detected["distribution"]="ArchLinux"
_os_detected["revision_name"]="Rolling"
_os_detected["revision_number"]="$(grep base /var/log/pacman.log|tail -n 1)"
elif [ -f /etc/gentoo-release ];then
_os_detected["base"]=Gentoo
_os_detected["distribution"]="$(cat /etc/gentoo-release|sed s/\ release.*//)"
_os_detected["revision_number"]="$(cat /etc/gentoo-release|sed s/.*release\ //|sed s/\ .*//)"
elif [ -f /etc/redhat-release ];then
_os_detected["base"]=RedHat
_os_detected["distribution"]="$(cat /etc/redhat-release|sed s/\ release.*//)"
_os_detected["revision_name"]="$(cat /etc/redhat-release|sed s/.*\(//|sed s/\)//)"
_os_detected["revision_number"]="$(cat /etc/redhat-release|sed s/.*release\ //|sed s/\ .*//)"
elif [ -f /etc/SuSE-release ];then
_os_detected["base"]=SuSe
_os_detected["revision_name"]="$(cat /etc/SuSE-release|tr "\n" ' '|sed s/VERSION.*//)"
_os_detected["revision_number"]="$(cat /etc/SuSE-release|tr "\n" ' '|sed s/.*=\ //)"
elif [ -f /etc/mandrake-release ];then
_os_detected["base"]=Mandrake
_os_detected["revision_name"]="$(cat /etc/mandrake-release|sed s/.*\(//|sed s/\)//)"
_os_detected["revision_number"]="$(cat /etc/mandrake-release|sed s/.*release\ //|sed s/\ .*//)"
elif [ -f /etc/debian_version ];then
_os_detected["base"]=Debian
local revision
revision="$(cat /etc/debian_version|sed -e 's/\([0-9]*\)\..*/\1/;s/\/.*//')"
if [[ $revision =~ [a-z] ]];then
_os_detected["base_revision_number"]="$(curl -s https://ftp.debian.org/debian/dists/"$revision"/Release|grep Version|cut -d' ' -f2|sed 's/\..*//')"
_os_detected["base_revision_name"]="$revision"
else
_os_detected["base_revision_number"]="$revision"
_os_detected["base_revision_name"]="$(grep VERSION_CODENAME /etc/os-release|cut -d= -f2)"
fi
_os_detected["distribution"]="$(grep '^NAME=' /etc/os-release|head -n 1|awk -F= '{ print $2 }'|sed 's/"//g;s/ .*//')"
_os_detected["revision_number"]="$(grep '^VERSION_ID=' /etc/os-release|head -n 1|awk -F= '{ print $2 }'|sed 's/"//g')"
_os_detected["revision_name"]="$(grep '^VERSION_CODENAME=' /etc/os-release|head -n 1|awk -F= '{ print $2 }')"
fi
esac
_os_detected["kernel"]="$(uname -r)"
_os_detected["cpu_model"]="$(grep 'model name' /proc/cpuinfo|head -n 1|sed 's/^.*: //')"
_os_detected["cpu_num"]="$(grep -c ^processor /proc/cpuinfo)"
_os_detected["architecture"]="$(case ${_os_detected["os"]} in
Solaris)uname -p;;
*)uname -m
esac)"
_os_detected["machine_id"]="$(cat /etc/machine-id /var/lib/dbus/machine-id /var/db/dbus/machine-id /sys/class/dmi/id/board_serial 2>/dev/null|head -n 1||true)"
_os_detected["virtual_machine"]="$(grep -q '^flags.* hypervisor' /proc/cpuinfo&&echo true||echo false)"
for key in "${!_os_detected[@]}";do
echo -e "$key=${_os_detected[$key]}"
done|debug
fi
case ${1-} in
data)for key in "${!_os_detected[@]}"
do
echo -e "$key\t${_os_detected[$key]}"
done
;;
info)echo -n "${_os_detected["os"]} system with kernel ${_os_detected["kernel"]} on ${_os_detected["architecture"]} (${_os_detected["cpu_num"]}x ${_os_detected["cpu_model"]})"
[ "${_os_detected["virtual_machine"]}" = "true" ]&&echo "virtual machine"||echo
echo "${_os_detected["distribution"]} version ${_os_detected["revision_number"]} (${_os_detected["revision_name"]})"
if [ -n "${_os_detected["base_revision_number"]}" ];then
echo "Based on ${_os_detected["base"]} version ${_os_detected["base_revision_number"]} (${_os_detected["base_revision_name"]})"
fi
;;
*)echo "${_os_detected["$1"]}"
esac
}
detect_os(){ _deprecated "use os_detect data";}
system_info(){ deprected "use os_detect info";}
disk_free(){
local opt="" free_operator free_percent free_bytes collect
eval set -- "$(option_parse $'l locale -\nc collect +\nf free +' "$@")"
while true;do
case "$1" in
-l|--locale)opt="-l"
shift
;;
-f|--free)local text="$2"
if [[ $text =~ ^([<>]=?|==|!=)?(([0-9]+)[%bB]?)$ ]];then
read -r _ free_operator val num <<<"${BASH_REMATCH[@]}"
free_operator="${free_operator:-<}"
[[ $val =~ ^[0-9]+%$ ]]&&free_percent="$num"||free_bytes="$(numfmt --from=iec <<<"${num^^}")"
else
die "Option value --free=$2 not supported!"
fi
shift 2
;;
-c|--collect)declare -n collect="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
debug "collect into $collect ($free_operator $free_percent%/${free_bytes}B)"
local firstline="" percent mount device limit_c limit_e limit_w limit_o
IFS=$'\n'
for line in $(df -h $opt -x tmpfs -x efivarfs -x devtmpfs -x squashfs "$@");do
if [ -z "$firstline" ];then
firstline=1
invers "$line"
else
percent=$(echo "$line"|xargs echo|cut -d' ' -f5|sed 's/%//')
bytes=$(echo "$line"|xargs echo|cut -d' ' -f4)
mount=$(echo "$line"|xargs echo|cut -d' ' -f6|nocr)
device=$(echo "$line"|xargs echo|cut -d' ' -f1)
for ((i=0; i<${#MOUNT_COLOR_LIMIT[@]}; i+=5));do
pattern="${MOUNT_COLOR_LIMIT[i]}"
if [[ $device =~ $pattern ]];then
limit_c="${MOUNT_COLOR_LIMIT[i+1]}"
limit_e="${MOUNT_COLOR_LIMIT[i+2]}"
limit_w="${MOUNT_COLOR_LIMIT[i+3]}"
limit_o="${MOUNT_COLOR_LIMIT[i+4]}"
break
fi
done
if ((percent==limit_c));then
critical "$line"
elif ((percent==limit_e));then
error "$line"
elif ((percent==limit_w));then
warn "$line"
elif ((percent==limit_o));then
ok "$line"
else
echo "$line"
fi
if [ -n "$free_operator" ];then
if [ -n "$free_percent" ]&&eval "(( 100 - percent $free_operator free_percent ))";then
collect+="$mount "
elif [ -n "$free_bytes" ]&&eval "(( bytes $free_operator free_bytes ))";then
collect+="$mount "
fi
fi
fi
done
unset IFS
}
has_tty(){
{ : >/dev/tty;} &>/dev/null
}
is_bash(){
[[ -n ${BASH_VERSION:-} ]]
}
help(){
heading "Hilfe: $1"
info "Usage: $2"
echo ""
if [ -n "$3" ];then
option_help "$3"
echo ""
fi
echo "$4"
exit 0
}
heading(){
local prefix=""
test -z "${server-}"||prefix="${server-} "
echo -e "\n$CC_INVERS$prefix$CC_RESET$CC_HEADING$(input "$@")...$CC_RESET\n"
}
critical(){
local text
text="$(input "$@")"
test -z "$text"||echo -e "$CC_CRITICAL$text$CC_RESET"
}
error(){
local text
text="$(input "$@")"
test -z "$text"||echo -e "$CC_ERROR$text$CC_RESET"
}
warn(){
local text
text="$(input "$@")"
test -z "$text"||echo -e "$CC_WARN$text$CC_RESET"
}
info(){
local text
text="$(input "$@")"
test -z "$text"||echo -e "$CC_INFO$text$CC_RESET"
}
ok(){
local text
text="$(input "$@")"
test -z "$text"||echo -e "$CC_OK$text$CC_RESET"
}
invers(){
local text
text="$(input "$@")"
test -z "$text"||echo -e "$CC_INVERS$text$CC_RESET"
}
color(){
local text
text="$(input_args 1 "$@")"
test -z "$text"||echo -e "$CC_ERROR$text$CC_RESET"
}
uncolorize(){
input "$@"|sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}
html2md(){
input "$@"|sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li>#\n- #g;s#<[^>]*>##g'|grep -v '^$'
}
nocr(){
input "$@"|sed 's/\r$//'
}
urlencode(){
install jq
input "$@"|jq -sRr @uri|sed 's/%0A$//'
}
tsv2table(){
install mlr
input "$@"|mlr --csvlite --ifs '\t' -o pprint cat
}
tsv2md(){
install mlr
input "$@"|uncolorize|mlr --csvlite --ifs '\t' --omd cat
}
erase_line(){
printf '%b' $'\e[1K\r'
}
_spinner_pid=""
spinner_start(){
if ! command -v tput >/dev/null 2>&1||[ ! -t 2 ];then
debug "Disabled because tput and terminal is needed"
return 0
fi
local format="${1:-braile}"
local spinner
local size=1
local chars=1
local delay=${2:-0.2}
case $format in
arrows)spinner='→↑←↓';;
vertical)spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏';;
bar)spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ '&&chars=2&&size=2;;
fade)spinner=' ░▒▓█▓▒░';;
braile)spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏';;
roll)spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓';;
moon)spinner='🌑🌒🌓🌔🌕🌖🌗🌘'&&size=2;;
clock)spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛'&&size=2;;
weather)spinner='🌤🌥🌦🌧🌨🌩🌪';;
*)spinner='-\|/'
esac
local back=$((size+1))
tput civis
(while
true
do
for ((i=0; i<${#spinner}; i+=chars));do
printf " %s%s" "${spinner:i:chars}" "$(printf '\b%.0s' $(seq 1 "$back"))" >/dev/tty
sleep "$delay"
done
done) \
&
_spinner_pid=$!
disown
}
spinner_stop(){
[ -n "$_spinner_pid" ]||return
kill "$_spinner_pid" >/dev/null 2>&1
wait "$_spinner_pid" 2>/dev/null
_spinner_pid=""
printf "    \b\b\b\b"
tput cnorm
}
sudo_allow(){
((EUID!=0))||return 0
command -v sudo >/dev/null||return 0
command sudo -ln "$@" >/dev/null||die "User $(whoami) is not allowed to call 'sudo $*', but this is neccessary!"
}
sudo(){
if ((EUID!=0))&&command -v sudo >/dev/null;then
command sudo "$@"
else
"$@"
fi
}
repeat(){
local -i n=$1
((n>0))||return
shift
for n in $(seq "$n");do
debug 3 "call #$n: $*"
"$@"
done
}
function retry {
local retries=$1
shift
local count=0 exit wait
until "$@";do
exit=$?
wait=$((2**count))
count=$((count+1))
if ((count<retries));then
debug 3 "Try $count/$retries exited $exit, retrying in $wait seconds..."
sleep "$wait"
else
debug 3 "Try $count/$retries exited $exit, no more retries left."
return "$exit"
fi
done
return 0
}
countdown(){ _deprecated "use pause <text> --timeout=<duration> --abort";}
LOCK_SLEEP=10
_lock_remove(){
pid=$(cat "$lockfile")||true
([ -n "$pid" ]&&kill -0 "$pid" 2>/dev/null)||rm -f "$lockfile" "$lockfile.$pid"||die "$(gettext "Failed to remove lockfile"): $lockfile"
}
lock(){
local lockfile logged pid
lockfile="$(mktemp 'lockfile')"
echo $$ >"$lockfile.$$" 2>/dev/null||die "$(gettext "Failed to create PID lockfile"): $lockfile.$$"
_lock_remove
logged=0
while ! ln "$lockfile.$$" "$lockfile" 2>/dev/null;do
if ((logged==0));then
pid="$(cat "$lockfile")"
echo "$(eval_gettext 'Waiting for unlock in $lockfile by PID $pid')..." >&1
logged=1
fi
sleep "$LOCK_SLEEP"
echo $$ >"$lockfile.$$" 2>/dev/null
_lock_remove
done
trap_add unlock EXIT
}
lock_exit(){
local lockfile logged pid
lockfile="$(mktemp 'lockfile')"
echo $$ >"$lockfile.$$" 2>/dev/null||die "$(gettext "Failed to create PID lockfile"): $lockfile.$$"
_lock_remove
if ! ln "$lockfile.$$" "$lockfile" 2>/dev/null;then
unlock
pid="$(cat "$lockfile")"
die "$(eval_gettext "Stop processing because this is locked in \$lockfile by PID $pid")"
fi
trap_add unlock EXIT
}
unlock(){
local lockfile
lockfile="$(mktemp 'lockfile')"
[ ! -e "$lockfile.$$" ]||rm -f "$lockfile.$$" 2>/dev/null
pid=$(cat "$lockfile")||true
[ -z "$pid" ]||[[ $pid != "$$" ]]||rm -r "$lockfile" 2>/dev/null
trap_remove unlock EXIT
return 0
}
env_store(){
debug "env_store $*"
eval set -- "$(option_parse $'d disk -\np path +' "$@")"
local opt="-m"
while true;do
case "$1" in
-d|--disk)opt=""
shift
;;
-p|--path)opt="$1 $2"
shift 2
;;
--)shift
break
;;
*)shift
esac
done
local ident=$1
shift||true
declare -p "$@"|sed 's/^declare\b/declare -g/' >"$(mktemp $opt -e env "$ident")"
}
env_restore(){
debug "env_restore $*"
eval set -- "$(option_parse $'d disk -\np path +' "$@")"
local opt="-m"
while true;do
case "$1" in
-d|--disk)opt=""
shift
;;
-p|--path)opt="$1 $2"
shift 2
;;
--)shift
break
;;
*)shift
esac
done
local ident="${1-}" shm_env
shift||true
shm_env="$(mktemp $opt -e env "$ident")"
[ -s "$shm_env" ]||return 0
if [[ $# -gt 0 ]];then
temp="$(mktemp -me env-sub "${ident}_$BASHPID")"
grep -E "$(tr ' ' '|' <<<"$*")" "$shm_env" >"$temp"||true
source "$temp"||true
rm -r "$temp"||true
else
source "$shm_env" 2>/dev/null||true
fi
}
env_clean(){
debug "env_clean $*"
eval set -- "$(option_parse $'d disk -\np path +' "$@")"
local opt="-m"
while true;do
case "$1" in
-d|--disk)opt=""
shift
;;
-p|--path)opt="$1 $2"
shift 2
;;
--)shift
break
;;
*)shift
esac
done
rm -f "$(mktemp $opt -e env "$1")"
}
env_change(){
eval set -- "$(option_parse $'d disk -\np path +' "$@")"
local opt
while true;do
case "$1" in
-d|--disk)opt="$opt $1"
shift
;;
-p|--path)opt="$opt $1 $2"
shift 2
;;
--)shift
break
;;
*)shift
esac
done
num_parameters --min 2 --die "At least <ident> <command> is needed!" -- "$@"
local ident=$1
shift||true
local command=$1
shift||true
env_restore $opt "$ident"
eval "$command"
env_store $opt "$ident" "$@"
}
declare -A _async_running
STEPS_VARIABLES=
steps_init(){
declare -g -A _STEPS
env_restore steps
declare -p _STEPS
env_store steps _STEPS "$STEPS_VARIABLES"
echo "$(gettext "Work steps are logged so that you can resume work mid-process")..." >&2
}
steps_check(){
local name="$1"
num_parameters --min 1 --max 1 --die "Only an <ident> is needed, but must be there!" -- "$@"
declare -p _STEPS 2>/dev/null|grep -q 'declare -A'||return 1
if [ -n "${_STEPS["$name"]}" ];then
echo "$(eval_gettext 'Job $name already done in this run, skipping')" >&2
return 0
else
return 1
fi
}
steps_done(){
local name="$1"
num_parameters --min 0 --max 1 --die "Only an <ident> is needed!" -- "$@"
declare -p _STEPS 2>/dev/null|grep -q 'declare -A'||return
if [ -n "$1" ];then
_STEPS["$name"]=1
local date="$(date_format sql)"
echo "$(eval_gettext 'Finished: Step $name at $date')" >&2
env_store steps _STEPS "$STEPS_VARIABLES"
else
env_clean steps
fi
}
sync(){
num_parameters --min 1 --die "At least a <command> is needed!" -- "$@"
sync_name "$1" "$@"
}
sync_name(){
num_parameters --min 2 --die "At least a <name> and <command> is needed!" -- "$@"
local name=$1
shift
steps_check "$name"&&return||true
local date
date="$(date_format sql)"
declare -p _STEPS 2>/dev/null|grep -q 'declare -A'&&echo "$(eval_gettext 'Started: step $name at $date')" >&2||true
"$@"
steps_done "$name"
}
async(){
num_parameters --min 1 --die "At least a <command> is needed!" -- "$@"
async_name "$1" "$@"
}
async_name(){
num_parameters --min 2 --die "At least a <name> and <command> is needed!" -- "$@"
local name=$1
shift
! steps_check "$name"||return
declare -p _STEPS 2>/dev/null|grep -q 'declare -A'&&echo "Started: step $name at $(date_format sql)" >&2||true
"$@"&
env_change queue "_async_running[\"$name\"]=$!" _queue _async_running
}
async_wait(){
[ -z "${_async_running["$1"]}" ]&&return 0||true
wait "${_async_running["$1"]}"
local code=$?
if ((code==0));then
steps_done "$1"
env_change queue "unset async_running[\"$1\"]" _queue _async_running
else
declare -p _STEPS 2>/dev/null|grep -q 'declare -A'&&echo echo "Failed: Step $1 at $(date_format sql)" >&2||true
fi
return "$code"
}
ASYNC_QUEUE_MAX=2
declare -a _queue
declare _queue_control_pid
_queue_control(){
local name pid free first params
while true;do
sleep 1
env_restore queue
if ((${#_async_running[@]}>0));then
for name in "${!_async_running[@]}";do
pid="${_async_running["$name"]}"
if ! kill -0 "$pid" 2>/dev/null;then
steps_done "$name"
env_change queue "unset _async_running[\"$name\"]" _queue _async_running
fi
done||true
fi
env_restore queue
debug "Task queue: $$ $BASHPID async ${#_async_running[@]} queue ${#_queue[@]}"
((${#_queue[@]}>0||${#_async_running[@]}>0))||return 0
free=$((ASYNC_QUEUE_MAX-${#_async_running[@]}))
if ((free>0));then
for _ in $(seq 1 "$free");do
((${#_queue[@]}>0))||break
first="${_queue[0]}"
env_change queue '_queue=("${_queue[@]:1}")' _queue _async_running
IFS=$'\x1f' read -r -a params <<<"$first"
async_name "${params[@]}"
done
fi
done
env_clean queue
}
queue(){
num_parameters --min 1 --die "At least a <command> is needed!" -- "$@"
queue_name "$1" "$@"
}
queue_name(){
num_parameters --min 2 --die "At least a <name> and <command> is needed!" -- "$@"
! steps_check "$1"||return 0
local entry
entry=$(printf "%s\x1f" "$@")
entry=${entry%$'\x1f'}
env_change queue "_queue+=(\"$entry\")" _queue _async_running
if [ -z "$_queue_control_pid" ];then
_queue_control&
_queue_control_pid=$!
fi
}
random(){
num_parameters --min 1 --die "At least a <pattern> is needed!" -- "$@"
local pattern="$1"
local length=${2:-16}
local result=""
local umlaut UMLAUT
if [[ $LANG =~ ^de ]];then
umlaut="äöüß€"
UMLAUT="ÄÖÜ"
fi
case $pattern in
num)pattern="0-9";;
letters)pattern="a-z";;
LETTERS)pattern="A-Z";;
alpha)pattern="a-zA-Z";;
alphanum)pattern="a-zA-Z0-9";;
base64)pattern="a-zA-Z0-9+/";;
printable)pattern="a-zA-Z0-9!@#$%^&*()-_=+[](){}|;:,.<>?/$umlaut$UMLAUT";;
hex)pattern="0-9a-f";;
HEX)pattern="0-9A-F"
esac
while ((${#result}<length));do
result+="$(head /dev/urandom|tr -dc "$pattern")"
done
echo "${result:0:length}"
}
declare -F "num_parameters" >/dev/null||source "$BASHLIB_HOME"/module/validator
remote(){
local _login host jump
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
if [ -p /dev/stdin ]&&(($#==0));then
ssh $ssh bash -s
return "${PIPESTATUS[0]}"
else
ssh $ssh "$@"
return "${PIPESTATUS[0]}"
fi
}
remote_term(){
local _login host jump
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
if [ -p /dev/stdin ];then
ssh -t $ssh bash -s
return "${PIPESTATUS[0]}"
else
ssh -t $ssh "$@"
return "${PIPESTATUS[0]}"
fi
}
remote_term_line(){
local _login host jump
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
if [ -p /dev/stdin ];then
ssh -t $ssh bash -s 2> >(grep -v '^Connection to .* closed\.' >&2)|nocr
return "${PIPESTATUS[0]}"
else
ssh -t $ssh "$@" 2> >(grep -v '^Connection to .* closed\.' >&2)|nocr
return "${PIPESTATUS[0]}"
fi
}
remote_file(){
local _login host jump
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
local file
file="$(input "$@")"
test "${file:0:1}" = "/"||file="$(path)/$file"
test -f "$file"||die "$(eval_gettext 'No file to execute remotely under $file')"
ssh $ssh 'bash -s' <"$file"
}
remote_console(){
local _login host jump opt
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +\nA forward-agent -' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
-A|--forward-agent)opt="-A"
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: semver_diff [-h] <first> <second>"
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
local rc
ssh $ssh '(nohup touch .hushlogin && sleep 1 && rm .hushlogin) >/dev/null 2>&1 </dev/null &'
ssh $opt $ssh </dev/tty||rc=$?
return "$rc"
}
upload(){
local _login host jump
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
local dir=${2:-~}
debug "rsync -av $1 $ssh:$dir"
rsync -av "$1" $ssh:"$dir"
}
download(){
local _login host jump
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login)_login="$2"
shift 2
;;
-h|--host)host="$2"
shift 2
;;
-j|--jump)jump="$2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
host=${host:-$server}
local ssh="$_login@$host"
[ -z "$jump" ]||ssh="-J $jump $ssh"
local dir=${2:-.}
rsync -av $ssh:"$1" "$dir"
}
remote_bashlib(){
_deprecated "use remote_bashlib os disk_free instead" warn
local opt
eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
while true;do
case "$1" in
-l|--login|-h|--host|-j|--jump)opt+=" $1 $2"
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local modules
IFS=',' read -ra modules <<<"${1-}"
shift
(echo "DEBUG=${DEBUG:-}"
if [[ ${modules[0]} =~ full|base ]];then
cat "$BASHLIB_HOME/${modules[0]}"
modules=("${modules[@]:1}")
else
cat "$BASHLIB_HOME"/base
fi
for module in "${modules[@]}";do
if [ "$module" = "configs" ];then
for f in "$BASHLIB_HOME"/config/*;do
if [[ -f $f && $f != *.* ]];then
cat "$f"
fi
done
else
[[ $module =~ .*/.* ]]||module="module/$module"
cat "$BASHLIB_HOME/$module"
fi
done
(($#==0))||echo "$*"
[ ! -p /dev/stdin ]||cat </dev/stdin)|shfmt -mn|remote $opt
}
remote_install(){
_deprecated "use remote_bashlib software install" warn
remote_bashlib software install
}
remote_system_info(){
_deprecated "use remote_bashlib os system_info" warn
remote_bashlib os system_info
}
remote_df(){
local opt=""
eval set -- "$(option_parse $'l locale -' "$@")"
while true;do
case "$1" in
-l|--locale)opt="-l"
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
if [ -n "$3" ]&&is_integer "$3";then
declare -n ref="$1"
local op="$2"
local limit=$3
shift 3
fi
local firstline="" percent mount device limit_c limit_e limit_w limit_o
IFS=$'\n'
for line in $(remote df -h $opt -x tmpfs -x efivarfs -x devtmpfs -x squashfs "$@");do
if [ -z "$firstline" ];then
firstline=1
invers "$line"
else
percent=$(echo "$line"|xargs echo|cut -d' ' -f5|sed 's/%//')
mount=$(echo "$line"|xargs echo|cut -d' ' -f6|nocr)
device=$(echo "$line"|xargs echo|cut -d' ' -f1)
for ((i=0; i<${#MOUNT_COLOR_LIMIT[@]}; i+=5));do
pattern="${MOUNT_COLOR_LIMIT[i]}"
if [[ $device =~ $pattern ]];then
limit_c="${MOUNT_COLOR_LIMIT[i+1]}"
limit_e="${MOUNT_COLOR_LIMIT[i+2]}"
limit_w="${MOUNT_COLOR_LIMIT[i+3]}"
limit_o="${MOUNT_COLOR_LIMIT[i+4]}"
break
fi
done
if ((percent==limit_c));then
critical "$line"
elif ((percent==limit_e));then
error "$line"
elif ((percent==limit_w));then
warn "$line"
elif ((percent==limit_o));then
ok "$line"
else
echo "$line"
fi
if [ -n "$limit" ]&&eval "(( percent $op limit ))";then
ref="$ref$mount "
fi
fi
done
unset IFS
echo ""
}
remote_lvm(){
remote sudo vgs --noheadings \&\& [ -n "$(sudo vgs --noheadings 2>/dev/null)" ] &>/dev/null
}
boot_wait(){
eval set -- "$(option_parse $'q quiet -' "$@")"
local quiet
while true;do
case "$1" in
-q|--quiet)quiet=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
local uptime seconds=15
echo -ne "Warten bis der Reboot fertig ist" >&2
sleep "$seconds"
while true;do
[ -n "$quiet" ]||echo -ne "\r$(eval_gettext 'Wait until the reboot is complete ($seconds seconds)')" >&2
uptime=$(remote cut -d"' '" -f1 /proc/uptime 2>/dev/null|sed 's/[ .].*//')
if ((uptime>0&&uptime<300));then
break
else
sleep 1
((seconds++))
fi
done
[ -n "$quiet" ]||remote uptime --since
[ -n "$quiet" ]||echo ""
}
CURL_HTTP_CODE=""
curl(){
local file res
file=$(mktemp -m -r)
res=$(command curl -s -w "Error: %{method} %{url_effective} with RC:%{http_code}" -o "$file" -L "$@")
CURL_HTTP_CODE=${res: -3}
if [[ $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
cat "$file"
rm "$file"
else
error "$res" >&2
jq . "$file" >&2 2>/dev/null||cat "$file" >&2
rm "$file"
return 1
fi
}
declare -A _software_install
install(){
local apt=""
local snap=""
local apk=""
local reload=""
for cmd in "$@";do
if [[ ! -v _software_install["$cmd"] ]];then
PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" which "$cmd" >/dev/null||if command -v apt-get >/dev/null;then
case $cmd in
yq)snap+=" $cmd";;
mlr)apt+=" miller";;
*)apt+=" $cmd"
esac
elif command -v apkt >/dev/null;then
case $cmd in
mlr)apk+=" miller";;
*)apk+=" $cmd"
esac
fi
_software_install["$cmd"]=1
fi
done
if test -n "$snap"&&! command -v snapd >/dev/null;then
apt="$apt snapd"
snap="$snap snapd"
reload+=" ~/.bashrc"
fi
test -z "$apt"||sudo apt-get install -y $apt
test -z "$snap"||sudo apt snap install $snap
test -z "$apk"||sudo apk update
test -z "$apk"||sudo apk add "$apk"
for file in $reload;do
source $file
done
}
semver(){
input "$@"|sed -e 's#[^0-9]*\([0-9]*:\)\?\([0-9]*\)\([.]\([0-9]*\)\)\?\([.]\([0-9]*\)\)\?\(-\([^+]*\)\)\?+\?\(.*\)\?.*#\2\n\4\n\6\n\8\n\9#'
}
semver_diff(){
eval set -- "$(option_parse "h human -" "$@")"
local human
while true;do
case "$1" in
-h|--human)human=1
shift
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: semver_diff [-h] <first> <second>"
[[ ${1-} =~ [.-] ]]&&version1="$(semver "$1")"||version1="$1"
[[ ${2-} =~ [.-] ]]&&version2="$(semver "$2")"||version2="$2"
IFS=$'\n' readarray -t v1 <<<"$version1"
IFS=$'\n' readarray -t v2 <<<"$version2"
local num=0
maj1=${v1[0]}
maj2=${v2[0]}
min1=${v1[1]:-0}
min2=${v2[1]:-0}
pat1=${v1[2]:-0}
pat2=${v2[2]:-0}
pre1=${v1[3]}
pre2=${v2[3]}
bld1=${v1[4]}
bld2=${v2[4]}
if [ "$maj1" -ne "$maj2" ];then
num=$(((maj2-maj1)*1000000000))
elif [ "$min1" -ne "$min2" ];then
num=$(((min2-min1)*1000000))
((num<1000000000))||num=999000000
elif [ "$pat1" -ne "$pat2" ];then
num=$(((pat2-pat1)*1000))
((num<1000000))||num=999000
elif [[ $pre1 < $pre2 ]];then
num=10
elif [[ $pre1 > $pre2 ]];then
num=-10
elif [[ $bld1 < $bld2 ]];then
num=1
elif [[ $bld1 > $bld2 ]];then
num=-1
fi
local step
if [ -n "$human" ];then
echo -n "$1 -> $2 "
if ((num==0));then
gettext "are identical versions"
echo
elif ((num>=1000000000));then
step=$((num/1000000000))
eval_ngettext "is an upgrade of one major version" 'is an upgrade of $step mayjor versions' "$step"
echo
elif ((num>=1000000));then
step=$((num/1000000))
eval_ngettext "is an upgrade of one minor version" 'is an upgrade of $step minor versions' "$step"
echo
elif ((num>=1000));then
step=$((num/1000))
eval_ngettext "is an upgrade of one patch version" 'is an upgrade of $step patch versions' "$step"
echo
elif ((num>=1));then
gettext "is a developer upgrade"
echo
elif ((num>=-1000));then
gettext "is a developer downgrade"
echo
elif ((num>=1000000));then
step=$((num/-1000))
eval_ngettext "is an downgrade of one patch version" 'is an downgrade of $step patch versions' "$step"
echo
elif ((num>=1000000000));then
step=$((num/-1000000))
eval_ngettext "is an upgrade of one minor version" 'is an upgrade of $step minor versions' "$step"
echo
else
step=$((num/1000000000))
eval_ngettext "is an upgrade of one major version" 'is an upgrade of $step mayjor versions' "$step"
echo
fi
return 0
else
echo "$num"
fi
((num==0))&&return 0||return 1
}
num_parameters(){
eval set -- "$(option_parse $'- min +\n- max +\n- die +' "$@")"
local min max die
while true;do
case "$1" in
--min)min=$2
shift 2
;;
--max)max=$2
shift 2
;;
--die)die=$2
shift 2
;;
--)shift
break
;;
*)die "$(gettext "Unrecognized option"): $1"
esac
done
_die(){
read -r line func file <<<"$(caller 1)"
echo "Check ${FUNCNAME[1]}: $1 ($func in $file:$line)" >&2
[ -z "$die" ]||die "$die"
return 1
}
[ -z "$min" ]||(($#>=min))||_die "[$*] $# < $min (min)"||return 1
[ -z "$max" ]||(($#<=max))||_die "[$*] $# > $max (max)"||return 1
}
is_success(){
num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
return "$1"
}
is_empty(){
num_parameters --max 1 --die "Only one argument allowed, got: $#" -- "$@"
[ -z "$1" ]
}
is_integer(){
num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
[[ $1 =~ ^-?[0-9]+$ ]]
}
is_float(){
num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
[[ $1 =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]]
}
trim_start(){
local str="${1-}"
local char="${2:-[:space:]}"
echo "${str#"${str%%[!$char]*}"}"
}
trim_end(){
local str="${1:-}"
local char="${2:-[:space:]}"
echo "${str%"${str##*[!$char]}"}"
}
trim(){
trim_end "$(trim_start "$1" "$2")" "$2"
}
value_if_variable(){
local _name="$1"
if [[ $_name =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]&&[ -n "${!_name-}" ];then
echo "${!_name}"
else
echo "$_name"
fi
}
source /home/alex/dvb/bash-lib/configs
