#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

BASHLIB_DOWNLOAD="https://gitlab.com/alinex/bash-lib/-/archive/master/bash-lib-master.tar.gz"

logo() {
    a=$'\033[36m' # cyan
    b=$'\033[93m' # yellow bold
    c=$'\033[43m' # yellow bg
    r=$'\033[0m'  # reset
    u=$'\033[4m'  # underline
    p="$(printf '%*s' $((($(tput cols) - 80) / 2)))"
    t="$(printf '%*s' $((($(tput cols) - ${#1}) / 2)))"
    echo
    echo "$p$a                         $b  __   ____     ___"
    echo "$p$a           ######  ##### $b ▕  ▏ ▕    ╲   ▕   ▏ $a  ########### #####       #####"
    echo "$p$a          ######## ##### $b ▕  ▏ ▕     ╲  ▕   ▏ $a ############  #####     #####"
    echo "$p$a         ######### ##### $b ▕  ▏ ▕  ▕╲  ╲ ▕   ▏ $a #####          #####   #####"
    echo "$p$a        ########## ##### $b ▕  ▏ ▕  ▕ ╲  ╲▕   ▏ $a #####           ##### #####"
    echo "$p$a       ##### ##### ##### $b ▕  ▏ ▕  ▕  ╲  ▔   ▏ $a ############     #########"
    echo "$p$a      #####  ##### ##### $b ▕  ▏ ▕  ▕   ╲     ▏ $a ############     #########"
    echo "$p$a     #####   ##### ##### $b ▕  ▏ ▕  ▕    ╲    ▏ $a #####           ##### #####"
    echo "$p$a    #####    ##### ##### $b  ▔▔   ▔▔▔     ▔▔▔▔  $a #####          #####   #####"
    echo "$p$a   ##### ######### ########################### ############  #####     #####"
    echo "$p$a  ##### ##########  #########################   ########### #####       ##### $r"
    echo "$p$b▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$r$c"
    echo "$t$1$r"
    echo "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$r"
    echo
}

# To avoid question give all information:
# Usage:    install <path> <y|n> <config-path>

set -eE         # exit on uncatched failure
set -o pipefail # fail if any command in a pipeline fails

logo "Bash Lib 2 - INSTALLER"

echo "This will setup the bashlib on this host if not already done..."
echo ""
# check bash version
if [ -z "${BASH_VERSION:-}" ]; then
    echo "No bash CLI! This can only be run under bash >=4.2!"
    exit 1
fi
if ((${BASH_VERSINFO[0]} < 4 || (${BASH_VERSINFO[0]} == 4 && ${BASH_VERSINFO[1]} < 2))); then
    echo "Bash library to old! This can only be run under bash >=4.2! You have Bash Version $BASH_VERSION"
    exit 1
fi
# ask for type of installation (if not update)
if [ -e /opt/bashlib ]; then
    yn=y
    echo "This will replace the instalation under /opt/bashlib"
    sudo rm -rf /opt/bashlib
elif [ -e "$HOME"/bashlib ]; then
    yn=n
    echo "This will replace the instalation under $HOME/bashlib"
    rm -rf "$HOME"/bashlib
else
    [ -n "$2" ] && yn="$2" || read -r -n 1 -s -p "Should the bashlib path be added globally (y/n) " yn </dev/tty
fi
case $yn in
"" | [JjYy])
    instdir=/opt/bashlib
    sudo mkdir "$instdir"
    config=/etc/bashlib/
    sudo mkdir "$config"
    ;;
*)
    instdir="$HOME"/bashlib
    mkdir "$instdir"
    config="$HOME"/.bashlib-
    ;;
esac

echo "Step 1: Install mandatory packages"
if [ -f /etc/debian_version ]; then
    sudo apt update 2>&1 | sed 's/^/        /g'
    sudo apt install -y bash iproute2 git tzdata curl locales gettext expect jq 2>&1 | sed 's/^/        /g'
elif [ -f /etc/alpine-release ]; then
    sudo apk update 2>&1 | sed 's/^/        /g'
    sudo apk add bash tzdata musl-locales musl-locales-lang git curl coreutils gettext expect sed jq 2>&1 | sed 's/^/        /g'
elif [ -f /etc/arch-release ]; then
    sudo pacman -Syu --noconfirm 2>&1 | sed 's/^/        /g'
    sudo pacman -Sy --noconfirm git expect jq glibc glibc-locales which less python 2>&1 | sed 's/^/        /g'
else
    echo "This operating system is currently not supported, please install on your own."
    exit 1
fi

echo "Step 2: Download bashlib to your system"
curl -L "$BASHLIB_DOWNLOAD" -o /tmp/bashlib.tgz
tar -xzf /tmp/bashlib.tgz -C "$instdir"
rm /tmp/bashlib.tgz
echo ""

echo "Step 3: Setup BASHLIB_HOME in your environment."
if [ "$instdir" = "/opt/bashlib" ]; then
    echo "BASHLIB_HOME=\"$instdir\"" | sudo tee /etc/environment.d/bashlib.conf >/dev/null
    echo "        Set in /etc/environment.d/bashlib.conf"
else
    if grep "export BASHLIB_HOME=\"$instdir\"" "$HOME"/.bashrc; then
        echo "        Already set in $HOME/.bashrc"
    else
        echo "        Added to $HOME/.bashrc"
        echo "export BASHLIB_HOME=\"$instdir\"" >>"$HOME"/.bashrc
    fi
fi
echo ""

echo "Step 4: Update local configuration files."
if [ -e "$config"secrets ]; then
    echo "        Use the existing ${config}secrets"
else
    cp "$BASHLIB_HOME"/config/secrets.example "$config"secrets
    echo "        Created example under ${config}secrets"
fi
if [ -e "$config"overwrite ]; then
    echo "        Use the existing ${config}overwrite"
else
    cp "$BASHLIB_HOME"/config/overwrite.example "$config"overwrite
    echo "        Created example under ${config}overwrite"
fi
echo "        Link files into bashlib config dir"
rm -rf "$BASHLIB_HOME"/config/secrets "$BASHLIB_HOME"/config/overwrite
ln -s "$config"secrets "$BASHLIB_HOME"/config/secrets
ln -s "$config"overwrite "$BASHLIB_HOME"/config/overwrite
echo ""

echo "You could now use the bashlib by running: source $BASHLIB_HOME/full
Or add it in your scripts.

Have fun!
"
