#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

BASHLIB_DOWNLOAD="https://gitlab.com/alinex/bash-lib/-/archive/master/bash-lib-master.tar.gz"

# To avoid question give all information:
# Usage:    install <path> <y|n> <config-path>

set -eE         # exit on uncatched failure
set -o pipefail # fail if any command in a pipeline fails

echo "This will setup the bashlib on this host if not already done..."
echo ""
# check bash version
if [ -n "${BASH_VERSION:-}" ]; then
    echo "No bash CLI! This can only be run under bash >=4.2!"
    exit 1
fi
if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
    echo "No bash CLI! This can only be run under bash >=4.2!"
    exit 1
fi
# detect os
if [ -f /etc/alpine-release ]; then
    OS=alpine
elif [ -f /etc/debian_version ]; then
    OS=debian
else
    echo "This operating system is currently not supported, please install on your own."
    exit 1
fi

echo "Step 1: Install packages"
case $OS in
debian)
    sudo apt update
    sudo apt install -y bash iproute2 git tzdata curl locales gettext expect jq
    ;;
alpine)
    sudo apk update
    sudo apk add bash tzdata musl-locales musl-locales-lang git curl coreutils gettext expect sed jq
    ;;
esac

echo "Step 2: Download bashlib to your system"
# shellcheck disable=SC2015
[ -n "$1" ] && path="$1" || read -rp "Where to put it: [$HOME/bashlib] " path </dev/tty
path="${path:-$HOME/bashlib}"
mkdir -p "$path"
curl -L "$BASHLIB_DOWNLOAD" -o /tmp/bashlib.tgz
tar -xzf /tmp/bashlib.tgz -C "$path"
rm /tmp/bashlib.tgz
echo ""

echo "Step 3: Setup BASHLIB_HOME in your environment."
# shellcheck disable=SC2015
[ -n "$2" ] && yn="$2" || read -r -n 1 -s -p "Should the bashlib path be added to $HOME/.bashrc (J/n) " yn
case $yn in
"" | [JjYy])
    echo "export BASHLIB_HOME=\"$path\"" >>"$HOME"/.bashrc
    ;;
*) true ;;
esac
echo ""

echo "Step 4: Update configuration links."
# shellcheck disable=SC2015
[ -n "$3" ] && config="$3" || read -rp "Where to put local configuration: [$HOME] " config </dev/tty
config="${config:-$HOME}"
mkdir -p "$config"
rm -rf "$BASHLIB_HOME"/config/secrets "$BASHLIB_HOME"/config/overwrite
touch "$config"/.bashlib-secrets
ln -s "$config"/.bashlib-secrets "$path"/config/secrets
touch "$config"/.bashlib-overwrite
ln -s "$config"/.bashlib-overwrite "$path"/config/overwrite
echo ""

echo "You could now use the bashlib by adding:
source $BASHLIB_HOME/full
"
