#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

for folder in core module; do
    for f in "$BASHLIB_HOME/$folder"/*; do
        if [[ -f "$f" && "$f" != *.* ]]; then
            source "$f"
        fi
    done
done

source "$BASHLIB_HOME"/configs
