#!/bin/bash

# Usage:
#
# source ./locking  # load functions
# lock <lockfile>   # create the lock
# unlock <lockfile> # remove the lock
#
# The second script will wait till the lock is released.

function lock {
    if [ "$#" -ne 1 ]; then
        echo 'lib:lock: incorrect library call use: lock [LOCKFILENAME]' 1>&2
        return 1
    fi

    local lockfile="$1"

    # make a file with our PID
    # easy way to show who's waiting for a lock
    if ! touch "$lockfile.$$" ; then
        echo "lib:lock: failed to create PID lockfile: $1" 1>&2
        return 1
    fi

    # try to symlink it
    while ! ln "$lockfile.$$" "$lockfile" 2>/dev/null
    do
        # if the symlink failed, wait for the current lock holder to exit
        sleep 1
    done

    # symlink was created successfully, lock acquired

    # if the locking process exits with unlocking, delete our lock
    trap 'rm -f "$lockfile" "$lockfile.$$"' EXIT

    return 0
}


function unlock {
    if [ "$#" -ne 1 ]; then
        echo 'lib:lock: incorrect library call use: unlock [LOCKFILENAME]' 1>&2
        return 2
    fi

    rm -f "$lockfile" # the symlink that locks are competing for
    rm -f "$lockfile.$$"

    return 0
}
