site_name: Alinex Bash Library
site_description: Helper programs and libraries for administration tool development (mostly in bash).
site_author: Alexander Schilling
copyright: Copyright &copy; 2018 - 2020 <a href="https://alinex.de">Alexander Schilling</a>

nav:
    - Home:
          - README.md
          - skeleton.md
          - CHANGELOG.md
          - roadmap.md
          - policy.md
    - Libraries:
          - libs/README.md
          - libs/core.md
          - libs/colors.md
          - libs/log.md
          - libs/info.md
          - libs/process.md
          - libs/psql.md
          - bin/README.md
    - Development:
          - dev/README.md
          - dev/build.md
    - Downloads:
          - downloads/README.md
          - downloads/license.md

theme:
    name: material
    icon:
        logo: material/code-tags
    favicon: https://assets.gitlab-static.net/uploads/-/system/project/avatar/10069235/images__1_.jpeg
    language: en
    palette:
        primary: grey
        accent: deep orange
    font: false
    # remove to be GDPR conform
    #    font:
    #        text: Roboto
    #        code: Roboto Mono
    features:
        - tabs
        - instant

repo_name: 'alinex/bash-lib'
repo_url: 'https://gitlab.com/alinex/bash-lib'

extra:
    manifest: 'manifest.webmanifest'
    social:
        - icon: material/gitlab
          link: https://gitlab.com/alinex
        - icon: material/github
          link: https://github.com/alinex
        - icon: material/book-open-variant
          link: https://alinex.gitlab.io
        - icon: material/home
          link: https://alinex.de

extra_css:
    - assets/extra.css
#PDF#    - assets/pdf.css

plugins:
    - search
# Enable for PDF export
#PDF#    - pdf-export:
#PDF#          verbose: false
#PDF#          media_type: print
#PDF#          combined: true
#PDF#          combined_output_path: alinex-bashlib.pdf
# theme_handler_path: theme-handler.py

markdown_extensions:
    - extra
    - toc:
          permalink: true
    - pymdownx.caret
    - pymdownx.tilde
    - pymdownx.mark
    - admonition
    - pymdownx.details
    - codehilite:
          guess_lang: false
          linenums: false
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
          custom_checkbox: true
    - markdown_blockdiag:
          format: svg
    - markdown_include.include
