site_name: Alinex Bash Library
site_description: Helper programs and libraries for administration tool development (mostly in bash).
site_author: Alexander Schilling
copyright: Copyright &copy; 2018 - 2020 <a href="https://alinex.de">Alexander Schilling</a>

nav:
    - Home:
          - README.md
          - skeleton.md
          - CHANGELOG.md
          - policy.md
    - Libraries:
          - libs/README.md
          - libs/core.md
          - libs/colors.md
          - libs/log.md
          - libs/info.md
          - libs/process.md
          - libs/psql.md
          - bin/README.md
    - Development:
          - dev/README.md
          - dev/build.md
    - Downloads:
          - downloads/README.md
          - downloads/license.md

theme:
    name: material
    logo:
        icon: code
    favicon: https://assets.gitlab-static.net/uploads/-/system/project/avatar/10069235/images__1_.jpeg
    language: en
    palette:
        primary: grey
        accent: deep orange
    font: false
    # remove to be GDPR conform
    #    font:
    #        text: Roboto
    #        code: Roboto Mono
    feature:
        tabs: true

repo_name: "alinex/bash-lib"
repo_url: "https://gitlab.com/alinex/bash-lib"

extra:
    manifest: "manifest.webmanifest"
    social:
        - type: gitlab
          link: https://gitlab.com/alinex
        - type: github
          link: https://github.com/alinex
        - type: book
          link: https://alinex.gitlab.io
        - type: home
          link: https://alinex.de
        - type: envelope
          link: mailto:info@alinex.de

extra_css:
    - assets/extra.css
    - assets/pdf.css

plugins:
    - search
    - pdf-export:
          verbose: false
          media_type: print
          combined: true
          combined_output_path: bash-lib-book.pdf
          enabled_if_env: ENABLE_PDF_EXPORT
#    - mkpdfs:
#          - company: The War Company Inc.
#          - author: Monsieur Silvestre

markdown_extensions:
    - extra
    - toc:
          permalink: true
    - pymdownx.caret
    - pymdownx.tilde
    - pymdownx.mark
    - admonition
    - pymdownx.details
    - codehilite:
          guess_lang: false
          linenums: false
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
          custom_checkbox: true
    - markdown_blockdiag:
          format: svg
    - markdown_include.include
