#!/usr/bin/env bash

# Usage:  ./test [<name> [<version>]]
#         ./test ci         # for gitlab
#         ./test            # for full run
#         ./test debian     # run all debian
#         ./test debian 11  # only run debian 11
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]:-$(pwd)/x}")")" || exit
export BASHLIB_HOME
BASHLIB_HOME="$(pwd)"

# Reset all
CC_RESET=$'\033[0m'
# Set text color to bold cyan
CC_CYAN_BOLD=$'\033[96m'

# run within CI
if [ "$1" = "ci" ]; then
  # create results folder
  mkdir -p test-results
  rm -rf test-results/* 2>/dev/null || true
  # run all tests
  bats --formatter junit --output test-result core
  #for file in core/date.bats; do
  #  name=${file%.bats} # remove the .bats extension
  #  name=${name//\//-} # replace all / with -
  #  echo "Run $name tests..."
  #  bats --formatter junit $file >test-results/$name.xml
  #done
# local test run
else
  [ -z "$2" ] || echo "Running multiple OS using local docker (that may take some time)"
  # Debian
  for name in debian ubuntu; do
    [ "$1" = "$name" ] || [ -z "$1" ] || continue
    # set version list
    case $name in
    debian) versions="11 12 13" ;;
    ubuntu) versions="22.04 24.04" ;;
    esac
    for version in $versions; do
      [ "$2" = "$version" ] || [ -z "$2" ] || continue
      echo -en "${CC_CYAN_BOLD}${name^} $version${CC_RESET} "
      echo -n "($(docker pull -q "$name:$version")) "
      docker run --rm -it -v "$PWD:/mnt" -w /mnt "$name:$version" bash -c \
        "echo -n 'prepare'
        source test-setup/docker-debian
        echo -n '; run '
        bats --tap core | grep -v ^ok"
    done
  done
fi
