#!/usr/bin/env bash

# Usage:  ./test [<name>] [<version>] [<tag>]
#         ./test ci           # for gitlab
#         ./test              # for full run
#         ./test debian       # run all debian
#         ./test debian 11    # only run debian 11
#         ./test debian 11 os # only run debian 11 with filter tag os

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]:-$(pwd)/x}")")" || exit
export BASHLIB_HOME
BASHLIB_HOME="$(pwd)"

# Reset all
CC_RESET=$'\033[0m'
# Set text color to bold cyan
CC_CYAN_BOLD=$'\033[96m'

# run within CI
if [ "$1" = "ci" ]; then
  # create results folder
  mkdir -p tests/results
  rm -rf tests/results/* 2>/dev/null || true
  ## run all tests
  #bats --formatter junit --output tests/results core
  find core module -name \*.bats |
    while read -r file; do
      name=${file%.bats} # remove the .bats extension
      name=${name//\//-} # replace all / with -
      echo "Run $name tests..."
      bats --formatter junit "$file" >tests/results/"$name".xml </dev/null
    done
# local test run
else
  [ -z "$2" ] || echo "Running multiple OS using local docker (that may take some time)"
  [ -z "$3" ] || echo "Only run $3 tests!"
  [ -z "$3" ] || filter="--filter-tags $3"
  # shellcheck disable=SC2086
  source "$BASHLIB_HOME"/full
  # prepare
  sudo rm -rf /tmp/bashlib-docker 2>/dev/null
  mkdir /tmp/bashlib-docker
  cp -rL ./* /tmp/bashlib-docker
  rm -rf /tmp/bashlib-docker/tests/results 2>/dev/null || true
  mkdir /tmp/bashlib-docker/tests/results
  # Run each distribution
  for name in debian ubuntu alpine; do
    [ "$1" = "$name" ] || [ -z "$1" ] || continue
    # set version list
    case $name in
    debian) versions="11 12 13" ;;
    ubuntu) versions="22.04 24.04" ;;
    alpine) versions="3.19 3.20 3.21 3.22" ;;
    esac
    # loop over versions
    for version in $versions; do
      [ "$2" = "$version" ] || [ -z "$2" ] || continue
      echo "Loading $(docker pull -q "$name:$version")"
      container="$(docker run --rm -it -v "/tmp/bashlib-docker:/mnt" -w /mnt -d "$name:$version" sh -c \
        ". tests/setup/docker-$name
        rm -rf tests/results/${name}-${version} 2>/dev/null || true
        mkdir -p tests/results/${name}-${version} || true
        for dir in core module; do
          for file in \$dir/*.bats; do
            name=\$(basename \$file)
            # shellcheck disable=SC2154
            bats \$file $filter >tests/results/${name}-${version}/\$dir_\$name
          done
        done")"
      # analyze results while running
      dir=/tmp/bashlib-docker/tests/results/${name}-${version}
      while [ -n "$(docker ps -q --filter "id=$container")" ]; do
        if [ -e "$dir" ]; then
          total="$(grep -E "^([0-9]+\.\.[0-9]+)" "$dir"/* | sed 's/.*\.//' | awk '{sum += $1} END {print sum}')" || true
          # shellcheck disable=SC2126
          ok="$(grep -h "^ok" "$dir"/* | wc -l)" || true
          # shellcheck disable=SC2126
          skip="$(grep -h "# skip" "$dir"/* | wc -l)" || true
          # shellcheck disable=SC2126
          fail="$(grep -h "^not ok" "$dir"/* | wc -l)" || true
          ((total > ok + skip + fail)) || total="${CC_NOTICE}${total}${CC_RESET}"
          ((ok == 0)) || ok="${CC_OK}${ok}${CC_RESET}"
          ((fail == 0)) || fail="${CC_ERROR}${fail}${CC_RESET}"
          printf '%b' $'\e[1K\r'
          echo -n "Running ${CC_CYAN_BOLD}${name^} $version${CC_RESET}... "
          echo -en "${total}/$ok/$fail ${CC_ERROR}$(grep -l "^not ok" "$dir"/* | sed 's#.*/##;s#\..*##' | xargs echo || true)${CC_RESET}"
        else
          printf '%b' $'\e[1K\rinitializing...'
        fi
        sleep 2
      done
      printf '%b' $'\e[1K\r'
      echo "Finished ${CC_CYAN_BOLD}${name^} $version${CC_RESET} with ${total}/$ok/$fail ${CC_ERROR}$(grep -l "^not ok" "$dir"/* | sed 's#.*/##;s#\..*##' | xargs echo || true)${CC_RESET}"
      #rm -rf tests/results/${name}-${version} 2>/dev/null || true
      cp -r /tmp/bashlib-docker/tests/results/${name}-${version} tests/results
    done
  done

  # redhat fedora centos
  # archlinux manjaro
  # solaris
  # mandriva
  # freebsd openbsd
  # opensuse
  # Gentoo
fi
