#!/usr/bin/env bash

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]:-$(pwd)/x}")")" || exit
export BASHLIB_HOME
BASHLIB_HOME="$(pwd)"

# run within CI
if [ "$1" = "ci" ]; then
  # create results folder
  mkdir -p test-results
  rm -rf test-results/* 2>/dev/null || true
  # run all tests
  for file in core/date.bats; do
    name=${file%.bats} # remove the .bats extension
    name=${name//\//-} # replace all / with -
    echo "Run $name tests..."
    bats --formatter tap $file
    echo "Run again for junit.xml files..."
    bats --formatter junit $file >test-results/$name.xml
  done
# local test run
else
  for version in 11 12; do
    echo
    echo "Debian $version"
    cmd="
    export BASHLIB_HOME=/mnt
    apt-get update >/dev/null && apt-get install -y bats curl gettext >/dev/null
    ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
    bats core/date.bats
    "
    docker run --rm -it -v "$PWD:/mnt" -w /mnt "debian:$version" bash -c "$cmd"
  done
fi
