#!/usr/bin/env bash

# Array helpers.

######################################################################################
### Array analyzing
######################################################################################

# Check if value is contained in array
# Usage:    contains <array-name> <match>
# Example:  x=( one two three )
#           contains x two && echo YES || echo NO
contains() {
    local -n array=$1
    local value=$2
    local e
    for e in "${array[@]}"; do
        [[ "$e" != "$value" ]] || return 0
    done
    return 1
}

######################################################################################
### Join
######################################################################################

# Join array elements by delimiter.
# Convert all elements in array into a string separated by delimiter.
# Usage:    join <array-name> [<delimiter>=,]
# Output:   <string>
join() {
    local -n array=$1
    local sep="${2:-,}"
    local joined="${array[0]}"
    for element in "${array[@]:1}"; do
        joined+="${sep}${element}"
    done
    echo "$joined"
}
