#!/usr/bin/env bash

# Array helpers.

######################################################################################
### Array analyzing
######################################################################################

# Check if value is contained in array
# Usage:    contains <array-name> <match>
# Example:  x=( one two three )
#           contains x two && echo YES || echo NO
contains() {
    local -n array=$1
    local value=$2
    local e
    for e in "${array[@]}"; do
        [[ "$e" != "$value" ]] || return 0
    done
    return 1
}

######################################################################################
### Join/Split
######################################################################################

# Join array elements by delimiter.
# Convert all elements in array into a string separated by delimiter (default is `,`).
# Usage:    join <array-name> [<delimiter>]
# Output:   <string>
join() {
    local -n array=$1
    local sep="${2:-,}"
    local joined="${array[0]}"
    for element in "${array[@]:1}"; do
        joined+="${sep}${element}"
    done
    echo "$joined"
}

# Splits string by delimiter into array
# The delimiter defaults to `,`.
# Usage:    split <atring> <array-name> [<delimiter>]
# Output:   <string>
split() {
    local string="$1"
    local -n array=$2
    local sep="${3:-,}"
    # Set IFS to the separator and read into array
    IFS="$sep" read -ra array <<<"$string"
}
