#!/usr/bin/env bash
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null
# shellcheck source=base
source /dev/null

# This covers Atlassian API for Jira and confluence.

# Atlassian user for API access in confluence and jira
ATLASSIAN_USER=$ATLASSIAN_USER
# Atlassian password for API access in confluence and jira
ATLASSIAN_TOKEN=$ATLASSIAN_TOKEN

######################################################################################
# Confluence
######################################################################################

# Atlassian confluence API URL used together with $ATLASSIAN_USER and $ATLASSIAN_TOKEN and silently disables @confluence functions if not set
CONFLUENCE_API="$CONFLUENCE_API"

# Get page content from Confluence using API
#
# Usage:    confluence <page_id>
# Output:   <html>
confluence() {
  is integer --name=arguments --max=1 --die -- $#
  is set --name=page-id --die -- "$1"
  # processing
  install jq
  curl -H "Content-Type: application/json" -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" "$CONFLUENCE_API/content/$1?expand=body.storage" |
    jq .body.storage.value -r ||
    die "Could not read confluence page!"
}

######################################################################################
# Jira
######################################################################################
# ADF:
# - https://developer.atlassian.com/cloud/jira/platform/apis/document/structure
# - https://atlas-doc-parser.readthedocs.io/en/latest/index.html

# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-group-issues

# Atlassian Jira URL this can be https://my-company.atlassian.net used together with $ATLASSIAN_USER and $ATLASSIAN_TOKEN and silently disables @jira functions if not set
JIRA_HOST="$JIRA_HOST"

# Jira API calls
#
# To connect the $ATLASSIAN_USER and $ATLASSIAN_TOKEN is needed.
# Jira API V3 is used there: https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro which brings some elements in the [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/).
#
# The following commands are supported:
#
# - `get` will return all fields of an issue as json
# - `search` will find matching issues
# - `create` to generate a new issue
# - `delete` to remove an issue
# - `json` manipulate jira issue json
#
# The Jira JSON consists of the `fields` array and some additional meta like `id`, `key`. To simplify work with it the json helper allows to manipulate it.
#
# Usage:    jira get <issueId>|<key>                      # get an jira issue
#           jira search <jql>                             # search jira issue id
#           jira update <ticket-id> <json>                # update jira issue
#           jira create <json>                            # create new jira issue
#           jira delete <issueId>|<key>                   # delete jira issue
#           jira project <key>                            # get project information
#           jira fields <projectId>|<key> <issueTypeId>   # get fields by project and issue type
#           # work with the issue json:
#           jira json <json> set <field> [adf|json] <value>   # set field with the possibility to format (from markdown) adf fields
#           jira json <json> get <field> [md]                 # get field value with possible format adf field as markdown
#           jira json <json> remove <field>
#           # convert atlassian document format:
#           jira md_to_adf <json>
#           jira adf_to_md <md>
# Global:   - $JIRA_HOST
#           - $ATLASSIAN_USER
#           - $ATLASSIAN_TOKEN
# Output:   - get: <json>
#           - search: <issueId> list, each in a separate line
#           - create: <issueId> which was just created
# Return:   - die on 400, 404 Error
#           - retry on other not 2xx Code
jira() {
  is set --name=JIRA_HOST --die -- "$JIRA_HOST"
  is set --name=ATLASSIAN_USER --die -- "$ATLASSIAN_USER"
  is set --name=ATLASSIAN_TOKEN --die -- "$ATLASSIAN_TOKEN"
  is enum --name=command --allow="get search create update delete project fields json adf_to_md md_to_adf" --die -- "$1" && local command="$1" && shift
  # processing
  case "$command" in
  get)
    is set --name=arguments --max=1 --die -- $#
    is set --name=issueId-or-key --die -- "$1"
    debug "GET issue $1"
    _jira GET "issue/$1"
    ;;
  search)
    is set --name=arguments --max=1 --die -- $#
    is set --name=jql --die -- "$1"
    debug "SEARCH issue $1"
    local res rc=0
    _jira GET "search/jql?jql=$(urlencode "$1")" | jq .issues[].id -r
    ;;
  create)
    is set --name=arguments --max=1 --die -- $#
    is set --name=json --die -- "$1"
    debug "CREATE issue ${jq-r '.fields.summary' <<<"$1"}"
    _jira POST issue "$1" | jq .id -r
    ;;
  update)
    is set --name=arguments --max=2 --die -- $#
    is set --name=issueId-or-key --die -- "$1"
    is set --name=json --die -- "$2"
    debug "UPDATE issue $1"
    _jira PUT "issue/$1" "$2" >/dev/null
    ;;
  delete)
    is set --name=arguments --max=1 --die -- $#
    is set --name=issueId-or-key --die -- "$1"
    debug "DELETE issue $1"
    _jira GET "issue/$1"
    ;;
  project)
    is set --name=arguments --max=1 --die -- $#
    is set --name=projectId-or-key --die -- "$1"
    debug "GET project $1"
    _jira GET "project/$1"
    ;;
  fields)
    is set --name=arguments --max=2 --die -- $#
    is set --name=projectId-or-key --die -- "$1"
    is set --name=issueTypeId --die -- "$2"
    debug "GET fields $1/$2"
    _jira GET "issue/createmeta/$1/issuetypes/$2"
    ;;
  json)
    local empty='{"fields":{}}' var="$1"
    local json="${!1:-$empty}" && shift
    is enum --name=sub-command --allow="set get remove" --die -- "$1" && local subCommand="$1" && shift
    is set --name=field --die -- "$1" && local field="$1"
    case "$subCommand" in
    set)
      if [ -z "$2" ] || [[ "$2" =~ ^adf$|^json$ && -z "$3" ]]; then
        jira json "$var" remove "$field"
      elif [ "$2" = "json" ] && [ -n "$3" ]; then
        printf -v "$var" '%s' "$(jq -c --argjson v "$3" ".fields.$field = \$v" <<<"$json")"
      elif [ "$2" = "adf" ] && [ -n "$3" ]; then
        local val
        [[ "$3" =~ ^\{ ]] && val="$3" || val="$(jira md_to_adf "$3")"
        printf -v "$var" '%s' "$(jq -c --argjson v "$val" ".fields.$field = \$v" <<<"$json")"
      elif is integer -- "$2"; then
        printf -v "$var" '%s' "$(jq -c ".fields.$field = $2" <<<"$json")"
      else
        printf -v "$var" '%s' "$(jq -c --arg v "$2" ".fields.$field = \$v" <<<"$json")"
      fi
      ;;
    get)
      local val
      val="$(jq -c ".fields.$field" <<<"$json")"
      [ ! "$val" = null ] || val=""
      [[ "$2" == "md" && "$val" =~ ^\{ ]] && jira adf_to_md "$val" || printf '%s' "$val"
      ;;
    remove) printf -v "$var" '%s' "$(jq -c "del(.fields.$field)" <<<"$json")" ;;
    esac
    ;;
  adf_to_md)
    is set --name=json --die -- "$1" && local json="$1"
    jq -r '
    def para(p):
      p.content[]?.text // "";

    .content[] |
    if .type == "paragraph" then
      para(.) + "\n"

    elif .type == "bulletList" then
      (
        .content
        | map("- " + para(.content[0]))
        | join("\n")
      ) + "\n\n"

    elif .type == "orderedList" then
      (
        .content
        | to_entries
        | map("\(.key + 1). " + para(.value.content[0]))
        | join("\n")
      ) + "\n\n"

    elif .type == "codeBlock" then
      "```\n" + (.content[0].text) + "\n```\n\n"

    else
      ""
    end
  ' <<<"$1" | sed -E '
    s/<strong>(.+?)<\/strong>/**\1**/g
    s/<em>(.+?)<\/em>/*\1*/g
    s/<code>(.+?)<\/code>/`\1`/g
  '
    ;;
  md_to_adf)
    is set --name=text --die -- "$1"
    jq -c -n --arg text "$1" '
    def paragraph(t):
      { type: "paragraph", content: [{ type: "text", text: t }] };

    def bullet(items):
      {
        type: "bulletList",
        content: items | map({
          type: "listItem",
          content: [ paragraph(.) ]
        })
      };

    def ordered(items):
      {
        type: "orderedList",
        attrs: { order: 1 },
        content: items | map({
          type: "listItem",
          content: [ paragraph(.) ]
        })
      };

    def heading(level; t):
      {
        type: "heading",
        attrs: { level: level },
        content: [{ type: "text", text: t }]
      };

    def codeblock(lang; body):
      {
        type: "codeBlock",
        attrs: { language: lang },
        content: [{ type: "text", text: body }]
      };

    def rule:
      { type: "rule" };

    def blockquote(paras):
      {
        type: "blockquote",
        content: paras
      };

    ($text | split("\n")) as $lines
    | reduce $lines[] as $line (
        {
          out: [],
          mode: null,      # "ul" / "ol" / null
          buf: [],         # list items buffer
          pBuf: [],        # paragraph buffer
          code: false,
          codeLang: "",
          codeBuf: [],
          quoteBuf: []     # paragraphs inside current blockquote
        };

        # fenced code blocks
        if ($line | test("^```")) then
          if .code then
            .out += [ codeblock(.codeLang; (.codeBuf | join("\n"))) ]
            | .code = false
            | .codeBuf = []
            | .codeLang = ""
          else
            .code = true
            | .codeLang = ($line | sub("^```"; ""))
          end

        elif .code then
          .codeBuf += [ $line ]

        # horizontal rules
        elif ($line | test("^(-{3,}|\\*{3,}|_{3,})$")) then
          # flush paragraph
          if (.pBuf | length) > 0 then
            .out += [ paragraph(.pBuf | join("\n")) ]
            | .pBuf = []
          else .
          end
          # flush quote
          | if (.quoteBuf | length) > 0 then
              .out += [ blockquote(.quoteBuf) ]
              | .quoteBuf = []
            else .
            end
          # flush list
          | if .mode == "ul" then
              .out += [ bullet(.buf) ]
              | .buf = [] | .mode = null
            elif .mode == "ol" then
              .out += [ ordered(.buf) ]
              | .buf = [] | .mode = null
            else .
            end
          | .out += [ rule ]

        # blockquotes
        elif ($line | test("^> ")) then
          # flush list before starting/continuing quote
          if .mode == "ul" then
            .out += [ bullet(.buf) ]
            | .buf = [] | .mode = null
          elif .mode == "ol" then
            .out += [ ordered(.buf) ]
            | .buf = [] | .mode = null
          else .
          end
          # flush paragraph into quote if we were in text
          | if (.pBuf | length) > 0 then
              .quoteBuf += [ paragraph(.pBuf | join("\n")) ]
              | .pBuf = []
            else .
            end
          | ($line | sub("^> "; "")) as $t
          | .quoteBuf += [ paragraph($t) ]

        # headings
        elif ($line | test("^#{1,6} ")) then
          # flush paragraph
          if (.pBuf | length) > 0 then
            .out += [ paragraph(.pBuf | join("\n")) ]
            | .pBuf = []
          else .
          end
          # flush quote
          | if (.quoteBuf | length) > 0 then
              .out += [ blockquote(.quoteBuf) ]
              | .quoteBuf = []
            else .
            end
          # flush list
          | if .mode == "ul" then
              .out += [ bullet(.buf) ]
              | .buf = [] | .mode = null
            elif .mode == "ol" then
              .out += [ ordered(.buf) ]
              | .buf = [] | .mode = null
            else .
            end
          | ($line | capture("^(?<h>#+) (?<t>.*)")) as $h
          | .out += [ heading(($h.h | length); $h.t) ]

        # bullet list
        elif ($line | startswith("- ")) then
          # flush paragraph
          if (.pBuf | length) > 0 then
            .out += [ paragraph(.pBuf | join("\n")) ]
            | .pBuf = []
          else .
          end
          # flush quote
          | if (.quoteBuf | length) > 0 then
              .out += [ blockquote(.quoteBuf) ]
              | .quoteBuf = []
            else .
            end
          | if .mode == "ul" then
              .buf += [ $line[2:] ]
            else
              if .mode == "ol" then
                .out += [ ordered(.buf) ]
              else .
              end
              | .mode = "ul"
              | .buf = [ $line[2:] ]
            end

        # ordered list
        elif ($line | test("^[0-9]+\\. ")) then
          # flush paragraph
          if (.pBuf | length) > 0 then
            .out += [ paragraph(.pBuf | join("\n")) ]
            | .pBuf = []
          else .
          end
          # flush quote
          | if (.quoteBuf | length) > 0 then
              .out += [ blockquote(.quoteBuf) ]
              | .quoteBuf = []
            else .
            end
          | if .mode == "ol" then
              .buf += [ ($line | sub("^[0-9]+\\. "; "")) ]
            else
              if .mode == "ul" then
                .out += [ bullet(.buf) ]
              else .
              end
              | .mode = "ol"
              | .buf = [ ($line | sub("^[0-9]+\\. "; "")) ]
            end

        # empty line → flush paragraph / quote / list
        elif $line == "" then
          if .mode == "ul" then
            .out += [ bullet(.buf) ]
            | .buf = [] | .mode = null
          elif .mode == "ol" then
            .out += [ ordered(.buf) ]
            | .buf = [] | .mode = null
          else .
          end
          | if (.quoteBuf | length) > 0 then
              .out += [ blockquote(.quoteBuf) ]
              | .quoteBuf = []
            else .
            end
          | if (.pBuf | length) > 0 then
              .out += [ paragraph(.pBuf | join("\n")) ]
              | .pBuf = []
            else .
            end

        # normal text → paragraph buffer
        else
          # if we were in a list, close it before plain text
          if .mode == "ul" then
            .out += [ bullet(.buf) ]
            | .buf = [] | .mode = null
          elif .mode == "ol" then
            .out += [ ordered(.buf) ]
            | .buf = [] | .mode = null
          else .
          end
          | .pBuf += [ $line ]
        end
      )
    # final flush
    | (
        .out
        + (if .mode == "ul" then [ bullet(.buf) ]
           elif .mode == "ol" then [ ordered(.buf) ]
           else [] end)
        + (if (.quoteBuf | length) > 0 then [ blockquote(.quoteBuf) ] else [] end)
        + (if (.pBuf | length) > 0 then [ paragraph(.pBuf | join("\n")) ] else [] end)
      )
    | {
        type: "doc",
        version: 1,
        content: .
      }
  ' | sed -E '
    s/\*\*(.+?)\*\*/<strong>\1<\/strong>/g
    s/\*(.+?)\*/<em>\1<\/em>/g
    s/`([^`]+)`/<code>\1<\/code>/g
  '
    ;;
  esac
}

# Usage _jira <method> <path> <data>
_jira() {
  local METHOD=$1
  local REST="$2"
  local DATA="$3"
  local api=rest/api/3
  local res rc=0 num=0 retry=5
  while ((num <= retry)); do
    ((num == 0)) || debug "Retry $num"
    res="$(curl --store $$ --request "$METHOD" --url "$JIRA_HOST/$api/$REST" --user "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" --data "$DATA" -H "Content-Type: application/json")" || rc=$?
    variables restore --clean $$
    if ((rc == 0)) && [[ "$CURL_HTTP_CODE" !~ ^2[0-9]{2}$ ]]; then
      printf '%s' "$res"
      return
    else
      # error code handling without retry
      # shellcheck disable=SC2059
      case $CURL_HTTP_CODE in
      400 | 404) (printf "HTTP Code $CURL_HTTP_CODE: ($rc) " && jq .errorMessages[] -r <<<"$res" || printf '%s' "$res") | die ;;
      esac
    fi
    ((num++)) || true
    sleep $(((num + 1) ** 2)) # 3 tries 30s; 5 tries 90s; 10 tries 9m
  done
  # shellcheck disable=SC2059
  (printf "HTTP Code $CURL_HTTP_CODE: " && jq .errorMessages[] -r <<<"$res" || printf '%s' "$res") | die
}
