#!/usr/bin/env bash
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# This covers Atlassian API for Jira and confluence.

######################################################################################
# Confluence
######################################################################################

# Get page content from Confluence using API
# Usage:    confluence <page_id>
# Output:   `<html>`
confluence() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=page-id --die -- "$1"
    # processing
    install jq
    curl -H "Content-Type: application/json" -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" "$CONFLUENCE_API/content/$1?expand=body.storage" |
        jq .body.storage.value -r ||
        die "Could not read confluence page!"
}

######################################################################################
# Jira
######################################################################################
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#version
# ADF:
# - https://developer.atlassian.com/cloud/jira/platform/apis/document/structure
# - https://atlas-doc-parser.readthedocs.io/en/latest/index.html

# Search for jira tickets
# Usage:    jira_search <jql>
# Output:   `<json>`
jira_search() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=jql --die -- "$1"
    # processing
    install jq
    curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X GET "$JIRA_API/search/jql?jql=$1&fields=*all" |
        jq '.issues[]' ||
        die "Could not search for Jira issues using $1!"
}

# Get jira ticket details
# Usage:    jira_get <issue-key>
# Output:   `<json>`
jira_get() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=issue-key --die -- "$1"
    # processing
    curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X GET "$JIRA_API/issue/$1" ||
        die "Could not get Jira issue $1!"
}

# Create jira tickets
# Usage:    jira_create <json>
# Output:   `<issue-key>`
jira_create() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=json --die -- "$1"
    # processing
    install jq
    curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X POST "$JIRA_API/issue/" -d "$1" |
        jq '.key' -r ||
        die "Could not create Jira issue!"
}

# Update jira tickets
# Usage:    jira_update <issue-key> <json>
jira_update() {
    is integer --name=arguments --max=2 --die -- $#
    is set --name=issue-key --die -- "$1"
    is set --name=json --die -- "$2"
    # processing
    curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X PUT "$JIRA_API/issue/$1" -d "$1" ||
        die "Could not update Jira issue $1!"
}
