#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# Module with modifiers for csv/tsv tables.

# Load dependent modules if not done
_load_module module/software

# Convert TSV data into visual table
# Usage:    tsv2table <tsv>
#           <tsv> | tsv2table
# Stdout:   <table>
tsv2table() {
    install mlr
    input "$@" | mlr --csvlite --ifs '\t' -o pprint cat
}

# Convert TSV data into markdown table
# Usage:    tsv2md <tsv>
#           <tsv> | tsv2md
# Stdout:   <md>
tsv2md() {
    install mlr
    input "$@" | uncolorize | mlr --csvlite --ifs '\t' --omd cat
}
