#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Module with database access helpers.

# Load dependent modules if not done
use module/software

######################################################################################
# Mongo
######################################################################################

# Run command on Mongo DB
# Usage:    mongo "" <command>            # global command
#           mongo <database> <command>    # work in database
# Global:   $server
#           $MONGO_ADMIN_USERPASS
mongo() {
    num_parameters --min 2 --max 2 --die "Mongo needs two parameters: Usage mongo <database> <command>" "$@"
    local cluster key
    install mongosh
    # shellcheck disable=SC2001
    # shellcheck disable=SC2154
    cluster="$(sed 's/^[^.]*\.//' <<<"$server")"
    debug "Use settings for $cluster"
    command mongosh "mongodb://$(hash MONGO_ADMIN_USERPASS get "$cluster")@$server:27017/$1" \
        --eval "print(EJSON.stringify($2))"
}

######################################################################################
# Postgres
######################################################################################

# Run command on postgres
postgres() {
    echo "TODO"
}
