#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Module with database access helpers.

# load other modules if not already done
declare -F "num_parameters" >/dev/null || source "$BASHLIB_HOME"/module/validator

######################################################################################
# Mongo
######################################################################################

# Run command on Mongo DB
# Usage:    mongosh "" <command>            # global command
#           mongosh <database> <command>    # work in database
# Global:   $server
#           $MONGO_ADMIN_USERPASS
mongosh() {
    # TODO: rename as mongodb
    num_parameters --min 2 --max 2 --die "Mongosh needs two parameters: Usage mongosh <database> <command>" "$@"
    local cluster
    # shellcheck disable=SC2001
    cluster="$(sed 's/^[^.]*\.//' <<<"$server")"
    command mongosh "mongodb://${MONGO_ADMIN_USERPASS["$cluster"]}@$server:27017/$1" --eval "$2"
}

######################################################################################
# Postgres
######################################################################################

# Run command on postgres
postgres() {
    echo "TODO"
}
