#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Module with database access helpers.

# load other modules if not already done
declare -F "num_parameters" >/dev/null || source "$BASHLIB_HOME"/module/validator

######################################################################################
# Mongo
######################################################################################

# Run command on Mongo DB
# Usage:    mongo "" <command>            # global command
#           mongo <database> <command>    # work in database
# Global:   $server
#           $MONGO_ADMIN_USERPASS
mongo() {
    num_parameters --min 2 --max 2 --die "Mongo needs two parameters: Usage mongo <database> <command>" "$@"
    local cluster
    # shellcheck disable=SC2001
    # shellcheck disable=SC2154
    cluster="$(sed 's/^[^.]*\.//;s/[^a-zA-Z0-9_]/_/g' <<<"$server")"
    debug "Use settings for $cluster"
    command mongosh "mongodb://${MONGO_ADMIN_USERPASS["$cluster"]}@$server:27017/$1" \
        --eval "print(EJSON.stringify($2))"
}

# Deprectaed: Run command on Mongo DB
# Use `mongo` now.
# Usage:    mongosh "" <command>            # global command
#           mongosh <database> <command>    # work in database
# Global:   $server
#           $MONGO_ADMIN_USERPASS
mongosh() {
    _deprecated "Use $(mongo) now." warn
    mongo "$@"
}

######################################################################################
# Postgres
######################################################################################

# Run command on postgres
postgres() {
    echo "TODO"
}
