#!/usr/bin/env bash

# Some helpers to work easier with dates.

######################################################################################
### Timestamp
######################################################################################

# Get current timestamp
# Usage:    now
# Stdout:   <int> seconds since 1970
now() {
   date +%s
}

######################################################################################
### Working with date string or timestamp
######################################################################################

# Calculate difference in seconds
# Usage:    date_diff <start> <end> # timestamp or date string
# Stdout:   <seconds> negative if <start> behind <end>
date_diff() {
    local start end
    num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: diff_sec <start> <end>"
    is_integer "$1" && start=${1-} || start=$(date -d "$1" +%s) \
    || die "Date format '$1' not parsable!"
    is_integer "$2" && end=${2-} || end=$(date -d "$2" +%s) \
    || die "Date format '$2' not parsable!"
    echo $((end - start))
}

# Format date in different nnamed versions or format string
# Usage:    date_format <format> [<value>] # use now if missing
# Formats:  iso         2025-10-01T12:00:00+02:00
#           iso-date    2025-10-01
#           zulu        2025-10-01T10:00:00Z
#           sql         2025-10-01 12:00:00
#           unix        1759312800
#           eu-date     01.10.2025
#           us-date     10/01/2025
#           human-date  Mittwoch, Oktober 01, 2025
#           time        12:00:00
#           time-short  12:00
#           +%Y         2025 (custom format)
# Stdout:   <string>
date_format() {
    local value format
    # date_format <format> <value>
    case $1 in
        iso)        format="--iso-8601=seconds" ;;
        iso-date)   format="--iso-8601" ;;
        zulu)       format="-u +%Y-%m-%dT%H:%M:%SZ" ;;
        sql)        format="+\"%Y-%m-%d %H:%M:%S\"" ;;
        unix)       format="+%s" ;;
        eu-date)    format="+%Y-%m-%d" ;;
        us-date)    format="+%m/%d/%Y" ;;
        human-date) format="+%A, %B %d, %Y" ;;
        time)       format="%H:%M:%S" ;;
        time-short) format="%H:%M" ;;
        *)          format="$1" ;;
    esac
    [ -n "$2" ] && value="${2-}" || value=$(now)
    is_integer "$value" && eval "date -d @$value $format" || eval "date -d \"$value\" $format" \
    || die "Date format '$value' not parsable!"
}
