#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# Management of docker.

######################################################################################
# Version
######################################################################################

# Get the latest version number
#
# This is done by checking the docker hub image tags.
#
# Usage:    docker_latest_version
# Output:   latest version tag or empty if not found
docker_latest_version() {
    is set --name=software --die -- "$1"
    case $1 in
    *.elastic.co/*)
        # use another registry
        curl -s https://artifacts-api.elastic.co/v1/versions | jq -r '.versions[]' | grep -E '^[0-9]\.[0-9]+\.?[0-9]*$' | sort -V | tail -1 || true
        ;;
    neo4j)
        # newest versions are <year>.<<month>
        _docker_registry_tag_latest "$1" '^20[0-9]{2}\.[0-9]+*$'
        ;;
    mongo)
        # only *.0 versions are for server install, others are for cloud
        _docker_registry_tag_latest "$1" '^[0-9]+\.0$'
        ;;
    *)
        _docker_registry_tag_latest "$1" '^[0-9]+\.[0-9]+\.?[0-9]*$'
        ;;
    esac
}
_docker_registry_tag_latest() {
    curl -s "https://registry.hub.docker.com/v2/repositories/library/$1/tags?page_size=200" | jq -r '.results[].name' 2>/dev/null | grep -E "$2" | sort -V | tail -1 || true
}

######################################################################################
# Cleanup
######################################################################################

# Cleanup docker installation
#
# This will remove:
#
# - all stopped **containers**
# - all unused **networks**
# - all **images** which are unused
# - cleanup the **build cache**
# - all **volumes** that are not referenced by any container (running or stopped)
#
# Usage:    docker_cleanup
docker_cleanup() {
    sudo docker system prune -a -f
    sudo docker volume prune -f
}
