#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# File and directory helpers.

######################################################################################
### Path
######################################################################################

# Strip directory and suffix from filenames
# This is a much faster implementation as the basename command because it is using shell parameter expansion.
# It will remove the directory and output only the filename.
# Usage:    basename <path>
#           <path> | basename
# Output:   <file>
basename() {
    local path
    path="$(input "$@")"
    path="${path%/}"
    echo "${path##*/}"
}

# Get the path from the called command
# Usage:    script_path
# Output:   full real directory path to script
script_path() {
    dirname "$(readlink -f "${BASH_SOURCE[-1]:-$(pwd)/x}")"
}
