#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=module/color
source /dev/null

# Module with user interaction helpers.

# load other modules if not already done
declare -F "color_256" >/dev/null || source "$BASHLIB_HOME"/module/color

######################################################################################
# User Input
######################################################################################

# Wait for user input
# Usage:    pause <message>
#           <message> | pause
# TTY:      <question> <key>
pause() {
    local text
    text="$(input "$@")"
    test -z "$text" || warn "$text"
    read -n 1 -s -r -p "$(gettext 'Press any key to continue...')" key </dev/tty
    echo "" >/dev/tty
}

# Ask a yes/no question.
# The default can be yes or no and if a default is set <return> will use it. Additional to a default a timeout can be set meaning to use default if timeout is reached. If an invalid character is typed, the timeout will restart.
# Usage:    confirm <question>
# Options:  -t, --true                  # default: yes
#           -f, --false                 # default: no
#           -t, --timeout <duration>    # time after which the default will be used
# TTY:      <question> <key>
confirm() {
    # parameter parsing
    local default timeout
    eval set -- "$(option_parse $'t true -\nf false -\nT timeout +' "$@")"
    while true; do
        case "$1" in
        -t | --true)
            default=1
            shift
            ;;
        -f | --false)
            default=0
            shift
            ;;
        -T | --timeout)
            timeout="-t $(duration_format seconds "$2")"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    local prompt
    prompt="${1:-$(gettext "Should this be done")}"
    local char="" seq
    if [ -n "$default" ]; then
        ((default == 0)) && prompt="$prompt [$(gettext "No")]" || prompt="$prompt [$(gettext "Yes")]"
    fi
    echo -en "${CC_INFO}$prompt?${CC_RESET} " >/dev/tty
    # read input
    # shellcheck disable=SC2086
    # shellcheck disable=SC2229
    while IFS= read -r $timeout -s -n 1 char </dev/tty || true; do
        # stop maybe on enter (newline)
        if [[ $char == "" ]]; then
            # end if default is set
            if [ -n "$default" ]; then
                if ((default == 1)); then
                    echo -e "$(gettext "Yes")" >/dev/tty
                    return 0
                else
                    echo -e "$(gettext "No")" >/dev/tty
                    return 1
                fi
            fi
        # ignore escape sequences
        elif [[ $char == $'\033' ]]; then
            # Read next few characters non-blocking to drain escape sequence
            read -r -s -n 1 -t 0.01 seq
            while [[ $seq == "[" || $seq =~ [0-9A-Za-z~] ]]; do
                read -r -s -n 1 -t 0.01 seq || break
            done
        # yes
        elif [[ $char =~ [JjYy] ]]; then
            echo -e "$(gettext "Yes")" >/dev/tty
            return 0
        # no
        elif [[ $char =~ [Nn] ]]; then
            echo -e "$(gettext "No")" >/dev/tty
            return 1
        fi
    done
}

ask_no() { _deprecated "use confirm --false <question>"; }
ask_yes() { _deprecated "use confirm --true <question>"; }
ask_input() { _deprecated "use ask <question>"; }

# Ask for an input element
# This will also validate while typing if you select the correct format. So you can only input characters matching the input format.
# Possible formats are:
# - `string` - (default) allow anything
# - `integer` or `number` - only allow [0-9]
# - `float` - allow number [0-9]+.[0-9]+
# - `password` - will show only `*` characters to hide input
# Usage:    ask <format> <question>
# Options:  -e, --empty             # allowe empty value
#           -d, --default <value>   # set default if none given
#           -n, --allow-negative    # on number, integer, float
# TTY:      <question> <valid characters>...
# Stdout:   <answer>
ask() {
    # parameter parsing
    local default empty negative
    eval set -- "$(option_parse $'e empty -\nd default +' "$@")"
    while true; do
        case "$1" in
        -e | --empty)
            empty=1
            shift
            ;;
        -d | --default)
            default="$2"
            shift 2
            ;;
        -n | --negative)
            negative=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    local prompt pattern mask
    case $1 in
    integer | number)
        prompt="${2:-$(gettext "Enter integer number")}"
        if [ -n "$negative" ]; then
            pattern="^-?[0-9]+$"
        else
            pattern="^[0-9]+$"
        fi
        ;;
    float)
        prompt="${2:-$(gettext "Enter float number")}"
        if [ -n "$negative" ]; then
            pattern="-?^[0-9]+(\.[0-9]?)?$"
            final="^-?[0-9]+(\.[0-9])?$"
        else
            pattern="^[0-9]+(\.[0-9]*?)?$"
            final="^[0-9]+(\.[0-9]+)?$"
        fi
        ;;
    password)
        prompt="${2:-$(gettext "Enter password")}"
        mask=1
        ;;
    time)
        prompt="${2:-$(gettext "Enter time")}"
        pattern="^([0-1]?[0-9]|2[0-3])(:([0-5]?[0-9])?)?$"
        final="^([0-1][0-9]|2[0-3]):[0-5][0-9]$"
        ;;
    *)
        prompt="${2:-$(gettext "Enter short text")}"
        ;;
    esac
    local input="" char="" seq
    [ -z "$default" ] || prompt="$prompt [$default]"
    echo -en "${CC_INFO}$prompt:${CC_RESET} " >/dev/tty
    # Read one character at a time silently (-s), without newline (-n 1)
    while IFS= read -r -s -n 1 char </dev/tty; do
        # stop maybe on enter (newline)
        if [[ $char == "" ]]; then
            # end if final pattern reached
            if [ -n "$final" ]; then
                if [[ "$input" =~ $final ]]; then
                    echo >/dev/tty
                    break
                fi
            # end if input done
            elif [ -n "$input" ]; then
                echo >/dev/tty
                break
            # end if default possible
            elif [ -n "$default" ]; then
                input="$default"
                echo >/dev/tty
                break
            # end if empty allowed
            elif [ -n "$empty" ]; then
                echo >/dev/tty
                break
            fi
        # Handle backspace
        elif [[ $char == $'\177' ]]; then
            if [ ${#input} -gt 0 ]; then
                input=${input:0:-1}
                echo -ne "\b \b" >/dev/tty
            fi
        # ignore escape sequences
        elif [[ $char == $'\033' ]]; then
            # Read next few characters non-blocking to drain escape sequence
            read -r -s -n 1 -t 0.01 seq
            while [[ $seq == "[" || $seq =~ [0-9A-Za-z~] ]]; do
                read -r -s -n 1 -t 0.01 seq || break
            done
        # next character
        else
            if [ -n "$pattern" ]; then
                debug 7 "$(od -An -to1 -v <<<"$char") [[ \"$input$char\" =~ $pattern ]] $([[ "$input$char" =~ $pattern ]] && echo true || echo false)"
                [[ "$input$char" =~ $pattern ]] || continue
            fi
            input+="$char"
            [ -n "$mask" ] && echo -n "*" >/dev/tty || echo -n "$char" >/dev/tty
        fi
    done
    debug 4 "Octal result: $(od -An -to1 -v <<<"$input")"
    # return input
    echo "$input"
}

# Select from list (extended version of native select)
# Usage:    choose [-t] <entry>...
#           <list> | choose [-t]
# Options:  -t, --title <title>         # display text line above selection
#           -x, --exit <string>         # will add an exit option at the end -> return "exit"
#           -d, --default <string|int>  # the command or number which will be returned on <enter>
#           -T, --timeout <duration>    # timeout till default selection as seconds or duration @duration_format
# Entry:    <entry> := <string> | <key> "|" <display> # whitespace arround values are removed
# TTY:      [<title>]
#           <list>
#           ...
#           <question> <key>
# Stdout:   selected <line>
# TODO > 10 entries make two columns using mlr display
choose() {
    # parameter parsing
    local end default readopt
    eval set -- "$(option_parse $'t title +\nx exit +\nd default +\nT timeout +' "$@")"
    while true; do
        case "$1" in
        -t | --title)
            info "$2" >/dev/tty
            shift 2
            ;;
        -d | --default)
            default="$2"
            shift 2
            ;;
        -x | --exit)
            end="$2"
            shift 2
            ;;
        -T | --timeout)
            readopt="-t $(duration_format seconds "$2")"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    # shellcheck disable=SC2155
    local question="$(gettext "Select one of the above options:")"
    [ -z "$default" ] && readopt="" || question="$question [$default]"
    local list line key display num=0
    list="$(input_lines "$@")"
    list="$(trim "$list")"
    while read -r line; do
        num=$((num + 1))
        IFS="|" read -r key display <<<"$line"
        printf "%4d) $(trim "${display:-$key}")\n" "$num" >/dev/tty
    done <<<"$list"
    [ -z "$end" ] || printf "%4s) ${end}\n" x >/dev/tty
    while true; do
        # shellcheck disable=SC2086
        # shellcheck disable=SC2229
        read $readopt -r -p "$question " select </dev/tty || true
        if [[ "$select" =~ ^[1-$num]$ ]]; then
            sed -n "${select}p" <<<"$list" | sed 's/|.*//'
            return
        elif [ -n "$default" ] && [ -z "$select" ]; then
            if is_integer "$default"; then
                sed -n "${default}p" <<<"$list" | sed 's/|.*//'
                return
            else
                select="$default"
            fi
        fi
        if [ -n "$end" ] && [[ "$select" =~ [xXqQ] ]]; then
            echo >/dev/tty
            echo exit
            return
        else
            echo -n "$(gettext "Disallowed answer"): " >/dev/tty
        fi
    done
}

# Run tasks as selected by user
# Often the functions are also named `check-...` for the ones which will return tasks and `task-...` for the ones really doing the job. The first one may do a lot of analyzation and output user information on stdout.
# The '|' character is not possible within the commands. If a pipe is neccessary put it within a function. Also some commands can be disabled in the list by preceding the command with an `#` character.
# If there are no tasks defined or the dynamic list will return no tasks it will end with a success message.
# Usage:    tasks <entry>...
#           # <entry>       := <check-fn> or "<task-line>"
#           # <check-fn>    := function called to return up to multiple <task-lines>
#           # <task-fn>     := function to be run when selected
#           # <task-line>   := "<task-fn> | <name>"
#           <task-lines> | tasks            # entries from pipe
#           tasks <check-fn>                # add entries from function (dynamic)
# Option    -t, --title <title>             # display text line above selection
#           -d, --default <var> | <task-fn> | "x"   # default command to start
#           -T, --timeout <sec>             # timeout till default selection
# Files:    `/dev/shm/<program>_tasks_<pid>` will be used while dynamically generating the tasks list and removed afterwards
# TTY:      Nächste Schritte
#              1) Analyse einzelner Partitionen
#              2) Docker aufräumen mit etwa 206MB unter /data
#              3) Remote Host Console (interaktiv)
#              x) Beenden
#           Wähle eine der obigen Optionen: [1]
# Example:  &tasks different possibilities
tasks() {
    # parameter parsing
    local end title _default opt
    eval set -- "$(option_parse $'t title +\nd default +\nT timeout +' "$@")"
    while true; do
        case "$1" in
        -t | --title)
            title="-t$2" >/dev/tty
            shift 2
            ;;
        -d | --default)
            _default="$2" >/dev/tty
            shift 2
            ;;
        -T | --timeout)
            opt="-T $2 " >/dev/tty
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    local raw list task num newlist cmd name
    find /dev/shm -regex ".*/$0_tasks_[0-9]*" -mmin +60 -delete 2>/dev/null || true # cleanup broken runs
    newlist="$(mktemp -m "tasks_$$")"
    raw="$(input_lines "$@" | grep -v '^[[:space:]]*#')"
    # ask user to select
    while true; do
        list="$raw"
        # check for dynamic parts in list
        while grep -qv '|' <<<"$list"; do
            : >"$newlist"
            while IFS= read -r line; do
                IFS='|' read -r cmd name <<<"$line"
                if [ -n "$name" ]; then
                    echo "$line" >>"$newlist"
                else
                    $cmd </dev/null >>"$newlist" || die "$(gettext "Could not get task list from command"): $cmd"
                fi
            done <<<"$list"
            list="$(sed '/^[[:space:]]*$/d' "$newlist")"
            rm "$newlist"
            # list is empty
            if [ -z "$list" ]; then
                ok "$(gettext "No tasks found to be executed.")"
                return
            fi
        done
        [ -z "$_default" ] || [ -z "${!_default}" ] || _default="${!_default}"
        if [ "$_default" = "x" ]; then
            opt+="-d x "
        elif [ -n "$_default" ]; then
            num=0
            while IFS= read -r line; do
                ((num++)) || true
                IFS='|' read -r cmd name <<<"$line"
                [ ! "$_default" = "$(trim "$cmd")" ] || opt+="-d $num "
            done <<<"$list"
        fi
        # shellcheck disable=SC2086
        task=$(choose "$title" -x "$(gettext "Exit")" $opt "$list")
        debug "choosen $task"
        [[ "$task" != "exit" ]] || break
        # shellcheck disable=SC2034
        local error=$?
        eval "$task" || die "$(eval_gettext "Got error \$error running \$task")"
        echo ""
    done
}
