#!/usr/bin/env bash
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Using the mattermost API to write messages.

######################################################################################
# Mattermost Internal
######################################################################################

# Cache used to prevent multiple API calls for the same information in one run
declare -A _mattermost_cache

# Get my user id
# Usage:    _mattermost_user
# Output:   <user-id>
_mattermost_user() {
    if [[ ! -v _mattermost_cache["__u"] ]]; then
        debug "GET mattermost/users/me"
        _mattermost_cache["__u"]="$(
            curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/users/me |
                jq '.id' -r
        )" ||
            die "Could not find myself in mattermost!"
    fi
    echo "${_mattermost_cache["__u"]}"
}

# Get team id by name
# Usage:    _mattermost_team <name>
# Output:   <team-id>
_mattermost_team() {
    if [[ ! -v _mattermost_cache["__t_$1"] ]]; then
        debug "GET mattermost/teams"
        _mattermost_cache["__t_$1"]="$(
            curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/teams |
                jq '.[] | select(.display_name == "'"$1"'") | .id' -r
        )" ||
            die "Could not get ID of team $1 in mattermost!"
    fi
    [ -n "${_mattermost_cache["__t_$1"]}" ] || die "Team $1 does not exist in mattermost."
    echo "${_mattermost_cache["__t_$1"]}"
}

# Get channel id by team-id and name
# Usage:    channel <team-id> <display_name>
# Output:   <channel-id>
_mattermost_channel() {
    local cache="channel_$1_$2"
    cache=${cache//[^a-zA-Z0-9_]/}
    if [[ ! -v _mattermost_cache[$cache] ]]; then
        debug "GET mattermost/users/me/teams/<team-id>/channels"
        _mattermost_cache[$cache]="$(
            curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/users/me/teams/"$1"/channels |
                jq '.[] | select(.display_name == "'"$2"'") | .id' -r
        )" ||
            die "Could not get ID of channel $1/$2 in mattermost!"
    fi
    [ -n "${_mattermost_cache[$cache]}" ] || die "Channel $2 does not exist in mattermost (team $1)"
    echo "${_mattermost_cache[$cache]}"
}

# Get channel by <post-id>
# Usage:    _mattermost_channel_by_post <post-id>
# Output:   <channel-id>
_mattermost_channel_by_post() {
    debug "GET mattermost/posts/<post-id>"
    curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/posts/"$1" |
        jq '.channel_id' -r ||
        die "Could not get channel of post $1 in mattermost!"
}

# New post in channel
# Usage:    _mattermost_post <channel-id> <message> [<attachments>]
# Output:   <channel-id>/<post-id>
_mattermost_post() {
    local att=""
    if [ -n "$3" ]; then
        [[ "$3" == \[* ]] && att="$3" || att="[$3]"
        att=', "props": {"attachments": '"$att"'}'
    fi
    local json pid
    json="$(jq -n --arg c "$1" --arg t "$2" '{ channel_id: $c, message: $t '"$att"' }')"
    debug "POST mattermost/posts"
    debug "JSON: $json" >&2
    pid=$(
        curl -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' -X POST "$MATTERMOST_API"/posts -d "$json" |
            jq '.id' -r
    ) ||
        die "Could not send new post to mattermost!"
    debug "-> $pid"
    echo "$1/$pid"
}

# Repost in channel
# Usage:    _mattermost_repost <channel-id> <post-id> <message> [<attachments>] -> <channel-id>/<post-id>
_mattermost_repost() {
    local att=""
    if [ -n "$4" ]; then
        [[ "$4" == \[* ]] && att="$4" || att="[$4]"
        att=', "props": {"attachments": '"$att"'}'
    fi
    local json pid
    json="$(jq -n --arg c "$1" --arg r "$2" --arg t "$3" '{ channel_id: $c, root_id: $r, message: $t '"$att"' }')"
    debug "POST mattermost/posts"
    debug "JSON: $json" >&2
    pid=$(
        curl -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' -X POST "$MATTERMOST_API"/posts -d "$json" |
            jq '.id' -r
    ) ||
        die "Could not send repost to mattermost!"
    echo "$1/$pid"
}

# Add reaction to post
# Usage:    _mattermost_reaction <post-id> <smiley>
_mattermost_reaction() {
    local json
    json="$(jq -n --arg u "$(_mattermost_user)" --arg p "$1" --arg t "$2" '{ user_id: $u, post_id: $p, emoji_name: $t }')"
    debug "POST mattermost/reactions"
    curl -X POST -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' "$MATTERMOST_API"/reactions -d "$json" \
        >/dev/null ||
        die "Could not add reaction to mattermost post!"
}

# Repost in channel
# Usage:    _mattermost_delete <post-id>
_mattermost_delete() {
    debug "DELETE mattermost/posts"
    curl -H "Authorization: Bearer $MATTERMOST_TOKEN" -H 'Content-Type: application/json' -X DELETE "$MATTERMOST_API"/posts/"$1" ||
        die "Could not send delete to mattermost!"
}

# Find channels by predefined pattern
# Usage:    _mattermost_find_channels <name>
# Output:   `<team-id>/<channel-id>` ... # first main, following links
#           `<team-id>/<channel-id>` ... # one line per team matching
_mattermost_find_channels() {
    id() {
        local val
        val=$(_mattermost_channel "$1" "$2") || exit 1
        echo -n "$1/$val "
    }
    local channel=${1:-$server}
    local divibib ekz result
    # shellcheck disable=SC2034
    divibib=$(_mattermost_team divibib) || exit 1
    # shellcheck disable=SC2034
    ekz=$(_mattermost_team ekz) || exit 1
    result=""
    shopt -s nocasematch
    local missing=0 found team
    shopt -s nocasematch
    for team in divibib ekz; do
        # main post
        found=0
        for ((i = 0; i < ${#MATTERMOST_CHANNEL_PATTERN[@]}; i += 3)); do
            [[ "${MATTERMOST_CHANNEL_PATTERN[i]}" == "$team" ]] || continue # only entries of this team
            if [[ "$channel" =~ ${MATTERMOST_CHANNEL_PATTERN[i + 1]} ]]; then
                if [[ "${MATTERMOST_CHANNEL_PATTERN[i + 2]}" != "-" ]]; then
                    id "${!team}" "${MATTERMOST_CHANNEL_PATTERN[i + 2]}"
                    found=1
                else
                    ((missing++)) || true
                fi
                debug "Match Mattermost channel ${MATTERMOST_CHANNEL_PATTERN[i]} ${MATTERMOST_CHANNEL_PATTERN[i + 1]} ${MATTERMOST_CHANNEL_PATTERN[i + 2]}"
                break
            fi
        done
        if ((found > 0)); then
            debug "search for links"
            # link
            for ((i = 0; i < ${#MATTERMOST_LINK_PATTERN[@]}; i += 3)); do
                [[ "${MATTERMOST_LINK_PATTERN[i]}" = "$team" ]] || continue # only entries of this team
                if [[ "$channel" =~ ${MATTERMOST_LINK_PATTERN[i + 1]} ]]; then
                    id "${!team}" "${MATTERMOST_LINK_PATTERN[i + 2]}"
                    debug "Match Mattermost link ${MATTERMOST_LINK_PATTERN[i]} ${MATTERMOST_LINK_PATTERN[i + 1]} ${MATTERMOST_LINK_PATTERN[i + 2]}"
                    break
                fi
            done
        fi
        echo ""
    done
    shopt -u nocasematch
    ((missing < 2)) || die "Could not detect mattermost channel for $1"
    shopt -s nocasematch
}

######################################################################################
# Mattermost Chat
######################################################################################

# Post IDs from last main posting to be used later for repost and reactions
mattermost_post_ids=""

# Send a message to Mattermost
# Usage:    mattermost <channel-name> <text> [<attachments>]
# Globals:  $MATTERMOST_API + $MATTERMOST_TOKEN to access API
# Output:   <post-id list>
# Returns:  0 without action if no $MATTERMOST_API + $MATTERMOST_TOKEN
mattermost() {
    is integer --name=arguments --max=3 --die -- $#
    is set --name=channel-name --die -- "$1"
    # processing
    if [ -z "$MATTERMOST_API" ] || [ -z "$MATTERMOST_TOKEN" ]; then
        debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
        return 0
    fi
    install jq
    local channels line main links link mainId postId result
    channels="$(_mattermost_find_channels "$1")" || exit 1
    # for lines in channels
    while read -r line; do
        [ -n "$line" ] || continue
        read -r main links <<<"$line"
        IFS="/" read -r _ channel <<<"$main"
        mainId=$(_mattermost_post "$channel" "$2" "$3")
        IFS="/" read -r _ post <<<"$mainId"
        result="$result\n$mainId"
        while IFS=" " read -r link; do
            [ -n "$link" ] || continue
            IFS="/" read -r _ channel <<<"$link"
            postId=$(_mattermost_post "$channel" "https://mattermost.ekz.de/divibib/pl/$post")
            result="$result $postId"
        done <<<"$links"
    done <<<"$channels"
    mattermost_post_ids="${result:2}"
}

# Create an attachment json to be used in post
# Find free linkable icons under https://icons8.de/icons/all
# Usage:    mattermost_attachment
#           mattermost_post <channel-id> "" "$(mattermost_attachment --color ...)"
# Globals:  $MATTERMOST_API + $MATTERMOST_TOKEN to access API
# Options:  color <hexcode>   # rgb color or names: critical, error, warning, ok, info, default
#           text <md>         # text content
#           author <name>     # author name
#           avatar <url>      # author icon
#           home <url>        # author link
#           title <string>    # title
#           link <url>        # title link
#           image <url>       # bottom image
#           thumb <url>       # right image
#           fields <json>     # array title=<words>, value=<text>, short=false
#           footer <string>   # footer
#           logo <url>        # footer image
# Output:   <json> for this attachment
# Returns:  0 without action if no $MATTERMOST_API + $MATTERMOST_TOKEN
mattermost_attachment() {
    if [ -z "$MATTERMOST_API" ] || [ -z "$MATTERMOST_TOKEN" ]; then
        debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
        return 0
    fi
    install jq
    local json="{}"
    local fields
    # parameter parsing
    eval set -- "$(option_parse $'- color +\n- text +\n- author +\n- avatar +\n- home +\n- title +\n- link +\n- image +\n- thumb +\n- fields +\n- footer +\n- logo +' "$@")"
    while true; do
        case "$1" in
        --color)
            local color="$2"
            case $color in
            critical) color="#FF0000" ;;
            error) color="#FFA500" ;;
            warning) color="#FFFF00" ;;
            ok) color="#008000" ;;
            info) color="#0000FF" ;;
            default) color="#808080" ;;
            esac
            json="$(echo "$json" | jq --arg i "$color" '. + {color: $i}')"
            shift 2
            ;;
        --text) json="$(echo "$json" | jq --arg i "$2" '. + {text: $i}')" && shift 2 ;;
        --author) json="$(echo "$json" | jq --arg i "$2" '. + {author_name: $i}')" && shift 2 ;;
        --avatar) json="$(echo "$json" | jq --arg i "$2" '. + {author_icon: $i}')" && shift 2 ;;
        --home) json="$(echo "$json" | jq --arg i "$2" '. + {author_link: $i}')" && shift 2 ;;
        --title) json="$(echo "$json" | jq --arg i "$2" '. + {title: $i}')" && shift 2 ;;
        --link) json="$(echo "$json" | jq --arg i "$2" '. + {title_link: $i}')" && shift 2 ;;
        --image) json="$(echo "$json" | jq --arg i "$2" '. + {image_url: $i}')" && shift 2 ;;
        --thumb) json="$(echo "$json" | jq --arg i "$2" '. + {thumb_url: $i}')" && shift 2 ;;
        --fields) fields="$2" && shift 2 ;;
        --footer) json="$(echo "$json" | jq --arg i "$2" '. + {footer: $i}')" && shift 2 ;;
        --logo) json="$(echo "$json" | jq --arg i "$2" '. + {footer_image: $i}')" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # adding fields to json
    if [ -n "$fields" ]; then
        [[ "$fields" == \[* ]] || fields="[$fields]"
        json="$(echo "$json" | jq ". + {fields: $fields}")"
    fi
    echo "$json"
}

# Add reaction to existing post
# This can only be called if a @mattermost call was used previously.
# Usage:    mattermost_reaction <emoji>
# Globals:  $MATTERMOST_API + $MATTERMOST_TOKEN to access API
# Options:  l, links     # also post this to the links
# Returns:  0 without action if no $MATTERMOST_API + $MATTERMOST_TOKEN
mattermost_reaction() {
    if [ -z "$MATTERMOST_API" ] || [ -z "$MATTERMOST_TOKEN" ]; then
        debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
        return 0
    fi
    # parameter parsing
    local post_links emoji line main links link channel post
    eval set -- "$(option_parse $'l links -' "$@")"
    while true; do
        case "$1" in
        -l | --links)
            post_links=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is integer --name=arguments --max=1 --die -- $#
    is set --name=emoji -- "$1"
    emoji=$1
    case $1 in
    check | ok) emoji=white_check_mark ;;
    esac
    # for lines in channels
    while read -r line; do
        [ -n "$line" ] || continue
        read -r main links <<<"$line"
        IFS="/" read -r channel post <<<"$main"
        _mattermost_reaction "$post" "$emoji"
        if [ -n "$post_links" ]; then
            while IFS=" " read -r link; do
                [ -n "$link" ] || continue
                IFS="/" read -r channel post <<<"$link"
                _mattermost_reaction "$post" "$emoji"
            done <<<"$links"
        fi
    done <<<"$mattermost_post_ids"
}

# Add response to mattermost posting
# This can only be called if a @mattermost call was used previously.
# Usage:    mattermost_response <text> [<attachments>]
# Globals:  $MATTERMOST_API + $MATTERMOST_TOKEN to access API
# Returns:  0 without action if no $MATTERMOST_API + $MATTERMOST_TOKEN
mattermost_repost() {
    if [ -z "$MATTERMOST_API" ] || [ -z "$MATTERMOST_TOKEN" ]; then
        debug "Disabled because MATTERMOST_API and MATTERMOST_TOKEN are not both set"
        return 0
    fi
    is integer --name=arguments --max=2 --die -- $#
    local line main channel post
    # for lines in channels
    while read -r line; do
        [ -n "$line" ] || continue
        read -r main _ <<<"$line"
        debug "main $main"
        IFS="/" read -r channel post <<<"$main"
        debug "channel $channel post $post"
        _mattermost_repost "$channel" "$post" "$1" "$2" >/dev/null
    done <<<"$mattermost_post_ids"
}
