#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Using the Grafana/Prometheus APIs to get Monitoring information.

######################################################################################
# Prometheus Exporter
######################################################################################

# Get exporter list
#
# The result can be filtered by additional argument specification.
#
# Usage:    exporter [<field>=<value>]...
# Globals:  $PROMETHEUS_HOST + $PROMETHEUS_API
# Output:   Tab separated list without header:
#           `<url>   <job>   <label-values>`
# Return:   0 without output if no $PROMETHEUS_HOST + $PROMETHEUS_API
exporter() {
    if [ -z "$PROMETHEUS_HOST" ] || [ -z "$PROMETHEUS_API" ]; then
        debug "Disabled because PROMETHEUS_HOST and PROMETHEUS_API are not both set"
        return 0
    fi
    install jq yq
    local arg name value
    local filter=""
    for arg in "$@"; do
        IFS='=' read -r name value <<<"$arg"
        unset IFS
        case $name in
        instance) filter="$filter select(.labels.$name|test(\"$value\")) |" ;;
        *) filter="$filter select(.labels.$name==\"$value\") |" ;;
        esac
    done
    local server api line
    local auth=""
    for server in $PROMETHEUS_HOST; do
        remote true 2>/dev/null || continue
        # shellcheck disable=SC2016
        auth="$auth"$'\n'"$(remote cat /etc/prometheus/prometheus.yml |
            yq -r '.scrape_configs[] 
            | select(.basic_auth) 
            | .job_name as $j 
            | .basic_auth as $b 
            | .static_configs[].targets[] 
            | [$j, $b.username, $b.password, .] 
            | @tsv')"
    done
    for api in $PROMETHEUS_API; do
        curl "$api"/targets | jq '.data.activeTargets[] | '"$filter"' [.scrapeUrl, .labels.job, (.labels | join(", ")), .discoveredLabels.__address__] | @tsv' -r |
            while read -r line; do
                local login user pass
                login="$(printf '%s' "$auth" | grep "$(cut -f2 <<<"$line")" | grep "$(cut -f4 <<<"$line")")"
                if [ -n "$login" ]; then
                    # shellcheck disable=SC2119
                    user="$(cut -f2 <<<"$login" | tr -d '\n' | urlencode)"
                    # shellcheck disable=SC2119
                    pass="$(cut -f3 <<<"$login" | tr -d '\n' | urlencode)"
                    cut -f1-3 <<<"$line" | sed "s#://#://$user:$pass@#"
                else
                    cut -f1-3 <<<"$line"
                fi
            done ||
            (($? == 141)) ||
            die "$(gettext "Could not get exporters from Prometheus!")"
    done
}

######################################################################################
# Prometheus
######################################################################################

# Prometheus API URLs as space separated list
PROMETHEUS_API="$PROMETHEUS_API"
# Prometheus host names as space separated list
PROMETHEUS="$PROMETHEUS"

# Scrape Prometheus exporter url now
#
# The metrics can be filtered by <pattern> argument.
#
# Usage:    scrape <url> <pattern>
# Output:   Tab separated list:
#           `<metric>    [<value>=<text>],...    <value>`
# Return:   - 0 if metrics found
#           - 1 if no matching metric
scrape() {
    is integer --name=arguments --max=2 --die -- $#
    is set --name=url --die -- "$1"
    local url="$1"
    debug "Scrape the Prometheus exporter at $1"
    local metrics
    metrics="$(curl "$url" | grep -Ev '^($|#)' || die "$(eval_gettext "Could not scrape the Prometheus exporter at \$url!")")"
    debug ">>> $metrics"
    local found=2
    grep -E "$2" <<<"$metrics" | grep '{' | sed 's/,\?[{}] \?/\t/g' || ((found--))
    grep -E "$2" <<<"$metrics" | grep -v '{' | sed 's/ /\t\t/g' || ((found--))
    ((found > 0))
}

######################################################################################
# Grafana
######################################################################################

# Grafana API URL used together with $GRAFANA_TOKEN and silently disables Grafana functions if not set
GRAFANA_API="$GRAFANA_API"
# Grafana API Token used in @alerts
GRAFANA_TOKEN="$GRAFANA_TOKEN"

# Get Grafana alerts
#
# The list can be filtered by options and a specific output format can be selected.
#
# Usage:    alerts [<format>]                       # tsv, json, console, mattermost
#           alerts -i "^$server" console || echo "" # will print the alerts with an empty line if there are some
# Options:  -a, --alertname <regexp>                # select alert name
#           -n, --net <name>                        # select network name (net label)
#           -g, --group <name>                      # show only messages for them (group label)
#           -i, --instance <regexp>                 # select only matching instances
#           -s, --summary <regexp>                  # select by summary text
#           -q, --quiet                             # return only status code
# Output:   - `format=json` - directly like in the Grafana API
#           - `format=mattermost` - json in the format of mattermost attachments
#           - `format=tsv` - Tab separated table
#           - `format=console` - like tsv but colorized and fixed column width instead of tabs
# Return:   - 0 - no alerts
#           - <num> - at least one alert
#           - 0 - without output if no $GRAFANA_API + $GRAFANA_TOKEN
alerts() {
    if [ -z "$GRAFANA_API" ] || [ -z "$GRAFANA_TOKEN" ]; then
        debug "Disabled because GRAFANA_API and GRAFANA_TOKEN are not both set"
        return 0
    fi
    # parameter parsing
    local filter="" quiet
    eval set -- "$(option_parse $'a alertname +\ng group +\ni instance +\nn net +\ns summary +\nq quiet -' "$@")"
    while true; do
        case "$1" in
        -g | --group)
            [ -z "$2" ] || filter+=" | select(.labels|has(\"group\")) | select(.labels.group|test(\".*$2.*\"; \"i\"))"
            shift 2
            ;;
        -i | --instance)
            [ -z "$2" ] || filter+=" | select(.labels.instance|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -a | --alertname)
            [ -z "$2" ] || filter+=" | select(.labels.alertname|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -s | --summary)
            [ -z "$2" ] || filter+=" | select(.annotations.summary? // \"\"|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -n | --net)
            [ -z "$2" ] || filter+=" | select(.labels.net? // \"\"|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -q | --quiet) quiet=1 && shift ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    debug "$filter"
    # processing
    install jq
    local list
    list="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts")" ||
        die "$(gettext "Could not get alerts from Grafana!")"
    echo "$list" >/tmp/alerts.json
    list="$(jq 'sort_by(.startsAt) | .[] '"$filter" <<<"$list")" || die "$(gettext "Parse error in Grafana alerts list with filter"): $filter"
    local format=${1:-console}
    # empty list
    [ -n "$list" ] || return 0
    # quiet mode
    [ -z "$quiet" ] || return 1
    # pre format
    case $format in
    mattermost)
        list="$(jq -s '
            .[] | {
                color:  (if .labels.severity == "disaster" then "#ff0000"
                        elif  .labels.severity == "critical" then "#FFA500"
                        elif  .labels.severity == "warning" then "#FFFF00"
                        else "#0000FF" end), 
                title:  ((.labels.severity|(.[:1] | ascii_upcase) + .[1:]) + ": " + .labels.alertname), 
                linktitle_link: .generatorURL,
                text:   ("**" + .annotations.summary + "**\n" + .annotations.description), 
                footer: "Grafana Alerts",
                fields: (.labels 
                    | {
                        Netz:(.net|ascii_upcase),Instanz:.instance
                    } 
                    | to_entries
                    | map({title: (.key|(.[:1] | ascii_upcase) + .[1:]), value: .value, short:true})
                )
            }
            ' <<<"$list" | jq -s .)"
        ;;
    *)
        # shellcheck disable=SC2059
        header="$(printf "$(gettext "Severity\tNetwork\tInstance\tSummary\tStart")\n")"
        list="$header"$'\n'"$(jq -r '[.labels.severity, .labels.net, .labels.instance, .annotations.summary, (.startsAt| split(".")[0]| strptime("%Y-%m-%dT%H:%M:%S")| strftime("%Y-%m-%d %H:%M:%S"))] | @tsv' <<<"$list")"
        ;;
    esac
    # final format
    case $format in
    console)
        local first=1
        printf '%s\n' "$list" |
            tsv to pprint |
            while read -r line; do
                case $line in
                warning*) warn "$line" ;;
                critical*) error "$line" ;;
                disaster*) critical "$line" ;;
                *)
                    if [ -n "$first" ]; then
                        invers "$line"
                        first=""
                    else
                        printf '%s\n' "$line"
                    fi
                    ;;
                esac
            done
        ;;
    *)
        printf '%s\n' "$list"
        ;;
    esac
    return 1
}

# Prom ql ausführen
#
# Usage:    prometheus <prom-ql>
# Globals:  $PROMETHEUS_API to query
# Returns:  0 - without output if no $PROMETHEUS_API
prometheus() {
    if [ -z "$PROMETHEUS_API" ]; then
        debug "Disabled because PROMETHEUS_API is not set"
        return 0
    fi
    is integer --name=arguments --max=1 --die -- $#
    is set --name=prom-ql --die -- "$1"
    # processing
    local api
    api="${PROMETHEUS_API%% *}"
    # shellcheck disable=SC2119
    curl "$api/query?query=$(urlencode "$1")"
    # start=
    # end=
    # step=
}

# Change scrape interval to scrape now and set back
#
# Usage:    prometheus_scrape_now <job> [<timeout>]
# Globals:  $PROMETHEUS_HOST to change config temporarily
# Returns:  0 - without output if no $PROMETHEUS_HOST
prometheus_scrape_now() {
    if [ -z "$PROMETHEUS_HOST" ]; then
        debug "Disabled because PROMETHEUS_HOST is not set"
        return 0
    fi
    install yq
    local job=$1
    local -i seconds=${2:-60}
    for server in $PROMETHEUS_HOST; do
        remote true 2>/dev/null || continue # only work on reachable server
        printf '%s\n' "Let $server scrape $job again, now."
        printf '%s\n' "yq '(.scrape_configs[] | select(.job_name == \"$job\")).scrape_interval = \"${seconds}s\" | (.scrape_configs[] | select(.job_name == \"$job\")).scrape_timeout = \"${seconds}s\"' </etc/prometheus/prometheus.yml | sponge /etc/prometheus/prometheus.yml" | remote
        remote curl -sX POST http://localhost:9090/-/reload
    done
    pause --timeout="$seconds" "Wait till scrape should be done..."
    printf '%s\n' "Reset config back to default."
    for server in $PROMETHEUS_HOST; do
        remote true 2>/dev/null || continue # only work on reachable server
        remote /etc/prometheus/config-builder/update >/dev/null
    done
}
