#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Using the Grafana/Prometheus APIs to get Monitoring information.

# load other modules if not already done
declare -F "curl" >/dev/null || source "$BASHLIB_HOME"/module/remote

######################################################################################
# Monitoring
######################################################################################

# Get exporter list
# Usage:    exporter [<field>=<value>]...
# Stdout:   <url>\t<job>\t<label-values>
#           ...
exporter() {
    install jq yq
    local arg name value
    local filter=""
    for arg in "$@"; do
        IFS='=' read -r name value <<<"$arg"
        unset IFS
        case $name in
        instance) filter="$filter select(.labels.$name|test(\"$value\")) |" ;;
        *) filter="$filter select(.labels.$name==\"$value\") |" ;;
        esac
    done
    local server api line
    local auth=""
    for server in $PROMETHEUS; do
        remote true 2>/dev/null || continue
        # shellcheck disable=SC2016
        auth="$auth"$'\n'"$(remote cat /etc/prometheus/prometheus.yml |
            yq -r '.scrape_configs[] 
            | select(.basic_auth) 
            | .job_name as $j 
            | .basic_auth as $b 
            | .static_configs[].targets[] 
            | [$j, $b.username, $b.password, .] 
            | @tsv')"
    done
    for api in $PROMETHEUS_API; do
        curl "$api"/targets | jq '.data.activeTargets[] | '"$filter"' [.scrapeUrl, .labels.job, (.labels | join(", ")), .discoveredLabels.__address__] | @tsv' -r |
            while read -r line; do
                local login user pass
                login="$(echo "$auth" | grep "$(echo "$line" | cut -f2)" | grep "$(echo "$line" | cut -f4)")"
                if [ -n "$login" ]; then
                    user="$(echo "$login" | cut -f2 | tr -d '\n' | urlencode)"
                    pass="$(echo "$login" | cut -f3 | tr -d '\n' | urlencode)"
                    echo "$line" | cut -f1-3 | sed "s#://#://$user:$pass@#"
                else
                    echo "$line" | cut -f1-3
                fi
            done ||
            die "Could not get exporters from prometheus!"
    done
}

# Scrape prometheus exporter url now
# Usage:    scrape <url> <pattern>
# Stdout:   <metric>\t[<value>=<text>],...\t<value>
#           ...
scrape() {
    num_parameters "$@" --min 1 --max 2 --die "Wrong number of parameters for scrape!"
    debug "Scrape the prometheus exporter at $1"
    local metrics
    metrics="$(curl "$1" | grep -E "$2" | grep -Ev '^($|#)' || die "Could not scrape the prometheus exporter at $1!")"
    debug ">>> $metrics"
    echo "$metrics" | grep '{' | sed 's/,\?[{}] \?/\t/g'
    echo "$metrics" | grep -v '{' | sed 's/ /\t\t/g'
}

# Get grafana alerts
# Usage:    alerts [<format>]                       # json, console, mattermost
#           alerts -i "^$server" console || echo "" # will print the alerts with an empty line if there are some
# Options:  -a, --alertname <regexp>                # select alert name
#           -n, --net <name>                        # select network name
#           -i, --instance <regexp>                 # select only matching instances
#           -s, --summary <regexp>                  # select by summary text
#           -q, --quiet                             # return only status code
# Stdout:   <header-line>
#           <severity>\t<network>\t<instance>\t<decription>\t<time>
#           ...
# Return:   0 := no alerts
#           0 := at least one alert
alerts() {
    # parameter parsing
    local filter="" quiet
    eval set -- "$(option_parse $'a alertname +\ni instance +\nn net +\ns summary +\nq quiet -' "$@")"
    while true; do
        case "$1" in
        -i | --instance)
            [ -z "$2" ] || filter="$filter | select(.labels.instance|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -a | --alertname)
            [ -z "$2" ] || filter="$filter | select(.labels.alertname|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -s | --summary)
            [ -z "$2" ] || filter="$filter | select(.annotations.summary? // \"\"|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -n | --net)
            [ -z "$2" ] || filter="$filter | select(.labels.net? // \"\"|test(\"$2\"; \"i\"))"
            shift 2
            ;;
        -q | --quiet)
            quiet=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *) die "Unerwartete option in: $1" ;;
        esac
    done
    # processing
    install jq mlr
    local list
    list="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts")" ||
        die "Could not get alerts from Grafana!"
    list="$(jq 'sort_by(.startsAt) | .[] '"$filter" <<<"$list")" || die "Parse error in Grafana alerts list with filter: $filter"
    local format=${1:-console}
    # empty list
    [ -n "$list" ] || return 0
    # quiet mode
    [ -z "$quiet" ] || return 1
    # pre format
    case $format in
    mattermost)
        list="$(jq -s '.[] | {
                color:  (if .labels.severity == "disaster" then "#ff0000"
                        elif  .labels.severity == "critical" then "#FFA500"
                        elif  .labels.severity == "warning" then "#FFFF00"
                        else "#0000FF" end), 
                title:  ((.labels.severity|(.[:1] | ascii_upcase) + .[1:]) + ": " + .labels.alertname), 
                linktitle_link: .generatorURL,
                text:   ("**" + .annotations.summary + "**\n" + .annotations.description), 
                footer: "Grafana Alerts",
                fields: (.labels 
                    | {
                        Netz:(.net|ascii_upcase),Instanz:.instance
                    } 
                    | to_entries
                    | map({title: (.key|(.[:1] | ascii_upcase) + .[1:]), value: .value, short:true})
                )
            }' <<<"$list" | jq -s .)"
        ;;
    *)
        list=$'Severity\tNetz\tInstanz\tZusammenfassung\tStart          _\n'"$(jq -r '[.labels.severity, .labels.net, .labels.instance, .annotations.summary, (.startsAt| split(".")[0]| strptime("%Y-%m-%dT%H:%M:%S")| strftime("%Y-%m-%d %H:%M:%S"))] | @tsv' <<<"$list")"
        ;;
    esac
    # final format
    case $format in
    console)
        echo -e "$list" |
            tsv2table |
            while read -r line; do
                case $line in
                Severity*) invers "$line" ;;
                warning*) warn "$line" ;;
                critical*) error "$line" ;;
                disaster*) critical "$line" ;;
                *) echo "$line" ;;
                esac
            done
        ;;
    *)
        echo "$list"
        ;;
    esac
    return 1
}

# Prom ql ausführen
# Usage:    prometheus <prom-ql>
prometheus() {
    local api
    api="${PROMETHEUS_API%% *}"
    curl "$api/query?query=$(echo "$1" | urlencode)"
    # start=
    # end=
    # step=
}

# Change scrape interval to scrape now and set back
# Usage:    prometheus_scrape <job> [<timeout>]
prometheus_scrape() {
    install yq
    local job=$1
    local -i seconds=${2:-60}
    for server in $PROMETHEUS; do
        remote true 2>/dev/null || continue # only work on reachable server
        echo "Let $server scrape $job again, now."
        echo "yq '(.scrape_configs[] | select(.job_name == \"$job\")).scrape_interval = \"${seconds}s\" | (.scrape_configs[] | select(.job_name == \"$job\")).scrape_timeout = \"${seconds}s\"' </etc/prometheus/prometheus.yml | sponge /etc/prometheus/prometheus.yml" | remote
        remote curl -sX POST http://localhost:9090/-/reload
    done
    echo "Wait $seconds seconds till scrape should be done..."
    sleep "$seconds"
    echo "Reset config back to default."
    for server in $PROMETHEUS; do
        remote true 2>/dev/null || continue # only work on reachable server
        remote /etc/prometheus/config-builder/update >/dev/null
    done
}
