#!/usr/bin/env bash
# shellcheck disable=SC2034

# Module with network functions.

######################################################################################
### IP handling
######################################################################################

# Get IP of given hostname
#
# This uses `getent` which may take some seconds to resolve. But if `dig` is installed this will be used, because it works faster.
#
# Usage:    ip_resolve [<option>] host.de
# Options:  v, version=<int>    # ip version 4 or 6
# Output:   one ip address
ip_resolve() {
    eval set -- "$(option_parse $'v version +' "$@")"
    local type
    while true; do
        case "$1" in
        -v | --version) is enum --name=version --allow="4 6" --die --output=type -- "$2" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is set --name=host --die -- "$1"
    # processing
    local query
    if command -v dig >/dev/null; then
        [ "$type" = 4 ] && query="A" || true
        [ "$type" = 6 ] && query="AAAA" || true
        dig +short $query "$1"
    else
        is set -- "$type" && query="ahostsv$type" || query=hosts
        getent $query "$1" | awk '{print $1}' | head -n1
    fi
}

# Show the IP addresses
#
# The possible response formats are:
#
# - `main` - (default) to return only the main IP
# - `data` - complete data table tab separated
#
# Usage:    ip_intern <format>
# Output:   <ip>
# shellcheck disable=SC2120
ip_intern() {
    is integer --name=arguments --max=1 --die -- $#
    install ip
    case ${1-} in
    data)
        printf '%s\n' "$(gettext "IP\tInterface")"
        ip -o addr show | awk 'BEGIN { OFS="\t" } $2 != "lo" {print $4, $2}'
        ;;
    *) ip route get 1 | awk '{print $7; exit}' ;;
    esac
}

# Array: Provider selection per ip (regex provider) used in @ip_pattern
IP_PROVIDER_PATTERN="${IP_PROVIDER_PATTERN:-(".*" Unknown)}"
# Array: Network segment selection per ip (regex segment) used in @ip_pattern
IP_SEGMENT_PATTERN="${IP_SEGMENT_PATTERN:-(".*" other)}"
# Array: Network segment selection per ip (regex segment) used in @ip_pattern
IP_VMWARE_PATTERN="${IP_VMWARE_PATTERN}"

# Find info about IP by configured patterns.
#
# Possible types are like in the configuration:
#
# - provider
# - segment
# - vmware
#
# If no pattern matches there won't be any return value
#
# Usage:    ip_pattern <type> [<ip>]
# Output:   <value> of first matching line
# Return:   1 if no match found
ip_pattern() {
    is integer --name=arguments --max=2 --die -- $#
    is enum --name=type --allow="provider segment vmware" --die -- "$1"
    local type=$1
    local ip=${2-}
    [ -n "$ip" ] || ip="$(ip_intern)"
    # processing
    # use referenced array
    local name="IP_${type^^}_PATTERN"
    declare -p "$name" 2>/dev/null | grep -q 'declare -a' || die "No configuration array $name defined."
    debug "checking $ip against $name"
    declare -n lookup="$name"
    # find pattern
    for ((i = 0; i < ${#lookup[@]}; i += 2)); do
        if [[ "$ip" =~ ${lookup[i]} ]]; then
            printf '%s\n' "${lookup[i + 1]}"
            return 0
        fi
        debug 7 "$ip =~ ${lookup[i]} => false"
    done
    return 1
}

declare -A _ip_extern_data
_ip_extern_json=

# Run  os detection and set the constants
#
# The following formats are possible:
#
# - data - all values with `<name>\t<value>`
# - ip - <ipv4>\n<ipv6>
# - ipv4
# - ipv6
# - country - like DE
# - region - like Baden-Württemberg
# - city - like Reutlingen
# - zip - like 72766
# - loc - <lat>,<lon>
# - timezone - like Europe/Berlin
# - org - like AS3320 Deutsche Telekom AG
#
# Usage:    ip_extern <format>
# Output:   <tsv-table> for data
#           <value> else
ip_extern() {
    is integer --name=arguments --max=1 --die -- $#
    is enum --name=format --allow="data country countryCode region regionName city zip lat lon timezone isp org as ip" --die -- "$1"
    # get ips
    if [ -z "$_ip_extern_ip" ]; then
        hash _ip_extern_data set ipv4 "$(curl -s4 icanhazip.com)"
        hash _ip_extern_data set ipv6 "$(curl -s6 ifconfig.co)"
    fi
    # return ips
    case ${1-} in
    ipv4) hash _ip_extern_data get ipv4 && return ;;
    ipv6) hash _ip_extern_data get ipv6 && return ;;
    ip) printf '%s\n%s' "$(hash _ip_extern_data get ipv4)" "$(hash _ip_extern_data get ipv6)" && return ;;
    esac
    # get other data
    hash _ip_extern_data has isp || _ip_extern_ipapi_com || _ip_extern_ipinfo_co
    # return other data
    case ${1-} in
    data) hash _ip_extern_data to tsv ;;
    *) hash _ip_extern_data get "$1" ;;
    esac
}
_ip_extern_ipapi_com() {
    local json
    json="$(curl http://ip-api.com/json)"
    hash _ip_extern_data set country "$(jq .countryCode -r <<<"$json")"
    hash _ip_extern_data set region "$(jq .regionName -r <<<"$json")"
    hash _ip_extern_data set city "$(jq .city -r <<<"$json")"
    hash _ip_extern_data set zip "$(jq .zip -r <<<"$json")"
    hash _ip_extern_data set timezone "$(jq .timezone -r <<<"$json")"
    hash _ip_extern_data set org "$(jq .as -r <<<"$json")"
    hash _ip_extern_data set loc "$(jq '(.lat|tostring)+","+(.lon|tostring)' -r <<<"$json")"
}
_ip_extern_ipinfo_co() {
    local json
    json="$(curl ipinfo.io)"
    hash _ip_extern_data set country "$(jq .country -r <<<"$json")"
    hash _ip_extern_data set region "$(jq .region -r <<<"$json")"
    hash _ip_extern_data set city "$(jq .city -r <<<"$json")"
    hash _ip_extern_data set zip "$(jq .postal -r <<<"$json")"
    hash _ip_extern_data set timezone "$(jq .timezone -r <<<"$json")"
    hash _ip_extern_data set org "$(jq .org -r <<<"$json")"
    hash _ip_extern_data set loc "$(jq .loc -r <<<"$json")"
}
