#!/usr/bin/env bash
# shellcheck disable=SC2034

# Module with network functions.

######################################################################################
### IP handling
######################################################################################

# Show the IP addresses.
# The possible response formats are:
#
# - `main` - (default) to return only the main IP
# - `data` - complete data table tab separated
# Usage:    ip_intern <format>
# Output:   <ip>
# shellcheck disable=SC2120
ip_intern() {
    is integer --name=arguments --max=1 --die -- $#
    case ${1-} in
    data)
        echo -e "$(gettext "IP\tInterface")"
        ip -o addr show | awk 'BEGIN { OFS="\t" } $2 != "lo" {print $4, $2}'
        ;;
    *) ip route get 1 | awk '{print $7; exit}' ;;
    esac
}

# Find info about IP by configured patterns.
# Possible types are like in the configuration:
#
# - provider
# - segment
# - vmware
#
# If no pattern matches there won't be any return value
# Usage:    ip_pattern <type> [<ip>]
# Output:   <value> of first matching line
# Return:   1 if no match found
ip_pattern() {
    is integer --name=arguments --max=2 --die -- $#
    is enum --name=type --allow="provider segment vmware" --die -- "$1"
    local type=$1
    local ip=${2-}
    [ -n "$ip" ] || ip="$(ip_intern)"
    # processing
    # use referenced array
    local name="IP_${type^^}_PATTERN"
    declare -p "$name" 2>/dev/null | grep -q 'declare \-a' || die "No configuration array $name defined."
    debug "checking $ip against $name"
    declare -n lookup="$name"
    # find pattern
    for ((i = 0; i < ${#lookup[@]}; i += 2)); do
        if [[ "$ip" =~ ${lookup[i]} ]]; then
            echo "${lookup[i + 1]}"
            return 0
        fi
        debug 7 "$ip =~ ${lookup[i]} => false"
    done
    return 1
}

_ip_extern_json=

# Run  os detection and set the constants
# The following formats are possible:
#
# - data - all values with `<name>\t<value>`
# - country
# - countryCode
# - region
# - regionName
# - city
# - zip
# - lat
# - lon
# - timezone
# - isp
# - org
# - as
# - ip
# Usage:    ip_extern <format>
# Output:   <tsv-table> for data
#           <value> else
ip_extern() {
    is integer --name=arguments --max=1 --die -- $#
    is enum --name=format --allow="data country countryCode region regionName city zip lat lon timezone isp org as ip" --die -- "$1"
    # processing
    [ -n "$_ip_extern_json" ] || _ip_extern_json="$(curl http://ip-api.com/json)"
    case ${1-} in
    data) jq -r 'with_entries(if .key == "query" then .key = "ip" else . end) | to_entries[] | "\(.key)\t\(.value)"' <<<"$_ip_extern_json" ;;
    ip) jq -r .query <<<"$_ip_extern_json" ;;
    *) jq -r ".$1" <<<"$_ip_extern_json" ;;
    esac
}

detect_extern_ip() { _deprecated "use ip_extern instead"; }
