#!/usr/bin/env bash
# shellcheck disable=SC2034

# Module with operating system specific helper functions.

######################################################################################
### Detect OS
######################################################################################

declare -A _os_detected

# Detect OS settings
# The following formats are possible:
# - data - all values with `<name>\t<value>`
# - info - show human readable paragraph
# - os - operating system type like Linux, Solaris, Windows
# - base - base distribution type like Debian, ArchLinux
# - base_revision_name - (optional)
# - base_revision_number - (optional)
# - distribution - real distribution name
# - revision_number - distribution number
# - revision_name - version code name
# - kernel - version number of kernel like 6.8.0-87-generic
# - cpu_model - cpu name
# - cpu_num - number of cpus
# - architecture - x86_64, i686, i386, armv7l, aarch64...
# - machine_id
# - virtual_machine - `false` or `true`
# Usage:    os_detect <format>
# Output:   <tsv-table> for data
#           <value> else
os_detect() {
    num_parameters --min 1 --max 1 --die "A format is needed." -- "$@"
    if [ ${#_os_detected[@]} -eq 0 ]; then
        # get values
        _os_detected["os"]="$(
            case "$(uname -s)" in
            "Darwin") echo MacOS ;;
            "SunOS") echo Solaris ;;
            "GNU"*) echo Linux ;;
            *"BSD" | "DragonFly" | "Bitrig") echo BSD ;;
            "CYGWIN"* | "MSYS"* | "MINGW"*) echo Windows ;;
            *) uname -s ;;
            esac
        )"
        case ${_os_detected["os"]} in
        Linux)
            if [ -f /etc/arch-release ]; then
                _os_detected["base"]=ArchLinux
                _os_detected["distribution"]="ArchLinux"
                _os_detected["revision_name"]="Rolling"
                _os_detected["revision_number"]="$(grep base /var/log/pacman.log | tail -n 1)"
            elif [ -f /etc/alpine-release ]; then
                _os_detected["base"]=Alpine
                _os_detected["distribution"]=Alpine
                _os_detected["revision_number"]="$(grep '^VERSION_ID=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }' | sed 's/"//g')"
            elif [ -f /etc/gentoo-release ]; then
                _os_detected["base"]=Gentoo
                _os_detected["distribution"]="$(cat /etc/gentoo-release | sed s/\ release.*//)"
                _os_detected["revision_number"]="$(cat /etc/gentoo-release | sed s/.*release\ // | sed s/\ .*//)"
            elif [ -f /etc/redhat-release ]; then
                _os_detected["base"]=RedHat
                _os_detected["distribution"]="$(cat /etc/redhat-release | sed s/\ release.*//)"
                _os_detected["revision_name"]="$(cat /etc/redhat-release | sed s/.*\(// | sed s/\)//)"
                _os_detected["revision_number"]="$(cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//)"
            elif [ -f /etc/SuSE-release ]; then
                _os_detected["base"]=SuSe
                _os_detected["revision_name"]="$(cat /etc/SuSE-release | tr "\n" ' ' | sed s/VERSION.*//)"
                _os_detected["revision_number"]="$(cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //)"
            elif [ -f /etc/mandrake-release ]; then
                _os_detected["base"]=Mandrake
                _os_detected["revision_name"]="$(cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//)"
                _os_detected["revision_number"]="$(cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//)"
            elif [ -f /etc/debian_version ]; then
                _os_detected["base"]=Debian
                local revision
                revision="$(cat /etc/debian_version | sed -e 's/\([0-9]*\)\..*/\1/;s/\/.*//')"
                if [[ "$revision" =~ [a-z] ]]; then
                    _os_detected["base_revision_number"]="$(curl -s https://ftp.debian.org/debian/dists/"$revision"/Release |
                        grep Version | cut -d' ' -f2 | sed 's/\..*//')"
                    _os_detected["base_revision_name"]="$revision"
                else
                    _os_detected["base_revision_number"]="$revision"
                    _os_detected["base_revision_name"]="$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)"
                fi
                _os_detected["distribution"]="$(grep '^NAME=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }' | sed 's/"//g;s/ .*//')"
                _os_detected["revision_number"]="$(grep '^VERSION_ID=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }' | sed 's/"//g')"
                _os_detected["revision_name"]="$(grep '^VERSION_CODENAME=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }')"
            fi
            ;;
        esac
        _os_detected["kernel"]="$(uname -r)"
        _os_detected["cpu_model"]="$(grep 'model name' /proc/cpuinfo | head -n 1 | sed 's/^.*: //')"
        _os_detected["cpu_num"]="$(grep -c ^processor /proc/cpuinfo)"
        _os_detected["architecture"]="$(
            case ${_os_detected["os"]} in
            Solaris) uname -p ;;
            *) uname -m ;;
            esac
        )"
        _os_detected["machine_id"]="$(cat /etc/machine-id /var/lib/dbus/machine-id /var/db/dbus/machine-id /sys/class/dmi/id/board_serial 2>/dev/null | head -n 1 || true)"
        _os_detected["virtual_machine"]="$(grep -q '^flags.* hypervisor' /proc/cpuinfo && echo true || echo false)"
        for key in "${!_os_detected[@]}"; do
            echo -e "$key=${_os_detected[$key]}"
        done | debug
    fi
    # make output
    case ${1-} in
    data)
        for key in "${!_os_detected[@]}"; do
            echo -e "$key\t${_os_detected[$key]}"
        done
        ;;
    info)
        echo -n "${_os_detected["os"]} system with kernel ${_os_detected["kernel"]} on ${_os_detected["architecture"]} (${_os_detected["cpu_num"]}x ${_os_detected["cpu_model"]})"
        [ "${_os_detected["virtual_machine"]}" = "true" ] && echo "virtual machine" || echo
        echo "${_os_detected["distribution"]} version ${_os_detected["revision_number"]} (${_os_detected["revision_name"]})"
        if [ -n "${_os_detected["base_revision_number"]}" ]; then
            echo "Based on ${_os_detected["base"]} version ${_os_detected["base_revision_number"]} (${_os_detected["base_revision_name"]})"
        fi
        ;;
    *) echo "${_os_detected["$1"]}" ;;
    esac
}

detect_os() { _deprecated "use os_detect data"; }
system_info() { deprected "use os_detect info"; }

######################################################################################
### Disk
######################################################################################

# Disk free with visual display
# The lines will be colorized based on `$MOUNT_COLOR_LIMIT`` setting, which contains sets of 5 entries (pattern critical error warn ok). The first matching pattern will decide the color limits.
# If a `--free` condition and `--collect` is given all disks violating this will be collected as string within the collection variable for further use.
# Usage:    disk_free [options] [<mount>...]            # show table
# Options:  -l, --local     # only list local devices
#           -c, --collect <variable-name>
#           -f, --free [<operator>]<percent%|bytes>
# Output:   # same as `df` command but colorized
disk_free() {
    # parameter parsing
    local opt="" free_operator free_percent free_bytes collect
    eval set -- "$(option_parse $'l locale -\nc collect +\nf free +' "$@")"
    while true; do
        case "$1" in
        -l | --locale)
            opt="-l"
            shift
            ;;
        -f | --free)
            local text="$2"
            if [[ "$text" =~ ^([<>]=?|==|!=)?(([0-9]+)[%bB]?)$ ]]; then
                read -r _ free_operator val num <<<"${BASH_REMATCH[@]}"
                free_operator="${free_operator:-<}"
                [[ "$val" =~ ^[0-9]+%$ ]] &&
                    free_percent="$num" ||
                    free_bytes="$(numfmt --from=iec <<<"${num^^}")"
            else
                die "Option value --free=$2 not supported!"
            fi
            shift 2
            ;;
        -c | --collect)
            declare -n collect="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    debug "collect into $collect ($free_operator ${free_percent}%/${free_bytes}B)"
    # processing
    local firstline="" percent mount device limit_c limit_e limit_w limit_o
    IFS=$'\n'
    # shellcheck disable=SC2248
    for line in $(df -h $opt -x tmpfs -x efivarfs -x devtmpfs -x squashfs "$@"); do
        if [ -z "$firstline" ]; then
            firstline=1
            invers "$line"
        else
            percent=$(echo "$line" | xargs echo | cut -d' ' -f5 | sed 's/%//')
            bytes=$(echo "$line" | xargs echo | cut -d' ' -f4)
            mount=$(echo "$line" | xargs echo | cut -d' ' -f6 | nocr)
            # get color limits
            device=$(echo "$line" | xargs echo | cut -d' ' -f1)
            # shellcheck disable=SC2154
            for ((i = 0; i < ${#MOUNT_COLOR_LIMIT[@]}; i += 5)); do
                pattern="${MOUNT_COLOR_LIMIT[i]}"
                if [[ "$device" =~ $pattern ]]; then
                    limit_c="${MOUNT_COLOR_LIMIT[i + 1]}"
                    limit_e="${MOUNT_COLOR_LIMIT[i + 2]}"
                    limit_w="${MOUNT_COLOR_LIMIT[i + 3]}"
                    limit_o="${MOUNT_COLOR_LIMIT[i + 4]}"
                    break
                fi
            done
            # display
            if ((percent == limit_c)); then
                critical "$line"
            elif ((percent == limit_e)); then
                error "$line"
            elif ((percent == limit_w)); then
                warn "$line"
            elif ((percent == limit_o)); then
                ok "$line"
            else
                echo "$line"
            fi
            # collection limit
            # shellcheck disable=SC1105
            if [ -n "$free_operator" ]; then
                if [ -n "$free_percent" ] &&
                    eval "(( 100 - percent $free_operator free_percent ))"; then
                    collect+="${mount} "
                elif [ -n "$free_bytes" ] &&
                    eval "(( bytes $free_operator free_bytes ))"; then
                    collect+="${mount} "
                fi
            fi
        fi
    done
    unset IFS
}

######################################################################################
### Further Specialities
######################################################################################

# Has tty present
# Usage:    has_ttyp
# Status:   0 || 1
has_tty() {
    { : >/dev/tty; } &>/dev/null
}

# Is running with bash console
# Usage:    is_bash
# Status:   0 || 1
is_bash() {
    [[ -n "${BASH_VERSION:-}" ]]
}
