#!/usr/bin/env bash
# shellcheck disable=SC2034
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null

# Module with operating system specific helper functions.

######################################################################################
### Detect OS / Hardware
######################################################################################

declare -A _os_detected

# Detect OS settings and Hardware
#
# The following formats are possible:
#
# - data - all values with `<name>\t<value>`
# - info - show human readable paragraph
# - os - operating system type like Linux, Solaris, Windows
# - base - base distribution type like Debian, ArchLinux
# - base_revision_name - (optional)
# - base_revision_number - (optional)
# - distribution - real distribution name
# - revision_number - distribution number
# - revision_name - version code name
# - kernel - version number of kernel like 6.8.0-87-generic
# - architecture - x86_64, i686, i386, armv7l, aarch64...
# - cpu_model - cpu name
# - cpu_num - number of cpus
# - memory - hardware memory in GB
# - machine_id
# - virtual_machine - `false` or `true`
#
# Usage:    os_detect <format>
# Output:   - <tsv-table> for data
#           - <value> else
os() {
    is integer --name=arguments --max=1 --die -- $#
    is enum --name=format --allow="data info os base base_revision_name base_revision_number distribution revision_number revision_name kernel cpu_model cpu_num memory architecture machine_id virtual_machine" --die -- "$1"
    # processing
    if [ ${#_os_detected[@]} -eq 0 ]; then
        # get values
        _os_detected["os"]="$(
            case "$(uname -s)" in
            "Darwin") printf MacOS ;;
            "SunOS") printf Solaris ;;
            "GNU"*) printf Linux ;;
            *"BSD" | "DragonFly" | "Bitrig") printf BSD ;;
            "CYGWIN"* | "MSYS"* | "MINGW"*) printf Windows ;;
            *) uname -s ;;
            esac
        )"
        case ${_os_detected["os"]} in
        Linux)
            if [ -f /etc/arch-release ]; then
                _os_detected["base"]=ArchLinux
                _os_detected["distribution"]="ArchLinux"
                _os_detected["revision_name"]="Rolling"
                _os_detected["revision_number"]="$(grep base /var/log/pacman.log | tail -n 1)"
            elif [ -f /etc/alpine-release ]; then
                _os_detected["base"]=Alpine
                _os_detected["distribution"]=Alpine
                _os_detected["revision_number"]="$(grep '^VERSION_ID=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }' | sed 's/"//g')"
            elif [ -f /etc/gentoo-release ]; then
                _os_detected["base"]=Gentoo
                _os_detected["distribution"]="$(cat /etc/gentoo-release | sed s/\ release.*//)"
                _os_detected["revision_number"]="$(cat /etc/gentoo-release | sed s/.*release\ // | sed s/\ .*//)"
            elif [ -f /etc/redhat-release ]; then
                _os_detected["base"]=RedHat
                _os_detected["distribution"]="$(cat /etc/redhat-release | sed s/\ release.*//)"
                _os_detected["revision_name"]="$(cat /etc/redhat-release | sed s/.*\(// | sed s/\)//)"
                _os_detected["revision_number"]="$(cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//)"
            elif [ -f /etc/SuSE-release ]; then
                _os_detected["base"]=SuSe
                _os_detected["revision_name"]="$(cat /etc/SuSE-release | tr "\n" ' ' | sed s/VERSION.*//)"
                _os_detected["revision_number"]="$(cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //)"
            elif [ -f /etc/mandrake-release ]; then
                _os_detected["base"]=Mandrake
                _os_detected["revision_name"]="$(cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//)"
                _os_detected["revision_number"]="$(cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//)"
            elif [ -f /etc/debian_version ]; then
                _os_detected["base"]=Debian
                local revision
                revision="$(cat /etc/debian_version | sed -e 's/\([0-9]*\)\..*/\1/;s/\/.*//')"
                if [[ "$revision" =~ [a-z] ]]; then
                    _os_detected["base_revision_number"]="$(curl -s https://ftp.debian.org/debian/dists/"$revision"/Release |
                        grep Version | cut -d' ' -f2 | sed 's/\..*//')"
                    _os_detected["base_revision_name"]="$revision"
                else
                    _os_detected["base_revision_number"]="$revision"
                    _os_detected["base_revision_name"]="$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)"
                fi
                _os_detected["distribution"]="$(grep '^NAME=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }' | sed 's/"//g;s/ .*//')"
                _os_detected["revision_number"]="$(grep '^VERSION_ID=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }' | sed 's/"//g')"
                _os_detected["revision_name"]="$(grep '^VERSION_CODENAME=' /etc/os-release | head -n 1 | awk -F= '{ print $2 }')"
            fi
            ;;
        esac
        _os_detected["kernel"]="$(uname -r)"
        _os_detected["cpu_model"]="$(grep 'model name' /proc/cpuinfo | head -n 1 | sed 's/^.*: //')"
        _os_detected["cpu_num"]="$(grep -c ^processor /proc/cpuinfo)"
        _os_detected["memory"]="$(LANG=C free --giga | awk '/^Mem:/ {printf "%.0f\n", $2 * (1000/1024)}')"
        _os_detected["architecture"]="$(
            case ${_os_detected["os"]} in
            Solaris) uname -p ;;
            *) uname -m ;;
            esac
        )"
        _os_detected["machine_id"]="$(cat /etc/machine-id /var/lib/dbus/machine-id /var/db/dbus/machine-id /sys/class/dmi/id/board_serial 2>/dev/null | head -n 1 || true)"
        _os_detected["virtual_machine"]="$(grep -q '^flags.* hypervisor' /proc/cpuinfo && printf true || printf false)"
        for key in "${!_os_detected[@]}"; do
            printf '%s=%s' "$key" "${_os_detected[$key]}"
        done | debug
    fi
    # make output
    case ${1-} in
    data)
        for key in "${!_os_detected[@]}"; do
            printf '%s\n' "$key\t${_os_detected[$key]}"
        done
        ;;
    info)
        printf '%s' "${_os_detected[os]} system with kernel ${_os_detected[kernel]} on ${_os_detected[architecture]} (${_os_detected[cpu_num]}x ${_os_detected[cpu_model]})"
        [ "${_os_detected["virtual_machine"]}" = "true" ] && printf 'virtual machine\n' || printf '\n'
        printf '%s\n' "${_os_detected[distribution]} version ${_os_detected[revision_number]} (${_os_detected[revision_name]})"
        if [ -n "${_os_detected[base_revision_number]}" ] && [ ! "${_os_detected[revision_number]}" = "${_os_detected[base_revision_number]}" ]; then
            printf '%s\n' "Based on ${_os_detected[base]} version ${_os_detected[base_revision_number]} (${_os_detected[base_revision_name]})"
        fi
        ;;
    *) printf '%s\n' "${_os_detected["$1"]}" ;;
    esac
}

# Deprecates: OS detection
# Renamed to @os
os_detect() {
    _deprecated "Use os now"
}

# Hardware description
#
# This will show information like:
#
# ```text
# System HP ZBook Firefly 16 inch G10 Mobile Workstation PC 5CG3371SB8
# BIOS HP V70 Ver. 01.09.00 04/11/2025 firmware 81.67
# Processor Intel(R) Corporation 13th Gen Intel(R) Core(TM) i7-1360P 12 cores 16 threads
# Memory 16 GB Samsung DDR5 SODIMM
# Memory 16 GB Samsung DDR5 SODIMM
# Port Type-C Port 1
# Port Type-C Port 2
# Port Left  USB Port
# Port Right USB Port
# Port HDMI Port
# Port Speaker Port
# Port SIM card
# ```
#
# Usage:    bios
# Output:   List with type as first word and details (type specific) behind
bios() {
    sudo dmidecode -t 1 | awk '
    /Product Name:/ { prod=$0; sub(".*Product Name: *","",prod) }
    /Serial Number:/ { ser=$0; sub(".*Serial Number: *","",ser); print "System " prod " " ser }'
    sudo dmidecode -t 0 | awk '
    /Vendor:/        { vendor=$0; sub(".*Vendor: *","",vendor) }
    /Version:/       { version=$0; sub(".*Version: *","",version) }
    /Release Date:/  { date=$0; sub(".*Release Date: *","",date) }
    /Firmware Revision:/  { firmware=$0; sub(".*Firmware Revision: *","",firmware); print "BIOS " vendor " " version " " date " firmware " firmware}'
    sudo dmidecode -t 4 | awk '
    /Manufacturer:/ { pm=$0; sub(".*Manufacturer: *","",pm) }
    /Version:/      { pv=$0; sub(".*Version: *","",pv) }
    /Core Count:/   { pc=$0; sub(".*Core Count: *","",pc) }
    /Thread Count:/ { pt=$0; sub(".*Thread Count: *","",pt); print "Processor " pm " " pv " " pc " cores " pt " threads" }'
    sudo dmidecode -t 17 | awk '
    /Size:/ { size=$0; sub(".*Size: *","",size) }
    /Type:/ { type=$0; sub(".*Type: *","",type) }
    /Form Factor:/ { ff=$0; sub(".*Form Factor: *","",ff) }
    /Manufacturer:/ { mm=$0; sub(".*Manufacturer: *","",mm); print "Memory " size " " mm " " type " " ff }'
    sudo dmidecode -t 8 | awk '
    /External Reference Designator:/ { des=$0; sub(".*External Reference Designator: *","",des); print "Port " des }'
    sudo dmidecode -t 9 | awk '
    section=="slot" && /Designation:/ { des=$0; sub(".*Designation: *","",des); print "system-slot " des }'
}

######################################################################################
### Disk
######################################################################################

use config/local

# Array: Color limits per mount (regex critical error warn ok) used in @df
MOUNT_COLOR_LIMIT="${MOUNT_COLOR_LIMIT:=('.*' 100 90 80 50)}"

# File system analyzation
#
# The following formats are defined:
#
# - list    only list mounts
# - data    all data as tsv table
# - console colored visual output
#
# Usage:    disk [options] <format> [<path>]...
# Options:  l, local    # show only local file systems
#           f, free [<operator>]<percent%|bytes>
disk() {
    # parameter parsing
    local opt="" format free_operator free_percent free_bytes
    eval set -- "$(option_parse $'l locale -\nr remote -\nf free +' "$@")"
    while true; do
        case "$1" in
        -l | --locale) opt="-l" && shift ;;
        -r | --remote) opt="-t nfs -t cifs -t sshfs -t smbfs -t fuse" && shift ;;
        -f | --free)
            local text="$2"
            if [[ "$text" =~ ^([<>]=?|==|!=)?(([0-9]+)[%bB]?)$ ]]; then
                read -r _ free_operator val num <<<"${BASH_REMATCH[@]}"
                free_operator="${free_operator:-<}"
                [[ "$val" =~ ^[0-9]+%$ ]] &&
                    free_percent="$num" ||
                    free_bytes="$(numfmt --from=iec <<<"${num^^}")"
            else
                die "Option value --free=$2 not supported!"
            fi
            shift 2
            ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is enum --name=format --allow="list data console" --die --output=format -- "$1" && shift
    # processing
    local type source size used avail pcent itotal iused iavail ipcent target list pval ival i pattern level
    # shellcheck disable=SC2086
    while read -r type source size used avail pcent itotal iused iavail ipcent target; do
        pval=${pcent%%%}
        [ "$ipcent" = "-" ] || ival=${ipcent%%%}
        for ((i = 0; i < ${#MOUNT_COLOR_LIMIT[@]}; i += 5)); do
            pattern="${MOUNT_COLOR_LIMIT[i]}"
            if [[ "$source" =~ $pattern ]]; then
                limit_c="${MOUNT_COLOR_LIMIT[i + 1]}"
                limit_e="${MOUNT_COLOR_LIMIT[i + 2]}"
                limit_w="${MOUNT_COLOR_LIMIT[i + 3]}"
                limit_o="${MOUNT_COLOR_LIMIT[i + 4]}"
                break
            fi
        done
        # display
        percent=$pval
        ((percent >= ival)) || percent=$ival
        if ((limit_c > 0 && percent >= limit_c)); then
            level=critical
        elif ((limit_e > 0 && percent >= limit_e)); then
            level=error
        elif ((limit_w > 0 && percent >= limit_w)); then
            level=warn
        elif ((limit_o > 0 && percent >= limit_o)); then
            level=ok
        else
            level=info
        fi
        debug "$target Limit: $limit_c $limit_e $limit_e $limit_o -> $level"
        if [ -n "$free_operator" ]; then
            if [ -n "$free_percent" ] &&
                eval "(( 100 - ${pcent%%%} $free_operator free_percent ))"; then
                list+="$type $source $size $used $avail $pcent $itotal $iused $iavail $ipcent $target $pval $ival $level"$'\n'
            elif [ -n "$free_bytes" ] &&
                eval "(( avail $free_operator free_bytes ))"; then
                list+="$type $source $size $used $avail $pcent $itotal $iused $iavail $ipcent $target $pval $ival $level"$'\n'
            fi
        else
            list+="$type $source $size $used $avail $pcent $itotal $iused $iavail $ipcent $target $pval $ival $level"$'\n'
        fi
    done < <(df -B1 $opt -x tmpfs -x efivarfs -x devtmpfs -x squashfs --output=fstype,source,size,used,avail,pcent,itotal,iused,iavail,ipcent,target "$@" 2>/dev/null |
        tail -n +2 | grep -v ^fuse.cryfs)
    # output
    case $format in
    list)
        while read -r type source size used avail pcent itotal iused iavail ipcent target pval ival level; do
            # shellcheck disable=SC2086
            is empty -- "$type" || printf '%s\n' $target
        done <<<"$list"
        ;;
    data)
        printf '%s\t' "$(gettext Type)" "$(gettext Source)" "$(gettext Total)" "$(gettext Used)" "$(gettext Avail)" "$(gettext Percent)" "$(gettext I-Total)" "$(gettext I-Used)" "$(gettext I-Avail)" "$(gettext I-Percent)" "$(gettext Mount)"
        printf '\n'
        while read -r type source size used avail pcent itotal iused iavail ipcent target pval ival level; do
            is set -- "$type" || continue
            # shellcheck disable=SC2086
            print '%s\t' $type $source $size $used $avail $pcent $itotal $iused $iavail $ipcent $target
            print '\n'
        done <<<"$list"
        ;;
    console)
        printf "${CC_INVERSE}%-30s %8s %8s %8s %8s %8s${CC_RESET}\n" "$(gettext Mount)" "$(gettext Total)" "$(gettext Used)" "$(gettext Avail)" "$(gettext Percent)" "$(gettext Inodes)"
        while read -r type source size used avail pcent itotal iused iavail ipcent target pval ival level; do
            # shellcheck disable=SC2046
            # shellcheck disable=SC2086
            is empty -- "$type" || printf '%-30s %8s %8s %8s %8s %8s\n' $target $(numfmt --to=iec --suffix=B $size) $(numfmt --to=iec --suffix=B $used) $(numfmt --to=iec --suffix=B $avail) $pcent $ipcent | $level
        done <<<"$list"
        ;;
    esac
}

# Deprecated: Disk free with visual display
# Use @disk instead.
#
# The lines will be colorized based on `$MOUNT_COLOR_LIMIT`` setting, which contains sets of 5 entries (pattern critical error warn ok). The first matching pattern will decide the color limits.
#
# If a `--free` condition and `--collect` is given all disks violating this will be collected as string within the collection variable for further use.
#
# Usage:    disk_free [options] [<mount>...]            # show table
# Options:  l, local     # only list local devices
#           c, collect <variable-name>
#           f, free [<operator>]<percent%|bytes>
# Output:   # same as `df` command but colorized
disk_free() {
    _deprecated "Use disk instead" warn
    # parameter parsing
    debug "$*"
    local opt="" free_operator free_percent free_bytes
    eval set -- "$(option_parse $'l locale -\nc collect +\nf free +' "$@")"
    while true; do
        case "$1" in
        -l | --locale) opt="-l" && shift ;;
        -f | --free)
            local text="$2"
            if [[ "$text" =~ ^([<>]=?|==|!=)?(([0-9]+)[%bB]?)$ ]]; then
                read -r _ free_operator val num <<<"${BASH_REMATCH[@]}"
                free_operator="${free_operator:-<}"
                [[ "$val" =~ ^[0-9]+%$ ]] &&
                    free_percent="$num" ||
                    free_bytes="$(numfmt --from=iec <<<"${num^^}")"
            else
                die "Option value --free=$2 not supported!"
            fi
            shift 2
            ;;
        -c | --collect) declare -n collect="$2" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    debug "$opt"
    ! declare -p collect >/dev/null || debug "collect into $collect ($free_operator ${free_percent}%/${free_bytes}B)"
    # processing
    local firstLine="" percent mount device limit_c limit_e limit_w limit_o
    IFS=$'\n'
    # shellcheck disable=SC2248
    for line in $(df -h $opt -x tmpfs -x efivarfs -x devtmpfs -x squashfs "$@"); do
        if [ -z "$firstLine" ]; then
            firstLine=1
            printf "${CC_INVERSE}%s${CC_RESET}\n" "$line"
        else
            percent=$(echo "$line" | xargs echo | cut -d' ' -f5 | sed 's/%//')
            bytes=$(echo "$line" | xargs echo | cut -d' ' -f4)
            mount=$(echo "$line" | xargs echo | cut -d' ' -f6 | sed 's/\r$//')
            # get color limits
            device=$(echo "$line" | xargs echo | cut -d' ' -f1)
            # shellcheck disable=SC2154
            for ((i = 0; i < ${#MOUNT_COLOR_LIMIT[@]}; i += 5)); do
                pattern="${MOUNT_COLOR_LIMIT[i]}"
                if [[ "$device" =~ $pattern ]]; then
                    limit_c="${MOUNT_COLOR_LIMIT[i + 1]}"
                    limit_e="${MOUNT_COLOR_LIMIT[i + 2]}"
                    limit_w="${MOUNT_COLOR_LIMIT[i + 3]}"
                    limit_o="${MOUNT_COLOR_LIMIT[i + 4]}"
                    break
                fi
            done
            # display
            if ((percent == limit_c)); then
                critical "$line"
            elif ((percent == limit_e)); then
                error "$line"
            elif ((percent == limit_w)); then
                warn "$line"
            elif ((percent == limit_o)); then
                ok "$line"
            else
                printf '%s\n' "$line"
            fi
            # collection limit
            if declare -p collect >/dev/null; then
                # shellcheck disable=SC1105
                if [ -n "$free_operator" ]; then
                    if [ -n "$free_percent" ] &&
                        eval "(( 100 - percent $free_operator free_percent ))"; then
                        collect+="${mount} "
                    elif [ -n "$free_bytes" ] &&
                        eval "(( bytes $free_operator free_bytes ))"; then
                        collect+="${mount} "
                    fi
                fi
            fi
        fi
    done
    unset IFS
}

# Show big directory and files
#
# Usage:    files big <path>
#           files interactive <path>
# Options:  p, percent <limit>
# Output:   <size human>\t<path> for `big`
files() {
    # parameter parsing
    local percent=10
    eval set -- "$(option_parse $'p percent +' "$@")"
    while true; do
        case "$1" in
        -p | --percent) is integer --name=percent --min=0 --max=100 --die --output=percent-- "$2" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is enum --name=command --allow="big interactive" --die --output=command -- "$1"
    is path --name=path --die --output=path -- "$2"
    # processing
    case $command in
    big)
        local max min size
        max=$(df -B1 "$path" | awk 'NR==2 {print $3}')
        min=$((max * percent / 100))
        while read -r size path; do
            # shellcheck disable=SC2046
            printf '%s\t%s\n' $(numfmt --to=iec --suffix=B <<<"$size") "$path"
        done < <(sudo du -abx "$path" 2>/dev/null | grep -v 'du: cannot access' | awk '$1 > '"$min" | sort -k2)
        ;;
    interactive)
        install ncdu
        ncdu -xe "$path"
        ;;
    esac
}

######################################################################################
### Users / SSH
######################################################################################

# Get information about user
#
# The sudo column will show: no, all, specified.
# Find more about the sudo rights using @sudo_info.
#
# Usage:    user_info [<user>]
# Output:   <tsv with header>
#           User UID  GID  Home       SuDo Login                     From    Duration
#           alex 1000 1000 /home/alex all  2026-01-13T07:01:09+01:00 0.0.0.0 still logged in
user_info() {
    local user home from login logout time uid gid shell sudo info
    getent passwd $1 | awk -F: '$3 >= 1000 && $3 < 60000 && $1 !~ /^snap_/ && $1 !~ /^(nobody|daemon|www-data|postgres|mysql|redis|git)/ {print $1}' | while IFS= read -r user; do
        IFS=: read -r _ _ uid gid _ home shell < <(getent passwd "$user")
        read -r _ _ from login logout < <(last -dw --time-format=iso -n 1 "$user")
        time="$(sed 's/.*(\|).*//g;s/+0\?/d /;s/:/h /;s/00/0/;s/\([0-9]\)$/\1m/' <<<"$logout")"

        info=$(LANG=C sudo -l -U "$user" 2>/dev/null)
        if grep -q "not allowed\|Sorry" <<<"$info" || [ -z "$info" ]; then
            sudo=no
        elif grep -q "(ALL.*ALL)" <<<"$info"; then
            sudo=all
        else
            sudo=specified
        fi
        # no output: $shell
        printf '%-20s\t' "$(gettext User)" "$(gettext UID)" "$(gettext GID)" "$(gettext Home)" "$(gettext SuDo)" "$(gettext Login)" "$(gettext From)" "$(gettext Duration)"
        printf '\n'
        printf '%-20s\t' "$user" "$uid" "$gid" "$home" "$sudo" "$login" "$from" "$time"
        printf '\n'
    done
}

# Get sudo information
#
# This lists all allowed sudo commands for the user.
#
# Usage:    sudo_info [<user>]
# Output:   <tsv with header>
#           username as UID as GID  command
#           alex     ALL            /usr/bin/openfortivpn
#           alex     ALL    ALL     ALL
sudo_info() {
    echo -e "username\tas UID\tas GID\tcommand"

    getent passwd $1 | awk -F: '$3 >= 1000 && $3 < 60000 {print $1}' |
        while IFS= read -r user; do
            LANG=C sudo -lU "$user" 2>/dev/null | sed '1,/User .* may run the following commands/d' |
                while read -r line; do
                    sed 's/(\([A-Z0-9]*\) *:\? *\([A-Z0-9]*\)\?) * \(NOPASSWD:\)\? */'"$user"'\t\1\t\2\t/' <<<"$line"
                done
        done
}

######################################################################################
### LVM
######################################################################################

# Check if LVM is used
#
# Usage:    uses_lvm
# Return:   0 for uses LVM
#           1 if not
uses_lvm() {
    is integer --name=arguments --max=0 --die -- $#
    sudo bash -lc 'command -v vgs' >/dev/null &&      # installed
        sudo vgs --noheadings >/dev/null &&           # vgs returns ok
        [ -n "$(sudo vgs --noheadings)" ] &>/dev/null # vgs returns at least one group
}
