#!/usr/bin/env bash
# shellcheck source=module/color
source /dev/null

# Module with output and user interaction helpers.

######################################################################################
# Context
######################################################################################

# Show help page and exit
# Usage:    help <heading> <usage> <options-spec> <details>
help() {
    heading "Hilfe: $1"
    info "Usage: $2"
    echo ""
    if [ -n "$3" ]; then
        option_help "$3"
        echo ""
    fi
    echo "$4"
    exit 0
}

# Print block heading
# Usage:    heading <title>
#           <title> | heading
# Stdout:   colored <string>
# Variable: $server
heading() {
    local prefix=""
    test -z "${server-}" || prefix="${server-} "
    printf "\n%s\n\n" "${CC_INVERS}$prefix${CC_RESET}${CC_HEADING}$(input "$@")...${CC_RESET}"
}

# Print critical/disaster message
# Usage:    critical <message>
#           <message> | critical
# Stdout:   colored <string>
critical() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_CRITICAL}$text${CC_RESET}"
}

# Print error message
# Usage:    error <message>
#           <message> | error
# Stdout:   colored <string>
error() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_ERROR}$text${CC_RESET}"
}

# Print warning message
# Usage:    warn <message>
#           <message> | warn
# Stdout:   colored <string>
warn() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_WARN}$text${CC_RESET}"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Stdout:   colored <string>
notice() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_NOTICE}$text${CC_RESET}"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Stdout:   colored <string>
info() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "$text"
}

# Print success message
# Usage:    ok <message>
#           <message> | ok
# Stdout:   colored <string>
ok() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_OK}$text${CC_RESET}"
}

# Print special marked message like table header
# Usage:    invers <message>
#           <message> | invers
# Stdout:   colored <string>
invers() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_INVERS}$text${CC_RESET}"
}

# Print message in defined color
# Usage:    color <color> <message>
#           <message> | color <color>
# Stdout:   colored <string>
color() {
    local text
    text="$(input_args 1 "$@")"
    test -z "$text" || echo -e "${CC_ERROR}$text${CC_RESET}"
}

######################################################################################
# Format Helpers
######################################################################################

# Remove color codes from text
# Usage:    uncolorize <text>
#           <text> | uncolorize
# Stdout:   <text>
# shellcheck disable=SC2120
uncolorize() {
    input "$@" | sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}

# Convert HTML to markdown (simplified version)
# Usage:    html2md <html-part>
#           <html-part> | html2md
# Stdout:   <md>
html2md() {
    input "$@" |
        sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li>#\n- #g;s#<[^>]*>##g' |
        grep -v '^$'
}

# Remove carriage return from line endings
# Usage:    nocr <text>
#           <text> | nocr
# Stdout:   <text>
nocr() {
    input "$@" | sed 's/\r$//' # removes all: tr -d '\r'
}

# Encode message to be used within the url
# Usage:    urlencode <string>
#           <string> | urlencode
# Stdout:   <string>
urlencode() {
    install jq
    input "$@" | jq -sRr @uri | sed 's/%0A$//'
}

# Convert TSV data into visual table
# Usage:    tsv2table <tsv>
#           <tsv> | tsv2table
# Stdout:   <table>
tsv2table() {
    install mlr
    input "$@" | mlr --csvlite --ifs '\t' -o pprint cat
}

# Convert TSV data into markdown table
# Usage:    tsv2md <tsv>
#           <tsv> | tsv2md
# Stdout:   <md>
tsv2md() {
    install mlr
    input "$@" | uncolorize | mlr --csvlite --ifs '\t' --omd cat
}

######################################################################################
# Visual effects
######################################################################################

# Remove current line
# When printed to a terminal, it will erase everything from the current cursor position backward to the beginning of the line.
# Usage:    erase_line
erase_line() {
    printf '%b' $'\e[1K\r'
}

# Show a horizontal line
# Format can be:
# - light (default) ──────────
# - bold ━━━━━━━━━━
# - double ══════════
# - half ▄▄▄▄▄▄▄▄▄▄
# - full ██████████
# Usage:    horizontal_line [<format>]
# Output:   ────────── # over full width of terminal
horizontal_line() {
    local char
    case $1 in
    light) char="─" ;;
    bold) char="━" ;;
    double) char="═" ;;
    half) char="▄" ;;
    full) char="█" ;;
    *) char="─" ;;
    esac
    local cols
    read _ cols < <(stty size)
    printf "%.0s$char" $(seq 1 "$cols")
}

_spinner_pid=""

# Function to start the spinner in the background
# To stop it later call @spinner_stop.
# Some formats have multiple character width:
# - `simple`:   - \ | /
# - `arrows`:   → ↑ ← ↓
# - `vertical`: ▏ ▎ ▍ ▌ ▋ ▊ ▉ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏
# - `bar`:      (as `vertical` but two characters wide)
# - `fade`:     ░ ▒ ▓ █ ▓ ▒ ░
# - `braile`:   ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ (default)
# - `roll`:     ⠋ ⠙ ⠚ ⠞ ⠖ ⠦ ⠴ ⠲ ⠳ ⠓
# - `moon`:     🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘
# - `clock`:    🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛
# - `weather`:  🌤 🌥 🌦 🌧 🌨 🌩 🌪
# Usage:    spinner_start <format> <time>
#           # <format> see above
#           # <time> 0.1 or more seconds (default 0.2)
# TTY:      <symbol> with back-space so that cursor is always before it
# Returns:   0 without doing anything if no `tput` and terminal available
spinner_start() {
    if ! command -v tput >/dev/null 2>&1 || [ ! -t 2 ]; then
        debug "Disabled because tput and terminal is needed"
        return 0
    fi
    local format="${1:-braile}"
    local spinner
    local size=1
    local chars=1
    local delay=${2:-0.2}
    case $format in
    arrows) spinner='→↑←↓' ;;
    vertical) spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏' ;;
    bar) spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ ' && chars=2 && size=2 ;;
    fade) spinner=' ░▒▓█▓▒░' ;;
    braile) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
    roll) spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓' ;;
    moon) spinner='🌑🌒🌓🌔🌕🌖🌗🌘' && size=2 ;;
    clock) spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛' && size=2 ;;
    weather) spinner='🌤🌥🌦🌧🌨🌩🌪' ;;
    *) spinner='-\|/' ;;
    esac
    local back=$((size + 1))
    # Spinner function running in background loop
    printf '\e[?25l' # make cursor invisible
    (
        while true; do
            for ((i = 0; i < ${#spinner}; i += chars)); do
                printf " %s%s" "${spinner:i:$chars}" "$(printf '\b%.0s' $(seq 1 "$back"))" >/dev/tty
                sleep "$delay"
            done
        done
    ) &
    _spinner_pid=$!
    disown
}

# Function to stop the spinner
# Call this after @spinner_start to stop it. It has to be called within the same thread!
# Usage:    spinner_stop
spinner_stop() {
    [ -n "$_spinner_pid" ] || return # spinner not started
    kill "$_spinner_pid" >/dev/null 2>&1
    wait "$_spinner_pid" 2>/dev/null
    _spinner_pid=""
    printf "    \b\b\b\b" # Clear spinner character
    printf '\e[?25h'      # make cursor visible again
}
