#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# Module with output and user interaction helpers.

######################################################################################
# Context
######################################################################################

# Show help page and exit
# Usage:    help <heading> <usage> <options-spec> <details>
help() {
    heading "Hilfe: $1"
    info "Usage: $2"
    echo ""
    if [ -n "$3" ]; then
        option_help "$3"
        echo ""
    fi
    echo "$4"
    exit 0
}

######################################################################################
# Logging
######################################################################################

declare -ag _log_level=(debug info notice warn error critical)
declare -Ag _log_rotate_time
_log_rotate_time[hourly]="%Y-%m-%dT%H"
_log_rotate_time[daily]="%Y-%m-%d"
_log_rotate_time[weekly]="%Y_week_%W"
_log_rotate_time[monthly]="%Y-%m"
declare -Ag _log_active
# _log_active[path]="<path> <level> <rotate> [<compress> [<cleanup>]]"

# Additional logging (at the moment only into files).
# After initialising a log using `start` the default output options will additionally write into log. But you can also specifically write t it using the log function.
# Multiple log with different levels are possible.
# Usage:    log start <file>        # no spaces in file path allowed
#           log <level> <message>
#           log end <file>
# Options:  -l, --level=<level>                 # level := debug info notice warn error critical
#           # File logging:
#           -r, --rotate=hourly|daily|weekly|monthly|<bytes>
#           -c, --cleanup=<num>|<duration>
#           -z, --compress
# Files:    <file>[_<pattern>]                  # will contain the logs
# Example:  # Format: <date> <time> <level> <message>
#           2025-12-02 14:07:35 INFO Hello
#           2025-12-02 14:10:04 ERROR Thius is only a test
log() {
    # parameter parsing
    local level=1 rotate compress=0 cleanup text size
    eval set -- "$(option_parse $'l level +\nr rotate +\nz compress -\nc cleanup +' "$@")"
    while true; do
        case "$1" in
        -l | --level)
            level="$(array _log_level indexof "$2")" || die "Log level $2 is undefined, use one of: ${_log_level[*]}"
            shift 2
            ;;
        -r | --rotate)
            if (($2 > 0)); then
                rotate="$2"
            else
                rotate="$(hash _log_rotate_time get "$2")" || die "Rotate option $2 is not recognized use: horly daily weekly monthly"
            fi
            shift 2
            ;;
        -z | --compress)
            compress=1
            shift
            ;;
        -c | --cleanup)
            cleanup="$(duration_format seconds "$2")"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    [ -n "$rotate" ] || cleanup=""  # no cleanup if no rotate
    [ -n "$rotate" ] || compress="" # no compress if no rotate
    # processing
    case $1 in
    start)
        num_parameters --min=2 --max=2 --die="To start a new log a file path is needed as argument" "$@"
        [ -w "$2" ] || [ -w "$(dirname "$2")" ] || die "Could not write/create log under $2"
        hash _log_active set "$2" "$2 $level $rotate $compress $cleanup"
        ;;
    stop)
        num_parameters --min=2 --max=2 --die="To end a log it'S file path is needed as argument" "$@"
        hash _log_active unset "$2"
        ;;
    debug | info | notice | warn | error | critical)
        level="$(array _log_level indexof "$1")"
        text="$(input_args 1 "$@")"
        [ -n "$text" ] || return 0 # no message
        # loop over _log_active values
        local file minlevel
        for e in "${_log_active[@]}"; do
            read -r file minlevel rotate cleanup <<<"$e"
            ((level >= minlevel)) || continue
            path="$file"
            if [ -n "$rotate" ] && ((rotate == 0)); then
                path+="_$(date_format "$rotate")"
            fi
            # log entry
            echo "$(date_format sql) ${1^^} $(uncolorize "$text")" >>"$path"
        done
        ;;
    *) die "Unrecognized command $1: start, stop or any log level allowed" ;;
    esac
}

_log_manager() {
    local parent=$PPID file minlevel rotate compress cleanup size
    while true; do
        for e in "${_log_active[@]}"; do
            read -r file minlevel rotate compress cleanup <<<"$e"
            # cleanup
            if [ -n "$cleanup" ]; then
                find "$(dirname "$file")" -type f -name "$(basename "$file")*" ! -newermt "$(date -d "$cleanup seconds ago")" -delete 2>/dev/null
            fi
            # rotate on size
            if ((rotate > 0)); then
                size="$(stat -c %s "$file")"
                if ((size > rotate)); then
                    mr -f "${file}.99"
                    # Shift existing numbered files up
                    for ((i = 99; i > 1; i--)); do
                        local old="${file}.${i}"
                        local new="${file}.$((i - 1))"
                        [ ! -f "$old" ] || mv "$old" "$new"
                    done
                    # Rotate the main file to .1
                    ! [ -f "$file" ] || mv "$file" "${file}.1"
                fi
            fi
            # compress
            if ((compress == 1)); then
                find "$(dirname "$file")" -type f -name "$(basename "$file")*" -mmin 3600 -exec gzip --best {} \; 2>/dev/null
            fi
        done
        # run manager every 5 minutes
        for ((i = 0; i < 300; i++)); do
            sleep 1
            kill -0 "$parent" 2>/dev/null || exit 0 # end if parent ended
        done
    done
}
_log_manager &
disown

######################################################################################
# Messages
######################################################################################

# Print block heading
# Usage:    heading <title>
#           <title> | heading
# Stdout:   colored <string>
# Variable: $server
heading() {
    local prefix=""
    test -z "${server-}" || prefix="${server-} "
    printf "\n%s\n\n" "${CC_INVERS}$prefix${CC_RESET}${CC_HEADING}$(input "$@")...${CC_RESET}"
}

# Print critical/disaster message
# Usage:    critical <message>
#           <message> | critical
# Stdout:   colored <string>
critical() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_CRITICAL}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log critical "$text"
}

# Print error message
# Usage:    error <message>
#           <message> | error
# Stdout:   colored <string>
error() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_ERROR}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log error "$text"
}

# Print warning message
# Usage:    warn <message>
#           <message> | warn
# Stdout:   colored <string>
warn() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_WARN}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log warn "$text"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Stdout:   colored <string>
notice() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "${CC_NOTICE}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log notice "$text"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Stdout:   colored <string>
info() {
    local text
    text="$(input "$@")"
    test -z "$text" || printf "%s\n" "$text"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

# Print success message
# Usage:    ok <message>
#           <message> | ok
# Stdout:   colored <string>
ok() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_OK}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log notice "$text"
}

# Print special marked message like table header
# Usage:    invers <message>
#           <message> | invers
# Stdout:   colored <string>
invers() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_INVERS}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

# Print message in defined color
# Usage:    color <color> <message>
#           <message> | color <color>
# Stdout:   colored <string>
color() {
    local text
    text="$(input_args 1 "$@")"
    test -z "$text" || echo -e "${CC_ERROR}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

######################################################################################
# Format Helpers
######################################################################################

# Remove color codes from text
# Usage:    uncolorize <text>
#           <text> | uncolorize
# Stdout:   <text>
# shellcheck disable=SC2120
uncolorize() {
    input "$@" | sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}

# Convert HTML to markdown (simplified version)
# Usage:    html2md <html-part>
#           <html-part> | html2md
# Stdout:   <md>
html2md() {
    input "$@" |
        sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li>#\n- #g;s#<[^>]*>##g' |
        grep -v '^$'
}

# Remove carriage return from line endings
# Usage:    nocr <text>
#           <text> | nocr
# Stdout:   <text>
nocr() {
    input "$@" | sed 's/\r$//' # removes all: tr -d '\r'
}

# Encode message to be used within the url
# Usage:    urlencode <string>
#           <string> | urlencode
# Stdout:   <string>
urlencode() {
    install jq
    input "$@" | jq -sRr @uri | sed 's/%0A$//'
}

######################################################################################
# Visual effects
######################################################################################

# Remove current line
# When printed to a terminal, it will erase everything from the current cursor position backward to the beginning of the line.
# Usage:    erase_line
erase_line() {
    printf '%b' $'\e[1K\r'
}

# Show a horizontal line
# It will go over the full width of terminal, but be at least 60 characters wide.
# Format can be:
# - light (default) ──────────
# - bold ━━━━━━━━━━
# - double ══════════
# - half ▄▄▄▄▄▄▄▄▄▄
# - full ██████████
# Usage:    horizontal_line [<format>]
# Output:   ────────── # over full width of terminal
horizontal_line() {
    local char
    case $1 in
    light) char="─" ;;
    bold) char="━" ;;
    double) char="═" ;;
    half) char="▄" ;;
    full) char="█" ;;
    *) char="─" ;;
    esac
    local cols
    read -r _ cols < <(stty size)
    ((cols > 60)) || cols=60
    printf "%.0s$char" $(seq 1 "$cols")
}

_spinner_pid=""

# Function to start the spinner in the background
# To stop it later call @spinner_stop.
# Some formats have multiple character width:
# - `simple`:   - \ | /
# - `arrows`:   → ↑ ← ↓
# - `vertical`: ▏ ▎ ▍ ▌ ▋ ▊ ▉ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏
# - `bar`:      (as `vertical` but two characters wide)
# - `fade`:     ░ ▒ ▓ █ ▓ ▒ ░
# - `braile`:   ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ (default)
# - `roll`:     ⠋ ⠙ ⠚ ⠞ ⠖ ⠦ ⠴ ⠲ ⠳ ⠓
# - `moon`:     🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘
# - `clock`:    🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛
# - `weather`:  🌤 🌥 🌦 🌧 🌨 🌩 🌪
# Usage:    spinner_start <format> <time>
#           # <format> see above
#           # <time> 0.1 or more seconds (default 0.2)
# TTY:      <symbol> with back-space so that cursor is always before it
# Returns:   0 without doing anything if no `tput` and terminal available
spinner_start() {
    if ! command -v tput >/dev/null 2>&1 || [ ! -t 2 ]; then
        debug "Disabled because tput and terminal is needed"
        return 0
    fi
    local format="${1:-braile}"
    local spinner
    local size=1
    local chars=1
    local delay=${2:-0.2}
    case $format in
    arrows) spinner='→↑←↓' ;;
    vertical) spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏' ;;
    bar) spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ ' && chars=2 && size=2 ;;
    fade) spinner=' ░▒▓█▓▒░' ;;
    braile) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
    roll) spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓' ;;
    moon) spinner='🌑🌒🌓🌔🌕🌖🌗🌘' && size=2 ;;
    clock) spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛' && size=2 ;;
    weather) spinner='🌤🌥🌦🌧🌨🌩🌪' ;;
    *) spinner='-\|/' ;;
    esac
    local back=$((size + 1))
    # Spinner function running in background loop
    printf '\e[?25l' # make cursor invisible
    (
        while true; do
            for ((i = 0; i < ${#spinner}; i += chars)); do
                printf " %s%s" "${spinner:i:$chars}" "$(printf '\b%.0s' $(seq 1 "$back"))" >/dev/tty
                sleep "$delay"
            done
        done
    ) &
    _spinner_pid=$!
    disown
}

# Function to stop the spinner
# Call this after @spinner_start to stop it. It has to be called within the same thread!
# Usage:    spinner_stop
spinner_stop() {
    [ -n "$_spinner_pid" ] || return # spinner not started
    kill "$_spinner_pid" >/dev/null 2>&1
    wait "$_spinner_pid" 2>/dev/null
    _spinner_pid=""
    printf "    \b\b\b\b" # Clear spinner character
    printf '\e[?25h'      # make cursor visible again
}
