#!/usr/bin/env bash
# shellcheck source=module/color
source /dev/null

# Module with output and user interaction helpers.

######################################################################################
# Context
######################################################################################

# Show help page and exit
# Usage:    help <heading> <usage> <options-spec> <details>
help() {
    heading "Hilfe: $1"
    info "Usage: $2"
    echo ""
    if [ -n "$3" ]; then
        option_help "$3"
        echo ""
    fi
    echo "$4"
    exit 0
}

# Print block heading
# Usage:    heading <title>
#           <title> | heading
# Stdout:   colored <string>
# Variable: $server
heading() {
    local prefix=""
    test -z "${server-}" || prefix="${server-} "
    echo -e "\n${CC_INVERS}$prefix${CC_RESET}${CC_HEADING}$(input "$@")...${CC_RESET}\n"
}

# Print critical/disaster message
# Usage:    critical <message>
#           <message> | critical
# Stdout:   colored <string>
critical() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_CRITICAL}$text${CC_RESET}"
}

# Print error message
# Usage:    error <message>
#           <message> | error
# Stdout:   colored <string>
error() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_ERROR}$text${CC_RESET}"
}

# Print warning message
# Usage:    warn <message>
#           <message> | warn
# Stdout:   colored <string>
warn() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_WARN}$text${CC_RESET}"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Stdout:   colored <string>
info() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_INFO}$text${CC_RESET}"
}

# Print success message
# Usage:    ok <message>
#           <message> | ok
# Stdout:   colored <string>
ok() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_OK}$text${CC_RESET}"
}

# Print special marked message like table header
# Usage:    invers <message>
#           <message> | invers
# Stdout:   colored <string>
invers() {
    local text
    text="$(input "$@")"
    test -z "$text" || echo -e "${CC_INVERS}$text${CC_RESET}"
}

# Print message in defined color
# Usage:    color <color> <message>
#           <message> | color <color>
# Stdout:   colored <string>
color() {
    local text
    text="$(input_args 1 "$@")"
    test -z "$text" || echo -e "${CC_ERROR}$text${CC_RESET}"
}

######################################################################################
# Format Helpers
######################################################################################

# Remove color codes from text
# Usage:    uncolorize <text>
#           <text> | uncolorize
# Stdout:   <text>
# shellcheck disable=SC2120
uncolorize() {
    input "$@" | sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}

# Convert HTML to markdown (simplified version)
# Usage:    html2md <html-part>
#           <html-part> | html2md
# Stdout:   <md>
html2md() {
    input "$@" |
        sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li>#\n- #g;s#<[^>]*>##g' |
        grep -v '^$'
}

# Remove carriage return from line endings
# Usage:    nocr <text>
#           <text> | nocr
# Stdout:   <text>
nocr() {
    input "$@" | sed 's/\r$//' # removes all: tr -d '\r'
}

# Encode message to be used within the url
# Usage:    urlencode <string>
#           <string> | urlencode
# Stdout:   <string>
urlencode() {
    install jq
    input "$@" | jq -sRr @uri | sed 's/%0A$//'
}

# Convert TSV data into visual table
# Usage:    tsv2table <tsv>
#           <tsv> | tsv2table
# Stdout:   <table>
tsv2table() {
    install mlr
    input "$@" | mlr -i tsv -o pprint cat
}

# Convert TSV data into markdown table
# Usage:    tsv2md <tsv>
#           <tsv> | tsv2md
# Stdout:   <md>
tsv2md() {
    install mlr
    input "$@" | uncolorize | mlr -i tsv -o md cat
}

######################################################################################
# Visual effects
######################################################################################

_spinner_pid=""

# Function to start the spinner in the background stop it with @spinner_stop
# Usage:    spinner_start <format> <time>
#           # <format> arrows, vertical, bar, fade, braile, roll, moon, clock, weather (default spinner)
#           # <time> 0.1 or more seconds (default 0.2)
# Output:   | / - \
spinner_start() {
    local format="${1:-simple}"
    local spinner
    local size=1
    local chars=1
    local delay=${2:-0.2}
    case $format in
    arrows) spinner='→↑←↓' ;;
    vertical) spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏' ;;
    bar) spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ ' && chars=2 && size=2 ;;
    fade) spinner=' ░▒▓█▓▒░' ;;
    braile) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
    roll) spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓' ;;
    moon) spinner='🌑🌒🌓🌔🌕🌖🌗🌘' && size=2 ;;
    clock) spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛' && size=2 ;;
    weather) spinner='🌤🌥🌦🌧🌨🌩🌪' ;;
    *) spinner='-\|/' ;;
    esac
    local back=$((size + 1))
    # Spinner function running in background loop
    tput civis
    (
        while true; do
            for ((i = 0; i < ${#spinner}; i += chars)); do
                printf " %s%s" "${spinner:i:$chars}" "$(printf '\b%.0s' $(seq 1 $back))"
                sleep "$delay"
            done
        done
    ) &
    _spinner_pid=$!
    disown
}

# Function to stop the spinner started using @spinner_start
# Usage:    spinner_stop
spinner_stop() {
    if [[ -n $_spinner_pid ]]; then
        kill "$_spinner_pid" >/dev/null 2>&1
        wait "$_spinner_pid" 2>/dev/null
        _spinner_pid=""
        printf "    \b\b\b\b" # Clear spinner character
        tput cnorm
    fi
}
