#!/usr/bin/env bash

# Module for process control

######################################################################################
# Sudo
######################################################################################

# Check if sudo is needed for command
# This will @die if
# Usage:    sudo_allow <command-line>
# Return:   0 if allowed
#           @die if not allowed
sudo_allow() {
    is integer --name=arguments --max=1 --die -- $#
    # processing
    ((EUID != 0)) || return 0
    command -v sudo >/dev/null || return 0
    command sudo -ln "$@" >/dev/null || die "User $(whoami) is not allowed to call 'sudo $*', but this is necessary!"
}

# Sudo overwrite to only use sudo if needed
# Usage:    sudo <command-line>
sudo() {
    if ((EUID != 0)) && command -v sudo >/dev/null; then
        command sudo "$@"
    else
        "$@"
    fi
}

######################################################################################
# Looping
######################################################################################

# Execute command in N times
# Usage:    repeat <N> <command> [<params>]...
repeat() {
    is integer --name=num --min=0 --die -- "$1"
    is set --name=command --die -- "$2"
    local -i n=$1
    # processing
    ((n > 0)) || return
    shift
    for n in $(seq "$n"); do
        debug 3 "call #$n: $*"
        "$@"
    done
}

# Retry a command multiple times until it succeeds
# Using escalating delay between attempts. Delay is 2 * n + random up to 30s, then 30s + random after that.
# For large numbers of retries the max delay is effectively the retry count in minutes.
# Usage:    retry <N> <command> [<params>]...
function retry {
    is integer --name=num --min=0 --die -- "$1"
    is set --name=command --die -- "$2"
    local retries=$1
    # processing
    shift
    local count=0 exit wait
    until "$@"; do
        exit=$?
        wait=$((2 ** count))
        count=$((count + 1))
        if ((count < retries)); then
            debug 3 "Try $count/$retries exited $exit, retrying in $wait seconds..."
            sleep "$wait"
        else
            debug 3 "Try $count/$retries exited $exit, no more retries left."
            return "$exit"
        fi
    done
    return 0
}

countdown() { _deprecated "use pause <text> --timeout=<duration> --abort"; }

######################################################################################
# Locking
######################################################################################

LOCK_SLEEP=10

_lock_remove() {
    # Remove old locks for non existing processes or the defined pid lock
    # Usage: _lock_remove
    pid=$(cat "$lockfile") || true
    ([ -n "$pid" ] && kill -0 "$pid" 2>/dev/null) ||
        rm -f "$lockfile" "$lockfile.$pid" || die "$(gettext "Failed to remove lockfile"): $lockfile"
}

# Set a lock or wait till it can be set
# In any part of your script you can surround a block with @lock and @unlock statements. The
# process will wait on the lock statement till no other process with the same lock is running
# before going on.
# Usage:    lock
# Files:    /tmp/<prog>_lockfile        # hard link to active process
#           /tmp/<prog>_lockfile.<pid>  # active or waiting process
# Output:   <wait message>
lock() {
    is integer --name=arguments --max=0 --die -- $#
    local lockfile logged pid
    lockfile="$(mktemp 'lockfile')"
    # make a file with our PID
    echo $$ >"$lockfile.$$" 2>/dev/null || die "$(gettext "Failed to create PID lockfile"): $lockfile.$$"
    # remove old lock if no longer running
    _lock_remove
    # try it, till it works
    logged=0
    while ! ln "$lockfile.$$" "$lockfile" 2>/dev/null; do
        if ((logged == 0)); then # write message once
            pid="$(cat "$lockfile")"
            echo "$(eval_gettext "Waiting for unlock in \$lockfile by PID \$pid")..." >&1
            logged=1
        fi
        # if the symlink failed, wait for the current lock holder to exit
        sleep "$LOCK_SLEEP"
        # make a file with our PID, if no longer existent
        echo $$ >"$lockfile.$$" 2>/dev/null
        # check again for zombies
        _lock_remove
    done
    # if the locking process exits without unlocking, delete our lock
    trap_add unlock EXIT
}

# Set the lock or exit with optional error message
# While another program is running with this lock active it will @die.
# Usage:    lock_exit
# Files:    /tmp/<prog>-lockfile        # hard link to active process
#           /tmp/<prog>-lockfile.<pid>  # active or waiting process
lock_exit() {
    is integer --name=arguments --max=0 --die -- $#
    local lockfile logged pid
    lockfile="$(mktemp 'lockfile')"
    # make a file with our PID
    echo $$ >"$lockfile.$$" 2>/dev/null || die "$(gettext "Failed to create PID lockfile"): $lockfile.$$"
    # move old lock if no longer running
    _lock_remove
    # try to symlink it
    if ! ln "$lockfile.$$" "$lockfile" 2>/dev/null; then
        unlock
        pid="$(cat "$lockfile")"
        die "$(eval_gettext "Stop processing because this is locked in \$lockfile by PID $pid")"
    fi
    # if the locking process exits without unlocking, delete our lock
    trap_add unlock EXIT
}

# Remove the lock
# Usage:    unlock
# shellcheck disable=SC2120
unlock() {
    is integer --name=arguments --max=0 --die -- $#
    local lockfile
    lockfile="$(mktemp 'lockfile')"
    # remove own lockfile
    [ ! -e "$lockfile.$$" ] || rm -f "$lockfile.$$" 2>/dev/null
    # remove link if no pid or pointing to myself
    pid=$(cat "$lockfile") || true
    [ -z "$pid" ] || [[ "$pid" != "$$" ]] || rm -r "$lockfile" 2>/dev/null
    # remove the trap
    trap_remove unlock EXIT
    return 0
}

######################################################################################
# Persistent variables store
######################################################################################

# Store variables into shared memory/file
# The <ident> specifies also who will use the same file.
# To get the same file in all your invocations of this script only use a fixed string here.
# To have a different file for each script invocation include `$$` or '${$}'.
# Or to have another file in each sub process include $BASHPID.
#
# You may do the following:
#
# - `store` all or some variables
# - `restore` all or some variables
# - `clean` remove the store
# - `change` run a command which will change the variables in the store
# Usage:    variables store [<ident>] [<variable>]...   # store complete or only listed variables (ident can be empty string)
#           variables restore [<ident>] [<variable>]... # restore all or defined variables
#           variables clean [<ident>]                   # remove the store
#           variables update <ident> <cmd-line> [<variable>]..   # update some variables by the cmd-line
# Options:  d, disk                             # store on disk in temporary folder
#           p, path <base-dir>                  # store on disk in given folder
#           c, clean                            # remove after restore is done
# Files:    `/dev/shm/<prog>[-<ident>].env`     # stored environment
# Files:    `/tmp/<prog>[-<ident>].env`         # if `--disk` was used
# Example:  ```bash
#           variables restore
#           ...<code>
#           variables store # save changes
#           ....
#           variables store # save changes
#           ....
#           variables clean # everything done remove progress
#           ```
variables() {
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +\nc clean -' "$@")"
    local self opt="-m" command clean
    while true; do
        case "$1" in
        -d | --disk) self+=" -d" && opt="" && shift ;;
        -p | --path) self+=" -p \"$2\"" && opt="$1 $2" && shift 2 ;;
        -c | --clean) self+=" -c" && clean=1 && shift ;;
        --) shift && break ;;
        *) shift ;; # ignore
        esac
    done
    command="$(check enum --name=command --allow="store restore clean change" --die -- "$1")"
    shift
    local ident=$1
    shift || true
    # processing
    local file
    # shellcheck disable=SC2086
    file="$(mktemp $opt --extension=env "$ident")"
    case "$command" in
    store) declare -p "$@" | sed 's/^declare\b/declare -g/' >"$file" ;;
    restore)
        [ -s "$file" ] || return 0
        if [[ $# -gt 0 ]]; then
            temp="$(mktemp -me env-sub "${ident}_${BASHPID}")"
            grep -E "$(tr ' ' '|' <<<"$*")" "$file" >"$temp" || true
            # shellcheck disable=SC1090
            source "$temp" || true
            rm -r "$temp" || true
        else
            # shellcheck disable=SC1090
            source "$file" 2>/dev/null || true
        fi
        [ -z "$clean" ] || rm -f "$file" # also directly clean it
        ;;
    clean) rm -f "$file" ;;
    change)
        is set --name=cmd-line --die -- "$1"
        # processing
        local command=$1
        shift || true
        # shellcheck disable=SC2086
        variables restore $self "$ident"
        eval "$command"
        # shellcheck disable=SC2086
        variables store $self "$ident" "$@"
        ;;
    esac
}

# Deprecated: Store environment into shared memory/file
# Use: variables store...
# Use `$$` or '${$}' as the program PID which will be also the same in Subshell or `${BASHPID}` which will differ.
# Usage:    store [<ident>]                 # store complete environment
#           store [<ident>] [<variable>]... # store only listed variables (ident can be empty string)
# Options:  d, disk                          # store on disk in temporary folder
#           p, path <base-dir>               # store on disk in given folder
# Files:    `/dev/shm/<prog>[-<ident>].env`     # stored environment
# Example:  ```bash
#           env_restore
#           ...<code>
#           store # save changes
#           ....
#           store # save changes
#           ....
#           env_clean # everything done remove progress
#           ```
env_store() {
    _deprecated "Use: variables store..." warn
    debug "env_store $*"
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt="-m"
    while true; do
        case "$1" in
        -d | --disk)
            opt=""
            shift
            ;;
        -p | --path)
            opt="$1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    local ident=$1
    shift || true
    # shellcheck disable=SC2086
    declare -p "$@" | sed 's/^declare\b/declare -g/' >"$(mktemp $opt --extension=env "$ident")"
}

# Deprecated: Restore environment from shared memory/file
# Use: variables restore...
# If some variable names are given only those will be restored.
# Usage:    env_restore [<ident>] [<variable>]...
# Options:  d, disk                          # store on disk in temporary folder
#           p, path <base-dir>               # store on disk in given folder
# Files:    `/dev/shm/<prog>[-<ident>].env`     # stored environment
#           `/dev/shm/<prog>[_<ident>]_<sub-pid>.env-sub` # very short temporary file to filter input
env_restore() {
    _deprecated "Use: variables restore..." warn
    debug "env_restore $*"
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt="-m"
    while true; do
        case "$1" in
        -d | --disk)
            opt=""
            shift
            ;;
        -p | --path)
            opt="$1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    local ident="${1-}" shm_env
    shift || true
    # shellcheck disable=SC2086
    shm_env="$(mktemp $opt -e env "$ident")"
    [ -s "$shm_env" ] || return 0
    if [[ "$#" -gt 0 ]]; then
        temp="$(mktemp -me env-sub "${ident}_${BASHPID}")"
        grep -E "$(tr ' ' '|' <<<"$*")" "$shm_env" >"$temp" || true
        # shellcheck disable=SC1090
        source "$temp" || true
        rm -r "$temp" || true
    else
        # shellcheck disable=SC1090
        source "$shm_env" 2>/dev/null || true
    fi
}

# Deprecated: Remove stored environment from shared memory/file
# Usage:    env_clean [<ident>]
# Options:  d, disk                          # store on disk in temporary folder
#           p, path <base-dir>               # store on disk in given folder
# Use: variables clean...
env_clean() {
    _deprecated "Use: variables clean..." warn
    is integer --name=arguments --max=1 --die -- $#
    debug "env_clean $*"
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt="-m"
    while true; do
        case "$1" in
        -d | --disk)
            opt=""
            shift
            ;;
        -p | --path)
            opt="$1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    # shellcheck disable=SC2086
    rm -f "$(mktemp $opt -e env "$1")"
}

# Deprecated: Change environment in shared memory/file
# Use: variables change...
# Usage:    env_change <ident> <command>                # store complete environment
#           env_change <ident> <command> [<variable>]...# store only listed variables (ident can be empty string)
env_change() {
    _deprecated "Use: variables change..." warn
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt
    while true; do
        case "$1" in
        -d | --disk)
            opt="$opt $1"
            shift
            ;;
        -p | --path)
            opt="$opt $1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    is set --name=ident --die -- "$1"
    is set --name=command --die -- "$2"
    # processing
    local ident=$1
    shift || true
    local command=$1
    shift || true
    # shellcheck disable=SC2086
    env_restore $opt "$ident"
    eval "$command"
    # shellcheck disable=SC2086
    env_store $opt "$ident" "$@"
}

######################################################################################
# Sync/Async calls with optional step control
######################################################################################

declare -A _async_running

# Set the variables which should be stored with step control
STEPS_VARIABLES=

# Initialize step control
# Usage:    steps_init
# Example:  steps_init
#           # sync | async | queue calls
#           steps_done
steps_init() {
    is integer --name=arguments --max=0 --die -- $#
    declare -g -A _STEPS
    variables restore steps
    declare -p _STEPS
    variables store steps _STEPS "$STEPS_VARIABLES" # initial store
    echo "$(gettext "Work steps are logged so that you can resume work mid-process")..." >&2
}

# Check if step already finished successful
# Usage:    steps_check <name>
# Exit:     0 if done else not done or with failure
steps_check() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=name --die -- "$1"
    local name="$1"
    # processing
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' || return 1 # return not found if no step control
    if [ -n "${_STEPS["$name"]}" ]; then
        # shellcheck disable=SC2005
        echo "$(eval_gettext "Job \$name already done in this run, skipping")" >&2
        return 0
    else
        return 1
    fi
}

# Set step as successfully done
# Usage:    steps_done <name>   # finished one step
#           steps_done          # completely finished -> cleanup
steps_done() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=name --die -- "$1"
    local name="$1"
    # processing
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' || return # do nothing if no step control
    if [ -n "$1" ]; then
        _STEPS["$name"]=1
        # shellcheck disable=SC2155
        local date="$(date_format sql)"
        # shellcheck disable=SC2005
        echo "$(eval_gettext "Finished: Step \$name at \$date")" >&2
        variables store steps _STEPS "$STEPS_VARIABLES"
    else
        variables clean steps
    fi
}

# Run the given command with optional step control
# This will use the command itself as name. If you run the same command multiple times use
# async_name directly.
# Usage:    sync <command> [<params>...]
sync() {
    is set --name=command --die -- "$1"
    # processing
    sync_name "$1" "$@"
}

# Alternative to sync in which this call is given a name to refer
# Usage:     sync <name> <cmd> [<params>...]
sync_name() {
    is set --name=name --die -- "$1"
    is set --name=command --die -- "$2"
    local name=$1
    shift
    # processing
    steps_check "$name" && return || true
    local date
    # shellcheck disable=SC2034
    date="$(date_format sql)"
    # shellcheck disable=SC2005
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' && echo "$(eval_gettext "Started: step \$name at \$date")" >&2 || true
    "$@"
    steps_done "$name"
}

# Run the given command asynchronous ang go on in the calling routine (short form of async_name)
# This will use the command itself as name. If you run the same command multiple times use
# async_name directly.
# Usage:    async <command> [<params>...]
# Example:  ```bash
#           async task1
#           async task2
#           async_wait task1
#           async task3
#           wait # for all to end
#           ```
async() {
    is set --name=command --die -- "$1"
    # processing
    async_name "$1" "$@"
}

# Alternative to async in which this call is given a name to refer in async_wait
# Usage:    async <name> <cmd> [<params>...]
async_name() {
    is set --name=name --die -- "$1"
    is set --name=command --die -- "$2"
    local name=$1
    shift
    # processing
    ! steps_check "$name" || return
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' && echo "Started: step $name at $(date_format sql)" >&2 || true
    "$@" &
    variables change queue "_async_running[\"$name\"]=$!" _queue _async_running
}

# Check if the command is done or wait here till it is so
# Usage:    async_wait          # to wait for all to be done
#           async_wait <name>   # to wait for specific command to finish
async_wait() {
    [ -z "${_async_running["$1"]}" ] && return 0 || true
    wait "${_async_running["$1"]}"
    local code=$?
    if ((code == 0)); then
        steps_done "$1"
        variables change queue "unset async_running[\"$1\"]" _queue _async_running
    else
        declare -p _STEPS 2>/dev/null | grep -q 'declare -A' && echo echo "Failed: Step $1 at $(date_format sql)" >&2 || true
    fi
    return "$code"
}

######################################################################################
# Job Queue
######################################################################################

_queue_jobs=()
declare -A _queue_running

# Run bash commands parallel with limits from a queue.
# The queue first collects all jobs and then you execute them all in parallel. Therefore you can give a max number of parallel calls and a max percentage load limit for then to start the next job.
# You may also set the limits using environment $QUEUE_MAX_NUM and $QUEUE_MAX_LOAD.
# If the server is over the configured load limit one job will always run, but parallel execution will only start if possible.
# Usage:    queue add <job> [<args>...]             # add job to queue
#           queue run [<parallel>] [<load-percent>] # run the queue with specified limits
queue() {
    is enum --name=command --allow="add run" --die -- "$1" && local command="$1" && shift
    # processing
    case $command in
    add)
        is set --name=job --die -- "$1"
        # add job
        _queue_job+=("$*")
        debug "add ${#_queue_job[@]}: $*"
        ;;
    run)
        is empty -- "$1" || is integer --name=parallel --min 1 --die
        is empty -- "$2" || is integer --name=load-percent --min 1 --die
        local max="${1:-$QUEUE_MAX_NUM}"
        local load="${2:-$QUEUE_MAX_LOAD}"
        debug "${#_queue_job[@]} Jobs to be run..."
        while true; do
            # check for finished jobs
            for pid in "${!_queue_running[@]}"; do
                if [[ ! -d /proc/$pid ]]; then
                    debug "finished ${_queue_running[$pid]}"
                    unset "_queue_running[$pid]"
                fi
            done
            # check if possible to run (nothing is running or below limit)
            if ((${#_queue_running[@]} == 0)) ||
                ( ((${#_queue_running[@]} < max)) &&
                    (($(cut -d' ' -f1 /proc/loadavg | sed 's/\.//;s/^0*//') / $(nproc) < load))); then
                # get next job
                if ((${#_queue_job[@]} > 0)); then
                    local job="${_queue_job[0]}"
                    _queue_job=("${_queue_job[@]:1}")
                    # run job
                    debug "start $job (${#_queue_job[@]} jobs remaining)"
                    eval "$job" &
                    _queue_running[$!]="$job"
                # end if no new jobs and nothing running
                elif ((${#_queue_running[@]} == 0)); then
                    break
                else
                    sleep 1
                fi
            else
                debug "Limit reached: Running ${#_queue_running[@]} (max), Load: $(($(cut -d' ' -f1 /proc/loadavg | sed 's/\.//;s/^0*//') / $(nproc)))% (max $load%)"
                sleep 1
            fi
        done
        ;;
    esac
}

######################################################################################
# Random string
######################################################################################

# Return a random string in specific length
# The default length is 16.
#
# The `<pattern>` is a list of allowed characters in range:
#
# - num - `0-9`
# - letters - 'a-z'
# - LETTERS - 'A-Z'
# - alpha - `a-zA-Z`
# - alphanum - `a-zA-Z0-9`
# - base64 - `a-zA-Z0-9+/`
# - printable - `a-zA-Z0-9!@#$%^&*()-_=+[](){}|;:,.<>?/` (in german including umlaut)
# - hex - `0-9a-f`
# - HEX - `0-9A-F`
# - directly give pattern
# Usage:    random <pattern> [<length>]
random() {
    is integer --name=arguments --max=2 --die -- $#
    is set --name=pattern --die -- "$1"
    is set -- "$2" && is integer --name=length --min=0 --die -- "$2"
    local pattern="$1"
    local length=${2:-16}
    # processing
    local result=""
    local umlaut UMLAUT
    if [[ "$LANG" =~ ^de ]]; then
        umlaut="äöüß€"
        UMLAUT="ÄÖÜ"
    fi
    case $pattern in
    num) pattern="0-9" ;;
    letters) pattern="a-z" ;;
    LETTERS) pattern="A-Z" ;;
    alpha) pattern="a-zA-Z" ;;
    alphanum) pattern="a-zA-Z0-9" ;;
    base64) pattern="a-zA-Z0-9+/" ;;
    printable) pattern="a-zA-Z0-9!@#$%^&*()-_=+[](){}|;:,.<>?/$umlaut$UMLAUT" ;;
    hex) pattern="0-9a-f" ;;
    HEX) pattern="0-9A-F" ;;
    esac
    while ((${#result} < length)); do
        result+="$(head /dev/urandom | tr -dc "$pattern")"
    done
    echo "${result:0:$length}"
}
