#!/usr/bin/env bash

# Module for process control

######################################################################################
# Sudo
######################################################################################

# Check if sudo is needed for command
# This will @die if
# Usage:    sudo_allow <command-line>
# Return:   0 if allowed
#           @die if not allowed
sudo_allow() {
    ((EUID != 0)) || return 0
    command -v sudo >/dev/null || return 0
    command sudo -ln "$@" >/dev/null || die "User $(whoami) is not allowed to call 'sudo $*', but this is neccessary!"
}

# Sudo overwrite to only use sudo if needed
# Usage:    sudo <command-line>
sudo() {
    if ((EUID != 0)) && command -v sudo >/dev/null; then
        command sudo "$@"
    else
        "$@"
    fi
}

######################################################################################
# Looping
######################################################################################

# Execute command in N times
# Usage:    repeat <N> <command> [<params>]...
repeat() {
    local -i n=$1
    ((n > 0)) || return
    shift
    for n in $(seq "$n"); do
        debug 3 "call #$n: $*"
        "$@"
    done
}

# Retry a command multiple times until it succeeds
# Using escalating delay between attempts. Delay is 2 * n + random up to 30s, then 30s + random after that.
# For large numbers of retries the max delay is effectively the retry count in minutes.
# Usage:    retry <N> <command> [<params>]...
function retry {
    local retries=$1
    shift
    local count=0 exit wait
    until "$@"; do
        exit=$?
        wait=$((2 ** count))
        count=$((count + 1))
        if ((count < retries)); then
            debug 3 "Try $count/$retries exited $exit, retrying in $wait seconds..."
            sleep "$wait"
        else
            debug 3 "Try $count/$retries exited $exit, no more retries left."
            return "$exit"
        fi
    done
    return 0
}

countdown() { _deprecate "use pause <text> --timeout=<duration> --abort"; }

######################################################################################
# Locking
######################################################################################

LOCK_SLEEP=10

_lock_remove() {
    # Remove old locks for non existing processes or the defined pid lock
    # Usage: _lock_remove
    pid=$(cat "$lockfile") || true
    ([ -n "$pid" ] && kill -0 "$pid" 2>/dev/null) ||
        rm -f "$lockfile" "$lockfile.$pid" || die "$(gettext "Failed to remove lockfile"): $lockfile"
}

# Set a lock or wait till it can be set
# Usage:    lock
# Files:    /tmp/<prog>_lockfile        # hard link to active process
#           /tmp/<prog>_lockfile.<pid>  # active or waiting process
# Stderr:   <wait message>
# In any part of your script you can surround a block with lock and unlock statements. The
# process will wait on the lock statement till no other process with the same lock is running
# before going on.
lock() {
    local lockfile logged pid
    lockfile="$(mktemp 'lockfile')"
    # make a file with our PID
    echo $$ >"$lockfile.$$" 2>/dev/null || die "$(gettext "Failed to create PID lockfile"): $lockfile.$$"
    # rmove old lock if no longer running
    _lock_remove
    # try it, till it works
    logged=0
    while ! ln "$lockfile.$$" "$lockfile" 2>/dev/null; do
        if ((logged == 0)); then # write message once
            pid="$(cat "$lockfile")"
            echo "$(eval_gettext "Waiting for unlock in \$lockfile by PID \$pid")..." >&1
            logged=1
        fi
        # if the symlink failed, wait for the current lock holder to exit
        sleep "$LOCK_SLEEP"
        # make a file with our PID, if no longer existent
        echo $$ >"$lockfile.$$" 2>/dev/null
        # check again for zombies
        _lock_remove
    done
    # if the locking process exits without unlocking, delete our lock
    trap_add unlock EXIT
}

# Set the lock or exit with optional error message
# Usage:    lock_exit
# Files:    /tmp/<prog>-lockfile        # hard link to active process
#           /tmp/<prog>-lockfile.<pid>  # active or waiting process
# In any part of your script you can surround a block with lock and unlock statements. The
# process will wait on the lock statement till no other process with the same lock is running
# before going on.
lock_exit() {
    local lockfile logged pid
    lockfile="$(mktemp 'lockfile')"
    # make a file with our PID
    echo $$ >"$lockfile.$$" 2>/dev/null || die "$(gettext "Failed to create PID lockfile"): $lockfile.$$"
    # rmove old lock if no longer running
    _lock_remove
    # try to symlink it
    if ! ln "$lockfile.$$" "$lockfile" 2>/dev/null; then
        unlock
        pid="$(cat "$lockfile")"
        die "$(eval_gettext "Stop processing because this is locked in \$lockfile by PID $pid")"
    fi
    # if the locking process exits without unlocking, delete our lock
    trap_add unlock EXIT
}

# Remove the lock
# Usage:    unlock
unlock() {
    local lockfile
    lockfile="$(mktemp 'lockfile')"
    # remove own lockfile
    [ ! -e "$lockfile.$$" ] || rm -f "$lockfile.$$" 2>/dev/null
    # remove link if no pid or pointing to myself
    pid=$(cat "$lockfile") || true
    [ -z "$pid" ] || [[ "$pid" != "$$" ]] || rm -r "$lockfile" 2>/dev/null
    # remove the trap
    trap_remove unlock EXIT
    return 0
}

######################################################################################
# Persistent environment store
######################################################################################

# Store environment into shared memory/file
# Use `$$` or '${$}' as the program PID which will be also the same in Subshells or `${BASHPID}` which will differ.
# Usage:    env_store [<ident>]                 # store complete environment
#           env_store [<ident>] [<variable>]... # store only listed variables (ident can be empty string)
# Options:  -d, --disk                          # store on disk in temporary folder
#           -p, --path <base-dir>               # store on disk in given folder
# Files:    `/dev/shm/<prog>[-<ident>].env`     # stored environment
# Example:  env_restore
#           ...<code>
#           env_store # save changes
#           ....
#           env_store # save changes
#           ....
#           env_clean # everything done remove progress
env_store() {
    debug "env_store $*"
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt="-m"
    while true; do
        case "$1" in
        -d | --disk)
            opt=""
            shift
            ;;
        -p | --path)
            opt="$1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    local ident=$1
    shift || true
    # shellcheck disable=SC2086
    declare -p "$@" | sed 's/^declare\b/declare -g/' >"$(mktemp $opt -e env "$ident")"
}

# Restore environment from shared memory/file
# If some variable names are given only those will be restored.
# Usage:    env_restore [<ident>] [<variable>]...
# Options:  -d, --disk                          # store on disk in temporary folder
#           -p, --path <base-dir>               # store on disk in given folder
# Files:    `/dev/shm/<prog>[-<ident>].env`     # stored environment
#           `/dev/shm/<prog>[_<ident>]_<sub-pid>.env-sub` # very short temporary file to filter input
env_restore() {
    debug "env_restore $*"
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt="-m"
    while true; do
        case "$1" in
        -d | --disk)
            opt=""
            shift
            ;;
        -p | --path)
            opt="$1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    local ident="${1-}" shm_env
    shift || true
    # shellcheck disable=SC2086
    shm_env="$(mktemp $opt -e env "$ident")"
    [ -s "$shm_env" ] || return 0
    if [[ "$#" -gt 0 ]]; then
        temp="$(mktemp -me env-sub "${ident}_${BASHPID}")"
        grep -E "$(tr ' ' '|' <<<"$*")" "$shm_env" >"$temp" || true
        # shellcheck disable=SC1090
        source "$temp" || true
        rm -r "$temp" || true
    else
        # shellcheck disable=SC1090
        source "$shm_env" 2>/dev/null || true
    fi
}

# Remove stored environment from shared memory/file
# Usage:    env_clean [<ident>]
# Options:  -d, --disk                          # store on disk in temporary folder
#           -p, --path <base-dir>               # store on disk in given folder
env_clean() {
    debug "env_clean $*"
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt="-m"
    while true; do
        case "$1" in
        -d | --disk)
            opt=""
            shift
            ;;
        -p | --path)
            opt="$1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    # shellcheck disable=SC2086
    rm -f "$(mktemp $opt -e env "$1")"
}

# Change environment in shared memory/file
# Usage:    env_change <ident> <command>                # store complete environment
#           env_change <ident> <command> [<variable>]...# store only listed variables (ident can be empty string)
env_change() {
    # parameter parsing
    eval set -- "$(option_parse $'d disk -\np path +' "$@")"
    local opt
    while true; do
        case "$1" in
        -d | --disk)
            opt="$opt $1"
            shift
            ;;
        -p | --path)
            opt="$opt $1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    num_parameters --min 2 --die "At least <ident> <command> is needed!" -- "$@"
    local ident=$1
    shift || true
    local command=$1
    shift || true
    # shellcheck disable=SC2086
    env_restore $opt "$ident"
    eval "$command"
    # shellcheck disable=SC2086
    env_store $opt "$ident" "$@"
}

######################################################################################
# Sync/Async calls with optional step control
######################################################################################

declare -A _async_running

# Set the variables which should be stored with step control
STEPS_VARIABLES=

# Initialize nstep control
# Usage:    steps_init
# Example:  steps_init
#           # sync | async | queue calls
#           steps_done
steps_init() {
    declare -g -A _STEPS
    env_restore steps
    declare -p _STEPS
    env_store steps _STEPS "$STEPS_VARIABLES" # initial store
    echo "$(gettext "Work steps are logged so that you can resume work mid-process")..." >&2
}

# Check if step already finished successful
# Usage:    steps_done <name>
# Exit:     0 if done else not done or with failure
steps_check() {
    local name="$1"
    num_parameters --min 1 --max 1 --die "Only an <ident> is needed, but must be there!" -- "$@"
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' || return 1 # return not found if no step control
    if [ -n "${_STEPS["$name"]}" ]; then
        # shellcheck disable=SC2005
        echo "$(eval_gettext "Job \$name already done in this run, skipping")" >&2
        return 0
    else
        return 1
    fi
}

# Set step as successfully done
# Usage:    steps_done <name>   # finished one step
#           steps_done          # completely finished -> cleanup
steps_done() {
    local name="$1"
    num_parameters --min 0 --max 1 --die "Only an <ident> is needed!" -- "$@"
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' || return # do nothin if no step control
    if [ -n "$1" ]; then
        _STEPS["$name"]=1
        # shellcheck disable=SC2155
        local date="$(date_format sql)"
        # shellcheck disable=SC2005
        echo "$(eval_gettext "Finished: Step \$name at \$date")" >&2
        env_store steps _STEPS "$STEPS_VARIABLES"
    else
        env_clean steps
    fi
}

# Run the given command with optional step control
# Usage:    sync <command> [<params>...]
# This will use the command itself as name. If you run the same command multiple times use
# async_name directly.
sync() {
    num_parameters --min 1 --die "At least a <command> is needed!" -- "$@"
    sync_name "$1" "$@"
}

# Alternative to sync in which this call is given a name to refer
# Usage:     sync <name> <cmd> [<params>...]
sync_name() {
    num_parameters --min 2 --die "At least a <name> and <command> is needed!" -- "$@"
    local name=$1
    shift
    steps_check "$name" && return || true
    local date
    # shellcheck disable=SC2034
    date="$(date_format sql)"
    # shellcheck disable=SC2005
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' && echo "$(eval_gettext "Started: step \$name at \$date")" >&2 || true
    "$@"
    steps_done "$name"
}

# Run the given command asynchronous ang go on in the calling routine (short form of async_name)
# Usage:    async <command> [<params>...]
# This will use the command itself as name. If you run the same command multiple times use
# async_name directly.
# Example:  async task1
#           async task2
#           async_wait task1
#           async task3
#           wait # for all to end
async() {
    num_parameters --min 1 --die "At least a <command> is needed!" -- "$@"
    async_name "$1" "$@"
}

# Alternative to async in which this call is given a name to refer in async_wait
# Usage:    async <name> <cmd> [<params>...]
async_name() {
    num_parameters --min 2 --die "At least a <name> and <command> is needed!" -- "$@"
    local name=$1
    shift
    ! steps_check "$name" || return
    declare -p _STEPS 2>/dev/null | grep -q 'declare -A' && echo "Started: step $name at $(date_format sql)" >&2 || true
    "$@" &
    env_change queue "_async_running[\"$name\"]=$!" _queue _async_running
}

# Check if the command is done or wait here till it is so
# Usage:    async_wait          # to wait for all to be done
#           async_wait <name>   # to wiat for specific command to finish
async_wait() {
    [ -z "${_async_running["$1"]}" ] && return 0 || true
    wait "${_async_running["$1"]}"
    local code=$?
    if ((code == 0)); then
        steps_done "$1"
        env_change queue "unset async_running[\"$1\"]" _queue _async_running
    else
        declare -p _STEPS 2>/dev/null | grep -q 'declare -A' && echo echo "Failed: Step $1 at $(date_format sql)" >&2 || true
    fi
    return "$code"
}

# Maximum number of parallel tasks for queue
ASYNC_QUEUE_MAX=2

declare -a _queue
declare _queue_control_pid

_queue_control() {
    local name pid free first params
    while true; do
        sleep 1
        # loop async table
        env_restore queue
        if ((${#_async_running[@]} > 0)); then
            for name in "${!_async_running[@]}"; do
                pid="${_async_running["$name"]}"
                # process no longer running
                if ! kill -0 "$pid" 2>/dev/null; then
                    steps_done "$name"
                    env_change queue "unset _async_running[\"$name\"]" _queue _async_running
                fi
            done || true
        fi
        env_restore queue
        debug "Task queue: $$ $BASHPID async ${#_async_running[@]} queue ${#_queue[@]}"
        # test if queue and running are empty -> end control
        ((${#_queue[@]} > 0 || ${#_async_running[@]} > 0)) || return 0
        # async has free slots
        free=$((ASYNC_QUEUE_MAX - ${#_async_running[@]}))
        if ((free > 0)); then
            for _ in $(seq 1 "$free"); do
                ((${#_queue[@]} > 0)) || break
                # shift from queue
                first="${_queue[0]}"
                env_change queue "_queue=(\"\${_queue[@]:1}\")" _queue _async_running
                IFS=$'\x1f' read -r -a params <<<"$first" # split back into array
                # execute
                async_name "${params[@]}"
            done
        fi
    done
    env_clean queue
}

# Add command to process queue
# Usage:    queue <command> [<params>...]
# This will use the command itself as name. If you run the same command multiple times use
# queue_name directly.
# Example:  queue task1
#           queue task2
#           queue task3
#           async_wait task2
#           queue task4
#           wait # for all to end
queue() {
    num_parameters --min 1 --die "At least a <command> is needed!" -- "$@"
    queue_name "$1" "$@"
}

# Add command to process queue
# Usage:    queue_name <name> <command> [<params>...]
queue_name() {
    num_parameters --min 2 --die "At least a <name> and <command> is needed!" -- "$@"
    ! steps_check "$1" || return 0
    local entry
    entry=$(printf "%s\x1f" "$@")
    entry=${entry%$'\x1f'} # remove trailing separator
    # change queue and in shm
    env_change queue "_queue+=(\"$entry\")" _queue _async_running
    # start queue control if not running
    if [ -z "$_queue_control_pid" ]; then
        _queue_control &
        _queue_control_pid=$!
    fi
}
