#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Module with remote calling/execution helpers.

# load other modules if not already done
declare -F "num_parameters" >/dev/null || source "$BASHLIB_HOME"/module/validator

######################################################################################
# Remote SSH
######################################################################################

# Run command on remote host
# Usage:    remote [<options>] <command>... # special characters in command masked with backslash
#           # <special char> := | & * > < $
#           <commands> | remote [<options>]
# Options:  # following options, only before `<command>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
# Output:   passed through
remote() {
    # parameter parsing
    local _login host jump
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    if [ -p /dev/stdin ] && (($# == 0)); then
        # shellcheck disable=SC2086
        ssh $ssh bash -s
        return "${PIPESTATUS[0]}"
    else
        # this allows interactivity
        # shellcheck disable=SC2086
        # shellcheck disable=SC2029
        ssh $ssh "$@"
        return "${PIPESTATUS[0]}"
    fi
}

# Run remote command with pseudo terminal
# \r\n my be contained, remove with nocr
# "Connection ... closed" in stderr: remove using: 2> >(grep -v '^Connection to .* closed\.' >&2)
# Usage:    remote_term [<options>] <command>... # special characters have to be masked: | & * > <
#           <title> | remote_term [<options>]
# Options:  # following options, only before `<command>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
# Output:   passed through
remote_term() {
    # parameter parsing
    local _login host jump
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    if [ -p /dev/stdin ]; then
        # shellcheck disable=SC2086
        ssh -t $ssh bash -s
        return "${PIPESTATUS[0]}"
    else
        # this allows interactivity
        # shellcheck disable=SC2086
        ssh -t $ssh "$@"
        return "${PIPESTATUS[0]}"
    fi
}

# Run remote command with pseudo terminal but line based output (problematic with questions)
# Usage:    remote_term_line [<options>] <command>... # special characters have to be masked: | & * > <
#           <title> | remote_term_line [<options>]
# Options:  # following options, only before `<command>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
# Output:   passed through
remote_term_line() {
    # parameter parsing
    local _login host jump
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    if [ -p /dev/stdin ]; then
        # shellcheck disable=SC2086
        ssh -t $ssh bash -s 2> >(grep -v '^Connection to .* closed\.' >&2) | nocr
        return "${PIPESTATUS[0]}"
    else
        # this allows interactivity
        # shellcheck disable=SC2086
        ssh -t $ssh "$@" 2> >(grep -v '^Connection to .* closed\.' >&2) | nocr
        return "${PIPESTATUS[0]}"
    fi
}
# STDERR_CLEANUP="2> >(grep -v '^Connection to .* closed\.' >&2)"

# Run local script on remote
# Usage:    remote_file [<options>] <file>
#           <file> | remote_file [<options>]
# Options:  # following options, only before `<file>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
# Output:   passed through
remote_file() {
    # parameter parsing
    local _login host jump
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    local file
    file="$(input "$@")"
    test "${file:0:1}" = "/" || file="$(path)/$file"
    test -f "$file" || die "$(eval_gettext "No file to execute remotely under \$file")"
    # shellcheck disable=SC2086
    ssh $ssh 'bash -s' <"$file"
}

# Open an interactive console on remote host
# The motd and banner are prevented by touching .hushlogin on the server.
# Usage:    remote_console [<options>]
# Options:  -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
#           -A, --forward-agent     # use local ssh-agent also on remote host for authentication.
# Globals:  $server
#           $login - default is "operator"
# Output:   passed through
# Return:   passed through
remote_console() {
    # parameter parsing
    local _login host jump opt
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +\nA forward-agent -' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        -A | --forward-agent)
            opt="-A"
            shift
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: semver_diff [-h] <first> <second>"
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    local rc
    # shellcheck disable=SC2086
    ssh $ssh '(nohup touch .hushlogin && sleep 1 && rm .hushlogin) >/dev/null 2>&1 </dev/null &' # no banner
    # shellcheck disable=SC2086
    # shellcheck disable=SC2248
    ssh $opt $ssh </dev/tty || rc=$?
    return "$rc"
}

# Upload file
# Usage:    upload [<options>] <source> <dest>
# Options:  # following options, only before `<source>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
upload() {
    # parameter parsing
    local _login host jump
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    local dir=${2:-~}
    debug "rsync -av $1 $ssh:$dir"
    # shellcheck disable=SC2086
    rsync -av "$1" $ssh:"$dir"
}

# Download file
# Usage:    download [<options>] <source> <dest>
# Options:  # following options, only before `<source>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
download() {
    # parameter parsing
    local _login host jump
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login)
            _login="$2"
            shift 2
            ;;
        -h | --host)
            host="$2"
            shift 2
            ;;
        -j | --jump)
            jump="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _login=${_login:-${login:-$REMOTE_LOGIN_DEFAULT}}
    host=${host:-$server}
    local ssh="${_login}@${host}"
    [ -z "$jump" ] || ssh="-J $jump $ssh"
    local dir=${2:-.}
    # shellcheck disable=SC2086
    rsync -av $ssh:"$1" "$dir"
}

######################################################################################
### Extended remote commands
######################################################################################

_module_resolve() {
    local modules=()
    split "$1" modules ,
    local init=1 module line
    for module in "${modules[@]}"; do
        [[ "$module" =~ ^(full|base|.*/.*)$ ]] || module="module/$module"
        [ -n "$init" ] && init= || echo -n ,
        echo -n "$module"
        while read -r line; do
            echo -n ",$(_module_resolve "$line")"
        done < <(grep '^use ' "$BASHLIB_HOME/$module" | sed 's/^use //' || true)
    done
}

# Deprected: Run bashlib command on remote.
# The `modules` are a comma separated list of module names like network os.
# The modules can be:
# - `base` or `full` as first element
# - `module/<name>` to load the named module (if not full is used)
# - `extra/<name>` to load an extra module
# - `configs` to also transfer all the configurations
# - `config/<name>` to load only one config
# - any other name will be interpreted as `module/<name>` (short form)
# Usage:    remote_bashlib [<options>] <module>[,<module>...] <command> [<args>...]
#           <command> [<args>...] | remote_bashlib [<options>] <module>[,<module>...]
# Options:  # following options, only before `<module>`
#           -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
# Globals:  $server
#           $login - default is "operator"
# Examples: IP="$(remote_bashlib ip ip_intern)"
remote_bashlib() {
    # parameter parsing
    local opt
    eval set -- "$(option_parse $'+l login +\nh host +\nj jump +' "$@")"
    while true; do
        case "$1" in
        -l | --login | -h | --host | -j | --jump)
            opt+=" $1 $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    local list modules
    list="$(_module_resolve "${1-}")"
    IFS=',' read -ra modules <<<"$list"
    debug "Modules: ${modules[*]}"
    shift
    local pattern='^#!/usr/bin/env'" bash|source "'/dev/null'
    # shellcheck disable=SC2086
    (
        echo "#!/usr/bin/env" bash
        echo "DEBUG=${DEBUG:-}"
        echo "BASHLIB_LOADER=remote"
        # load base
        if [[ "${modules[0]}" =~ ^(full|base)$ ]]; then
            grep -Ev "$pattern" "$BASHLIB_HOME/${modules[0]}"
            modules=("${modules[@]:1}")
        else
            grep -Ev "$pattern" "$BASHLIB_HOME"/base
        fi
        # load modules
        for module in "${modules[@]}"; do
            if [ "$module" = "configs" ]; then
                for f in "$BASHLIB_HOME"/config/*; do
                    if [[ -f "$f" && "$f" != *.* ]]; then
                        grep -Ev "$pattern" "$f"
                    fi
                done
            else
                grep -Ev "$pattern" "$BASHLIB_HOME/$module"
            fi
        done
        (($# == 0)) || debug "Running: $*"
        (($# == 0)) || escape_args "$@"
        [ ! -p /dev/stdin ] || debug "Running piped command!"
        [ ! -p /dev/stdin ] || cat </dev/stdin
    ) | shfmt -mn | remote $opt
}

# Deprecated: Remote install package like @install
# Use `remote_bashlib software install`, see @remote_bashlib.
remote_install() {
    _deprecated "use remote_bashlib software install" warn
    remote_bashlib software install "$@"
}

# Deprecated: Display the system description (from remote)
# Use `remote_bashlib os system_info`, see @remote_bashlib.
remote_system_info() {
    _deprecated "use remote_bashlib os system_info" warn
    remote_bashlib os system_info "$@"
}

# Deprectaed: Remote df with visual display
# Use `remote_bashlib os disk_free` instead.
# The lines will be colorized based on $MOUNT_COLOR_LIMIT setting, which contains sets of 5 entries (pattern critical error warn ok). The first matching pattern will decide the color limits.
# Usage:    remote_df [<mount>...]                              # show table
#           remote_df <var> <operator> <limit%> [<mount>...]    # additionaly collect specific volumes
# Options:  -l, --local     # only list local devices
remote_df() {
    _deprecated "use remote_bashlib os disk_free" warn
    remote_bashlib os disk_free "$@"
}

# Deprecated: Remote check if LVM is used
# Use `remote_bashlib os uses_lvm` instead.
# Usage:    remote_lvm
# Return:   0 for uses LVM
#           1 if not
remote_lvm() {
    _deprecated "use remote_bashlib os uses_lvm" warn
    remote_bashlib os uses_lvm "$@"
}

# Wait till reboot is finished
# Usage:    boot_wait [<options>]
# Options:  -l, --login <user>
#           -h, --host <host>
#           -j, --jump <user>@<host>
#           -q, --quiet
# Globals:  $server
#           $login - default is "operator"
# Error:    <sql-time>
boot_wait() {
    # parameter parsing
    eval set -- "$(option_parse $'q quiet -' "$@")"
    local quiet
    while true; do
        case "$1" in
        -q | --quiet)
            quiet=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    local uptime seconds=15
    echo -ne "Warten bis der Reboot fertig ist" >&2
    sleep "$seconds"
    while true; do
        [ -n "$quiet" ] || echo -ne "\r$(eval_gettext "Wait until the reboot is complete (\$seconds seconds)")" >&2
        uptime=$(remote cut -d"' '" -f1 /proc/uptime 2>/dev/null | sed 's/[ .].*//')
        if ((uptime > 0 && uptime < 300)); then
            break
        else
            sleep 1
            ((seconds++))
        fi
    done
    [ -n "$quiet" ] || remote uptime --since
    [ -n "$quiet" ] || echo ""
}
