#!/usr/bin/env bash

# Software management functions.

######################################################################################
### Installer
######################################################################################

# Cache used to prevent multiple install calls for the same information in one run
declare -A _software_install

# Install software package
# Usage:    install <pack>...
install() {
    # collect what to be needed
    local apt=""
    local snap=""
    local apk=""
    local reload=""
    # check what is needed
    for cmd in "$@"; do
        if [[ ! -v _software_install["$cmd"] ]]; then
            PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" which "$cmd" >/dev/null ||
                # debian
                if command -v apt-get >/dev/null; then
                    case $cmd in
                    yq) snap+=" $cmd" ;;
                    mlr) apt+=" miller" ;;
                    *) apt+=" $cmd" ;;
                    esac
                # alpine
                elif command -v apkt >/dev/null; then
                    case $cmd in
                    mlr) apk+=" miller" ;;
                    *) apk+=" $cmd" ;;
                    esac
                fi
            _software_install["$cmd"]=1
        fi
    done
    if test -n "$snap" && ! command -v snapd >/dev/null; then
        apt="$apt snapd"
        snap="$snap snapd"
        reload+=" ~/.bashrc"
    fi
    # install
    # shellcheck disable=SC2086
    test -z "$apt" || sudo apt-get install -y $apt
    # shellcheck disable=SC2086
    test -z "$snap" || sudo apt snap install $snap
    # shellcheck disable=SC2086
    test -z "$apk" || sudo apk update
    test -z "$apk" || sudo apk add $apk
    # reload possibly changed config
    # shellcheck disable=SC1090
    for file in $reload; do
        # shellcheck disable=SC2086
        source $file
    done
}

######################################################################################
### Semantic Versioning
######################################################################################

# Parse semantic version number
# Usage:    semver <string>
#           <string> | semver
# Stdout:   <major>
#           <minor>         or "" if undefined
#           <patch>         or "" if undefined
#           <prerelease>    or "" if undefined
#           <build>         or "" if undefined
semver() {
    input "$@" |
        sed -e 's#[^0-9]*\([0-9]*:\)\?\([0-9]*\)\([.]\([0-9]*\)\)\?\([.]\([0-9]*\)\)\?\(-\([^+]*\)\)\?+\?\(.*\)\?.*#\2\n\4\n\6\n\8\n\9#'
}

# Calculate difference
# Usage:    semver_diff [-h] <first> <second> # can already be parsed or not
# Options:  -h,--human      # to show it user friendly
# Stdout:   <int>:  >1000000000 newer major (num / 1000000000 = steps)
#                   >1000000 newer minor (num / 1000000 = steps)
#                   >1000 newer patch (num / 1000 = steps)
#                   10 newer pre-release
#                   1 newer build
#                   0 identical
#                   -1 older build
#                   -10 older pre-release
#                   <-1000 older patch (num / 1000 = steps)
#                   <-1000000 older minor (num / 1000000 = steps)
#                   <-1000000000 older major (num / 1000000000 = steps)
semver_diff() {
    # parameter parsing
    eval set -- "$(option_parse "h human -" "$@")"
    local human
    while true; do
        case "$1" in
        -h | --human)
            human=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: semver_diff [-h] <first> <second>"
    # processing
    [[ "${1-}" =~ [.-] ]] && version1="$(semver "$1")" || version1="$1"
    [[ "${2-}" =~ [.-] ]] && version2="$(semver "$2")" || version2="$2"
    IFS=$'\n' readarray -t v1 <<<"$version1"
    IFS=$'\n' readarray -t v2 <<<"$version2"
    local num=0
    maj1=${v1[0]}
    maj2=${v2[0]}
    min1=${v1[1]:-0}
    min2=${v2[1]:-0}
    pat1=${v1[2]:-0}
    pat2=${v2[2]:-0}
    pre1=${v1[3]}
    pre2=${v2[3]}
    bld1=${v1[4]}
    bld2=${v2[4]}
    if [ "$maj1" -ne "$maj2" ]; then
        num=$(((maj2 - maj1) * 1000000000))
    elif [ "$min1" -ne "$min2" ]; then
        num=$(((min2 - min1) * 1000000))
        ((num < 1000000000)) || num=999000000
    elif [ "$pat1" -ne "$pat2" ]; then
        num=$(((pat2 - pat1) * 1000))
        ((num < 1000000)) || num=999000
    elif [[ "$pre1" < "$pre2" ]]; then
        num=10
    elif [[ "$pre1" > "$pre2" ]]; then
        num=-10
    elif [[ "$bld1" < "$bld2" ]]; then
        num=1
    elif [[ "$bld1" > "$bld2" ]]; then
        num=-1
    fi
    # output
    local step
    if [ -n "$human" ]; then
        echo -n "$1 -> $2 "
        if ((num == 0)); then
            gettext "are identical versions"
            echo
        elif ((num >= 1000000000)); then
            step=$((num / 1000000000))
            eval_ngettext "is an upgrade of one major version" "is an upgrade of \$step mayjor versions" "$step"
            echo
        elif ((num >= 1000000)); then
            step=$((num / 1000000))
            eval_ngettext "is an upgrade of one minor version" "is an upgrade of \$step minor versions" "$step"
            echo
        elif ((num >= 1000)); then
            step=$((num / 1000))
            eval_ngettext "is an upgrade of one patch version" "is an upgrade of \$step patch versions" "$step"
            echo
        elif ((num >= 1)); then
            gettext "is a developer upgrade"
            echo
        elif ((num >= -1000)); then
            gettext "is a developer downgrade"
            echo
        elif ((num >= 1000000)); then
            step=$((num / -1000))
            eval_ngettext "is an downgrade of one patch version" "is an downgrade of \$step patch versions" "$step"
            echo
        elif ((num >= 1000000000)); then
            step=$((num / -1000000))
            eval_ngettext "is an upgrade of one minor version" "is an upgrade of \$step minor versions" "$step"
            echo
        else
            step=$((num / 1000000000))
            eval_ngettext "is an upgrade of one major version" "is an upgrade of \$step mayjor versions" "$step"
            echo
        fi
        return 0
    else
        echo "$num"
    fi
    # return code
    ((num == 0)) && return 0 || return 1
}
