#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# Module with modifiers for csv/tsv tables.

# Load dependent modules if not done
use module/software

######################################################################################
# csv
######################################################################################

######################################################################################
# old
######################################################################################

# Convert TSV data into visual table
#
# Usage:    tsv2table <tsv>
#           <tsv> | tsv2table
# Output:   <table>
tsv2table() {
    is integer --name=arguments --max=1 --die -- $#
    # processing
    install mlr
    input "$@" | mlr --csvlite --ifs '\t' -o pprint cat
}

# Convert TSV data into markdown table
#
# Usage:    tsv2md <tsv>
#           <tsv> | tsv2md
# Output:   <md>
tsv2md() {
    is integer --name=arguments --max=1 --die -- $#
    # processing
    install mlr
    # shellcheck disable=SC2119
    input "$@" | uncolorize | mlr --csvlite --ifs '\t' --omd cat
}

######################################################################################
# csv
######################################################################################

# Transform comma separated table
#
# Usage:    <string> | csv {to} <param>...
#           <string> | csv to {tsv}              # convert
csv() {
    is set --name=command --allow="to" --die -- "$1"
    # processing
    case $1 in
    to)
        is integer --name=arguments --max=2 --die -- $#
        is set --name=format --allow="tsv" --die -- "$2"
        case $2 in
        tsv)
            python3 -c '
import sys, csv
reader = csv.reader(sys.stdin)
writer = csv.writer(sys.stdout, delimiter="\t", lineterminator="\n")
for row in reader:
    writer.writerow(row)
'
            ;;
        esac
        ;;
    esac
}

######################################################################################
# tsv
######################################################################################

# Transform tab separated table
#
# Usage:    <string> | tsv {to|crop} <param>...
#           <string> | tsv to {csv|pprint}              # convert
#           <string> | tsv crop <num|name> <width>      # crop column
#           <string> | tsv sort <num|name> [numeric]    # crop column
#           <string> | tsv reverse                      # reverse order
tsv() {
    local separator=$'\t'
    local input
    input=$(cat) # read stdin
    local cmd="$1"
    case $cmd in
    to)
        local format=$2
        case $format in
        csv)
            awk 'BEGIN { FS="\t"; OFS="," }
                {
                    for(i=1; i<=NF; i++) {
                        if ($i ~ /,|"|\n/) {
                            gsub(/"/, "\"\"", $i)  # double quotes inside field
                            $i = "\"" $i "\""
                        }
                    }
                    $1 = $1  # force rebuilding the line with OFS
                    print
                }' <<<"$input"
            ;;
        pprint)
            column -t -s $'\t' <<<"$input"
            ;;
        *) die "Allowed formats are only csv, not [$format]" ;;
        esac
        ;;
    crop)
        local cols idx
        IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
        is integer -- "$2" && idx=$(($2 - 1)) || idx="$(array cols indexof "$2")" || die "Column [$2] not found in table"
        local width="$3"
        [[ -n "$idx" && -n "$width" ]] || die "Usage: table crop <column> <width>"
        local line orig
        while IFS=$separator read -r -a line; do
            orig="${line[idx]}"
            # Crop string to width, adding "…" if truncated
            ((${#orig} <= width)) || line[idx]="${orig:0:width-1}…"
            (
                IFS="$separator"
                printf '%s\n' "${line[*]}"
            )
        done <<<"$input"
        ;;
    sort)
        local cols idx
        IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
        is integer -- "$2" && idx=$(($2 - 1)) || idx="$(array cols indexof "$2")" || die "Column [$2] not found in table"
        local col type
        col=$((idx + 1))
        [ ! "$3" = "numeric" ] || type=n
        [[ -n "$idx" ]] || die "Usage: table sort <column> [numeric]"
        # sort
        (
            IFS="$separator"
            printf '%s\n' "${cols[*]}"
        )
        tail -n +2 <<<"$input" | sort -t $'\t' "-k${col},${col}${type}"
        ;;
    reverse)
        head -1 <<<"$input"
        tail -n +2 <<<"$input" | tac
        ;;
    *) die "Usage: tsv {to|crop} [<value>]" ;;
    esac
}
