#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# Module with modifiers for csv/tsv tables.

# Load dependent modules if not done
use module/software

######################################################################################
# csv
######################################################################################

# Transform comma separated table
#
# Usage:    <string> | csv {to} <param>...
#           <string> | csv to {tsv}              # convert
csv() {
    is set --name=command --allow="to" --die -- "$1"
    # processing
    case $1 in
    to)
        is integer --name=arguments --max=2 --die -- $#
        is set --name=format --allow="tsv" --die -- "$2"
        case $2 in
        tsv)
            python3 -c '
import sys, csv
reader = csv.reader(sys.stdin)
writer = csv.writer(sys.stdout, delimiter="\t", lineterminator="\n")
for row in reader:
    writer.writerow(row)
'
            ;;
        esac
        ;;
    esac
}

######################################################################################
# tsv
######################################################################################

# Transform tab separated table
#
# The main element for tabular data within the BashLib is tab separated values which can easily used in bash.
# This command collection help with some common use cases to make them easier to write.
#
# To run multiple actions call it multiple times in a pipe.
#
# Usage:    <string> | tsv crop <num|name> <width>                 # crop column
#           <string> | tsv sort <num|name> [numeric] [<options>]   # sort by column
#           <string> | tsv reverse [<options>]                     # reverse order
#           <string> | tsv to {csv|pprint} [<options>]             # convert
#           <string> | tsv filter [<num|name> <pattern>]           # filter some rows
# Options:  --with-header              # keep first line as header in `sort`, `reverse`
#           --remove-header            # remove first (header) line
#           --color-red <pattern>      # to colorize in `pprint`
#           --color-yellow <pattern>   # to colorize in `pprint`
#           --color-blue <pattern>     # to colorize in `pprint`
# Example:  - `<string> | tsv filter --remove-header`
tsv() {
    # parameter parsing
    local withHeader removeHeader cmd
    eval set -- "$(option_parse $'- with-header -\n- remove-header -' "$@")"
    while true; do
        case "$1" in
        --with-header) withHeader=1 && shift ;;
        --remove-header) removeHeader=1 && shift ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is enum --name=command --allow="crop sort reverse to filter" --die --output=cmd -- "$1"
    # processing
    local separator=$'\t' input
    input=$(cat) # read stdin
    is false -- "$removeHeader" || removeHeader="${removeHeader#*$'\n'}"
    case $cmd in
    filter)
        echo "$input"
        ;;
    to)
        local format=$2
        case $format in
        csv)
            awk 'BEGIN { FS="\t"; OFS="," }
                {
                    for(i=1; i<=NF; i++) {
                        if ($i ~ /,|"|\n/) {
                            gsub(/"/, "\"\"", $i)  # double quotes inside field
                            $i = "\"" $i "\""
                        }
                    }
                    $1 = $1  # force rebuilding the line with OFS
                    print
                }' <<<"$input"
            ;;
        pprint)
            column -t -s $'\t' <<<"$input"
            ;;
        *) die "Allowed formats are only csv, not [$format]" ;;
        esac
        ;;
    crop)
        local cols idx
        IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
        is integer -- "$2" && idx=$(($2 - 1)) || idx="$(array cols indexof "$2")" || die "Column [$2] not found in table"
        local width="$3"
        [[ -n "$idx" && -n "$width" ]] || die "Usage: table crop <column> <width>"
        local line orig
        while IFS=$separator read -r -a line; do
            orig="${line[idx]}"
            # Crop string to width, adding "…" if truncated
            ((${#orig} <= width)) || line[idx]="${orig:0:width-1}…"
            (
                IFS="$separator"
                printf '%s\n' "${line[*]}"
            )
        done <<<"$input"
        ;;
    sort)
        local cols idx
        IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
        is integer -- "$2" && idx=$(($2 - 1)) || idx="$(array cols indexof "$2")" || die "Column [$2] not found in table"
        local col type
        col=$((idx + 1))
        [ ! "$3" = "numeric" ] || type=n
        [[ -n "$idx" ]] || die "Usage: table sort <column> [numeric]"
        # sort
        (
            IFS="$separator"
            printf '%s\n' "${cols[*]}"
        )
        tail -n +2 <<<"$input" | sort -t $'\t' "-k${col},${col}${type}"
        ;;
    reverse)
        if is true -- "$withHeader"; then
            head -1 <<<"$input"
            tail -n +2 <<<"$input" | tac
        else
            tac <<<"$input"
        fi
        ;;
    *) die "Usage: tsv {to|crop} [<value>]" ;;
    esac
}
