#!/usr/bin/env bash
# shellcheck source=config/environment
source /dev/null
# shellcheck source=base
source /dev/null

# Run trivy security scan and analyze results.

TRIVY_EXPLOITS_URL=https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

TRIVY_JIRA_BOARD=SEC
TRIVY_JIRA_ISSUE_TYPE=Code
TRIVY_JIRA_FIELD_SOURCES=Vorkommen
TRIVY_JIRA_FIELD_RATING=Fremdeinschätzung
TRIVY_JIRA_FIELD_VERSION=Version
TRIVY_JIRA_FIELD_LINKS=Links
TRIVY_JIRA_FIELD_APPROVAL=Freigabe
TRIVY_JIRA_APPROVAL_TEMP="Ok für 30 Tage"
TRIVY_JIRA_APPROVAL_IRRELEVANT="Irrelevant"

# Run a trivy security analysis.
#
# If not installed it will install trivy and then use it.
# It will run the security analysis and output the directory in which you find all data:
#
# ```
# trivy.json - the original output of trivy containing all vulnerabilities
# <severity>/
#   <type>/
#       <cve-id>/
#           data.json
# ```
#
# After use you should remove this temporary folder to reclaim space.
#
# The pure trivy data will be optimized by:
#
# - downgrade security level if published in the last days
# - add exploit information
# - downgrade if node development package
# - connect with jira ticket management
#
# The jira ticket management needs some setup to work, all `JIRA_TRIVY_*` settings have to be set defined and therefore you need a board there you manage this tickets.
# Please make sure the custom fields are created for each of the setting. The approval needs also two defined values for temporarily allowed or irrelevant = always allowed.
#
# An Example is Board SEC with an `IssueType=Code`  which has the fields:
#
# - Sources as textarea field to store information of there this was found
# . Rating as textarea field containing the values from CVSS
# - Version as textarea field containing the installed and fixed version
# - Links as textarea field for all the references from trivy
# - Approval as enumeration with: Null, Blocked, Irrelevant, Allowed for 30 days
#
# Warning: This will overwrite the original trivy command, so if you want to use trivy directly while bashlib is loaded, use `command trivy ....`
#
# Usage:    trivy [<options>] root
#           trivy [<options>] files <path>
#           trivy [<options>] docker <file>
#           trivy [<options>] docker <image>
# Options:  t, timeout <duration>   set the timeout for the job in <int>m or <int>h
#           o, only-os              let `root` command only scan OS without filesystem traversal
# Output:   <report-path> or nothing if no vulnerabilities found
# Return:   1 if there are at least one CRITICAL or HIGH vulnerabilities
trivy() {
    is enum --name=command --allow="root files docker" --die -- "$1" && local command="$1" && shift
    local timeout
    timeout=${TRIVY_DEFAULT_TIMEOUT:-60m}
    # parameter parsing
    local _login host jump term lines file
    eval set -- "$(option_parse $'t timeout +\no only-os -' "$@")"
    while true; do
        case "$1" in
        -t | --timeout) timeout="$2" && shift 2 ;;
        -o | --only-os) onlyOS=1 && shift ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    install trivy
    local work cmd opt="--exit-code 0 --no-progress --skip-version-check --timeout $timeout -f json"
    local source="$1"
    work="$(mktemp --directory "${$}_trivy")"
    cmd="$(command -v trivy)"
    opt+=" -o $work/trivy.json"
    is empty -- "$DEBUG" || opt+=" --debug"
    is empty -- "$TRIVY_CACHE_SERVER" || opt+=" --server $TRIVY_CACHE_SERVER"
    case $command in
    root)
        is empty -- "$onlyOS" || opt+=" --pkg-types os"
        source="$(hostname -f)"
        sudo $cmd rootfs $opt $exclude / 2>&1 | sed 's/[^A-Z]*T[^A-Z]*//' | debug
        ;;
    files) command $cmd fs $opt "$1" 2>&1 | sed 's/[^A-Z]*T[^A-Z]*//' | debug ;;
    docker) command $cmd image $opt --input "$1" 2>&1 | sed 's/[^A-Z]*T[^A-Z]*//' | debug ;;
    esac
    # Splitting
    debug "Optimize JSON structure for splitting..."
    jq '.Results[]?|. as $g|.Vulnerabilities[]?|{Class: $g.Class, Target: $g.Target, Type: $g.Type}*.' "$work"/trivy.json >"$work"/split.json
    debug "Splitting JSON..."
    mkdir "$work"/split
    csplit -f "$work"/split/ -b '%06d' -zs $work/split.json /^{/ "{*}"
    rm "$work"/split.json
    # skip if nothing found
    local found
    found="$(ls -1 "$work"/split/ | wc -l)"
    if ((found == 0)); then
        debug "Nothing found."
        rm -r "$work"
        return 0
    fi
    debug "Found $found reports."
    # trivy report cache
    mkdir -p "$_trivy_cache/jira"
    ! is file -- "$_trivy_cache/exploits.json" || find "$_trivy_cache/exploits.json" -mmin +1440 -delete
    is file -- "$_trivy_cache/exploits.json" || curl -s "$TRIVY_EXPLOITS_URL" -o "$_trivy_cache/exploits.json"
    # initialize jira
    local project
    project="$(jira project "$TRIVY_JIRA_BOARD")"
    _trivy_jira[board]="$(jq .id -r <<<"$project")"
    is set -- "${_trivy_jira[board]}" || die "Could not find JIRA Board ID for $TRIVY_JIRA_BOARD!"
    _trivy_jira[issueType]="$(jq '.issueTypes[] | select(.name == "'"$TRIVY_JIRA_ISSUE_TYPE"'").id' -r <<<"$project")"
    is set -- "${_trivy_jira[issueType]}" || die "Could not find JIRA Issue Type ID for $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    fields="$(jira fields "${_trivy_jira[board]}" "${_trivy_jira[issueType]}")"
    _trivy_jira[field_sources]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_SOURCES"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_sources]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_SOURCES\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_rating]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_RATING"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_rating]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_RATING\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_version]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_VERSION"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_version]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_VERSION\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_links]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_LINKS"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_links]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_LINKS\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_approval]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_APPROVAL"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_approval]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_APPROVAL\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    # Loop over entries and create report
    local num
    for file in "$work"/split/*; do
        num="$(basename "$file")"
        queue add _trivy_report "$work" "$file" "$source"
    done
    queue run
    #rm -r "$work"/split

    # Output folder
    echo "$work"
}
trivy_test() {
    work="$1"
    source="test"
    rm -r "$work"/split/critical "$work"/split/high "$work"/split/medium "$work"/split/low 2>/dev/null || true
    # initialize jira
    local project
    project="$(jira project "$TRIVY_JIRA_BOARD")"
    _trivy_jira[board]="$(jq .id -r <<<"$project")"
    is set -- "${_trivy_jira[board]}" || die "Could not find JIRA Board ID for $TRIVY_JIRA_BOARD!"
    _trivy_jira[issueType]="$(jq '.issueTypes[] | select(.name == "'"$TRIVY_JIRA_ISSUE_TYPE"'").id' -r <<<"$project")"
    is set -- "${_trivy_jira[issueType]}" || die "Could not find JIRA Issue Type ID for $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    fields="$(jira fields "${_trivy_jira[board]}" "${_trivy_jira[issueType]}")"
    _trivy_jira[field_sources]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_SOURCES"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_sources]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_SOURCES\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_rating]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_RATING"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_rating]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_RATING\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_version]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_VERSION"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_version]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_VERSION\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_links]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_LINKS"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_links]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_LINKS\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
    _trivy_jira[field_approval]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_APPROVAL"'").key' -r <<<"$fields")"
    is set -- "${_trivy_jira[field_approval]}" || die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_APPROVAL\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"

    #_trivy_report "/tmp/_test_816357_trivy" "/tmp/_test_816357_trivy/split/000000" "test"
    #return 0
    # Loop over entries
    local num
    for file in "$work"/split/*; do
        num="$(basename "$file")"
        queue add _trivy_report "$work" "$file" "$source"
    done
    queue run
    # Create reports

    #rm -r "$work"/split
}
_trivy_cache=/tmp/trivy-cache
declare -A _trivy_jira
_trivy_report() {
    debug "trivy_report \"$1\" \"$2\" \"$3\""
    local work="$1"
    local file="$2"
    local source="$3"
    # initialize data and structure
    local type severity target id json title pkgPath description cvss installed sourceLine
    json="$(cat "$file")"
    type="$(jq .Type -r <<<"$json")"
    severity="$(jq .Severity -r <<<"$json")"
    target="$(jq .Target -r <<<"$json")"
    id="$(jq .VulnerabilityID -r <<<"$json")"
    title="$(jq .Title -r <<<"$json")"
    pkgPath="$(jq .PkgPath -r <<<"$json")"
    test ! "$pkgPath" = "null" || pkgPath=""
    description="$(jq .Description -r <<<"$json")"
    cvss="$(jq '.CVSS[]?.V3Score' -r <<<"$json")" | tr $'\n' '\;' | sed 's/;$//;s/;/; /g'
    installed="$(jq .InstalledVersion -r <<<"$json")"
    sourceLine="$source $target ($type) $pkgPath - Version $installed"
    # collect json changes
    local changes=() rules=() action
    # new findings
    local date
    date="$(jq .PublishedDate -r <<<"$json")"
    test ! "$date" = "null" || date=""
    if (($(date_format unix "$date") > $(now) - $(duration_format seconds 3d))) &&
        [[ "$severity" = "HIGH" || "$severity" = "CRITICAL" ]]; then
        action="Downgrade $severity -> MEDIUM because it was published less than 3 days ago"
        info "$id at $target: $action" >&2
        changes+=("{\"Severity\": \"MEDIUM\",\"OriginalSeverity\": \"$severity\"}")
        rules+=("{\"Title\": \"Just Published\",\"Description\": \"$action.\"}")
    fi
    # exploited
    local exploited
    exploited="$(jq '.vulnerabilities[]|select(.cveID=="'$id'")' "$_trivy_cache/exploits.json")"
    if is set -- "$exploited"; then
        action="Add information of known exploits and cancel downgrades in case of just published"
        info "$id at $target: $action" >&2
        changes+=("{\"Exploited\": $exploited, \"Severity\": \"$severity\"}")
        rules+=("{\"Title\": \"Exploited\",\"Description\": \"$action.\"}")
    fi
    # node dev-dependency -> downgrade to medium
    if [ "$type" = "npm" ] &&
        [[ "$severity" = "HIGH" || "$severity" = "CRITICAL" ]] && is file -- "$target" &&
        [ "$(jq '.packages|with_entries(select(.key|contains("'pkgname'")))|.[]|select(has("dev"))|[.dev]|any' $target/package-lock.json)" = "true" ]; then
        action="Downgrade $severity -> MEDIUM because it is a dev dependency"
        info "$id at $target: $action" >&2
        changes+=("{\"Severity\": \"MEDIUM\",\"OriginalSeverity\": \"$severity\"}")
        rules+=("{\"Title\": \"NPM Dev Dependency\",\"Description\": \"$action.\"}")
    fi
    # jira issues
    if is set -- "$TRIVY_JIRA_BOARD" && [[ "$severity" = "HIGH" || "$severity" = "CRITICAL" ]]; then
        # get information
        local issue created fixed fixStatus links
        issue="$(jira search "project = ${_trivy_jira[board]} AND summary ~ $id ORDER BY created ASC" | head -1)"
        fixed="$(jq .FixedVersion -r <<<"$json")"
        [ "$fixed" != "null" ] || fixed="-"
        fixStatus="$(jq .Status -r <<<"$json")"
        [ "$fixStatus" != "null" ] || fixStatus="-"
        links="$(jq '.References[]?' -r <<<"$json" | sed 's/^/- /')"
        if is empty -- "$issue"; then
            # create new jira issue
            local fields priority=Low
            case $severity in
            HIGH) priority=Major ;;
            CRITICAL) priority=Critical ;;
            esac
            jira json fields set project json "{\"id\":${_trivy_jira[board]}}"
            jira json fields set issuetype json "{\"id\":${_trivy_jira[issueType]}}"
            jira json fields set priority json "{\"name\":\"$priority\"}"
            jira json fields set summary "$id"
            jira json fields set description adf "$title"$'\n\n'"$description"
            jira json fields set ${_trivy_jira[field_sources]} adf "$(date +%Y-%m) > $source $target ($type)"
            jira json fields set ${_trivy_jira[field_rating]} adf "$severity (CVSS Rating ${cvss:--})"
            jira json fields set ${_trivy_jira[field_version]} adf "Gefixt ab Version $fixed $fixStatus"
            jira json fields set ${_trivy_jira[field_links]} adf "$links"
            jira json fields set ${_trivy_jira[field_sources]} adf "$(date +%Y-%m) > $sourceLine"
            jira json fields set labels json "[\"cve\", \"$(sed 's#.*ekz.de/##;s#/-/.*##;s#[/.]#", "#g' <<<"$source")\"]"
            issue="$(jira create "$fields")"
            created=1
        fi
        local jira deploy commentDate
        jira="$(jira get "$issue")"
        deploy="$(jq '.fields.'"${_trivy_jira[field_approval]}"'?.value' -r <<<"$jira")"
        commentDate=$(jq '.fields.comment.comments[].updated' -r <<<"$jira" | sort | tail -1)
        # downgrade
        if [[ "$severity" = "HIGH" || "$severity" = "CRITICAL" ]]; then
            if ([ "$deploy" = "$TRIVY_JIRA_APPROVAL_IRRELEVANT" ] || ([ "$deploy" = "$TRIVY_JIRA_APPROVAL_TEMP" ] && (($(date_diff "$(now)" "$commentDate") < $(duration_format seconds '30d'))))); then
                action="Downgrade $severity -> MEDIUM because of Jira status '$deploy'"
                info "$id at $target: $action" >&2
                changes+=("{\"Severity\": \"MEDIUM\",\"OriginalSeverity\": \"$severity\"}")
                rules+=("{\"Title\": \"Jira Approval\",\"Description\": \"$action.\"}")
            #elif [ "$deploy" = "$TRIVY_JIRA_APPROVAL_TEMP" ] && is set -- "$commentDate" && (($(date_diff "$(now)" "$commentDate") > $(duration_format seconds '30d'))); then
            #    expired=1
            fi
        fi
        # update jira
        if ! is set -- "$created"; then
            local old new fields update
            # update description
            old="$(jira json jira get description adf)"
            new="$title"$'\n\n'"$description"
            if [[ "$new" != "$old" ]]; then
                jira json fields set description adf "$new"
                update=1
            fi
            # update sources
            old="$(jira json jira get "${_trivy_jira[field_sources]}" md)"
            new="$(echo -e "$old\n$(date +%Y-%m) > $sourceLine" | sed -n '/>/p' | sort -t'>' -r -k2,1 | sort -t'>' -u -r -k2)"
            if [[ "$new" != "$old" ]]; then
                jira json fields set ${_trivy_jira[field_sources]} adf "$new"
                update=1
            fi
            # update rating
            old="$(jira json jira get "${_trivy_jira[field_rating]}" md)"
            new="$severity (CVSS Rating ${cvss:--})"
            if [[ "$new" != "$old" ]]; then
                jira json fields set ${_trivy_jira[field_rating]} adf "$new"
                update=1
            fi
            # update version
            old="$(jira json jira get "${_trivy_jira[field_version]}" md)"
            new="Gefixt ab Version $fixed $fixStatus"
            if [[ "$new" != "$old" ]]; then
                jira json fields set ${_trivy_jira[field_version]} adf "$new"
                update=1
            fi
            # update links
            old="$(jira json jira get "${_trivy_jira[field_links]}" md)"
            new="$links"
            if [[ "$new" != "$old" ]]; then
                jira json fields set ${_trivy_jira[field_links]} adf "$new"
                update=1
            fi
            # update labels
            local labels addLabel=()
            labels="$(jq '.fields.labels[]' -r <<<"$jira")"
            for label in $(echo "$source" | sed 's#.*ekz.de/##;s#/-/.*##;s#[/.]# #g'); do
                [[ ! "$labels" =~ $label ]] || continue
                addLabel+=('{"add": "'$label'"}')
            done
            if is set -- "$update"; then
                update="$fields"
                if ((${#addLabel[@]} > 0)); then
                    fields="$(jq --argjson l "[$(join $json ",")]" '.update = { "labels": $l }' <<<"$fields")"
                fi
                jira update "$issue" "$fields"
            fi
        fi
        action="Add information from Jira"
        info "$id at $target: $action" >&2
        changes+=("{\"Jira\": {\"id\": $issue, \"key\": $(jq .key <<<"$jira"), \"approval\": \"$deploy\", \"lastComment\": \"$commentDate\"}}")
        rules+=("{\"Title\": \"Jira Info\",\"Description\": \"$action.\"}")
    fi
    # store json changes
    is empty -- "$rules" || changes+=("{\"Rules\": [$(join rules)]}")
    for change in "${changes[@]}"; do
        json="$(jq -n --argjson o "$json" --argjson c "$change" '$o * $c')"
    done
    severity="$(jq .Severity -r <<<"$json")"
    local folder="$work/${severity,,}/$type/$id"
    mkdir -p "$folder"
    echo "$json" >"$folder/data.json"
    # create console text
    file="$folder/header.txt"
    if ! is file -- "$file"; then
        # set color
        case $severity in
        CRITICAL) echo -n "$CC_CRITICAL" >"$file" ;;
        HIGH) echo -n "$CC_ERROR" >"$file" ;;
        MEDIUM) echo -n "$CC_WARN" >"$file" ;;
        *) echo "" >"$file" ;;
        esac
        echo "================================================================================" >>"$file"
        echo "$severity $id $title" >>"$file"
        echo "--------------------------------------------------------------------------------" >>"$file"
        echo "$description" >>"$file"
        echo "    " >>"$file"
        echo "Rating: $severity (CVSS Rating $cvss)" >>"$file"
        echo "    " >>"$file"
        #test -z "$fixed" || echo -n " gefixt ab Version $fixed" >>$file_txt
        #test -z "$fixstatus" || echo -n " $fixstatus" >>$file_txt
        #test -z "$date" || echo "Eintragung vom: $date (vor $age)" >>$file
        #echo "$exploited" | jq '"Exploit bekannt seit "+.dateAdded+" bei "+.vendorProject+" "+.product' -r >>$file_txt
        #echo "$exploited" | jq '.notes' -r >>$file_txt
        #echo "Jira Ticket: https://ekz-gruppe.atlassian.net/browse/$issue" >>$file_txt
        #echo "Status: $status    Priorität: $priority    Zuständig: $assignee    Deploy: $deploy" >>$file_txt
        #echo "Letzte Kommentare:" >>$file_txt
        #echo -e "$comments" | sed 's/^/- /' >>$file_txt
        echo "Sources:" >>"$file"
    fi
    file="$folder/sources.txt"
    echo "- $sourceLine" >>"$file"
    file="$folder/footer.txt"
    if ! is file -- "$file"; then
        true
        #test -z "$links" || echo -e "Links:\n$links" >>$file_txt
    fi

    ## create markdown file
    #file="$folder/report.md"
    #if ! is file -- "$file"; then
    #    echo "  Title:      $title" >"$file"
    #fi
    ## create csv line
    #file="$folder/report.csv"
    #echo -e "$severity\t$type\t$id\t$title" >>"$file"

}
