#!/usr/bin/env bash

# Validators to make this easier and more readable.

######################################################################################
### Parameter Validation
######################################################################################

# Check that a specific number of parameters are given
# Usage:    num_parameters "$@" --min 1 --die "Zu viele Parameter: $USAGE"
# Options:  --min <int>     # at least <int> elements are needed
#           --max <int>     # not more than <int> elements are allowed
#           --die <string>  # exit with this message if not
num_parameters() {
    # parameter parsing
    eval set -- "$(option_parse $'- min +\n- max +\n- die +' "$@")"
    local min max die
    while true; do
        case "$1" in
        --min)
            min=$2
            shift 2
            ;;
        --max)
            max=$2
            shift 2
            ;;
        --die)
            die=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    # processing
    _die() {
        read -r line func file <<<"$(caller 1)"
        echo "Check ${FUNCNAME[1]}: $1 (${func} in ${file}:${line})" >&2
        [ -z "$die" ] || die "$die"
        return 1
    }
    [ -z "$min" ] || (($# >= min)) || _die "[$*] $# < $min (min)" || return 1
    [ -z "$max" ] || (($# <= max)) || _die "[$*] $# > $max (max)" || return 1
}

######################################################################################
### General Validation
######################################################################################

# Test if given value is an exit/return success
# Usage:    is_success <code>
# Status:   0 => true
is_success() {
    num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
    return $1
}

# Test if given value is an empty string or undefined
# Usage:    is_empty <var>
# Status:   0 => true
is_empty() {
    num_parameters --max 1 --die "Only one argument allowed, got: $#" -- "$@"
    [ -z "$1" ]
}

# Test if given value is an integer
# Usage:    is_integer <value>
# Status:   0 => is integer
is_integer() {
    num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
    [[ "$1" =~ ^-?[0-9]+$ ]]
}

# Test if given value is an float
# Usage:    is_float <value>
# Status:   0 => is float
is_float() {
    num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
    [[ "$1" =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]]
}

compare() { _deprecated "please use [[ ... ]] instead"; }

######################################################################################
### Sanitize
######################################################################################

# Trim leading whitespace or given character
# Usage:    trim_start <value> [<characters>]
# Stdout:   <string>
# See:      https://stackoverflow.com/a/3352015
trim_start() {
    local str="${1-}"
    local char="${2:-[:space:]}"
    echo "${str#"${str%%[!$char]*}"}"
}

# Trim trailing whitespace or given character
# Usage:    trim_end <value> [<characters>]
# Stdout:   <string>
# See:      https://stackoverflow.com/a/3352015
trim_end() {
    local str="${1:-}"
    local char="${2:-[:space:]}"
    echo "${str%"${str##*[!$char]}"}"
}

# Trim leading and trailing whitespace or given character
# Usage:    trim <value> [<characters>]
# Stdout:   <string>
# See:      https://stackoverflow.com/a/3352015
trim() {
    trim_end "$(trim_start "$1" "$2")" "$2"
}
