#!/usr/bin/env bash

# shellcheck disable=SC2154
load "$BASHLIB_HOME/tests/bats-support/load"
load "$BASHLIB_HOME/tests/bats-assert/load"
load "$BASHLIB_HOME/loader"
[ ! -e "$BASHLIB_HOME"/config/test-setup.conf ] || load "$BASHLIB_HOME"/config/test-setup.conf
