#!/usr/bin/env bash
# shellcheck source=base
source /dev/null
# shellcheck source=config/environment
source /dev/null
# shellcheck source=config/secrets
source /dev/null

# Module with divibib specific helpers.

[ -n "$MIDDLEWARE_SWAGGER_PASSWORD" ] || die "No MIDDLEWARE_SWAGGER_PASSWORD defined, please add this in the environment like .bashrc!"

######################################################################################
# Branding
######################################################################################

# divibib Logo with title text
#
# Usage:    logo <text>
# Output:   ASCII art logo including title
logo() {
    a=$'\033[30m'                # black bold
    b=$'\033[32m'                # green
    c=$'\033[42m\033[30m\033[1m' # green bg + black bold
    r=$'\033[0m'                 # reset
    u=$'\033[4m'                 # underline
    p="$(printf '%*s' $((($(tput cols) - 78) / 2)))"
    t="$(printf '%*s' $((($(tput cols) - ${#1}) / 2)))"
    echo
    echo "$p$a               ###   #                     #   $b###           #   ###"
    echo "$p$a               ###  ###                   ###  $b###          ###  ###"
    echo "$p$a               ###   #                     #   $b###           #   ###"
    echo "$p$a               ###                             $b###               ###"
    echo "$p$b ## $a      ########  ###  ###         ###  ###  $b########     ###  ########"
    echo "$p$b####$a    ###    ###  ###   ###       ###   ###  $b###    ###   ###  ###    ###"
    echo "$p$b ## $a   ###     ###  ###    ###     ###    ###  $b###     ###  ###  ###     ###"
    echo "$p$b    $a   ###     ###  ###     ###   ###     ###  $b###     ###  ###  ###     ###"
    echo "$p$b ## $a   ###     ###  ###      ### ###      ###  $b###     ###  ###  ###     ###"
    echo "$p$b####$a    ###    ###  ###       #####       ###  $b###    ###   ###  ###    ###"
    echo "$p$b ## $a      ########  ###        ###        ###  $b########     ###  ######## $r"
    echo "$p$b▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$r$c"
    echo "$t$1$r"
    echo "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$r"
    echo
}

######################################################################################
# Confluence
######################################################################################

# Get outage information
# Usage:    confluence_outage <search>
# Output:   <markdown>
confluence_outage() {
    local row office customer user
    row="$(confluence "$CONFLUENCE_OUTAGE" | sed 's/<\/tr>/<\/tr>\n/g;s/<tr>/\n<tr>/g' | grep '^<tr' | grep "$1" | head -1 | sed 's/<\/td>/<\/td>\n/g;s/<td>/\n<td>/g' | grep '^<td' || true)"
    test -n "$row" || return 0
    # shellcheck disable=SC2119
    office="$(echo "$row" | sed -n '1p' | html2md)"
    # shellcheck disable=SC2119
    customer="$(echo "$row" | sed -n '2p' | html2md)"
    # shellcheck disable=SC2119
    user="$(echo "$row" | sed -n '3p' | html2md)"
    echo -e "##### Auswirkungen für Endkunden\n\n$user\n\n##### Auswirkungen für Bibliotheken\n\n$customer\n\n##### Auswirkungen intern divibib/ekz\n\n$office"
}

######################################################################################
# Middleware
######################################################################################

backoffice_set() {
    # set message in backoffice <from> <to> <message>
    local start end
    # shellcheck disable=SC2119
    [[ "$1" =~ ^[0-9]+$ ]] &&
        start="$(date -d @"$1" -u +"%Y-%m-%dT%H:%M:%SZ" | urlencode)" ||
        start="$(date -d "$1" -u +"%Y-%m-%dT%H:%M:%SZ" | urlencode)"
    # shellcheck disable=SC2119
    [[ "$2" =~ ^[0-9]+$ ]] &&
        end="$(date -d @"$2" -u +"%Y-%m-%dT%H:%M:%SZ" | urlencode)" ||
        end="$(date -d "$2" -u +"%Y-%m-%dT%H:%M:%SZ" | urlencode)"
    local message
    # shellcheck disable=SC2119
    message="$(echo "${3:-Wartungsarbeiten}" | urlencode)"
    echo "Meldung im Backoffice: ${3:-Wartungsarbeiten}" >&2
    curl -u "swagger:$MIDDLEWARE_SWAGGER_PASSWORD" -X POST "http://user-application.service.user.dvb/v1/back-office/maintenance?validFrom=$start&validTo=$end&message=$message"
}
backoffice_unset() {
    echo "Meldung im Backoffice entfernt" >&2
    curl -u "swagger:$MIDDLEWARE_SWAGGER_PASSWORD" -X DELETE 'http://user-application.service.user.dvb/v1/back-office/maintenance'
}
