#!/usr/bin/env bash
# shellcheck disable=SC2034

# This module contains ANSI escape constants and helpers for color, cursor move, clear and more.

######################################################################################
# Color Configuration
######################################################################################

# Number of colors possible on terminal
COLORS=$(tput colors 2>/dev/null || echo 0)

# Reset all
CC_RESET=$'\e[0m'
# Reset text color
CC_RESET_FG=$'\e[39m'
# Reset background color
CC_RESET_BG=$'\e[49m'

# Set intensity to bold
CC_INTENSITY_BOLD=$'\e[1m'
# Set intensity to light
CC_INTENSITY_LIGHT=$'\e[2m'
# Set intensity back to normal
CC_INTENSITY_OFF=$'\e[22m'
# Set italic mode
CC_ITALIC=$'\e[3m'
# Unset italic mode
CC_ITALIC_OFF=$'\e[23m'
# Set underline mode
CC_UNDERLINE=$'\e[4m'
# Unset underline mode
CC_UNDERLINE_OFF=$'\e[24m'
# Set inverse mode (change text color and background color)
CC_INVERSE=$'\e[7m'
# Unset inverse mode
CC_INVERSE_OFF=$'\e[27m'
# Set strike through mode
CC_DASHED=$'\e[9m'
# Unset strike through mode
CC_DASHED_OFF=$'\e[29m'

# Set text color to black
CC_BLACK=$'\e[30m'
# Set text color to red
CC_RED=$'\e[31m'
# Set text color to green
CC_GREEN=$'\e[32m'
# Set text color to yellow
CC_YELLOW=$'\e[33m'
# Set text color to blue
CC_BLUE=$'\e[34m'
# Set text color to magenta
CC_MAGENTA=$'\e[35m'
# Set text color to cyan
CC_CYAN=$'\e[36m'
# Set text color to white
CC_WHITE=$'\e[37m'

# Set text color to bold black
CC_BLACK_BOLD=$'\e[90m'
# Set text color to bold red
CC_RED_BOLD=$'\e[91m'
# Set text color to bold green
CC_GREEN_BOLD=$'\e[92m'
# Set text color to bold yellow
CC_YELLOW_BOLD=$'\e[93m'
# Set text color to bold blue
CC_BLUE_BOLD=$'\e[94m'
# Set text color to bold magenta
CC_MAGENTA_BOLD=$'\e[95m'
# Set text color to bold cyan
CC_CYAN_BOLD=$'\e[96m'
# Set text color to gray
CC_WHITE_BOLD=$'\e[97m'

# Set background color to black
CC_BLACK_BG=$'\e[40m'
# Set background color to red
CC_RED_BG=$'\e[41m'
# Set background color to green
CC_GREEN_BG=$'\e[42m'
# Set background color to yellow
CC_YELLOW_BG=$'\e[43m'
# Set background color to blue
CC_BLUE_BG=$'\e[44m'
# Set background color to magenta
CC_MAGENTA_BG=$'\e[45m'
# Set background color to white
CC_CYAN_BG=$'\e[46m'

# Set background color to bold black
CC_BLACK_BOLD_BG=$'\e[100m'
# Set background color to bold red
CC_RED_BOLD_BG=$'\e[101m'
# Set background color to bold green
CC_GREEN_BOLD_BG=$'\e[102m'
# Set background color to bold yellow
CC_YELLOW_BOLD_BG=$'\e[103m'
# Set background color to bold blue
CC_BLUE_BOLD_BG=$'\e[104m'
# Set background color to bold magenta
CC_MAGENTA_BOLD_BG=$'\e[105m'
# Set background color to bold cyan
CC_CYAN_BOLD_BG=$'\e[106m'

# Get color code for text color number
# Usage:  color_256 <num>
# Output: <word> -> Code to set color
color_256() {
  is integer --name=arguments --max=1 --die -- $#
  local num
  num="$(is integer --name=num "$1" --sanitize --min=0 --max=255 --die --output)"
  # processing
  echo $'\e[38;5;'"$num"'m'
}

# Get color code for background color number
# Usage:  color_256_bg <num>
# Output: <word> -> Code to set color
color_256_bg() {
  is integer --name=arguments --max=1 --die -- $#
  local num
  num="$(is integer --name=num "$1" --sanitize --min=0 --max=255 --die --output)"
  # processing
  echo $'\e[48;5;'"$num"'m'
}

######################################################################################
# Context Specific Declaration
######################################################################################

# Set color for critical/disaster massages
CC_CRITICAL=$'\e[1;45m'
# Set color for error messages and failures
CC_ERROR=$'\e[1;31m'
# Set color for warnings
CC_WARN=$'\e[1;33m'
# Set color for highlighted information
CC_NOTICE=$'\e[1;34m'
# Set color for success messages
CC_OK=$'\e[1;32m'
# Set color for block headings
CC_HEADING=$'\e[44m'
# Set color for highlighted parts like table header
CC_INVERS=$'\e[7m'

######################################################################################
# Display
######################################################################################

# Show complete color table
#
# Usage:  color_table
# Output: human formatted Table in defined colors and styles
color_table() {
  is integer --name=arguments --max=0 --die -- $#
  echo "Basic Colors:"
  echo -e "\t${CC_BLACK}CC_BLACK\t${CC_BLACK_BOLD}CC_BLACK_BOLD\t${CC_BLACK_BG}CC_BLACK_BG\t${CC_BLACK_BOLD_BG}CC_BLACK_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_RED}CC_RED\t\t${CC_RED_BOLD}CC_RED_BOLD\t${CC_RED_BG}CC_RED_BG\t${CC_RED_BOLD_BG}CC_RED_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_GREEN}CC_GREEN\t${CC_GREEN_BOLD}CC_GREEN_BOLD\t${CC_GREEN_BG}CC_GREEN_BG\t${CC_GREEN_BOLD_BG}CC_GREEN_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_YELLOW}CC_YELLOW\t${CC_YELLOW_BOLD}CC_YELLOW_BOLD\t${CC_YELLOW_BG}CC_YELLOW_BG\t${CC_YELLOW_BOLD_BG}CC_YELLOW_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_BLUE}CC_BLUE\t\t${CC_BLUE_BOLD}CC_BLUE_BOLD\t${CC_BLUE_BG}CC_BLUE_BG\t${CC_BLUE_BOLD_BG}CC_BLUE_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_MAGENTA}CC_MAGENTA\t${CC_MAGENTA_BOLD}CC_MAGENTA_BOLD\t${CC_MAGENTA_BG}CC_MAGENTA_BG\t${CC_MAGENTA_BOLD_BG}CC_MAGENTA_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_CYAN}CC_CYAN\t\t${CC_CYAN_BOLD}CC_CYAN_BOLD\t${CC_CYAN_BG}CC_CYAN_BG\t${CC_CYAN_BOLD_BG}CC_CYAN_BOLD_BG${CC_RESET}"
  echo "Special Formats:"
  echo -e "\t${CC_INTENSITY_BOLD}CC_INTENSITY_BOLD\t${CC_INTENSITY_LIGHT}CC_INTENSITY_LIGHT${CC_RESET}"
  echo -e "\t${CC_ITALIC}CC_ITALIC${CC_RESET}"
  echo -e "\t${CC_UNDERLINE}CC_UNDERLINE${CC_RESET}"
  echo -e "\t${CC_DASHED}CC_DASHED${CC_RESET}"
  echo -e "\t${CC_INVERSE}CC_INVERSE${CC_RESET}"
  echo "256 Color palette:"
  local cols=15
  local rows=15
  for c in $(seq 0 "$cols"); do
    for r in $(seq 0 "$rows"); do
      num=$((r * cols + c))
      printf '%s' "\t$(color_256 "$num")FG $num"
    done
    echo ""
  done
  for c in $(seq 0 "$cols"); do
    for r in $(seq 0 "$rows"); do
      num=$((r * cols + c))
      printf '%s' "\t$(color_256_bg "$num")BG $num${CC_RESET}"
    done
    echo ""
  done
  echo "Context specific colors:"
  echo -e "\t${CC_CRITICAL}CC_CRITICAL${CC_RESET}"
  echo -e "\t${CC_ERROR}CC_ERROR${CC_RESET}"
  echo -e "\t${CC_WARN}CC_WARN${CC_RESET}"
  echo -e "\t${CC_NOTICE}CC_NOTICE${CC_RESET}"
  echo -e "\t${CC_OK}CC_OK${CC_RESET}"
  echo -e "\t${CC_HEADING}CC_HEADING${CC_RESET}"
  echo -e "\t${CC_INVERS}CC_INVERS${CC_RESET}"
}

######################################################################################
### Cursor Positioning
######################################################################################

# Cursor up 1 line
CURSOR_UP=$'\e[A'
#  Cursor down 1 line
CURSOR_DOWN=$'\e[B'
#  Cursor right 1 col
CURSOR_RIGHT=$'\e[C'
# Cursor left 1 col
CURSOR_LEFT=$'\e[D'
# Next Line (down, col 1)
CURSOR_NEXT=$'\e[E'
# Previous Line (up, col 1)
CURSOR_PREVIOUS=$'\e[F'
# Cursor to start of line
CURSOR_POS1=$'\e[G'
# Cursor to top-left
CURSOR_TOP=$'\e[H'
# Save cursor pos
CURSOR_STORE=$'\e[s'
# Restore cursor pos
CURSOR_RESTORE=$'\e[u'
# Show cursor
CURSOR_SHOW=$'\e[?25h'
# Hide cursor
CURSOR_HIDE=$'\e[?25l'

# Move cursor on console
#
# Possible directions are: up, down, right, left
# Move to col 1 with: next, previous
#
# Usage:    cursor <direction> <num>
#           cursor row <num>
#           cursor pos <row> <col>
cursor() {
  local num="${2:-1}" col="${3:-1}"
  is enum --name=direction --allow="up down right left row pos next previous" --die -- "$1"
  is integer --name=num --min=1 --die -- "$num"
  is integer --name=arguments --max=3 --die -- $#
  case "$1" in
  up) printf '\e[%sA' "$num" ;;
  down) printf '\e[%sB' "$num" ;;
  right) printf '\e[%sC' "$num" ;;
  left) printf '\e[%sD' "$num" ;;
  row) printf '\e[%sH' "$num" ;;
  pos)
    is integer --name=col --min=1 --die -- "$col"
    printf '\e[%s;%sH' "$num" "$col"
    ;;
  next) printf '\e[%sE' "$num" ;;
  previous) printf '\e[%sF' "$num" ;;
  esac
}

######################################################################################
### Screen Management
######################################################################################

# Change characters
#
# Usage:    character repeat <num> <character>
#           character delete <num>                  # delete character on the right side
#           character erase <num>                   # delete characters on the left side
character() {
  local num="$2"
  is enum --name=command --allow="repeat" --die -- "$1"
  is integer --name=num --min=1 --die -- "$num"
  case "$1" in
  repeat)
    is set --name=character --min=1 --die -- "$3"
    is length --name=character --min=1 --max=1 --die -- "$3"
    ((num == 1)) && printf '%s' "$3" || printf '%s\e[%sb' "$3" $((num - 1))
    ;;
  delete) printf '\e[%sP' "$num" ;;
  erase) printf '\e[%sX' "$num" ;;
  esac
}

# Reverse Index (up, scroll)
SCROLL_UP=$'\e[M'

# Clear entire screen
CLEAR_SCREEN=$'\e[2J'
# Clear from start of screen to cursor
CLEAR_UP=$'\e[1J'
# Clear from cursor to end of screen
CLEAR_DOWN=$'\e[0J'
# Clear from cursor to end of line
CLEAR_EOL=$'\e[0K'
# Clear from start of line to cursor
CLEAR_SOL=$'\e[1K'
# Clear entire line
CLEAR_LINE=$'\e[2K'

# restore screen
SCREEN_RESTORE=$'\e[?47l'
# save screen
SCREEN_SAVE=$'\e[?47h'

# Deprecated: Remove current line
# Use $CLEAR_LINE
#
# When printed to a terminal, it will erase everything from the current cursor position backward to the beginning of the line.
#
# Usage:    erase_line
erase_line() {
  _deprecated "Use $CLEAR_LINE" warn
  # shellcheck disable=SC2059
  printf "$CLEAR_LINE"
}
