#!/usr/bin/env bash

# Helper functions to work with arrays and associative arrays (hashes).

######################################################################################
### Array analyzing
######################################################################################

# Deprecated: Check if value is contained in array
# Usage:    contains <array-name> <match>
# Example:  x=( one two three )
#           contains x two && echo YES || echo NO
contains() {
    _deprecated "use array <array-name> has <value>" warn
    array "$1" has "$2"
}

# Array analyzation.
# Usage:    array <array-name> {has|indexof} [<value>]
array() {
    is integer --name=arguments --max=3 --die -- $#
    is set --name=array-name --die -- "$1"
    is enum --name=command --allow="has indexof" --die -- "$2"
    is set --name=value --die -- "$3"
    declare -n arr="$1"
    local cmd="$2"
    local value="$3"
    # processing
    case "$cmd" in
    has)
        for e in "${arr[@]}"; do
            [ ! "$e" = "$value" ] || return 0
        done
        return 1
        ;;
    indexof)
        for i in "${!arr[@]}"; do
            if [ "${arr[i]}" = "$value" ]; then
                echo "$i"
                return 0
            fi
        done
        return 1
        ;;
    esac
}

######################################################################################
### Join/Split array
######################################################################################

# Join array elements by delimiter.
# Convert all elements in array into a string separated by delimiter (default is `,`).
# Usage:    join <array-name> [<delimiter>]
# Output:   <string>
join() {
    is integer --name=arguments --max=2 --die -- $#
    is set --name=array-name --die -- "$1"
    local -n array=$1
    local sep="${2:-,}"
    # processing
    local joined="${array[0]}"
    for element in "${array[@]:1}"; do
        joined+="${sep}${element}"
    done
    echo "$joined"
}

# Splits string by delimiter into array
# The delimiter defaults to `,`.
# Usage:    split <string> <array-name> [<delimiter>]
# Output:   <string>
split() {
    is integer --name=arguments --max=3 --die -- $#
    is set --name=array-name --die -- "$2"
    local string="$1"
    local -n array=$2
    local sep="${3:-,}"
    # Set IFS to the separator and read into array
    IFS="$sep" read -ra array <<<"$string"
}

######################################################################################
### Hash
######################################################################################

# After declaring a variable as associative array: `declare -A <array-name>`
# Usage:    hash <array-name> {set|get|unset|has} <key> [<value>]
# Example:  hash cache set "my_name" "any value"
#           hash cache get "my_name"
#           hash cache has "my_name"
#           hash cache unset "my_name"
hash() {
    is integer --name=arguments --max=4 --die -- $#
    is set --name=array-name --die -- "$1"
    is enum --name=command --allow="set get unset has" --die -- "$2"
    is set --name=key --die -- "$3"
    declare -n arr="$1"
    local cmd="$2"
    local key="${3//[^a-zA-Z0-9_]/_}" # only a-zA-Z0-9_ allowed
    local value="$4"
    # processing
    case "$cmd" in
    set) arr["$key"]="$value" ;;
    get) echo "${arr[$key]}" ;;
    unset) unset 'arr[$key]' ;;
    has) [[ -v arr[$key] ]] ;;
    esac
}
