#!/usr/bin/env bash

# Array helpers.

######################################################################################
### Array analyzing
######################################################################################

# Check if value is contained in array
# Usage:    contains <array-name> <match>
# Example:  x=( one two three )
#           contains x two && echo YES || echo NO
contains() {
    local -n array=$1
    local value=$2
    local e
    for e in "${array[@]}"; do
        [[ "$e" != "$value" ]] || return 0
    done
    return 1
}

######################################################################################
### Join/Split array
######################################################################################

# Join array elements by delimiter.
# Convert all elements in array into a string separated by delimiter (default is `,`).
# Usage:    join <array-name> [<delimiter>]
# Output:   <string>
join() {
    local -n array=$1
    local sep="${2:-,}"
    local joined="${array[0]}"
    for element in "${array[@]:1}"; do
        joined+="${sep}${element}"
    done
    echo "$joined"
}

# Splits string by delimiter into array
# The delimiter defaults to `,`.
# Usage:    split <string> <array-name> [<delimiter>]
# Output:   <string>
split() {
    local string="$1"
    local -n array=$2
    local sep="${3:-,}"
    # Set IFS to the separator and read into array
    IFS="$sep" read -ra array <<<"$string"
}

######################################################################################
### Hash
######################################################################################

# After declaring a variable as associative array: `declare -A <arrax-name>`
# Usage:    hash <array-name> {set|get|unset|has} <key> [<value>]
# Example:  hash cache set "myname" "any value"
#           hash cache get "myname"
#           hash cache has "myname"
#           hash cache unset "myname"
hash() {
    num_parameters --min 3 --max 4 --die "Hash needs two to three parameters: Usage hash <array-name> <cmd> <key> [<value>]" "$@"
    declare -n arr="$1"
    local cmd=$2
    local key="${3//[^a-zA-Z0-9_]/_}" # only a-zA-Z0-9_ allowed
    local value=$4
    case "$cmd" in
    set) arr["$key"]="$value" ;;
    get) echo "${arr[$key]}" ;;
    unset) unset 'arr[$key]' ;;
    has) [[ -v arr[$key] ]] ;;
    *) die "Usage: hash <array_name> {set|get|unset|has} <key> [value]" ;;
    esac
}
