#!/usr/bin/env bash

# Helper functions to work with arrays and associative arrays (hashes).

######################################################################################
### Array analyzing
######################################################################################

# Deprecated: Check if value is contained in array
# Use array <array-name> has <value>
contains() {
    _deprecated "use array <array-name> has <value>"
}

# Array analyzation.
#
# This can be used for easy array access functions. The array itself is not given by value but by name, so no `$` before the name.
#
# The following commands ar<string-input>e possible:
#
# - `has` to check if a value could be found within the array
# - `indexof` will return the index number of the value if found
#
# Usage:        array <array-name> <command> [<value>]
# Variables:    <array-name> as basis to work on
# Output:       - <value> for `has`
#               - <index-num> for `indexof`
# Return:       0 if ok, 1 if entry not found
array() {
    is integer --name=arguments --max=3 --die -- $#
    is set --name=array-name --die -- "$1"
    is enum --name=command --allow="has indexof" --die -- "$2"
    is set --name=value --die -- "$3"
    declare -n arr="$1"
    local cmd="$2"
    local value="$3"
    # processing
    case "$cmd" in
    has)
        for e in "${arr[@]}"; do
            [ ! "$e" = "$value" ] || return 0
        done
        return 1
        ;;
    indexof)
        for i in "${!arr[@]}"; do
            if [ "${arr[i]}" = "$value" ]; then
                printf '%s' "$i"
                return 0
            fi
        done
        return 1
        ;;
    esac
}

######################################################################################
### Join/Split array
######################################################################################

# Join array elements by delimiter
#
# Convert all elements in array into a string separated by delimiter (default is `,`).
#
# Usage:        join <array-name> [<delimiter>]
# Variables:    <array-name> to read values to join
# Output:       <string>
join() {
    is integer --name=arguments --max=2 --die -- $#
    is set --name=array-name --die -- "$1"
    local -n array=$1
    local sep="${2:-,}"
    # processing
    local joined="${array[0]}"
    for element in "${array[@]:1}"; do
        joined+="${sep}${element}"
    done
    printf '%s' "$joined"
}

# Splits string by delimiter into array
# The delimiter defaults to `,`.
#
# Usage:        split <string> <array-name> [<delimiter>]
# Variables:    <array-name> to store values
split() {
    is integer --name=arguments --max=3 --die -- $#
    is set --name=array-name --die -- "$2"
    local string="$1"
    local -n array=$2
    local sep="${3:-,}"
    # Set IFS to the separator and read into array
    IFS="$sep" read -ra array <<<"$string"
}

######################################################################################
### Hash
######################################################################################

# Methods to work with assoziative arrays (hashes)
#
# After declaring a variable as associative array: `declare -A <array-name>` this commands may help working with it. The array itself is not given by value but by name, so no `$` before the name.
#
# As an assoziative array not allows all characters for the key, the key can be:
#
# - simple (default) - unsupported characters will be replaced by _
# - base64 - encode the whole key as base64
#
# The following commands ar<string-input>e possible:
#
# - `set` add or update a `<value>` in the index
# - `get` get the stored value for `<key>`
# - `unset` remove `<key>` from hash
# - `has` check if the `<key>` is set
# - `contains` check if the given `<value>` is found in any key
#
# Usage:        hash <array-name> <command> [<key>] [<value>]
# Options:      -k, --key-format={base64|simple} # how to convert key because of special characters
# Variables:    <array-name> as basis to work on
# Output:       <value> for `get`
# Error:        1 if not found for `get` or `has`
# Example:      - `hash cache set "my_name" "any value"`
#               - `hash cache get "my_name"`
#               - `hash cache has "my_name"`
#               - `hash cache unset "my_name"`
hash() {
    # parameter parsing
    local keyFormat="simple"
    eval set -- "$(option_parse $'k key-format +' "$@")"
    while true; do
        case "$1" in
        -k | --key-format) keyFormat="$(check enum --allow="simple base64" -- "$2")" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is integer --name=arguments --max=4 --die -- $#
    is set --name=array-name --die -- "$1"
    is enum --name=command --allow="set get unset has contains" --die -- "$2"
    declare -n arr="$1"
    local cmd="$2" key value="$4"
    case $keyFormat in
    base64) key="$(base64 -w0 <<<"$3")" ;;
    simple) key="${3//[^a-zA-Z0-9_]/_}" ;;
    esac
    # processing
    case "$cmd" in
    set) is set --name=key --die -- "$3" && arr["$key"]="$value" ;;
    get) is set --name=key --die -- "$3" && printf '%s' "${arr["$key"]}" ;;
    unset) is set --name=key --die -- "$3" && unset 'arr[$key]' ;;
    has) is set --name=key --die -- "$3" && [[ -v arr["$key"] ]] ;;
    contains)
        is set --name=value --die -- "$3"
        for key in "${!arr[@]}"; do
            [[ "${arr["$key"]}" != "$3" ]] || return 0
        done
        return 1
        ;;
    esac
}
