#!/usr/bin/env bash
# shellcheck disable=SC2034

# This module contains color specifications to be used in console output.

######################################################################################
# Color Configuration
######################################################################################

# Number of colors possible on terminal
COLORS=$(tput colors 2>/dev/null || echo 0)

# Reset all
CC_RESET=$'\033[0m'
# Reset text color
CC_RESET_FG=$'\033[39m'
# Reset background color
CC_RESET_BG=$'\033[49m'

# Set intensity to bold
CC_INTENSITY_BOLD=$'\033[1m'
# Set intensity to light
CC_INTENSITY_LIGHT=$'\033[2m'
# Set intensity back to normal
CC_INTENSITY_OFF=$'\033[22m'
# Set italic mode
CC_ITALIC=$'\033[3m'
# Unset italic mode
CC_ITALIC_OFF=$'\033[23m'
# Set underline mode
CC_UNDERLINE=$'\033[4m'
# Unset underline mode
CC_UNDERLINE_OFF=$'\033[24m'
# Set inverse mode (change text color and background color)
CC_INVERSE=$'\033[7m'
# Unset inverse mode
CC_INVERSE_OFF=$'\033[27m'
# Set strike through mode
CC_DASHED=$'\033[9m'
# Unset strike through mode
CC_DASHED_OFF=$'\033[29m'

# Set text color to black
CC_BLACK=$'\033[30m'
# Set text color to red
CC_RED=$'\033[31m'
# Set text color to green
CC_GREEN=$'\033[32m'
# Set text color to yellow
CC_YELLOW=$'\033[33m'
# Set text color to blue
CC_BLUE=$'\033[34m'
# Set text color to magenta
CC_MAGENTA=$'\033[35m'
# Set text color to cyan
CC_CYAN=$'\033[36m'
# Set text color to white
CC_WHITE=$'\033[37m'

# Set text color to bold black
CC_BLACK_BOLD=$'\033[90m'
# Set text color to bold red
CC_RED_BOLD=$'\033[91m'
# Set text color to bold green
CC_GREEN_BOLD=$'\033[92m'
# Set text color to bold yellow
CC_YELLOW_BOLD=$'\033[93m'
# Set text color to bold blue
CC_BLUE_BOLD=$'\033[94m'
# Set text color to bold magenta
CC_MAGENTA_BOLD=$'\033[95m'
# Set text color to bold cyan
CC_CYAN_BOLD=$'\033[96m'
# Set text color to gray
CC_WHITE_BOLD=$'\033[97m'

# Set background color to black
CC_BLACK_BG=$'\033[40m'
# Set background color to red
CC_RED_BG=$'\033[41m'
# Set background color to green
CC_GREEN_BG=$'\033[42m'
# Set background color to yellow
CC_YELLOW_BG=$'\033[43m'
# Set background color to blue
CC_BLUE_BG=$'\033[44m'
# Set background color to magenta
CC_MAGENTA_BG=$'\033[45m'
# Set background color to white
CC_CYAN_BG=$'\033[46m'

# Set background color to bold black
CC_BLACK_BOLD_BG=$'\033[100m'
# Set background color to bold red
CC_RED_BOLD_BG=$'\033[101m'
# Set background color to bold green
CC_GREEN_BOLD_BG=$'\033[102m'
# Set background color to bold yellow
CC_YELLOW_BOLD_BG=$'\033[103m'
# Set background color to bold blue
CC_BLUE_BOLD_BG=$'\033[104m'
# Set background color to bold magenta
CC_MAGENTA_BOLD_BG=$'\033[105m'
# Set background color to bold cyan
CC_CYAN_BOLD_BG=$'\033[106m'

# Get color code for text color number
# Usage:  color_256 <num>
# Stdout: <word> -> Code to set color
color_256() {
  is integer --name=arguments --max=1 --die -- $#
  local num
  num="$(check integer --name=num "$1" --sanitize --min=0 --max=255 --die)"
  # processing
  echo $'\033[38;5;'"$num"'m'
}

# Get color code for background color number
# Usage:  color_256_bg <num>
# Stdout: <word> -> Code to set color
color_256_bg() {
  is integer --name=arguments --max=1 --die -- $#
  local num
  num="$(check integer --name=num "$1" --sanitize --min=0 --max=255 --die)"
  # processing
  echo $'\033[48;5;'"$num"'m'
}

######################################################################################
# Context Specific Declaration
######################################################################################

# Set color for critical/disaster massages
CC_CRITICAL=$'\033[1;45m'
# Set color for error messages and failures
CC_ERROR=$'\033[1;31m'
# Set color for warnings
CC_WARN=$'\033[1;33m'
# Set color for highlighted information
CC_NOTICE=$'\033[1;34m'
# Set color for success messages
CC_OK=$'\033[1;32m'
# Set color for block headings
CC_HEADING=$'\033[44m'
# Set color for highlighted parts like table header
CC_INVERS=$'\033[7m'

######################################################################################
# Display
######################################################################################

# Show complete color table
# Usage:  color_table
# Stdout: human formatted Table in defined colors and styles
color_table() {
  is integer --name=arguments --max=0 --die -- $#
  echo "Basic Colors:"
  echo -e "\t${CC_BLACK}CC_BLACK\t${CC_BLACK_BOLD}CC_BLACK_BOLD\t${CC_BLACK_BG}CC_BLACK_BG\t${CC_BLACK_BOLD_BG}CC_BLACK_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_RED}CC_RED\t\t${CC_RED_BOLD}CC_RED_BOLD\t${CC_RED_BG}CC_RED_BG\t${CC_RED_BOLD_BG}CC_RED_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_GREEN}CC_GREEN\t${CC_GREEN_BOLD}CC_GREEN_BOLD\t${CC_GREEN_BG}CC_GREEN_BG\t${CC_GREEN_BOLD_BG}CC_GREEN_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_YELLOW}CC_YELLOW\t${CC_YELLOW_BOLD}CC_YELLOW_BOLD\t${CC_YELLOW_BG}CC_YELLOW_BG\t${CC_YELLOW_BOLD_BG}CC_YELLOW_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_BLUE}CC_BLUE\t\t${CC_BLUE_BOLD}CC_BLUE_BOLD\t${CC_BLUE_BG}CC_BLUE_BG\t${CC_BLUE_BOLD_BG}CC_BLUE_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_MAGENTA}CC_MAGENTA\t${CC_MAGENTA_BOLD}CC_MAGENTA_BOLD\t${CC_MAGENTA_BG}CC_MAGENTA_BG\t${CC_MAGENTA_BOLD_BG}CC_MAGENTA_BOLD_BG${CC_RESET}"
  echo -e "\t${CC_CYAN}CC_CYAN\t\t${CC_CYAN_BOLD}CC_CYAN_BOLD\t${CC_CYAN_BG}CC_CYAN_BG\t${CC_CYAN_BOLD_BG}CC_CYAN_BOLD_BG${CC_RESET}"
  echo "Special Formats:"
  echo -e "\t${CC_INTENSITY_BOLD}CC_INTENSITY_BOLD\t${CC_INTENSITY_LIGHT}CC_INTENSITY_LIGHT${CC_RESET}"
  echo -e "\t${CC_ITALIC}CC_ITALIC${CC_RESET}"
  echo -e "\t${CC_UNDERLINE}CC_UNDERLINE${CC_RESET}"
  echo -e "\t${CC_DASHED}CC_DASHED${CC_RESET}"
  echo -e "\t${CC_INVERSE}CC_INVERSE${CC_RESET}"
  echo "256 Color palette:"
  local cols=15
  local rows=15
  for c in $(seq 0 "$cols"); do
    for r in $(seq 0 "$rows"); do
      num=$((r * cols + c))
      echo -ne "\t$(color_256 "$num")FG $num"
    done
    echo ""
  done
  for c in $(seq 0 "$cols"); do
    for r in $(seq 0 "$rows"); do
      num=$((r * cols + c))
      echo -ne "\t$(color_256_bg "$num")BG $num${CC_RESET}"
    done
    echo ""
  done
  echo "Context specific colors:"
  echo -e "\t${CC_CRITICAL}CC_CRITICAL${CC_RESET}"
  echo -e "\t${CC_ERROR}CC_ERROR${CC_RESET}"
  echo -e "\t${CC_WARN}CC_WARN${CC_RESET}"
  echo -e "\t${CC_NOTICE}CC_NOTICE${CC_RESET}"
  echo -e "\t${CC_OK}CC_OK${CC_RESET}"
  echo -e "\t${CC_HEADING}CC_HEADING${CC_RESET}"
  echo -e "\t${CC_INVERS}CC_INVERS${CC_RESET}"
}
#color_table
