#!/usr/bin/env bash
# shellcheck disable=SC2034

# The core configuration which is needed for the core functions.

######################################################################################
### Script Base Setup
######################################################################################

# Set in the environment to where the BASHLIB is installed
BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}

# Set to level 0..9 (higher is more verbose) or specify function patterns as comma separated list
DEBUG=${DEBUG-}
