#!/usr/bin/env bash
# shellcheck source=full
source /dev/null

# The core configuration which is needed for the core functions.

######################################################################################
### Script Base Setup
######################################################################################

set -eE         # exit on uncatched failure
set -o pipefail # fail if any command in a pipeline fails
#set -u # exit on use of unset variables

# Set in the environment to where the BASHLIB is installed
BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}

######################################################################################
### Colors
######################################################################################

# Reset all
CC_RESET=$'\033[0m'
# Set color for critical/disaster massages used by @die
CC_CRITICAL=$'\033[1;45m'
