#!/usr/bin/env bash
# shellcheck source=full
source /dev/null

# The core functions contains essential parts which may also be used while loading the library.

######################################################################################
### Gettext setup
######################################################################################

export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
# shellcheck source=/usr/bin/gettext.sh
source gettext.sh

######################################################################################
### Base functions
######################################################################################

# Collect string from stdin (no parameters) or concatenate the parameters
# This can be used to make functions which you can feed with one or multiple parameters as well as through a pipe.
# See also: @input_args @input_lines
# Usage:    input "$@" | ....
#           text="$(input "$@")"
# Output:   <string-input> or
#           <string-params> separated by spaces
input() {
    test -p /dev/stdin && test $# -eq 0 && cat - || echo "$*"
}

# Collect string from stdin (not more than defined parameters) or concatenate the parameters
# This can be used to make functions which you can feed with one or multiple parameters as well as through a pipe.
# But instead of the @input this will allow the first <num> additional parameters which will be not slurped in.
# Usage:    input_args <num> "$@" | ....
#           text="$(input <num> "$@")"
# Output:   <string-input> or
#           <string-params> separated by spaces
input_args() {
    local num=${1-}
    local start=$((num + 2))
    [ -n "$num" ] || die "No <num> argument in call to input_args!"
    [ "$num" -gt 0 ] || die "<num>=$num argument is not a valid number!"
    test -p /dev/stdin && cat - || echo "${@:$start}"
}

# Collect string from stdin (no parameters) or parameters each as a line
# The same as @input for piped content but the arguments will not be joined by spaces but read as separate lines.
# Usage:    input_lines "$@" | ....
#           text="$(input_lines "$@")"
# Output:   <string-input> or
#           <string-params> separated by newlines
input_lines() {
    if [ -p /dev/stdin ] && [ -z "${1-}" ]; then
        cat -
    else
        for arg in "$@"; do echo "$arg"; done
    fi
}

# Output error message and exit
# Usage:    die <message>
#           <message> | die
# Error:    <message>
# Return:   always 1 and try to exit script with status 1
die() {
    echo -e "${CC_CRITICAL}$(input "$@")${CC_RESET}" >&2
    # kill -s TERM "$PPID" # forcibly terminite the parent
    exit 1
}

# Set or add an additional trap without overwriting existing ones
# This is done by adding the new code as additional command before the existing ones if the trap is already set.
# Usage:    trap_add <code> <signal>
trap_add() {
    local new="$1"
    local sig="$2"
    local old
    old="$(trap -p "$sig" | awk -F"'" '{print $2}')"
    if [[ -n "$old" ]]; then
        # shellcheck disable=SC2064
        trap "$new; $old" "$sig"
    else
        # shellcheck disable=SC2064
        trap "$new" "$sig"
    fi
}

# Remove a specific trap
# Not the whole trap is removed, but only the given code.
# Usage:    trap_remove
trap_remove() {
    local remove="$1"
    local sig="$2"
    local current new
    current="$(trap -p "$sig" | awk -F"'" '{print $2}')"
    # shellcheck disable=SC2001
    new="$(echo "$current" | sed "s#;* *$remove##")"
    # shellcheck disable=SC2064
    trap "$new" "$sig"
}

# Make a temporary file, which is recognizable
# As the same invocation from the same program will get the same file it can be called multiple times.
# The file will be conducted out of the program name and the given <identifier>.
# You should remove this file by yourself if no longer needed. The files will be available in `/tmp`` folder for about 3 unused days and in memory till the next reboot.
# Usage:    mktemp [<identifier>]       # use default temp if no identifier given
# Options:  -d, --directory             # to make a directorty instead of a file
#           -m, --memory                # use shared memory
#           -e, --extension <string>    # to specify file extension (better readability)
#           -p, --path <base-dir>       # folder under which to create file
#           -r, --random                # add a random (numeric) part to the identifier
# Output:   <path>
mktemp() {
    # parameter parsing
    eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -' "$@")"
    local dir ext result rand
    local path=${TMPDIR:-/tmp}
    while true; do
        case "$1" in
        -d | --directory)
            dir=1
            shift
            ;;
        -e | --extension)
            ext=".$2"
            shift 2
            ;;
        -m | --memory)
            path="/dev/shm"
            shift
            ;;
        -p | --path)
            path="$2"
            shift 2
            ;;
        -r | --random)
            rand=$RANDOM
            shift
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    result="$path/$(basename "$0")_$1$rand$ext"
    if [ -n "$rand" ]; then
        # loop while already exists
        while [ -e "$result" ]; do
            result="$path/$(basename "$0")_$1$RANDOM$ext"
        done
    fi
    if [ -n "$dir" ]; then
        mkdir -p "$result"
    else
        touch "$result"
    fi
    echo "$result"
}

######################################################################################
### Help and option handling
######################################################################################

# Parse arguments based on given specification
# This will parse the given options into a standardized form and validate them against the given specification.
# Options can be given in different forms: `-a 45`, `-a45`, `--age 45`, `--age=45` are all equal.
# Also multiple short options can be put together with only the last may need a value.
# Usage:        eval set -- "$(option_parse <spec> "$@")"
#               <spec> lines := <short-letter>|- <long-word> <type>|- <description>
# Output:       parsed options <string>
# Example:      OPTIONS="
#               n name  string  Name of Birthday Person
#               a age   int     Age in years
#               h help  -       Show Help Page"
#               option_parse "$OPTIONS" "$@"
option_parse() {
    local opt name type desc short="" long=""
    # read spec lines
    while IFS=$' \t\n' read -r opt name type desc; do
        [[ "$opt" =~ ^# ]] && continue # skip comments
        [[ -z "$opt" ]] && continue    # skip empty lines
        if [ ! "$type" = "-" ]; then
            [ "${opt}" = "-" ] || short+="${opt}:"
            long+="${name}:,"
        else
            [ "${opt}" = "-" ] || short+="${opt}"
            long+="${name},"
        fi
    done <<<"$1"
    shift
    # parse
    getopt -o "$short" --long "$long" -n "$0" -- "$@"
}

# Print help for options defined in options specification
# This is mainly used by the @help output.
# Usage:        option_help <spec>
#               <spec> lines := <short-letter>|- <long-word> <type>|- <description>
# Output:       List of options for help output
option_help() {
    declare opt name type desc
    declare -A opt_descriptions
    declare -A opt_type
    declare -A opt_short
    # read spec lines
    while read -r opt name type desc; do
        [[ "$opt" =~ ^# ]] && continue # skip comments
        [[ -z "$opt" ]] && continue    # skip empty lines
        opt_descriptions[$name]="$desc"
        opt_type[$name]=$type
        opt_short[$name]=$opt
    done <<<"$1"
    echo "Optionen:"
    for name in "${!opt_descriptions[@]}"; do
        local type_text=""
        local short_text=""
        if [ ! "${opt_type[$name]}" = "-" ]; then
            type_text=" <${opt_type[$name]}>"
        fi
        if [[ ! "${opt_short[$name]}" = "-" ]]; then
            short_text="-${opt_short[$name]}$type_text, "
        fi
        printf "  %-40s %s\n" "$short_text--$name$type_text" "${opt_descriptions[$name]}"
    done
}
