#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# The internal functions contains parts which are only needed within the bashlib but not outside.

######################################################################################
### Gettext setup
######################################################################################

export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
# shellcheck source=/usr/bin/gettext.sh
source gettext.sh

######################################################################################
### Internal functions
######################################################################################

# Define the calling function as deprecated and output this message if used
# Usage:    _deprecated
# Error:    DEPRECATED: ask_input at task_find in /home/alex/bin/dvb/cleanup:206 please use ask string
#           > _stacktrace          at die() in /home/alex/dvb/bash-lib/core/misc:59
#           > _stacktrace          at _deprecated() in /home/alex/dvb/bash-lib/core/internal:23
#           > _stacktrace          at ask_input() in /home/alex/dvb/bash-lib/module/input:150
#           > _stacktrace          at task_find() in /home/alex/bin/dvb/cleanup:206
#           > _stacktrace          at tasks() in /home/alex/dvb/bash-lib/module/input:451
#           > _stacktrace          at main() in /home/alex/bin/dvb/cleanup:364
# Return:   always 1 and try to exit script with status 1
_deprecated() {
    IFS=$' \t\n' read -r line func file <<<"$(caller 1)"
    die "DEPRECATED: ${FUNCNAME[1]} at ${func} in ${file}:${line} $1"
}

# Display stack trace from called position upwards
# Usage:    _stacktrace
# Output:   Debug Level 5:
#           > _stacktrace          at die() in /home/alex/dvb/bash-lib/core/misc:59
#           > _stacktrace          at _deprecated() in /home/alex/dvb/bash-lib/core/internal:23
#           > _stacktrace          at ask_input() in /home/alex/dvb/bash-lib/module/input:150
#           > _stacktrace          at task_find() in /home/alex/bin/dvb/cleanup:206
#           > _stacktrace          at tasks() in /home/alex/dvb/bash-lib/module/input:451
#           > _stacktrace          at main() in /home/alex/bin/dvb/cleanup:364
_stacktrace() {
    local level="${1:-5}"
    #debug "$level" "Stack trace:"
    local i
    # Skip this function itself and start from the caller
    for ((i = 1; i < ${#FUNCNAME[@]}; i++)); do
        local func="${FUNCNAME[i]}"
        local line="${BASH_LINENO[i - 1]}"
        local src="${BASH_SOURCE[i]}"
        printf "at %s() in %s:%s\n" "$func" "$src" "$line" | debug "$level"
    done
}
