#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# The internal functions contains parts which are only needed within the bashlib but not outside.

######################################################################################
### Gettext setup
######################################################################################

export TEXTDOMAIN=bashlib
export TEXTDOMAINDIR=$BASHLIB_HOME/locale
# shellcheck source=/usr/bin/gettext.sh
source gettext.sh

######################################################################################
### Internal functions
######################################################################################

# Define the calling function as deprecated and output this message if used
# Usage:    _deprecated [<warn>]   if `<warn>` is set go on, else die
# Error:    DEPRECATED: ask_input at task_find in /home/alex/bin/dvb/cleanup:206 please use ask string
#           > _stacktrace          at die() in /home/alex/dvb/bash-lib/core/misc:59
#           > _stacktrace          at _deprecated() in /home/alex/dvb/bash-lib/core/internal:23
#           > _stacktrace          at ask_input() in /home/alex/dvb/bash-lib/module/input:150
#           > _stacktrace          at task_find() in /home/alex/bin/dvb/cleanup:206
#           > _stacktrace          at tasks() in /home/alex/dvb/bash-lib/module/input:451
#           > _stacktrace          at main() in /home/alex/bin/dvb/cleanup:364
# Return:   1 and try to exit script with status 1 if not in warn state
_deprecated() {
    IFS=$' \t\n' read -r line func file <<<"$(caller 1)"
    local message="DEPRECATED: ${FUNCNAME[1]} at ${func} in ${file}:${line} $1"
    # shellcheck disable=SC2015
    [ -n "$2" ] && echo -e "${CC_WARN}$message (update it)${CC_RESET}" >&2 || die "$message"
}

# Display stack trace from called position upwards
# Usage:    _stacktrace [<trap-flag>]
# Output:   Debug Level 5:
#           > _stacktrace          /home/alex/dvb/bash-lib/core/validator:76 (is)
#           > _stacktrace            74: -n | --name) name="$2" && shift 2 ;;
#           > _stacktrace            75: -s | --sanitize) sanitize=1 && shift ;;
#           > _stacktrace            76: --min) [[ "$2" =~ ^-?[0-9]+$ ]] && min="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs integer")" min)" ;;
#           > _stacktrace            77: --max) [[ "$2" =~ ^-?[0-9]+$ ]] && max="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs integer")" max)" ;;
#           > _stacktrace            78: --) shift && break ;;
#           > _stacktrace          scripts/_test:35 (main)
#           > _stacktrace            33: #false
#           > _stacktrace            34:
#           > _stacktrace            35: is integer 5.27k --sanitize --min=o
# shellcheck disable=SC2120
_stacktrace() {
    local frame=1 line func src bestChoice
    if [ -z "$1" ] && ((DEBUG < 5)); then bestChoice=1; fi
    while read -r line func src < <(caller "$frame" || true); do
        if [ -n "$bestChoice" ] && [[ ! "$func" =~ ^is$|^check$ ]]; then
            printf "Possibly called at %s:%d (%s)\n" "$src" "$line" "$func" | warn >&2
            bestChoice=""
        fi
        # shellcheck disable=SC2015
        printf "\033[1m%s:%d (%s)\n" "$src" "$line" "$func" | ([ -n "$1" ] && ( ((frame == 1)) && warn || notice) || debug 5)
        # shellcheck disable=SC2015
        awk -v n="$line" '
            NR>=n-2 && NR<=n+2 {
                gsub(/^[ \t]+/, "", $0)  # Remove leading spaces/tabs
                printf "%4d: %s\n", NR, $0
                if(NR==n+2) exit
            }' "$src" | sed "/$line:/s/^/"$'\033[1m'"/;/$line:/s/$/"$'\033[22m'"/" | ([ -n "$1" ] && info || debug 6)
        ((frame++)) || true
    done
}
