#!/usr/bin/env bash

# The base language file, to support another language copy this to `config/lang.LL` and translate the values.

######################################################################################
### Core function
######################################################################################

# Translate: Unrecognized option given
LL_OPTIONS_UNRECOGNIZED="Unrecognized option:"
