#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# The core functions contains essential parts which may also be used while loading the library.

######################################################################################
### Debug and Error Handling
######################################################################################

# Write message to STDERR if in DEBUG mode else do nothing
# Debug can support multiple levels starting from 1 upwards to be more verbose. This will only be shown if environment variable `DEBUG` is the same number or higher. Or if the `DEBUG` variable includes the function name. Multiple lines will be printed seperately to have the function name prefix at the start of each.
# Usage:    debug [<num>] <message>
#           <message> | debug [<num>]
#               <num> := [1-9]      # (default 1) higher to only show in more verbose call
#               <message>           # the message text
# Globals:  $DEBUG - if unset nothing will be printed
#           $DEBUG=<num> - only print messages with same or lower numeric level
#           $DEBUG=<func>,... - only print if the function is matched
#           $DEBUG=9 - to output all
# Stderr:   > <func>           <message>      # color: gray
debug() {
    # get level and function
    local level=1 func
    if [[ "$1" =~ ^-?[0-9]+$ ]]; then
        level="$1"
        shift
    fi
    #IFS=$' \t\n' read -r _ pfunc _ <<<"$(caller 1)" # enable to show two levels
    IFS=$' \t\n' read -r _ func _ <<<"$(caller 0)"
    [ -z "$pfunc" ] || [ "$pfunc" = "$func" ] || func="$pfunc/$func"
    # collect text
    local text
    text="$(input "$@")"
    test -n "$text" || return 0
    # decide to print
    [[ -n "$DEBUG" ]] || return 0
    if [[ "$DEBUG" =~ ^-?[0-9]+$ ]]; then
        # numeric => decide on level
        ((level <= DEBUG)) || return 0
    else
        # string => check for match
        [[ "$func" =~ .*(${DEBUG//, /|}) ]] || return 0
    fi
    # print each line separately
    while IFS= read -r line; do
        printf "$CC_BLACK> %-20s %s$CC_RESET\n" "$func" "$line" >&2
    done <<<"$text"
}
debug "Running in DEBUG=${DEBUG-} mode!"

# Output error message and exit
# Usage:    die <message>
#           <message> | die
# Error:    # Example if called for deprecated call:
#           DEPRECATED: ask_input at task_find in /home/alex/bin/dvb/cleanup:206 please use ask string
#           > _stacktrace          at die() in /home/alex/dvb/bash-lib/core/misc:59
#           > _stacktrace          at _deprecated() in /home/alex/dvb/bash-lib/core/internal:23
#           > _stacktrace          at ask_input() in /home/alex/dvb/bash-lib/module/input:150
#           > _stacktrace          at task_find() in /home/alex/bin/dvb/cleanup:206
#           > _stacktrace          at tasks() in /home/alex/dvb/bash-lib/module/input:451
#           > _stacktrace          at main() in /home/alex/bin/dvb/cleanup:364
# Return:   always 1 and try to exit script with status 1
die() {
    echo -e "${CC_CRITICAL}$(input "$@")${CC_RESET}" >&2
    _stacktrace
    # kill -s TERM "$PPID" # forcibly terminite the parent
    exit 1
}
[ -n "${BASH_VERSION:-}" ] || die "No bash CLI! This can only be run under bash"

# Set or add an additional trap without overwriting existing ones
# This is done by adding the new code as additional command before the existing ones if the trap is already set.
# Usage:    trap_add <code> <signal>
trap_add() {
    local new="$1"
    local sig="$2"
    local old
    old="$(trap -p "$sig" | awk -F"'" '{print $2}')"
    if [[ -n "$old" ]]; then
        # shellcheck disable=SC2064
        trap "$new; $old" "$sig"
    else
        # shellcheck disable=SC2064
        trap "$new" "$sig"
    fi
}

# Remove a specific trap
# Not the whole trap is removed, but only the given code.
# Usage:    trap_remove <cmd> <signal>
trap_remove() {
    local remove="$1"
    local sig="$2"
    local current new
    debug 3 "remove $remove from $sig"
    current="$(trap -p "$sig" | awk -F"'" '{print $2}')"
    # shellcheck disable=SC2001
    new="$(echo "$current" | sed "s#;* *$remove##")"
    # shellcheck disable=SC2064
    trap "$new" "$sig"
}

######################################################################################
### Temporary Files
######################################################################################

# Make a temporary file, which is recognizable
# As the same invocation from the same program will get the same file it can be called multiple times, as long as no `--random` is set.
# The file will be conducted out of the program name and the given <identifier>.
# You should remove this file by yourself if no longer needed. The files will be available in `/tmp` folder for about 3 unused days (managed by your os) and in memory till the next reboot.
# Usage:    mktemp [<identifier>]       # use default temp if no identifier given
# Options:  -d, --directory             # to make a directorty instead of a file
#           -m, --memory                # use shared memory
#           -e, --extension <string>    # to specify file extension (better readability)
#           -p, --path <base-dir>       # folder under which to create file
#           -r, --random                # add a random (numeric) part to the identifier
#           -T, --ttl <duration>        # duration to remove file again as seconds or duration @duration_format
# Output:   <path>
#           Debug: path and if it is created
#           Debug: remove after TTL
mktemp() {
    # parameter parsing
    eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -\nT ttl +' "$@")"
    local dir ext result rand
    local path=${TMPDIR:-/tmp}
    while true; do
        case "$1" in
        -d | --directory)
            dir=1
            shift
            ;;
        -e | --extension)
            ext=".$2"
            shift 2
            ;;
        -m | --memory)
            path="/dev/shm"
            shift
            ;;
        -p | --path)
            path="$2"
            shift 2
            ;;
        -r | --random)
            rand=$RANDOM
            shift
            ;;
        -T | --ttl)
            ttl="$(duration_format seconds "$2")"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) shift ;; # ignore
        esac
    done
    # processing
    result="$path/$(basename "$0")_$1$rand$ext"
    if [ -n "$rand" ]; then
        # loop while already exists
        while [ -e "$result" ]; do
            result="$path/$(basename "$0")_$1$RANDOM$ext"
        done
    fi
    if [ -e "$result" ]; then
        debug "already exists $result"
    else
        if [ -n "$dir" ]; then
            debug "create dir $result"
            mkdir -p "$result"
        else
            debug "create file $result"
            touch "$result"
        fi
    fi
    echo "$result"
    [ -z "$ttl" ] || (
        _rmtemp "$ttl" "$result" >/dev/null 2>&1 &
        disown
    )
}
_rmtemp() {
    local wait="$1" file="$2"
    while [ -e "$result" ] && ((wait > 0)); do
        sleep 1
        ((wait--))
    done
    [ ! -e "$result" ] || rm -r "$result"
    debug "Removed $file after TTL $1 seconds"
}
