#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# The core functions contains essential parts which may also be used while loading the library.

######################################################################################
### Module Loading
######################################################################################

# Load bashlib module
# This can be used to load a special additional module as needed. If you try to load something which is already loaded it will do nothing.
#
# The core modules are always loaded, so you won't need to load them.
# Something from the module folder can be loaded manually if you are started with only the base library.
# And finally the extra folder has always to be loaded individually.
# Usage:    use [<folder>/]<module>
# Globals:  $BASHLIB_LOADER to know which loader was used
use() {
    is integer --name=arguments --max=1 --die -- $#
    is set --name=module-path --die -- "$1"
    # processing
    local module=$1
    [[ "$module" =~ / ]] || module="module/$module"
    local path
    path="$(dirname "$module")"
    # shellcheck disable=SC2154
    case $path in
    core) return 0 ;;
    module) [[ ! "$BASHLIB_LOADER" =~ loader|full|remote ]] || return 0 ;;
    esac
    debug 5 "Loading module $module"
    source "$module"
}

# Set or add an additional trap without overwriting existing ones
# This is done by adding the new code as additional command before the existing ones if the trap is already set.
# Usage:    trap_add <code> <signal>
trap_add() {
    is integer --name=arguments --min=2 --max=2 --die -- $#
    is set --name=code --die -- "$1"
    is enum --name=signal --allow="SIGINT SIGTERM SIGHUP SIGQUIT SIGUSR1 SIGALRM EXIT ERR DEBUG" --die -- "$2"
    local new="$1"
    local sig="$2"
    # processing
    local old
    old="$(trap -p "$sig" | awk -F"'" '{print $2}')"
    if [[ -n "$old" ]]; then
        # shellcheck disable=SC2064
        trap "$new; $old" "$sig"
    else
        # shellcheck disable=SC2064
        trap "$new" "$sig"
    fi
}

# Remove a specific trap
# Not the whole trap is removed, but only the given code.
# Usage:    trap_remove <cmd> <signal>
trap_remove() {
    is integer --name=arguments --min=2 --max=2 --die -- $#
    is set --name=code --die -- "$1"
    is enum --name=signal --allow="SIGINT SIGTERM SIGHUP SIGQUIT SIGUSR1 SIGALRM EXIT ERR DEBUG" --die -- "$2"
    local remove="$1"
    local sig="$2"
    # processing
    local current new
    debug 3 "remove $remove from $sig"
    current="$(trap -p "$sig" | awk -F"'" '{print $2}')"
    # shellcheck disable=SC2001
    new="$(echo "$current" | sed "s#;* *$remove##")"
    # shellcheck disable=SC2064
    trap "$new" "$sig"
}

######################################################################################
### Temporary Files
######################################################################################

# Make a temporary file, which can be recognizable/individual
# As the same invocation from the same program will get the same file it can be called multiple times, as long as no `--random` is set.
# The file will be conducted out of the program name and the given `<identifier>`.
#
# You should remove this file by yourself if it is no longer needed. The files will be available in `/tmp` folder for about 3 unused days (managed by your os) and in memory till the next reboot.
# Usage:    mktemp [<identifier>]       # use default temp if no identifier given
# Options:  -d, --directory             # to make a directory instead of a file
#           -m, --memory                # use shared memory
#           -e, --extension=<string>    # to specify file extension (better readability)
#           -p, --path=<base-dir>       # folder under which to create file
#           -r, --random                # add a random (numeric) part to the identifier
#           -T, --ttl=<duration>        # duration to remove file again as seconds or duration @duration_format
# Output:   <path>
#           Debug: path and if it is created
#           Debug: remove after TTL
mktemp() {
    # parameter parsing
    eval set -- "$(option_parse $'d directory -\ne extension +\nm memory -\np path +\nr random -\nT ttl +' "$@")"
    local dir ext result rand
    local path=${TMPDIR:-/tmp}
    while true; do
        case "$1" in
        -d | --directory) dir=1 && shift ;;
        -e | --extension) ext=".$2" && shift 2 ;;
        -m | --memory) path="/dev/shm" && shift ;;
        -p | --path) path="$2" && shift 2 ;;
        -r | --random) rand=$RANDOM && shift ;;
        -T | --ttl) ttl="$(duration_format seconds "$2")" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is integer --name=arguments --max=1 --die -- $#
    local ident
    is set -- "$1" && ident="_$1"
    # processing
    result="$path/$(basename "$0")$ident$rand$ext"
    if is set -- "$rand"; then
        # loop while already exists
        while [ -e "$result" ]; do
            result="$path/$(basename "$0")$ident$RANDOM$ext"
        done
    fi
    if [ -e "$result" ]; then
        debug "already exists $result"
    else
        if is set -- "$dir"; then
            debug "create dir $result"
            mkdir -p "$result"
        else
            debug "create file $result"
            touch "$result"
        fi
    fi
    echo "$result"
    is empty -- "$ttl" || (
        _rm_temp "$ttl" "$result" >/dev/null 2>&1 &
        disown
    )
}
_rm_temp() {
    local wait="$1" file="$2"
    while [ -e "$result" ] && ((wait > 0)); do
        sleep 1
        ((wait--))
    done
    [ ! -e "$result" ] || rm -r "$result"
    debug "Removed $file after TTL $1 seconds"
}

######################################################################################
# HTTP/HTTPS
######################################################################################

# Last HTTP return code from curl
CURL_HTTP_CODE=""

# Curl with added error handling
# This will load the content into a temporary shared memory file while running.
#
# The information of the CURL_* variables are stored in an environment file, if `--store` is added, and you get them set in your process parent using `variables restore curl` there.
# Usage:    like curl
# Options:  default Options like in vanilla curl
#           store   # if set `variable store` will be called
# Globals:  `CURL_HTTP_CODE` set with last code
# Error:    `<text>` if not RC:2xx
# Return:   0 if RC:2xx
#           1 if not
curl() {
    # check for additional flags
    local args=() i=1 store
    while [[ $i -le $# ]]; do
        if [[ "${!i}" == "--store" ]]; then
            store=1
            shift "$i"
            i=1
            continue
        fi
        args+=("${!i}")
        ((i++))
    done
    set -- "${args[@]}"
    # shellcheck disable=SC2034
    local args=("$@")
    local file res
    array args has '-o' || file=$(mktemp -r)
    local opt
    [ -z "$file" ] || opt="-o $file"
    debug "command curl -s -w \"Error: %{url_effective} with RC:%{http_code}\" $opt -L $(escape_args "$@")"
    # shellcheck disable=SC2086
    res=$(command curl -s -w "%{url_effective} with RC:%{http_code}" $opt -L "$@" | tail -1)
    debug "Response: $res"
    CURL_HTTP_CODE=${res:(-3)}
    # store variables
    [ -z "$store" ] || variables store curl CURL_HTTP_CODE
    # output response
    if [ -n "$file" ]; then
        cat "$file"
        rm "$file"
    fi
    if [[ ! "$CURL_HTTP_CODE" =~ ^2[0-9]{2}$ ]]; then
        error "Error: $res" >&2
        return 1
    fi
}
