#!/usr/bin/env bash
# shellcheck source=base
source /dev/null

# Module with output and user interaction helpers.

######################################################################################
### Debug and Error Handling
######################################################################################

# Write message to STDERR if in DEBUG mode else do nothing
# Debug can support multiple levels starting from 1 upwards to be more verbose. This will only be shown if environment variable `DEBUG` is the same number or higher. Or if the `DEBUG` variable includes the function name. Multiple lines will be printed separately to have the function name prefix at the start of each.
# Usage:    debug [<num>] <message>
#           <message> | debug [<num>]
#               <num> := [1-9]      # (default 1) higher to only show in more verbose call
#               <message>           # the message text
# Globals:  `DEBUG` - if unset nothing will be printed
#           `DEBUG=<num>` - only print messages with same or lower numeric level
#           `DEBUG=<func>,...` - only print if the function is matched
#           `DEBUG=9` - to output all
# Error:    `> <func>           <message>`      # color: gray
debug() {
    local level=1 func text
    is integer --name=arguments --max=2 --die -- $#
    is integer --min 1 -- "$1" && level="$1" && shift || true
    IFS=$' \t\n' read -r _ func _ <<<"$(caller 0)"
    is set -- "$1" || return 0
    is set -- "$DEBUG" || return 0
    text="$(input "$@")"
    # processing
    # decide to print
    if is integer -- "$DEBUG"; then
        # numeric => decide on level
        is integer --min=0 --die -- "$DEBUG"
        ((level <= DEBUG)) || return 0
    else
        # string => check for match
        [[ "$func" =~ .*(${DEBUG//, /|}) ]] || return 0
    fi
    # print each line separately
    while IFS= read -r line; do
        printf "$CC_BLACK> %-20s %s$CC_RESET\n" "$func" "$line" >&2
    done <<<"$text"
    ! command -v log >/dev/null || log debug "$func: $text"
}

# Output error message and exit
# Usage:    die <message>
#           <message> | die
# Error:    # Example if called for deprecated call:
#           DEPRECATED: ask_input at task_find in /home/alex/bin/dvb/cleanup:206 please use ask string
#           > _stacktrace          at die() in /home/alex/dvb/bash-lib/core/misc:59
#           > _stacktrace          at _deprecated() in /home/alex/dvb/bash-lib/core/internal:23
#           > _stacktrace          at ask_input() in /home/alex/dvb/bash-lib/module/input:150
#           > _stacktrace          at task_find() in /home/alex/bin/dvb/cleanup:206
#           > _stacktrace          at tasks() in /home/alex/dvb/bash-lib/module/input:451
#           > _stacktrace          at main() in /home/alex/bin/dvb/cleanup:364
# Return:   always 1 and try to exit script with status 1
die() {
    is integer --name=arguments --max=1 --die -- $#
    # processing
    local text trap line func src
    text="$(input "$@")"
    [[ "$text" != *"Uncaught exception at"* ]] || trap=1
    # output
    echo -e "${CC_CRITICAL}$text in ${FUNCNAME[1]}${CC_RESET}" >&2
    _stacktrace "$trap"
    if command -v log >/dev/null; then
        log critical "$text"
        _stacktrace "$trap" 2>&1 | log critical
    fi
    # kill -s TERM "$PPID" # forcibly terminate the parent
    [[ $- =~ i ]] && return 1 || exit 1
}

######################################################################################
# Context
######################################################################################

# Show help page and exit
# Usage:    help <heading> <usage> <options-spec> <details>
help() {
    is integer --name=arguments --min=2 --max=4 --die -- $#
    is set --name=heading --die -- "$1"
    is set --name=usage --die -- "$2"
    # processing
    heading "$(gettext Help): $1"
    info "Usage: $2"
    echo ""
    if is set -- "$3"; then
        option_help "$3"
        echo ""
    fi
    if is set -- "$4"; then
        echo "$4"
        echo
    fi
    exit 0
}

######################################################################################
# Logging
######################################################################################

declare -ag _log_level=(debug info notice warn error critical)
declare -Ag _log_rotate_time
_log_rotate_time[hourly]="%Y-%m-%dT%H"
_log_rotate_time[daily]="%Y-%m-%d"
_log_rotate_time[weekly]="%Y_week_%W"
_log_rotate_time[monthly]="%Y-%m"
declare -Ag _log_active
# _log_active[path]="<path> <level> <rotate> [<compress> [<cleanup>]]"

# Additional logging (at the moment only into files).
# After initializing a log using `start` the default output options will additionally write into log. But you can also specifically write t it using the log function.
# Multiple log with different levels are possible.
# Usage:    log start <destination>                    # no spaces in file path allowed
#           log <level> <message>
#           <message> | log <level>
#           log end <destination>
# Options:  -l, --level=<level>                 # level := debug info notice warn error critical
#           # File logging:
#           -r, --rotate=hourly|daily|weekly|monthly|<bytes>
#           -c, --cleanup=<num>|<duration>
#           -z, --compress
# Files:    <destination>[_<pattern>]                  # will contain the logs
# Example:  # Format: <date> <time> <level> <message>
#           2025-12-02 14:07:35 INFO Hello
#           2025-12-02 14:10:04 ERROR This is only a test
log() {
    # parameter parsing
    local level=1 rotate compress=0 cleanup text size
    eval set -- "$(option_parse $'l level +\nr rotate +\nz compress -\nc cleanup +' "$@")"
    while true; do
        case "$1" in
        -l | --level)
            is enum --name=level --allow="${_log_level[*]}" --die -- "$2"
            level="$(array _log_level indexof "$2")"
            shift 2
            ;;
        -r | --rotate)
            if (($2 > 0)); then
                rotate="$2"
            else
                # shellcheck disable=SC2145
                is enum --name=rotate --allow="${!_log_rotate_time[@]}" --die -- "$2"
                rotate="$(hash _log_rotate_time get "$2")"
            fi
            shift 2
            ;;
        -z | --compress) compress=1 && shift ;;
        -c | --cleanup) cleanup="$(check duration --name=cleanup --die -- "$2")" && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    is integer --name=arguments --min=1 --max=2 --die -- $#
    is enum --name=command --allow="start stop ${_log_level[*]}" --die -- "$1"
    is empty -- "$rotate" && cleanup="" && compress="" || true # no cleanup/compress if no rotate
    # processing
    case $1 in
    start)
        is set --name=destination --die -- "$2"
        [ -w "$2" ] || [ -w "$(dirname "$2")" ] || die "Could not write/create log under $2"
        hash _log_active set "$2" "$2 $level $rotate $compress $cleanup"
        ;;
    stop)
        is set --name=destination --die -- "$2"
        hash _log_active unset "$2"
        ;;
    debug | info | notice | warn | error | critical)
        level="$(array _log_level indexof "$1")"
        text="$(input_args 1 "$@")"
        [ -n "$text" ] || return 0 # no message
        # loop over _log_active values
        local file minLevel
        for e in "${_log_active[@]}"; do
            read -r file minLevel rotate cleanup <<<"$e"
            ((level >= minLevel)) || continue
            path="$file"
            if [ -n "$rotate" ] && ((rotate == 0)); then
                path+="_$(date_format "$rotate")"
            fi
            # log entry
            echo "$(date_format sql) ${1^^} $(uncolorize "$text")" >>"$path"
        done
        ;;
    *) die "Unrecognized command $1: start, stop or any log level allowed" ;;
    esac
}

_log_manager() {
    local parent=$PPID file minLevel rotate compress cleanup size
    while true; do
        for e in "${_log_active[@]}"; do
            read -r file minLevel rotate compress cleanup <<<"$e"
            # cleanup
            if [ -n "$cleanup" ]; then
                find "$(dirname "$file")" -type f -name "$(basename "$file")*" ! -newermt "$(date -d "$cleanup seconds ago")" -delete 2>/dev/null
            fi
            # rotate on size
            if ((rotate > 0)); then
                size="$(stat -c %s "$file")"
                if ((size > rotate)); then
                    mr -f "${file}.99"
                    # Shift existing numbered files up
                    for ((i = 99; i > 1; i--)); do
                        local old="${file}.${i}"
                        local new="${file}.$((i - 1))"
                        [ ! -f "$old" ] || mv "$old" "$new"
                    done
                    # Rotate the main file to .1
                    ! [ -f "$file" ] || mv "$file" "${file}.1"
                fi
            fi
            # compress
            if ((compress == 1)); then
                find "$(dirname "$file")" -type f -name "$(basename "$file")*" -mmin 3600 -exec gzip --best {} \; 2>/dev/null
            fi
        done
        # run manager every 5 minutes
        for ((i = 0; i < 300; i++)); do
            sleep 1
            kill -0 "$parent" 2>/dev/null || exit 0 # end if parent ended
        done
    done
}

######################################################################################
# Messages
######################################################################################

# Print block heading
# Usage:    heading <title>
#           <title> | heading
# Output:   colored <string>
# Variable: $server
heading() {
    local prefix=""
    # shellcheck disable=SC2154
    is empty -- "$server" || prefix="${server-} "
    printf "\n%s\n\n" "${CC_INVERS}$prefix${CC_RESET}${CC_HEADING}$(input "$@")...${CC_RESET}"
}

# Print critical/disaster message
# Usage:    critical <message>
#           <message> | critical
# Output:   colored <string>
critical() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "%s\n" "${CC_CRITICAL}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log critical "$text"
}

# Print error message
# Usage:    error <message>
#           <message> | error
# Output:   colored <string>
error() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "%s\n" "${CC_ERROR}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log error "$text"
}

# Print warning message
# Usage:    warn <message>
#           <message> | warn
# Output:   colored <string>
# shellcheck disable=SC2120
warn() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "%s\n" "${CC_WARN}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log warn "$text"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Output:   colored <string>
# shellcheck disable=SC2120
notice() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "%s\n" "${CC_NOTICE}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log notice "$text"
}

# Print special information message
# Usage:    info <message>
#           <message> | info
# Output:   colored <string>
info() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "%s\n" "$text"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

# Print success message
# Usage:    ok <message>
#           <message> | ok
# Output:   colored <string>
ok() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    echo -e "${CC_OK}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log notice "$text"
}

# Print special marked message like table header
# Usage:    invers <message>
#           <message> | invers
# Output:   colored <string>
invers() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    echo -e "${CC_INVERS}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

# Print message in defined color
# Usage:    color <color> <message>
#           <message> | color <color>
# Output:   colored <string>
color() {
    local text
    text="$(input_args 1 "$@")"
    is set -- "$text" || return 0
    echo -e "${CC_ERROR}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

######################################################################################
# Format Helpers
######################################################################################

# Remove color codes from text
# Usage:    uncolorize <text>
#           <text> | uncolorize
# Output:   <text>
# shellcheck disable=SC2120
uncolorize() {
    input "$@" | sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}

# Convert HTML to markdown (simplified version)
# Usage:    html2md <html-part>
#           <html-part> | html2md
# Output:   <md>
html2md() {
    input "$@" |
        sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li>#\n- #g;s#<[^>]*>##g' |
        grep -v '^$'
}

# Remove carriage return from line endings
# Usage:    nocr <text>
#           <text> | nocr
# Output:   <text>
nocr() {
    input "$@" | sed 's/\r$//' # removes all: tr -d '\r'
}

# Encode message to be used within the url
# Usage:    urlencode <string>
#           <string> | urlencode
# Output:   <string>
urlencode() {
    install jq
    input "$@" | jq -sRr @uri | sed 's/%0A$//'
}

######################################################################################
# Visual effects
######################################################################################

# Remove current line
# When printed to a terminal, it will erase everything from the current cursor position backward to the beginning of the line.
# Usage:    erase_line
erase_line() {
    is integer --name=arguments --max=0 --die -- $#
    # processing
    printf '%b' $'\e[1K\r'
}

# Show a horizontal line
# It will go over the full width of terminal, but be at least 60 characters wide.
# Format can be:
# - light (default) ──────────
# - bold ━━━━━━━━━━
# - double ══════════
# - half ▄▄▄▄▄▄▄▄▄▄
# - full ██████████
# Usage:    horizontal_line [<format>]
# Output:   ────────── # over full width of terminal
horizontal_line() {
    is integer --name=arguments --max=1 --die -- $#
    is empty -- "$1" || is enum --name=format --allow="light bold double half full"--die -- "$1"
    # processing
    local char
    case $1 in
    #light) char="─" ;; # is the default
    bold) char="━" ;;
    double) char="═" ;;
    half) char="▄" ;;
    full) char="█" ;;
    *) char="─" ;;
    esac
    local cols
    read -r _ cols < <(stty size)
    ((cols > 60)) || cols=60
    printf "%.0s$char" $(seq 1 "$cols")
}

_spinner_pid=""

# Function to start the spinner in the background
# To stop it later call @spinner_stop.
# Some formats have multiple character width:
# - `simple`:   - \ | /
# - `arrows`:   → ↑ ← ↓
# - `vertical`: ▏ ▎ ▍ ▌ ▋ ▊ ▉ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏
# - `bar`:      (as `vertical` but two characters wide)
# - `fade`:     ░ ▒ ▓ █ ▓ ▒ ░
# - `braille`:   ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ (default)
# - `roll`:     ⠋ ⠙ ⠚ ⠞ ⠖ ⠦ ⠴ ⠲ ⠳ ⠓
# - `moon`:     🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘
# - `clock`:    🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛
# - `weather`:  🌤 🌥 🌦 🌧 🌨 🌩 🌪
# Usage:    spinner_start <format> [<time>]
#           # <format> see above
#           # <time> 0.1 or more seconds (default 0.2)
# TTY:      <symbol> with back-space so that cursor is always before it
# Returns:   0 without doing anything if no `tput` and terminal available
spinner_start() {
    is integer --name=arguments --max=2 --die -- $#
    is empty -- "$1" || is enum --name=format --allow="simple arrows vertical bar fade braille roll moon clock weather" --die -- "$1"
    # processing
    if ! command -v tput >/dev/null 2>&1 || [ ! -t 2 ]; then
        debug "Disabled because tput and terminal is needed"
        return 0
    fi
    local format="${1:-braille}"
    local spinner
    local size=1
    local chars=1
    local delay=${2:-0.2}
    case $format in
    #simple) spinner='-\|/' ;; # is the default option, too
    arrows) spinner='→↑←↓' ;;
    vertical) spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏' ;;
    bar) spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ ' && chars=2 && size=2 ;;
    fade) spinner=' ░▒▓█▓▒░' ;;
    braille) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
    roll) spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓' ;;
    moon) spinner='🌑🌒🌓🌔🌕🌖🌗🌘' && size=2 ;;
    clock) spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛' && size=2 ;;
    weather) spinner='🌤🌥🌦🌧🌨🌩🌪' ;;
    *) spinner='-\|/' ;;
    esac
    local back=$((size + 1))
    # Spinner function running in background loop
    printf '\e[?25l' # make cursor invisible
    (
        while true; do
            for ((i = 0; i < ${#spinner}; i += chars)); do
                printf " %s%s" "${spinner:i:$chars}" "$(printf '\b%.0s' $(seq 1 "$back"))" >/dev/tty
                sleep "$delay"
            done
        done
    ) &
    _spinner_pid=$!
    disown
}

# Function to stop the spinner
# Call this after @spinner_start to stop it. It has to be called within the same thread!
# Usage:    spinner_stop
spinner_stop() {
    is integer --name=arguments --max=0 --die -- $#
    # processing
    [ -n "$_spinner_pid" ] || return # spinner not started
    kill "$_spinner_pid" >/dev/null 2>&1
    wait "$_spinner_pid" 2>/dev/null
    _spinner_pid=""
    printf "    \b\b\b\b" # Clear spinner character
    printf '\e[?25h'      # make cursor visible again
}
