#!/usr/bin/env bash
# shellcheck disable=SC2034
# shellcheck source=base
source /dev/null

# Module with output and user interaction helpers.

######################################################################################
### Debug and Error Handling
######################################################################################

# Write message to STDERR if in DEBUG mode else do nothing
#
# Debug can support multiple levels starting from 1 upwards to be more verbose. This will only be shown if environment variable `DEBUG` is the same number or higher. Or if the `DEBUG` variable includes the function name. Multiple lines will be printed separately to have the function name prefix at the start of each.
#
# With DEBUG=9 the $BASHPID will also be shown.
#
# Usage:    debug [<num>] <message>
#           <message> | debug [<num>]
#               <num> := [1-9]      # (default 1) higher to only show in more verbose call
#               <message>           # the message text
# Globals:  - $DEBUG - if unset nothing will be printed
#           - `DEBUG=<num>` - only print messages with same or lower numeric level
#           - `DEBUG=<func>,...` - only print if the function is matched
#           - `DEBUG=9` - to output all
# Error:    `> <func>           <message>`      # color: gray
debug() {
    local level=1 func text sign='>'
    is integer --name=arguments --max=2 --die -- $#
    is integer --min 1 -- "$1" && level="$1" && shift || true
    IFS=$' \t\n' read -r _ func _ <<<"$(caller 0 || true)"
    func="${func:-(main)}"
    is set -- "$DEBUG" || return 0
    text="$(input "$@")"
    [[ "$BASHLIB_LOADER" != "remote" ]] || sign='>>'
    # processing
    # decide to print
    if is integer -- "$DEBUG"; then
        # numeric => decide on level
        is integer --min=0 --die -- "$DEBUG"
        ((level <= DEBUG)) || return 0
    else
        # string => check for match
        [[ "$func" =~ .*(${DEBUG//,? /|}) ]] || return 0
    fi
    # print each line separately
    local line
    while IFS= read -r line; do
        is integer --min=9 -- "$DEBUG" &&
            printf "$CC_BLACK%-2s %7d %-20s %s$CC_RESET\n" "$sign" "$BASHPID" "$func" "$line" >&2 ||
            printf "$CC_BLACK%-2s %-20s %s$CC_RESET\n" "$sign" "$func" "$line" >&2
    done <<<"$text"
    ! command -v log >/dev/null || while IFS= read -r line; do
        log debug "$func: $line"
    done <<<"$text"
}

# Output error message and exit
#
# Usage:    die <message> [<source>:<line>]
#           <message> | die
# Error:    # Example if called for deprecated call:
#           ```
#           DEPRECATED: ask_input at task_find in /home/alex/bin/dvb/cleanup:206 please use ask string
#           > _stacktrace          at die() in /home/alex/dvb/bash-lib/core/misc:59
#           > _stacktrace          at _deprecated() in /home/alex/dvb/bash-lib/core/internal:23
#           > _stacktrace          at ask_input() in /home/alex/dvb/bash-lib/module/input:150
#           > _stacktrace          at task_find() in /home/alex/bin/dvb/cleanup:206
#           > _stacktrace          at tasks() in /home/alex/dvb/bash-lib/module/input:451
#           > _stacktrace          at main() in /home/alex/bin/dvb/cleanup:364
#           ```
# Return:   143 SIGTERM
die() {
    is integer --name=arguments --max=1 --die -- $#
    # processing
    trap - ERR
    local text trap line func src
    text="$(input "$@")"
    [[ "$text" != *"Uncaught exception at"* ]] || trap=1
    # output
    printf "${CC_CRITICAL}%s${CC_RESET}\n" "$text in ${FUNCNAME[1]}" >&2
    _stacktrace "$trap"
    if command -v log >/dev/null; then
        log critical "$text"
        _stacktrace "$trap" 2>&1 | log critical
    fi
    if [[ $- == *i* ]]; then
        return 143
    else
        sleep 1 # to let output pipes finish
        # sends SIGTERM to process group → process receives SIGTERM
        kill -- -$$ 2>/dev/null
        exit 143
    fi
}

# Unicode-aware printf variant for multibyte characters.
#
# This works exactly like printf, but should be used if width calculation is needed like in `%15s`. Instead of counting bytes (which the original printf does) this variant uses `awk` under the hood to count characters.
# Therefor it will also make the alignment correct for german Umlaut or other multibyte Unicode characters. But it will not work for all the Unicode symbols and emojis.
#
# Usage:    printf <pattern> [<value>]...
uprintf() {
    local cmd=awk
    for ((i = 1; i <= $#; i++)); do
        cmd+=" -v $(printf "\\$(printf '%03o' $((96 + i)))=\"\$$i\"")"
    done
    cmd+=" 'BEGIN{printf("
    for ((i = 1; i <= $#; i++)); do
        cmd+="$(printf "\\$(printf '%03o' $((96 + i)))"),"
    done
    cmd+="\"\")}'"
    eval "$cmd"
}

######################################################################################
# Context
######################################################################################

# Show help page and exit
#
# Usage:    help <heading> <usage> <options-spec> <details>
help() {
    is integer --name=arguments --min=2 --max=4 --die -- $#
    is set --name=heading --die -- "$1"
    is set --name=usage --die -- "$2"
    # processing
    heading "$(gettext Help): $1"
    info "Usage: $2"
    printf '\n'
    if is set -- "$3"; then
        option_help "$3"
        printf '\n'
    fi
    if is set -- "$4"; then
        printf '%s\n\n' "$4"
    fi
    exit 0
}

######################################################################################
# Messages
######################################################################################

# Print block heading
#
# Usage:    heading <title>
#           <title> | heading
# Output:   colored <string>
# Variable: $server
heading() {
    local prefix=""
    # shellcheck disable=SC2154
    is empty -- "$server" || prefix="${server-} "
    printf "\n%s\n\n" "${CC_INVERS}$prefix${CC_RESET}${CC_HEADING}$(input "$@")...${CC_RESET}"
}

# Print critical/disaster message
#
# Usage:    critical <message>
#           <message> | critical
# Output:   colored <string>
critical() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf '%s\n' "${CC_CRITICAL}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log critical "$text"
}

# Print error message
#
# Usage:    error <message>
#           <message> | error
# Output:   colored <string>
error() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf '%s\n' "${CC_ERROR}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log error "$text"
}

# Print warning message
#
# Usage:    warn <message>
#           <message> | warn
# Output:   colored <string>
# shellcheck disable=SC2120
warn() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf '%s\n' "${CC_WARN}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log warn "$text"
}

# Print special information message
#
# Usage:    info <message>
#           <message> | info
# Output:   colored <string>
# shellcheck disable=SC2120
notice() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf '%s\n' "${CC_NOTICE}$text${CC_RESET}"
    ((${#_log_active[@]} == 0)) || log notice "$text"
}

# Print special information message
#
# Usage:    info <message>
#           <message> | info
# Output:   colored <string>
info() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf '%s\n' "$text"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

# Print success message
#
# Usage:    ok <message>
#           <message> | ok
# Output:   colored <string>
ok() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "${CC_OK}%s${CC_RESET}\n" "$text"
    ((${#_log_active[@]} == 0)) || log notice "$text"
}

# Print special marked message like table header
#
# Usage:    invers <message>
#           <message> | invers
# Output:   colored <string>
invers() {
    local text
    text="$(input "$@")"
    is set -- "$text" || return 0
    printf "${CC_INVERS}%s${CC_RESET}\n" "$text"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

# Print message in defined color
#
# Usage:    color <color> <message>
#           <message> | color <color>
# Output:   colored <string>
color() {
    local text
    text="$(input_args 1 "$@")"
    is set -- "$text" || return 0
    printf "${CC_ERROR}%s${CC_RESET}\n" "$text"
    ((${#_log_active[@]} == 0)) || log info "$text"
}

######################################################################################
# Format Helpers
######################################################################################

# Remove color codes from text
#
# Usage:    uncolorize <text>
#           <text> | uncolorize
# Output:   <text>
# shellcheck disable=SC2120
uncolorize() {
    input "$@" | sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}

# Convert HTML to markdown (simplified version)
#
# Usage:    html2md <html-part>
#           <html-part> | html2md
# Output:   <md>
html2md() {
    input "$@" |
        sed 's#&rarr;#→#g;s#&auml;#ä#g;s#&ouml;#ö#g;s#&uuml;#ü#g;s#&Auml;#Ä#g;s#&Ouml;#Ö#g;s#&Uuml;#Ü#g;s#&szlig;#ß#g;s#<strong>\([^<]*\)</strong>#**\1**#g;s#<br/\?>#\n#g;s#<li[^>]*>#\n- #g;s#<[^>]*>##g' |
        grep -v '^$'
}

# Remove carriage return from line endings
#
# Usage:    nocr <text>
#           <text> | nocr
# Output:   <text>
nocr() {
    input "$@" | sed 's/\r$//' # removes all: tr -d '\r'
}

# Encode message to be used within the url
#
# Usage:    urlencode <string>
#           <string> | urlencode
# Output:   <string>
urlencode() {
    install jq
    input "$@" | jq -sRr @uri | sed 's/%0A$//'
}

######################################################################################
# Visual effects
######################################################################################

# Show a horizontal line
#
# It will go over the full width of terminal, but be at least 60 characters wide.
#
# Format can be:
#
# - light (default) ──────────
# - bold ━━━━━━━━━━
# - double ══════════
# - half ▄▄▄▄▄▄▄▄▄▄
# - full ██████████
#
# Usage:    horizontal_line [<format>]
# Output:   ────────── # over full width of terminal
horizontal_line() {
    is integer --name=arguments --max=1 --die -- $#
    is empty -- "$1" || is enum --name=format --allow="light bold double half full" --die -- "$1"
    # processing
    local char
    case $1 in
    #light) char="─" ;; # is the default
    bold) char="━" ;;
    double) char="═" ;;
    half) char="▄" ;;
    full) char="█" ;;
    *) char="─" ;;
    esac
    local cols
    read -r _ cols < <(stty size)
    ((cols > 60)) || cols=60
    printf '%s\n' "$(character repeat "$cols" "$char")"
}

_spinner_pid=""

# Function to start the spinner in the background
#
# To stop it later call @spinner_stop.
#
# Some formats have multiple character width:
#
# - `simple`:   - \ | /
# - `arrows`:   → ↑ ← ↓
# - `vertical`: ▏ ▎ ▍ ▌ ▋ ▊ ▉ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏
# - `bar`:      (as `vertical` but two characters wide)
# - `fade`:     ░ ▒ ▓ █ ▓ ▒ ░
# - `braille`:   ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ (default)
# - `roll`:     ⠋ ⠙ ⠚ ⠞ ⠖ ⠦ ⠴ ⠲ ⠳ ⠓
# - `moon`:     🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘
# - `clock`:    🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛
# - `weather`:  🌤 🌥 🌦 🌧 🌨 🌩 🌪
#
# Usage:    spinner_start <format> [<time>]
#           # <format> see above
#           # <time> 0.1 or more seconds (default 0.2)
# TTY:      <symbol> with back-space so that cursor is always before it
spinner_start() {
    is integer --name=arguments --max=2 --die -- $#
    is empty -- "$1" || is enum --name=format --allow="simple arrows vertical bar fade braille roll moon clock weather" --die -- "$1"
    # processing
    local format="${1:-braille}"
    local spinner
    local size=1
    local chars=1
    local delay=${2:-0.2}
    case $format in
    #simple) spinner='-\|/' ;; # is the default option, too
    arrows) spinner='→↑←↓' ;;
    vertical) spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏' ;;
    bar) spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ ' && chars=2 && size=2 ;;
    fade) spinner=' ░▒▓█▓▒░' ;;
    braille) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
    roll) spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓' ;;
    moon) spinner='🌑🌒🌓🌔🌕🌖🌗🌘' && size=2 ;;
    clock) spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛' && size=2 ;;
    weather) spinner='🌤🌥🌦🌧🌨🌩🌪' ;;
    *) spinner='-\|/' ;;
    esac
    local back=$((size + 1))
    # Spinner function running in background loop
    # shellcheck disable=SC2059
    printf "$CUR_HIDE" # make cursor invisible
    (
        while true; do
            for ((i = 0; i < ${#spinner}; i += chars)); do
                printf " %s%s" "${spinner:i:$chars}" "$(printf '\b%.0s' $(seq 1 "$back"))" >/dev/tty
                sleep "$delay"
            done
        done
    ) &
    _spinner_pid=$!
    disown
}

# Function to stop the spinner
#
# Call this after @spinner_start to stop it. It has to be called within the same thread!
#
# Usage:    spinner_stop
spinner_stop() {
    is integer --name=arguments --max=0 --die -- $#
    # processing
    [ -n "$_spinner_pid" ] || return # spinner not started
    kill "$_spinner_pid" >/dev/null 2>&1
    wait "$_spinner_pid" 2>/dev/null
    _spinner_pid=""
    printf "    \b\b\b\b" # Clear spinner character
    # shellcheck disable=SC2059
    printf "$CUR_SHOW" # make cursor visible again
}

# Output Logo with title text
#
# You may overload this function with one displaying your own logo by loading it from your `extra/my-company-logo` or so.
#
# Usage:    logo <text>
# Output:   ASCII art logo including title
# shellcheck disable=SC2059
logo() {
    a=$'\e[36m'            # cyan
    b=$'\e[33m\e[1m'       # yellow bold
    c=$'\e[43m\e[30m\e[1m' # yellow bg + black bold
    r=$'\e[0m'             # reset
    u=$'\e[4m'             # underline
    p="$(character repeat $((($(tput cols) - 80) / 2)) ' ')"
    t="$(character repeat $((($(tput cols) - ${#1}) / 2)) ' ')"
    printf "
$p$a                         $b  __   ____     ___
$p$a           ######  ##### $b ▕  ▏ ▕    ╲   ▕   ▏ $a  ########### #####       #####
$p$a          ######## ##### $b ▕  ▏ ▕     ╲  ▕   ▏ $a ############  #####     #####
$p$a         ######### ##### $b ▕  ▏ ▕  ▕╲  ╲ ▕   ▏ $a #####          #####   #####
$p$a        ########## ##### $b ▕  ▏ ▕  ▕ ╲  ╲▕   ▏ $a #####           ##### #####
$p$a       ##### ##### ##### $b ▕  ▏ ▕  ▕  ╲  ▔   ▏ $a ############     #########
$p$a      #####  ##### ##### $b ▕  ▏ ▕  ▕   ╲     ▏ $a ############     #########
$p$a     #####   ##### ##### $b ▕  ▏ ▕  ▕    ╲    ▏ $a #####           ##### #####
$p$a    #####    ##### ##### $b  ▔▔   ▔▔▔     ▔▔▔▔  $a #####          #####   #####
$p$a   ##### ######### ######""#####################"" ############  #####     #####
$p$a  ##### ##########  #####""#################### ""  ########### #####       ##### $r
$p$b▄\e[78b$r$c
$t$1$r
$p$b▀\e[78b$r
"
}
