#!/usr/bin/env bash

# Validators to make this easier and more readable.

######################################################################################
### General Validation
######################################################################################

# Validate and sanitize values.
#
# This validation is possible using the `check` and @is function.
# - `check` should be used for sanitize because it will output the value
# - @is should be used for checking only validity or stop processing on problem because no value is output
#
# Every parameter should be checked to prevent failure later in the code.
# For such checks you run it with the `--die` option to stop processing if wrong.
# But you can also use it in the program flow without that and use it's return status to check if it 0=ok or 1=failed.
#
# Because the values may start with an dash you should always put it at the end after '--' to prevent parsing it as option.
#
# The following checks are implemented:
#
# - `set` will fail if no value given
# - `empty` will fail if not empty like ""
# - `bool` will transform the value to `1` or `0` and allows: true/false, t/f, 1/0, yes/no, y/j/n, ja/nein, ""
# - `true` should be a boolean true
# - `false` should be a boolean false
# - `integer` will check for a number maybe within a range
# - `float` will check for a number maybe within a range
# - `enum' will check against valid words using `--allow="word1 word2"`
# - `length` check that the length is within range (like integer)
# - `date` check that the input is parsable as date and return unix timestamp
# - `time` check that the input is a valid time format
# - `duration` check and parse the @duration_format
# - `path` check that value is an existing path (any type)
# - `file` check that value is an existing file
# - `directory` check that value is an existing directory
# - `readable` check that value is a file readable by user
# - `writable` check that value is a file writable by user
# - `domain` check for a domain name (part of the url)
# - `ipv4` ip address check
# - `url` check that it is a full url
#
# Usage:    is <check> [options] -- <value>
# Options:  # general options
#           -d, --die                       # used in @is to stop with error instead of return state
#           -o, --output=[<variable-name>]  # will write the sanitized value into variable or output it to stdout
#           -n, --name=<string>             # used in @is to display variable name in `die` message
#           -m, --message=<string>          # additional message like usage
#           # for integer
#           -s, --sanitize                  # remove invalid characters
#           --min=<num>                     # minimum number allowed
#           --max=<num>                     # maximum number allowed
#           # enum/url
#           --allow=<words>                 # space separated (protocol in url)
#           # domain
#           --exists                        # domain can be resolved
#           # ipv4
#           --private                       # only private addresses
#           --public                        # only public addresses
#           --loopback                      # only local loopback addresses
#           --range <network-range>         # ip is within netmask (multiple allowed)
#           --ping                          # check that ping is possible
#           --no-ping                       # ping should not be possible
#           # url
#           --exists                        # url is reachable
#           --ok                            # url has code 2xx
# Output:   <value>                         # may be sanitized
# Exit:     with message if incorrect value
# Example:  - &is explains some regular use cases
#           - `is integer --name=arguments --max=2 -- $# >/dev/null` # mostly only check max, if all args are checked separately
#           - `name="$(is integer --name=age --sanitize --min=0 --output -- "$1")"`
#           - `is integer --name=age --sanitize --min=0 --output=name -- "$1"`
#           - `init="$(is bool --name=init --output -- "$1")"`
#           - `if is integer age --min=18 -- "$1"; then`
is() {
    # parameter parsing
    eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +\no output ?\nm message +\n- exists -\n- ok -\n- private -\n- public -\n- loopback -\n- ping -\n- no-ping -\n- range +' "$@")"
    local name die sanitize min max allow message output exists ok ping public range
    # shellcheck disable=SC2015
    # shellcheck disable=SC2059
    while true; do
        case "$1" in
        -n | --name) name="$2" && shift 2 ;;
        -m | --message) message="$2"$'\n' && shift 2 ;;
        -o | --output) output="${2:--}" && shift 2 ;;
        -d | --die) die=1 && shift ;;
        -s | --sanitize) sanitize=1 && shift ;;
        --min) [[ "$2" =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]] && min="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs number")" min)" ;;
        --max) [[ "$2" =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]] && max="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs number")" max)" ;;
        --allow) [ -n "$2" ] && allow="$2" && shift 2 || die "$(gettext "A list of words is needed")" ;;
        --exists) exists=1 && shift ;;
        --ok) ok=1 && shift ;;
        --range) range+=("$2") && shift 2 ;;
        --private) range+=(10.0.0.0/8 172.16.0.0/12 192.168.0.0/16) && shift ;;
        --public) public=1 && shift ;;
        --loopback) range+=(127.0.0.0/8) && shift ;;
        --ping) ping=1 && shift 2 ;;
        --no-ping) ping=0 && shift 2 ;;
        --) shift && break ;;
        *) die "$(gettext "Unrecognized option"): $1" ;;
        esac
    done
    name="${name:-argument}"
    # processing
    local usage
    usage="$(gettext "Incorrect call"): is <check> <value> [options]"
    # shellcheck disable=SC2015
    [ -n "$1" ] && local check="$1" || die "$usage"
    local val="$2" res="$2"
    # shellcheck disable=SC2015
    case $check in
    set)
        if [ -z "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be set with a value')"
        fi
        ;;
    empty)
        if [ -n "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be empty but has »${val}«')"
        fi
        ;;
    bool)
        if [[ "${val,,}" =~ ^(true|t|1|yes|y|ja|j)$ ]]; then
            res=1
        elif [[ -z "$val" || "${val,,}" =~ ^(false|f|0|no|n|nein)$ ]]; then
            res=0
        else
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')"
        fi
        ;;
    true)
        if [[ "${val,,}" =~ ^(true|t|1|yes|y|ja|j)$ ]]; then
            res=1
        else
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The value »${val}« for "$name" should be true but was »${val}«')"
        fi
        ;;
    false)
        if [[ -z "$val" || "${val,,}" =~ ^(false|f|0|no|n|nein)$ ]]; then
            res=0
        else
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The value »${val}« for "$name" should be false but was »${val}«')"
        fi
        ;;
    integer)
        if [ -n "$sanitize" ]; then
            [[ "$val" =~ ^(-?[0-9]+) ]] && res="${BASH_REMATCH[1]}" || true
        fi
        if [[ ! "$res" =~ ^-?[0-9]+$ ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')"
        fi
        if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
            if ((res != min)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
            fi
        elif [[ -n "$min" && -n "$max" ]]; then
            if ((res < min || res > max)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
            fi
        elif [[ -n "$min" ]]; then
            if ((res < min)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
            fi
        elif [[ -n "$max" ]]; then
            if ((res > max)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
            fi
        fi
        ;;
    float)
        if [ -n "$sanitize" ]; then
            [[ "$val" =~ ^(-?[0-9]+([.][0-9]+)?) ]] && res="${BASH_REMATCH[1]}" || true
        fi
        if [[ ! "$res" =~ ^-?[0-9]+([.][0-9]+)?$ ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be a float but »${val}« was given')"
        fi
        if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
            if ((res != min)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
            fi
        elif [[ -n "$min" && -n "$max" ]]; then
            if ((res < min || res > max)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
            fi
        elif [[ -n "$min" ]]; then
            if ((res < min)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
            fi
        elif [[ -n "$max" ]]; then
            if ((res > max)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
            fi
        fi
        ;;
    length)
        val=${#val}
        if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
            if ((val != min)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')"
            fi
        elif [[ -n "$min" && -n "$max" ]]; then
            if ((val < min || val > max)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')"
            fi
        elif [[ -n "$min" ]]; then
            if ((val < min)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')"
            fi
        elif [[ -n "$max" ]]; then
            if ((val > max)); then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')"
            fi
        fi
        ;;
    enum)
        [ -n "$allow" ] || die "$message$(gettext "A list with --allow=<words> is needed for enum check")"
        if [[ " $allow " != *" $val "* ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')"
        fi
        ;;
    domain)
        if [[ ! "$val" =~ ^([A-Za-z0-9](-?[A-Za-z0-9])*\.)+[A-Za-z]{2,}$ ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but this is no valid domain name')"
        fi
        if [ -n "$exists" ] && [ -z "$(ip_resolve $val)" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but this can not be resolved (not existing)')"
        fi
        ;;
    ipv4)
        if [[ ! "$val" =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but this is no valid ip V4 address')"
        fi
        if [ -n "$range" ]; then
            use network
            local check found
            for check in "${range[@]}"; do
                ip_in_netmask $val $check && found=1 || true
            done
            if [ -z "$found" ]; then
                check="${range[*]}"
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but this is not within: $check')"
            fi
        fi
        if [ -n "$public" ]; then
            use network
            local check found
            for check in 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 224.0.0.0/4 240.0.0.0/4 192.0.2.0/24 198.51.100.0/24 203.0.113.0/24 198.18.0.0/15 192.0.0.0/24 192.88.99.0/24; do
                ip_in_netmask $val $mask && found=1 || true
            done
            if [ -n "$found" ]; then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but this is no public ip')"
            fi
        fi
        if [ -n "$ping" ]; then
            use network
            local found
            ping_check $val && found=1 || found=0
            if [ "$ping" != "$found" ]; then
                if [ "$ping" = "1" ]; then
                    [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" and should be reachable using ping, but is not')"
                else
                    [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" and should not be reachable using ping, but it is')"
                fi
            fi
        fi
        ;;
    url)
        local proto status
        proto="${val%%://*}"
        if [ -n "$allow" ]; then
            if [[ " $allow " != *" $proto "* ]]; then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" is set to "${val}" but only allowed protocols are: $allow')"
            fi
        fi
        [[ "$val" =~ ^(https?|ftp|file)://[a-zA-Z0-9] ]] || die "$message$(eval_gettext '"$name" is set to "${val}" but this is not a valid URL')"
        if [ -n "$ok" ]; then
            status=$(command curl -s --head -w "%{http_code}" "$val" -o /dev/null 2>&1)
            if [[ $status -lt 200 && $status -ge 300 ]]; then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" should be accessible but "${val}" returns code $status')"
            fi
        elif [ -n "$exists" ]; then
            if !ccommand curl -s --head --fail "$val" >/dev/null 2>&1; then
                [ -z "$die" ] && return 1 || die "$message$(eval_gettext '"$name" should exist but "${val}" is not reachable')"
            fi
        fi
        ;;
    date)
        if ! res=$(date_format unix "$val"); then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be a parsable date format but »${val}« was given')"
        fi
        ;;
    time)
        if [[ ! $val =~ ^([0-1]?[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$ ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be a parsable time format but »${val}« was given')"
        fi
        res="$(printf "%02d:%02d:%02d" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "${BASH_REMATCH[3]}")"
        ;;
    duration)
        [[ "$res" =~ ^-?[0-9] ]] && res="$(duration_format seconds "$val")" || true
        if [[ ! "$res" =~ ^-?[0-9]+$ ]]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" has to be an integer or human duration but »${val}« was given')"
        fi
        ;;
    path)
        if [ ! -e "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" ${val} has to be an existing path')"
        fi
        ;;
    file)
        if [ ! -f "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" ${val} has to be an existing file')"
        fi
        ;;
    directory)
        if [ ! -d "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" ${val} has to be an existing directory')"
        fi
        ;;
    readable)
        if [ ! -r "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" ${val} has to be a file readable for user')"
        fi
        ;;
    writable)
        if [ ! -w "$val" ]; then
            [ -z "$die" ] && return 1 || die "$message$(eval_gettext 'The "$name" ${val} has to be a file writable for user')"
        fi
        ;;
    *) die "$(eval_gettext 'A check named ${check} is not defined')" ;;
    esac
    if [ -n "$output" ]; then
        [ "$output" = "-" ] && printf '%s' "$res" || printf -v "$output" '%s' "$res"
    fi
}

# Validate value against rule
#
# If you have more than one condition, call it multiple times.
#
# Text Operators:
#
# - `=`, `==`   - equal string presentation
# - `!=`        - not equal string presentation
# - `=*`        - match against pattern
# - `!*`        - no match against pattern
# - `=~`        - match against regular expression
# - `!~`        - no match against regular expression
# - `<`         - alphabetical before
# - '>'         - alphabetical behind
# - `empty`     - unset or empty string
# - `set`       - has a value
#
# Integer Operators:
#
# - `=`
# - `<`
# - `>`
# - `<=`
# - `>=`
# - `positiv`
# - `negativ`
# - `zero`
# - `odd`
# - `even`
# - `multiple-of` or `divisible-by`
# - `factor-of`
# - `prime`
# - `no-prime`
#
# Float Operators:
#
# - `=`
# - `<`
# - `>`
# - `<=`
# - `>=`
# - `positiv`
# - `negativ`
#
# Because some of the operators use special characters like `< > ! *` you have to put this in quotes or prefix them with backslashes.
#
# Usage:    check string <value> <operator> [<compare>]
#           check integer <value> <operator> [<compare>]
#           check float <value> <operator> [<compare>]
# Return:   0 if ok
# Example:  `check "$a" == "$b"`
check() {
    local type
    is enum --name=type --allow="string integer float" --die --output=type -- "$1"
    is integer --name=arguments --min=3 --max=4 --die -- $#
    case $type in
    string)
        is enum --name=operator --allow="= == != =* !* =~ !~ < > empty set" --die -- "$3"
        case $3 in
        empty) [ -z "$2" ] ;;
        set) [ -n "$2" ] ;;
        = | ==) [[ "$2" == "$4" ]] ;;
        !=) [[ "$2" != "$4" ]] ;;
        =\*) [[ "$2" == $4 ]] ;;
        !\*) [[ "$2" != $4 ]] ;;
        =~) [[ "$2" =~ $4 ]] ;;
        \!~) [[ ! "$2" =~ $4 ]] ;;
        \<) [[ "$2" < "$4" ]] ;;
        \>) [[ "$2" > "$4" ]] ;;
        esac
        ;;
    integer)
        is enum --name=operator --allow="= < > <= >= positiv negativ zero odd even multiple-of divisible-by factor-of prime no-prime" --die -- "$3"
        is integer --name=value -- "$2" || return 1
        case $3 in
        positiv) (($2 >= 0)) ;;
        negativ) (($2 < 0)) ;;
        zero) (($2 == 0)) ;;
        odd) (($2 % 2 == 1)) ;;
        even) (($2 % 2 == 0)) ;;
        prime) (($(factor $2 | wc -w) == 2)) ;;
        no-prime) (($(factor $2 | wc -w) > 2)) ;;
        *)
            is integer --name=compare --die -- "$4"
            case $3 in
            =) (($2 == $4)) ;;
            \<) (($2 < $4)) ;;
            \>) (($2 > $4)) ;;
            \<=) (($2 <= $4)) ;;
            \>=) (($2 >= $4)) ;;
            multiple-of | divisible-by) (($2 % $4 == 0)) ;;
            factor-of) (($4 % $2 == 0)) ;;
            esac
            ;;
        esac
        ;;
    float)
        is enum --name=operator --allow="= < > <= >= positiv negativ" --die -- "$3"
        is float --name=value -- "$2" || return 1
        case $3 in
        positiv) (($(bc -l <<<"$2 >= 0"))) ;;
        negativ) (($(bc -l <<<"$2 < 0"))) ;;
        *)
            is float --name=compare --die -- "$4"
            case $3 in
            =) (($(bc -l <<<"$2 == $4"))) ;;
            \<) (($(bc -l <<<"$2 < $4"))) ;;
            \>) (($(bc -l <<<"$2 > $4"))) ;;
            \<=) (($(bc -l <<<"$2 <= $4"))) ;;
            \>=) (($(bc -l <<<"$2 >= $4"))) ;;
            esac
            ;;
        esac
        ;;
    esac
}

######################################################################################
### Helper
######################################################################################

# Return the value or if it is a variable name which is not empty return it's value
#
# Usage:    value_if_variable <name>
# Output:   <string>
value_if_variable() {
    is integer --name=arguments --max=2 --die -- $#
    local _name="$1"
    # processing
    if [[ "$_name" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] &&
        [ -n "${!_name-}" ]; then
        printf '%s' "${!_name}"
    else
        printf '%s' "$_name"
    fi
}
