#!/usr/bin/env bash
# shellcheck disable=SC2034

# The configuration module contains a lot of general configuration settings for the bash-lib modules itself. Most of them are specific to the individual environment so they need to be set in the local `overwrite` config.

######################################################################################
### process
######################################################################################

# Maximum number of parallel tasks for queue
QUEUE_MAX_NUM=2
# Percentage of 1 Minute Load per CPU (100% 8Cpu => 8.0)
QUEUE_MAX_LOAD=100

######################################################################################
### Host Specific
######################################################################################

# Array: Color limits per mount (regex critical error warn ok) used in @df
MOUNT_COLOR_LIMIT=(
    ".*" 100 90 80 50
)

######################################################################################
### Mattermost
######################################################################################

# Mattermost API URL used together with $MATTERMOST_TOKEN and silently disables mattermost functions if not set
MATTERMOST_API=
# Mattermost API Token used in @mattermost @mattermost_repost @mattermost_reaction
MATTERMOST_TOKEN=

# Array: Channel per pattern (team regex channel) used in @mattermost ("-"" = no selection for team)
MATTERMOST_CHANNEL_PATTERN=(
    MyTeam ".*" "Town Square"
)
# Array: Link channel per pattern (team regex channel) used in @mattermost ("-"" = no selection for team)
MATTERMOST_LINK_PATTERN=()

######################################################################################
### Monitoring
######################################################################################

# Grafana API URL used together with $GRAFANA_TOKEN and silently disables Grafana functions if not set
GRAFANA_API=
# Grafana API Token used in @alerts
GRAFANA_TOKEN=

# Prometheus API URLs as space separated list
PROMETHEUS_API=
# Prometheus host names as space separated list
PROMETHEUS=

######################################################################################
### Atlassian
######################################################################################

# Atlassian user for API access in confluence and jira
ATLASSIAN_USER=
# Atlassian password for API access in confluence and jira
ATLASSIAN_TOKEN=
# Atlassian Jira URL this can be https://my-company.atlassian.net
JIRA_HOST=https://ekz-gruppe.atlassian.net

# Atlassian confluence API URL used together with $ATLASSIAN_USER and $ATLASSIAN_TOKEN and silently disables @confluence functions if not set
CONFLUENCE_API=
# Atlassian jira API URL used together with $ATLASSIAN_USER and $ATLASSIAN_TOKEN and silently disables @jira functions if not set
JIRA_API=

######################################################################################
### Remote
######################################################################################

# Default login if no `--login` or `$login` available
REMOTE_LOGIN_DEFAULT=

# Hash: Mongo Admin User Logins `<host> = <username>:<password>` but use `_` instead of `.` in hostname
declare -A MONGO_ADMIN_USERPASS=()

# PowerDNS API URL used together with $POWERDNS_TOKEN and silently disables powerdns function if not set
POWERDNS_API=
# PowerDNS API Token used together with $POWERDNS_API in dns function
POWERDNS_TOKEN=

# Base URL for Portal to Provider Plusserver
PLUSSERVER_PORTAL=

ABUSEIPDB_TOKEN=
NETLAS_TOKEN=

######################################################################################
### Trivy
######################################################################################

# Maximum time to generate trivy security report
TRIVY_DEFAULT_TIMEOUT=60m
# Optional, use specified trivy server for caching of the internet databases
TRIVY_CACHE_SERVER=

######################################################################################
### divibib
######################################################################################

# Atlassian confluence page id for outage information @confluence_outage
CONFLUENCE_OUTAGE=

export MIDDLEWARE_SWAGGER_PASSWORD=
