#!/bin/bash

# Library to serialize parallel tasks
#
# https://gitlab.ekz.de/divibib-betrieb/bash-lib/blob/master/doc/locking.md
#
# Usage:
#
# source ../bash-lib/include/locking  # load functions
# lockfile=<file mostly in tmp folder>
# lock $lockfile   # create the lock
# unlock $lockfile # remove the lock
#
# The second process which want to set the lock will wait till the lock is released.

source_dir=$(dirname "${BASH_SOURCE[0]}")
source "$source_dir/errors" # load error handler

function lock {
    [ "$#" -ne 1 ] && exit_message "lib:lock: incorrect library call use: lock [LOCKFILENAME]" 1>&2

    local lockfile="$1"

    # make a file with our PID
    # easy way to show who's waiting for a lock
    if ! touch "$lockfile.$$" ; then
        exit_message "lib:lock: failed to create PID lockfile: $lockfile.$$"
    fi

    # try to symlink it
    while ! ln "$lockfile.$$" "$lockfile" 2>/dev/null
    do
        # if the symlink failed, wait for the current lock holder to exit
        sleep 1
    done

    # symlink was created successfully, lock acquired

    # if the locking process exits with unlocking, delete our lock
    trap 'rm -f "$lockfile" "$lockfile.$$"' EXIT

    return 0
}

function unlock {
    [ "$#" -ne 1 ] && exit_message "lib:unlock: incorrect library call use: unlock [LOCKFILENAME]" 1>&2

    rm -f "$lockfile" || exit_message "lib:unlock: failed to remove lockfile: $lockfile"
    rm -f "$lockfile.$$" || exit_message "lib:unlock: failed to remove PID lockfile: $lockfile.$$"

    return 0
}
