#!/bin/bash

# Script to....
#
# http://172.17.101.90/divibib-betrieb/helper-lib/blob/master/doc/skeleton.md
#
# Usage: skeleton <params>
#
# The skeleton is used as a base to make your own scripts.

# Include bash-lib
source_dir=$(dirname $(readlink -f "${BASH_SOURCE[0]:-$(pwd)/x}"))
source "$source_dir/../lib/base.bash"

# Configuration
LOG_LEVEL=DEBUG
LOG_FILE=${LOG_FILE:-$source_dir/../log/$(basename $0).log}

VERSION=$(git describe --abbrev=0 --tags 2>/dev/null); VERSION=${VERSION:-master}
REVISION=$(git rev-parse --verify master)
GITLAB=$(git config --get remote.origin.url | sed 's/\.git$//')

# Parameter checking
parsed=$(getopt --options=:Vh --longoptions=version,help --name "$0" -- "$@")
[ ${PIPESTATUS[0]} -eq 0 ] || log_exit "Could not parse parameters!"
eval set -- "$parsed"
while true; do
    case "$1" in
        -V|--version) echo "$(basename $0) from bash-lib version $VERSION"; exit 0 ;;
        -h|--help) source "$(path)/$(basename $0).help"; exit 0 ;;
        --) shift; break ;;
        *) break ;;
    esac
done
[ $# -gt 0 ] && log WARN "No parameters are supported, only -h to show help - ignoring them"

# change into command directory
cd "$(path)"

# Processing





log NOTICE Done.
