#!/usr/bin/env sh

# shellcheck disable=SC2155
export BASHLIB_HOME="$(pwd)"

# allow to always use sudo, also if not needed
if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    alias sudo='sudo'
else
    alias sudo=''
fi

# install needed packages
sudo dnf update -y
sudo dnf install -y git python3 jq expect gettext glibc-all-langpacks glibc-locale-source
# Set timezone (for date tests)
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
export TZ=Europe/Berlin
# Set language
echo "LANG=de_DE.UTF-8" | sudo tee /etc/locale.conf
echo "LANGUAGE=de_DE.UTF-8" | sudo tee -a /etc/locale.conf
echo "LC_ALL=de_DE.UTF-8" | sudo tee -a /etc/locale.conf
sudo localedef -i de_DE -f UTF-8 de_DE.UTF-8
. /etc/profile

# install bats
# shellcheck disable=SC1091
. "$BASHLIB_HOME/tests/setup/bats"
